content = '''
  // ── Zone 5: modern_world ──────────────────────────────────────────────────
  // Level: cold_war
  {
    id: 'mw_cw_001', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 1,
    text: "The Cold War between the United States and Soviet Union was primarily characterized by:",
    choices: { A: "Frequent direct military combat between American and Soviet forces", B: "Ideological competition, arms race, proxy wars, and rivalry for global influence without direct superpower military conflict", C: "Economic cooperation combined with political rivalry", D: "A series of naval battles primarily in the Pacific Ocean" },
    correct: 'B',
    explanation: "The Cold War (c. 1947-1991) was defined by the absence of direct military conflict between the superpowers despite intense competition. Both sides understood that nuclear weapons made direct war suicidal (MAD — Mutually Assured Destruction). Instead, they competed through proxy wars (Korea, Vietnam, Angola), arms races, space exploration, economic competition, and ideological propaganda.",
  },
  {
    id: 'mw_cw_002', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "The Truman Doctrine (1947) committed the United States to:",
    choices: { A: "Rebuilding European economies through massive financial assistance", B: "Supporting free peoples resisting subjugation by armed minorities or outside pressures", C: "Forming a military alliance with Western Europe", D: "Nuclear disarmament negotiations with the Soviet Union" },
    correct: 'B',
    explanation: "Truman's speech to Congress in March 1947, requesting aid for Greece and Turkey, articulated the principle that the U.S. would support any nation threatened by communist takeover. This became the basis of containment policy — the doctrine that the U.S. must prevent Soviet expansion, not necessarily roll it back. It justified interventions from Korea to Vietnam to Nicaragua.",
  },
  {
    id: 'mw_cw_003', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 1,
    text: "The Berlin Wall, built in 1961, served primarily as:",
    choices: { A: "A defensive barrier protecting East Germany from Western military attack", B: "A visible symbol of the Iron Curtain, built to stop East Germans from fleeing to the West", C: "A trade barrier restricting East-West commercial activity", D: "A flood control structure protecting East Berlin from the Spree River" },
    correct: 'B',
    explanation: "By 1961, approximately 3.5 million East Germans had fled to the West through Berlin (then an open city). The East German government built the Wall overnight to stop this brain drain that was destabilizing the communist regime. The Wall became the iconic symbol of Cold War division; its fall in November 1989 symbolized the end of the Cold War.",
  },
  {
    id: 'mw_cw_004', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "The Cuban Missile Crisis (1962) is historically significant because:",
    choices: { A: "Cuba permanently expelled Soviet forces following the crisis", B: "Soviet nuclear missiles in Cuba brought the superpowers to the brink of nuclear war before a negotiated resolution", C: "The United States invaded Cuba and occupied the island", D: "Cuba became an independent nuclear power during the crisis" },
    correct: 'B',
    explanation: "When U.S. reconnaissance discovered Soviet nuclear missiles being installed in Cuba, President Kennedy imposed a naval blockade and demanded their removal. Thirteen days of tense negotiations — during which multiple accidents and miscommunications nearly triggered war — ended with the Soviets removing the missiles in exchange for a U.S. pledge not to invade Cuba and a secret agreement to remove U.S. missiles from Turkey.",
  },
  {
    id: 'mw_cw_005', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "How did the Cold War affect nations in Asia, Africa, and Latin America?",
    choices: { A: "These regions were completely unaffected by superpower competition", B: "Cold War competition drew these nations into proxy conflicts while also giving them leverage to obtain aid from both superpowers", C: "All nations in these regions allied with the United States against the Soviet Union", D: "These nations consistently and uniformly supported the Soviet Union" },
    correct: 'B',
    explanation: "The Cold War was often most violent in the Global South. Korea, Vietnam, Angola, Mozambique, Nicaragua, and many others became battlegrounds for superpower competition. But weaker nations also leveraged the competition — playing superpowers against each other for aid, arms, and economic assistance. The Non-Aligned Movement (1961) formalized this strategy.",
  },
  {
    id: 'mw_cw_006', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "The policy of Mutually Assured Destruction (MAD) shaped Cold War strategy primarily by:",
    choices: { A: "Making nuclear war highly likely as both sides built more weapons", B: "Creating deterrence through the certainty that any nuclear attack would result in the mutual annihilation of both sides", C: "Encouraging disarmament as leaders recognized nuclear weapons were useless", D: "Having no effect as political leaders ignored the strategic implications of nuclear arsenals" },
    correct: 'B',
    explanation: "MAD held that if either superpower launched a nuclear attack, the other would retaliate with equal destruction — making 'winning' a nuclear war impossible. This created a paradoxical stability: the more destructive nuclear weapons became, the less likely they were to be used. Both sides instead competed through conventional forces, proxy wars, and economic competition.",
  },
  {
    id: 'mw_cw_007', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "The Korean War (1950-1953) ended in:",
    choices: { A: "American victory and Korean unification under a pro-Western government", B: "Soviet victory and Korean unification under a communist government", C: "An armistice that approximately restored the pre-war division at the 38th parallel", D: "United Nations annexation of Korea as an international protectorate" },
    correct: 'C',
    explanation: "After three years of fighting — including Chinese intervention when U.S./UN forces approached the Yalu River — an armistice was signed in July 1953 roughly restoring the pre-war boundary. Korea remained divided into North (communist) and South (pro-Western) Korea. The Korean War established the pattern of limited war — fighting without using nuclear weapons or attacking superpower homelands.",
  },
  {
    id: 'mw_cw_008', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "Mikhail Gorbachev's reforms of glasnost and perestroika in the 1980s:",
    choices: { A: "Successfully saved the Soviet system by making it more efficient and popular", B: "Had no significant effect on the Soviet Union", C: "Inadvertently accelerated the disintegration of the Soviet Union by unleashing forces he could not control", D: "Were entirely imposed by American diplomatic and economic pressure" },
    correct: 'C',
    explanation: "Gorbachev introduced glasnost (openness — reducing censorship) and perestroika (restructuring — limited economic liberalization) to reform, not destroy, the Soviet system. But glasnost allowed suppressed nationalist movements in Baltic, Caucasus, and Central Asian republics to organize; perestroika disrupted the command economy without creating functioning markets. By 1991, the reforms had produced the Soviet collapse Gorbachev sought to prevent.",
  },
  {
    id: 'mw_cw_009', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 1,
    text: "What ultimately ended the Cold War?",
    choices: { A: "A military defeat of the Soviet Union by the United States", B: "A formal peace treaty negotiated between the superpowers", C: "The internal collapse of the Soviet Union (1991) due to economic failure, political reform, and nationalist movements", D: "The creation of the United Nations and its peacekeeping operations" },
    correct: 'C',
    explanation: "The Cold War ended not with a bang but with the Soviet collapse. By 1991, the Soviet economy was stagnant, Eastern European satellite states had broken free (1989), Soviet republics were declaring independence, and the Communist Party's monopoly on power had ended. On December 25, 1991, Gorbachev resigned as the Soviet Union formally dissolved into 15 independent states.",
  },
  {
    id: 'mw_cw_010', zoneId: 'modern_world', levelId: 'cold_war', skillTag: 'coldwar', difficulty: 2,
    text: "The Non-Aligned Movement (established 1961) sought to:",
    choices: { A: "Align smaller nations with the United States against the Soviet Union", B: "Create a third bloc of nations independent of both Cold War superpowers", C: "Coordinate military strategy among former colonial nations", D: "Establish a new communist economic order replacing capitalism" },
    correct: 'B',
    explanation: "Leaders like Nehru (India), Nasser (Egypt), Tito (Yugoslavia), and Nkrumah (Ghana) rejected the binary choice between American and Soviet alignment. The Non-Aligned Movement articulated a 'third way' focused on decolonization, economic development, and peaceful coexistence. In practice, many members accepted aid from both superpowers while maintaining formal non-alignment.",
  },
  // Level: decolonization
  {
    id: 'mw_dc_001', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 1,
    text: "Decolonization — the end of formal European colonial rule — occurred primarily during:",
    choices: { A: "1919-1939 (the interwar period)", B: "1945-1975 (the post-World War II generation)", C: "1975-2000 (the late Cold War period)", D: "1900-1919 (before World War I)" },
    correct: 'B',
    explanation: "The vast majority of decolonization occurred between 1945 and 1975. India and Pakistan became independent in 1947; most African nations in 1957-1965 (the 'Year of Africa' was 1960, when 17 African nations became independent); Southeast Asian nations between 1945-1975. Earlier movements existed but most independence was achieved in this post-WWII period.",
  },
  {
    id: 'mw_dc_002', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "Which of the following best explains why decolonization accelerated rapidly after World War II?",
    choices: { A: "European colonial powers voluntarily gave up their empires for economic reasons", B: "A combination of weakened European powers, strengthened independence movements, Cold War pressure, and new UN norms opposing colonialism", C: "The United States forced European nations to decolonize as a condition of Marshall Plan aid", D: "Colonial economics had become unprofitable to maintain" },
    correct: 'B',
    explanation: "Decolonization accelerated due to converging pressures: European economies were devastated and could not finance colonial repression; independence movements were stronger than before the war; both superpowers (for different reasons) opposed continued European colonialism; the UN Charter endorsed self-determination; and Japan's wartime victories had destroyed European prestige in Asia.",
  },
  {
    id: 'mw_dc_003', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "The partition of British India in 1947 resulted in:",
    choices: { A: "A peaceful transition to two unified states", B: "The creation of India and Pakistan, accompanied by massive communal violence and the displacement of 10-15 million people", C: "The permanent division of South Asia into three states including Bangladesh", D: "India and Pakistan immediately forming a voluntary federation" },
    correct: 'B',
    explanation: "Partition created two independent nations — Hindu-majority India and Muslim-majority Pakistan — but the process was catastrophic. Communal violence between Hindus, Muslims, and Sikhs killed 200,000-2 million people (estimates vary widely); 10-15 million people were displaced across the new borders. Partition trauma continues to shape India-Pakistan relations today.",
  },
  {
    id: 'mw_dc_004', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "The Algerian War of Independence (1954-1962) was particularly violent because:",
    choices: { A: "France peacefully negotiated with Algerian independence leaders from the start", B: "France considered Algeria an integral part of France itself, making independence fiercely resisted", C: "Algeria had recently discovered enormous oil reserves that France refused to surrender", D: "The United States militarily intervened on France's behalf" },
    correct: 'B',
    explanation: "Algeria was not a typical colony — it had been settled by over 1 million European colonists (pieds-noirs) since 1830 and was legally considered a department of France. The French army fought a brutal counterinsurgency; the FLN (National Liberation Front) used terrorism and guerrilla warfare. An estimated 300,000-1 million Algerians died. The war nearly caused a French military coup and eventually ended in Algerian independence under de Gaulle.",
  },
  {
    id: 'mw_dc_005', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "How did the United Nations contribute to decolonization?",
    choices: { A: "The UN forcibly expelled colonial powers from their territories using military force", B: "The UN provided a forum for independence arguments and established self-determination as a global norm through its Charter and resolutions", C: "The UN had no involvement in decolonization processes", D: "The UN consistently supported colonial powers against independence movements" },
    correct: 'B',
    explanation: "The UN Charter (1945) endorsed self-determination; the UN Trusteeship system oversaw former colonial territories; and the General Assembly — where newly independent nations increasingly formed majorities — passed resolutions condemning colonialism. The UN gave independence movements international legitimacy and created pressure on colonial powers, though it rarely took direct action.",
  },
  {
    id: 'mw_dc_006', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 1,
    text: "Ghana's independence in 1957, led by Kwame Nkrumah, is historically significant because:",
    choices: { A: "It was the first African nation to gain independence from any European power ever", B: "It was the first sub-Saharan African nation to gain independence in the post-WWII era, setting a precedent and inspiring others", C: "It was achieved through violent armed revolution", D: "Ghana immediately established a communist government aligned with the Soviet Union" },
    correct: 'B',
    explanation: "Ghana (formerly Gold Coast) became the first sub-Saharan African British colony to achieve independence. Nkrumah's success demonstrated that peaceful mass political organization could achieve independence and inspired similar movements across Africa. His statement 'Seek ye first the political kingdom' became a rallying cry for African nationalists throughout the continent.",
  },
  {
    id: 'mw_dc_007', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "The concept of 'neocolonialism,' developed by Kwame Nkrumah, refers to:",
    choices: { A: "Former colonial powers reconquering independent nations militarily", B: "The continuation of economic dependency and foreign influence despite formal political independence", C: "New colonial empires established by formerly colonized nations", D: "The cultural influence of former colonies on European societies" },
    correct: 'B',
    explanation: "Nkrumah argued that formal political independence was insufficient if economies remained dependent on foreign capital, markets, and expertise. Many newly independent nations found themselves structurally dependent on former colonial powers for investment, export markets, and even military security — a continuation of colonial relationships in economic rather than political form.",
  },
  {
    id: 'mw_dc_008', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "How did the Cold War complicate the decolonization process?",
    choices: { A: "Cold War tensions prevented any decolonization from occurring until 1991", B: "Both superpowers consistently and equally opposed independence movements", C: "Both superpowers intervened in independence movements to gain allies, sometimes supporting authoritarian regimes and creating proxy conflicts", D: "The Cold War ended before significant decolonization began" },
    correct: 'C',
    explanation: "The superpowers' competition for influence complicated decolonization. The U.S. sometimes supported colonial powers (France in Vietnam) to maintain NATO alliances. The USSR supported independence movements to weaken Western imperialism. Both backed authoritarian post-independence governments when ideologically favorable. The Congo, Angola, Vietnam, Korea — all experienced independence struggles distorted by Cold War intervention.",
  },
  {
    id: 'mw_dc_009', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 3,
    text: "What was the primary challenge faced by newly independent nations in Africa and Asia after decolonization?",
    choices: { A: "Rebuilding economies that colonizers had over-developed and left with excessive infrastructure", B: "Drawing new national boundaries where no disputes existed", C: "Nation-building with colonial-era boundaries that divided ethnic groups, underdeveloped economies, and amid Cold War interference", D: "Convincing populations who preferred colonial rule to accept independence" },
    correct: 'C',
    explanation: "Newly independent nations inherited: colonial boundaries drawn without regard for ethnic or cultural territories; underdeveloped economies structured to serve colonial needs; limited supplies of educated administrators; and immediate Cold War superpower interference. These structural constraints, not lack of political will, explain much of the difficult post-independence histories of many nations.",
  },
  {
    id: 'mw_dc_010', zoneId: 'modern_world', levelId: 'decolonization', skillTag: 'decolonization', difficulty: 2,
    text: "The Bandung Conference of 1955 brought together:",
    choices: { A: "European nations to coordinate colonial policy in Africa and Asia", B: "Asian and African nations to assert independence from both Cold War blocs", C: "Communist nations to coordinate resistance to American imperialism", D: "Former World War II Allied nations to plan post-war economic recovery" },
    correct: 'B',
    explanation: "Twenty-nine African and Asian nations met in Bandung, Indonesia, asserting their right to chart independent courses without Cold War alignment. The conference articulated principles of national sovereignty, non-aggression, and peaceful coexistence. It was a founding moment for what became the Non-Aligned Movement and represented the emergence of the Global South as a political actor.",
  },
  // Level: globalization
  {
    id: 'mw_gl_001', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 1,
    text: "Economic globalization since 1945 is best characterized by:",
    choices: { A: "The increasing isolation of national economies from one another", B: "The deepening integration of national economies through growing trade, investment, and financial flows", C: "The dominance of a single global currency eliminating exchange rate differences", D: "The equal distribution of economic benefits among all participating nations" },
    correct: 'B',
    explanation: "Post-1945 economic globalization, accelerated after 1990, involved dramatically increased international trade (from roughly 5% to over 25% of world GDP), cross-border investment, global supply chains, and financial integration. The liberalization of trade through GATT/WTO agreements and the reduction of transportation and communication costs drove this integration.",
  },
  {
    id: 'mw_gl_002', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "The Bretton Woods institutions (IMF and World Bank), created in 1944, primarily promoted:",
    choices: { A: "Socialist economic development models for poor nations", B: "A liberal international economic order based on free trade and stable exchange rates to prevent pre-war economic nationalism", C: "Economic independence for developing nations from Western influence", D: "Trade protection for newly industrializing nations" },
    correct: 'B',
    explanation: "At Bretton Woods (1944), Allied nations designed a post-war economic order to prevent the economic nationalism (tariffs, competitive devaluations) that had worsened the Great Depression. The IMF managed exchange rates; the World Bank funded reconstruction and development; GATT reduced trade barriers. This architecture created the institutional foundation for post-war economic globalization.",
  },
  {
    id: 'mw_gl_003', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "The 1997 Asian Financial Crisis demonstrated that:",
    choices: { A: "Globalization protected Asian economies from financial instability", B: "Financial globalization could rapidly spread economic crises across borders", C: "Only countries with weak domestic industries were vulnerable to financial contagion", D: "The IMF successfully prevented the crisis from spreading" },
    correct: 'B',
    explanation: "The Asian Financial Crisis began in Thailand when its currency collapsed, then spread rapidly to Indonesia, South Korea, Malaysia, and others through financial market connections. Billions in capital fled overnight; economies that had grown rapidly crashed. The IMF's response (demanding austerity in exchange for loans) was widely criticized as worsening the crisis. The episode revealed the vulnerability that comes with financial integration.",
  },
  {
    id: 'mw_gl_004', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "Which of the following BEST describes the relationship between globalization and inequality since 1980?",
    choices: { A: "Globalization has reduced inequality both between nations and within nations", B: "Globalization has increased inequality within many nations while lifting hundreds of millions out of poverty globally", C: "Globalization has had no measurable effect on economic inequality anywhere", D: "Globalization has only benefited wealthy nations at the exclusive expense of poor ones" },
    correct: 'B',
    explanation: "Globalization's distributional effects are complex. Between-nation inequality has declined as China, India, and others grew rapidly. Within-nation inequality has increased in many countries as manufacturing workers in developed nations face wage competition while capital owners benefit from global markets. This combination — global convergence with domestic divergence — drives much contemporary political tension.",
  },
  {
    id: 'mw_gl_005', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "How has the global expansion of manufacturing affected East Asian economies since the 1970s?",
    choices: { A: "East Asia has remained primarily agricultural with minimal industrialization", B: "Countries like South Korea, Taiwan, Singapore, and China industrialized rapidly through export-oriented manufacturing strategies", C: "East Asian manufacturing declined due to competition from Western nations", D: "Only Japan benefited from global manufacturing expansion" },
    correct: 'B',
    explanation: "The East Asian 'economic miracle' demonstrated that strategic integration into global manufacturing supply chains could accelerate development. South Korea (steel, shipbuilding, electronics), Taiwan (semiconductors), Singapore (finance, manufacturing), and especially China after 1978 all used export-oriented industrialization to achieve rapid growth — transforming global manufacturing geography.",
  },
  {
    id: 'mw_gl_006', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "The formation of the European Union represents which aspect of globalization?",
    choices: { A: "Economic nationalism among European states protecting themselves from global competition", B: "Regional economic and political integration, reducing barriers and creating shared institutions", C: "A military alliance directed against non-European powers", D: "A colonial organization managing European overseas territories" },
    correct: 'B',
    explanation: "The EU evolved from the post-WWII European Coal and Steel Community into a comprehensive economic and political union. The single market eliminated internal trade and capital movement barriers; the Eurozone created a shared currency; common institutions made binding decisions across member states. The EU represents the deepest regional integration achieved anywhere in the world.",
  },
  {
    id: 'mw_gl_007', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 1,
    text: "Global supply chains in contemporary manufacturing mean that:",
    choices: { A: "Most products are made entirely within a single country", B: "Components of a single product are often produced in multiple countries before final assembly", C: "Manufacturing has returned to consumer nations to reduce shipping costs", D: "Only wealthy nations participate in global manufacturing chains" },
    correct: 'B',
    explanation: "A modern smartphone illustrates global supply chains: designed in California, with chips fabricated in Taiwan, displays from South Korea, rare earth minerals from the Democratic Republic of Congo, assembled in China, and sold globally. Such fragmented production maximizes efficiency but creates dependencies — as COVID-19 supply chain disruptions vividly demonstrated.",
  },
  {
    id: 'mw_gl_008', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "The rise of multinational corporations (MNCs) is most historically significant because:",
    choices: { A: "MNCs have strengthened nation-state sovereignty and tax collection", B: "MNCs operate across national borders, complicating regulation and affecting labor standards and environmental practices globally", C: "MNCs have primarily benefited workers in developing nations through higher wages", D: "MNCs are entirely new institutions with no historical precedent" },
    correct: 'B',
    explanation: "Multinational corporations can shift production, profits, and headquarters across borders to minimize taxation and regulation. This 'regulatory arbitrage' creates a race to the bottom on labor and environmental standards as nations compete to attract investment. While MNCs bring jobs and technology transfer, their ability to leave undermines host nations' bargaining power.",
  },
  {
    id: 'mw_gl_009', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 2,
    text: "How did the internet transform global commerce and communication after the 1990s?",
    choices: { A: "It had minimal effect as traditional commerce continued to dominate economic activity", B: "It enabled instantaneous global communication, e-commerce, and the digital economy, fundamentally reshaping how businesses and individuals interact", C: "Its economic effects were limited to the United States and a few wealthy nations", D: "The internet only affected high-technology sectors with no impact on traditional industries" },
    correct: 'B',
    explanation: "The internet reduced communication costs toward zero and enabled transactions regardless of geographic distance. E-commerce, remote work, digital services, and platform economies emerged. Traditional industries from retail to banking to media were disrupted. The internet created new global winners (Google, Amazon, Alibaba) and displaced traditional industries — a digital Industrial Revolution with global reach.",
  },
  {
    id: 'mw_gl_010', zoneId: 'modern_world', levelId: 'globalization', skillTag: 'globalization', difficulty: 3,
    text: "The COVID-19 pandemic (2020-2022) illustrated which historical argument about globalization?",
    choices: { A: "Globalization had no effect on the pandemic's spread or management", B: "Global interconnection accelerated disease spread while simultaneously enabling rapid vaccine development through international scientific cooperation", C: "Only developing nations were severely affected by the pandemic", D: "The pandemic permanently reversed globalization and restored economic nationalism" },
    correct: 'B',
    explanation: "COVID-19 demonstrated globalization's dual nature: global travel networks spread the virus globally within weeks; but the pandemic also demonstrated globalization's benefits — vaccines were developed in under a year through unprecedented international scientific collaboration, building on decades of shared research. The pandemic exposed supply chain vulnerabilities while also showing global cooperation's power.",
  },
  // Level: environment_demography
  {
    id: 'mw_ed_001', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 1,
    text: "World population grew from roughly 2.5 billion in 1950 to over 7 billion by 2010. This rapid growth was most directly caused by:",
    choices: { A: "Dramatically increased birth rates globally", B: "Declining death rates due to improved medicine, sanitation, and food production", C: "Mass immigration from other continents", D: "Reduced warfare allowing more people to survive to adulthood" },
    correct: 'B',
    explanation: "The 20th century population explosion was driven primarily by falling death rates — especially infant mortality — as vaccines, antibiotics, clean water, and improved agriculture spread globally. Birth rates remained high while death rates fell, creating rapid natural increase. Population growth eventually slowed in developed nations as birth rates also fell (demographic transition), but continues in parts of Africa and Asia.",
  },
  {
    id: 'mw_ed_002', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 1,
    text: "The 'Green Revolution' of the 1960s-1970s refers to:",
    choices: { A: "The global environmental protection movement of the 1970s", B: "The development of high-yield crop varieties, synthetic fertilizers, and irrigation that dramatically increased agricultural production", C: "The conversion of factories to environmentally sustainable energy sources", D: "The global spread of organic farming and traditional agricultural methods" },
    correct: 'B',
    explanation: "The Green Revolution — associated with Norman Borlaug and agricultural scientists at CIMMYT and IRRI — developed dwarf wheat and rice varieties that produced dramatically higher yields. Combined with fertilizers, pesticides, and irrigation, it transformed agriculture in India, Mexico, Pakistan, and the Philippines, preventing famine despite population growth. However, it also had environmental costs and benefited larger farmers more than small ones.",
  },
  {
    id: 'mw_ed_003', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "Demographic transition theory predicts that as nations industrialize and develop:",
    choices: { A: "Birth and death rates both remain high", B: "Death rates fall first, then birth rates fall as education and development improve — population grows rapidly between these transitions", C: "Birth rates fall first, then death rates fall", D: "Both birth and death rates immediately fall simultaneously" },
    correct: 'B',
    explanation: "Demographic transition theory describes a pattern observed across industrialized nations: in pre-modern societies both birth and death rates are high. Development brings better medicine and food, lowering death rates first — causing population explosion. As education improves (especially women's education), economic incentives for large families change, and birth rates eventually fall too.",
  },
  {
    id: 'mw_ed_004', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "The scientific consensus on climate change, as expressed in IPCC reports, concludes that:",
    choices: { A: "The climate is changing but human activity is not the primary cause", B: "Human activities — primarily burning fossil fuels — are the dominant cause of observed warming since the mid-20th century", C: "Climate change is primarily driven by natural solar cycles", D: "There is no scientific consensus on whether significant climate change is occurring" },
    correct: 'B',
    explanation: "The Intergovernmental Panel on Climate Change (IPCC), representing thousands of scientists, has concluded with over 95% certainty that human activities are the primary cause of the climate warming observed since the mid-20th century. The burning of fossil fuels releases CO2 and other greenhouse gases that trap heat in the atmosphere. This represents one of the strongest scientific consensuses in history.",
  },
  {
    id: 'mw_ed_005', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "Rapid urbanization in the Global South since 1945 has resulted in:",
    choices: { A: "Orderly planned urban development with adequate infrastructure", B: "The growth of megacities with both formal and informal settlements facing serious infrastructure challenges", C: "Population flowing from cities back to rural areas after failed urban experiments", D: "Equal distribution of urban and rural populations across the developing world" },
    correct: 'B',
    explanation: "Cities like Lagos, Mumbai, Jakarta, and Mexico City grew at rates that far outpaced infrastructure investment, creating megacities with extensive informal settlements (slums, favelas, shantytowns). These areas often lack clean water, sanitation, electricity, and legal property rights. This rapid informal urbanization, while representing genuine economic aspiration, poses enormous governance and social challenges.",
  },
  {
    id: 'mw_ed_006', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "The concept of 'environmental justice' connects environmentalism to:",
    choices: { A: "International trade law governing environmental standards", B: "Religious environmental ethics across different faith traditions", C: "Social inequality — the observation that marginalized communities disproportionately bear environmental burdens while having least political power to resist them", D: "Military conflict over scarce natural resources" },
    correct: 'C',
    explanation: "Environmental justice research documents that toxic waste facilities, polluting industries, and climate vulnerability are disproportionately concentrated in communities of color and low-income communities with less political power to resist. Globally, the nations most vulnerable to climate change (small island states, sub-Saharan Africa) are those that contributed least historically to greenhouse gas emissions.",
  },
  {
    id: 'mw_ed_007', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "How did colonialism affect environmental history in colonized regions?",
    choices: { A: "Colonial powers carefully preserved environments in their territories through conservation policies", B: "Colonial extraction, monoculture agriculture, and resource exploitation caused significant environmental degradation with lasting consequences", C: "Environmental change in colonized regions only began after decolonization", D: "Colonial rule improved environmental conditions through technological transfer" },
    correct: 'B',
    explanation: "Colonial resource extraction devastated many environments: deforestation for rubber, cotton monoculture depleted soils, mining contaminated watersheds, and plantation agriculture displaced diverse ecosystems. In Africa, colonial land alienation pushed indigenous peoples onto marginal lands, accelerating degradation. These environmental legacies compound the economic challenges facing post-colonial nations.",
  },
  {
    id: 'mw_ed_008', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "The spread of HIV/AIDS since the 1980s illustrates which historical pattern?",
    choices: { A: "AIDS spread only in wealthy globalized nations with extensive international travel", B: "Global travel and trade networks facilitated disease spread while economic inequalities shaped radically unequal access to treatment", C: "AIDS was created deliberately by multinational pharmaceutical companies", D: "Only sub-Saharan Africa experienced significant AIDS mortality" },
    correct: 'B',
    explanation: "HIV/AIDS spread globally via travel and trade networks. By the late 20th century, sub-Saharan Africa bore 70% of global HIV burden. When effective antiretroviral drugs emerged in the 1990s at $10,000-15,000 per patient per year, wealthy nations had access while African nations could not afford treatment. This inequality — a globalized disease with unequally distributed treatment — became a defining issue in global health justice.",
  },
  {
    id: 'mw_ed_009', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 3,
    text: "The international response to climate change, from the UNFCCC (1992) through the Paris Agreement (2015), reflects:",
    choices: { A: "Complete international consensus on how to address climate change with universal compliance", B: "International recognition that climate change requires multilateral cooperation, despite persistent disagreements over responsibility and financing", C: "The successful elimination of greenhouse gas emissions through global cooperation", D: "The failure of all international environmental governance" },
    correct: 'B',
    explanation: "International climate negotiations have created frameworks for cooperation (UNFCCC, Kyoto Protocol, Paris Agreement) but struggled with fundamental tensions: between developed nations responsible for historical emissions and developing nations seeking economic growth; between binding commitments and national sovereignty; between market mechanisms and regulatory approaches. Progress has been made but falls short of what scientists say is necessary.",
  },
  {
    id: 'mw_ed_010', zoneId: 'modern_world', levelId: 'environment_demography', skillTag: 'environment', difficulty: 2,
    text: "Which of the following BEST explains why population growth has been uneven globally since 1950?",
    choices: { A: "Governments in some nations deliberately prevented population growth through forced sterilization", B: "Differential rates of economic development and education — particularly women's education — explain most variation in fertility rates across nations", C: "Religion is the primary determinant of birth rates across all nations", D: "Climate differences determine birth rates in different regions" },
    correct: 'B',
    explanation: "Research consistently shows that women's education and economic empowerment are the strongest predictors of declining fertility rates — stronger than income alone. Nations that have invested in girls' education and women's economic participation have seen the fastest fertility declines. This has profound implications for development policy.",
  },
  // Level: technology_contemporary
  {
    id: 'mw_tc_001', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 1,
    text: "The digital revolution's most significant historical impact has been:",
    choices: { A: "Replacing all previous forms of communication entirely", B: "Dramatically accelerating the speed and reducing the cost of information exchange globally", C: "Eliminating economic inequality through universal information access", D: "Being limited in effect to wealthy post-industrial nations" },
    correct: 'B',
    explanation: "The digital revolution — from personal computers (1970s-80s) through the internet (1990s) to smartphones and social media (2000s-2010s) — reduced communication costs toward zero and made information instantly available globally. This transformation rivals the printing press in its effects on information diffusion, commerce, politics, and culture.",
  },
  {
    id: 'mw_tc_002', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "The 'Arab Spring' of 2011 demonstrated which relationship between technology and politics?",
    choices: { A: "Social media can topple any authoritarian government", B: "Traditional media remained more influential than social media for political mobilization", C: "Social media facilitated rapid protest coordination, but political outcomes depended on many factors beyond technology", D: "Technology determined political outcomes independently of other social factors" },
    correct: 'C',
    explanation: "Social media (Facebook, Twitter, YouTube) helped Arab Spring protesters coordinate rapidly across large distances. But outcomes varied dramatically: Tunisia achieved a democratic transition; Libya descended into civil war; Syria into catastrophic civil war; Egypt returned to military rule. Technology shaped how movements organized but did not determine whether they succeeded. Historical change requires political, social, and economic conditions beyond technology.",
  },
  {
    id: 'mw_tc_003', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "The 'digital divide' refers to:",
    choices: { A: "Competition between technology companies for market dominance", B: "The gap between those with access to digital technology and those without, often reflecting existing economic inequalities", C: "Differences in internet connection speeds between nations", D: "Conflicts between traditional print media and social media platforms" },
    correct: 'B',
    explanation: "The digital divide describes unequal access to computers, smartphones, and internet connectivity that often mirrors other inequalities: wealthy vs. poor nations, urban vs. rural populations, educated vs. less-educated, older vs. younger. As economies and services move online, the digital divide increasingly determines economic opportunity and political participation.",
  },
  {
    id: 'mw_tc_004', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "How has social media affected political movements since 2010?",
    choices: { A: "Social media has had no measurable connection to political outcomes", B: "Social media has exclusively benefited democratic movements while always harming authoritarian regimes", C: "Social media is controlled exclusively by governments to suppress dissent", D: "Social media has facilitated rapid political organization while also enabling misinformation and political polarization" },
    correct: 'D',
    explanation: "Social media's political effects are genuinely dual. It has enabled marginalized voices, facilitated protest coordination, and created global awareness of human rights abuses. It has also amplified misinformation, created filter bubbles, enabled foreign electoral interference, and been weaponized by authoritarian governments for surveillance and propaganda. Understanding both dimensions is essential.",
  },
  {
    id: 'mw_tc_005', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "How has artificial intelligence affected the global economy in the early 21st century?",
    choices: { A: "AI has primarily eliminated manufacturing jobs in East Asia", B: "AI is gradually automating both routine and complex tasks across many industries, raising questions about employment and economic distribution", C: "AI has had no measurable economic impact yet", D: "Only the United States has developed significant AI capabilities with global effects" },
    correct: 'B',
    explanation: "AI and automation are transforming labor markets: routine cognitive tasks (data processing, customer service) are increasingly automated; AI assists in fields from medicine to law to creative work. The economic effects are unevenly distributed — AI-enabled productivity may benefit capital over labor, and developed nations over developing ones whose comparative advantage in low-wage manufacturing may diminish.",
  },
  {
    id: 'mw_tc_006', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "How has globalization affected cultural production and consumption since 1990?",
    choices: { A: "Cultural exchange has been completely one-directional from Western nations to the rest of the world", B: "Cultural globalization has involved complex flows in multiple directions while generating concerns about cultural homogenization", C: "Local cultures have been entirely and permanently replaced by American popular culture", D: "Cultural exchange has declined as nations actively protect their distinct cultures" },
    correct: 'B',
    explanation: "Cultural globalization is more complex than simple Westernization. South Korean K-pop, Bollywood films, Japanese anime, Brazilian telenovelas, and Nigerian music (Afrobeats) circulate globally alongside American cultural exports. Cultural flows move in multiple directions, often producing new hybrid forms. Yet real tensions exist around cultural homogenization and the dominance of English and American cultural industries.",
  },
  {
    id: 'mw_tc_007', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 1,
    text: "The United Nations Sustainable Development Goals (SDGs), adopted in 2015, reflect which historical trend?",
    choices: { A: "The decline of international cooperation since World War II", B: "Growing recognition that global challenges like poverty, climate change, and inequality require coordinated international responses", C: "The increasing ability of individual nation-states to solve global problems independently", D: "A return to Cold War-era bloc politics" },
    correct: 'B',
    explanation: "The SDGs — 17 goals ranging from poverty elimination to climate action to gender equality — represent the most ambitious multilateral framework ever established. They reflect 70+ years of learning that problems like climate change, pandemics, and poverty are inherently transnational and require global cooperation. Whether the framework produces results depends on the political will of member states.",
  },
  {
    id: 'mw_tc_008', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "The geopolitical competition between the United States and China in the early 21st century is best described as:",
    choices: { A: "A military conflict primarily fought through proxy wars as in the Cold War", B: "A multi-dimensional competition involving trade, technology, military power, and diplomatic influence", C: "A cooperative alliance against shared threats like climate change and terrorism", D: "Competition focused exclusively on territorial disputes in the South China Sea" },
    correct: 'B',
    explanation: "The U.S.-China relationship involves simultaneous competition and cooperation. Competition spans: trade imbalances and tariffs; technology (semiconductors, AI, 5G); military modernization and Pacific influence; and diplomatic competition for Global South alignment. Yet both nations cooperate on climate, public health, and nuclear non-proliferation. This complex relationship defies Cold War analogies.",
  },
  {
    id: 'mw_tc_009', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 3,
    text: "Which of the following BEST characterizes the current moment in world history (early 21st century)?",
    choices: { A: "An era of unprecedented global peace with no major conflicts", B: "A period of intensifying global interdependence combined with renewed nationalism and great-power competition", C: "The triumph of liberal democracy as the universal final form of government", D: "The beginning of a new American Century of unchallenged global dominance" },
    correct: 'B',
    explanation: "The early 21st century presents a paradox: deeper global economic integration and shared challenges (climate, pandemics) alongside rising nationalism, democratic backsliding, and renewed great-power competition (US-China-Russia). Globalization faces political resistance from populations experiencing its downsides. Understanding this tension between integration and fragmentation is central to analyzing contemporary world history.",
  },
  {
    id: 'mw_tc_010', zoneId: 'modern_world', levelId: 'technology_contemporary', skillTag: 'technology', difficulty: 2,
    text: "The development and rapid global rollout of COVID-19 vaccines in 2020-2021 is historically significant because:",
    choices: { A: "It demonstrated that any disease can be eliminated within two years", B: "It showed that international scientific collaboration and mRNA technology could compress vaccine development from decades to under a year", C: "It proved that vaccine access was equally distributed globally from the start", D: "It was the first time multiple countries worked together on a medical challenge" },
    correct: 'B',
    explanation: "COVID-19 vaccines were developed in under a year — historically unprecedented (flu vaccines took years; polio vaccine took 20+ years). This was enabled by decades of mRNA research, massive parallel investment, regulatory acceleration, and international data sharing. It demonstrated both scientific capability and, in the inequitable distribution of vaccines between wealthy and poor nations, the continuing challenges of global health equity.",
  },
];
'''

with open('/home/user/ascend/client/src/data/apWorldHistory.js', 'a') as f:
    f.write(content)

print("Zone 5 appended successfully")
