content = '''
  // ── Zone 4: age_of_crisis ────────────────────────────────────────────────
  // Level: wwi
  {
    id: 'ac_w1_001', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 1,
    text: "Which event most directly triggered the outbreak of World War I?",
    choices: { A: "Germany's invasion of France", B: "The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo", C: "The sinking of the British ocean liner Lusitania", D: "Austria-Hungary's annexation of Bosnia" },
    correct: 'B',
    explanation: "The assassination of Archduke Franz Ferdinand (heir to the Austro-Hungarian throne) by Gavrilo Princip, a Bosnian Serb nationalist, in Sarajevo on June 28, 1914 triggered the alliance system. Austria-Hungary issued an ultimatum to Serbia; when Serbia's response was deemed insufficient, Austria-Hungary declared war, activating interlocking treaties that pulled in Germany, Russia, France, and Britain.",
  },
  {
    id: 'ac_w1_002', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "The system of alliances in Europe c. 1900-1914 meant that:",
    choices: { A: "European nations were united in a single government preventing war", B: "A conflict between two nations could quickly draw in all major powers through mutual defense obligations", C: "Wars between European nations had become impossible due to mutual deterrence", D: "The United States was obligated by treaty to defend European allies" },
    correct: 'B',
    explanation: "Europe was divided into two armed camps: the Triple Alliance (Germany, Austria-Hungary, Italy) and the Triple Entente (France, Russia, Britain). When Austria-Hungary declared war on Serbia, Russia mobilized to defend Serbia; Germany declared war on Russia; France honored its treaty with Russia; Germany invaded neutral Belgium, bringing Britain into the war. A local Balkan conflict became a world war within weeks.",
  },
  {
    id: 'ac_w1_003', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 1,
    text: "Which of the following best describes the Western Front of World War I?",
    choices: { A: "A dynamic war of rapid advances and retreats across wide territory", B: "A naval conflict fought primarily in the North Sea", C: "A brutal stalemate of trench warfare with massive casualties for minimal territorial gain", D: "A colonial conflict fought primarily in Africa" },
    correct: 'C',
    explanation: "After the initial German advance was stopped at the Marne (1914), both sides dug trenches stretching 400 miles from the English Channel to Switzerland. Barbed wire, machine guns, and artillery made offensive attacks catastrophically costly. The Battle of the Somme (1916) killed 60,000 British soldiers on its first day, with one mile of territory gained. Trench warfare became the defining image of World War I.",
  },
  {
    id: 'ac_w1_004', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "The Armenian Genocide of 1915-1916 was carried out by:",
    choices: { A: "The Russian Empire during its invasion of Anatolia", B: "The German Empire against Ottoman civilians", C: "The Ottoman Empire against its Armenian Christian minority population", D: "The British Empire during its campaign in the Middle East" },
    correct: 'C',
    explanation: "The Ottoman government, controlled by the Committee of Union and Progress (Young Turks), ordered the deportation and massacre of the Armenian population during World War I. Approximately 1-1.5 million Armenians died through mass shootings, forced death marches into the Syrian desert, and starvation. This is widely recognized by historians and many governments as genocide.",
  },
  {
    id: 'ac_w1_005', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "How did World War I affect colonial subjects from Africa and Asia?",
    choices: { A: "Colonies were completely unaffected as the war was confined to Europe", B: "Colonial subjects fought in the war, and their service raised expectations of political rights that contributed to anti-colonial movements", C: "European empires expanded by conquering additional territories during the war", D: "All colonial peoples gained independence immediately after the war ended" },
    correct: 'B',
    explanation: "Millions of colonial subjects fought for their imperial rulers: Indian soldiers in the British Army, Senegalese tirailleurs in the French Army, labor battalions from Egypt and China. Many expected that fighting for democracy and national self-determination would result in greater rights. When these expectations were disappointed (as in the 1919 Paris Peace Conference), it fueled anti-colonial nationalism in India, Egypt, Korea, Vietnam, and elsewhere.",
  },
  {
    id: 'ac_w1_006', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "The Treaty of Versailles (1919) is significant because it:",
    choices: { A: "Created a fair settlement that all parties ultimately accepted", B: "Imposed war guilt, massive reparations, and territorial losses on Germany, generating resentment that contributed to World War II", C: "Gave Germany favorable economic terms in exchange for disarmament", D: "Immediately created the League of Nations with full German membership" },
    correct: 'B',
    explanation: "The Treaty of Versailles forced Germany to accept sole responsibility for the war (Article 231, the 'war guilt clause'), pay enormous reparations, cede territories including Alsace-Lorraine and the Polish Corridor, and drastically reduce its military. German politicians across the political spectrum called it a 'diktat' (dictated peace). This resentment became Hitler's most powerful recruiting tool.",
  },
  {
    id: 'ac_w1_007', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "Woodrow Wilson's Fourteen Points proposed:",
    choices: { A: "Harsh punishment of Germany as the aggressor nation", B: "American annexation of European colonial territories in Africa", C: "A peace based on self-determination, open diplomacy, free trade, and a League of Nations", D: "American military occupation of Central Europe for 20 years" },
    correct: 'C',
    explanation: "Wilson's Fourteen Points (1918) outlined his vision for a just peace: no secret treaties, freedom of the seas, self-determination of peoples, reduction of armaments, and a League of Nations to resolve future disputes peacefully. Many of these ideals were compromised or abandoned at Paris, particularly self-determination (applied to European peoples but not to Asian and African colonial subjects).",
  },
  {
    id: 'ac_w1_008', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "How did World War I contribute to the Russian Revolution of 1917?",
    choices: { A: "Germany sponsored the Bolshevik revolution to remove Russia from the war", B: "Military defeats, mass casualties, and economic collapse discredited the tsarist regime, creating conditions for Bolshevik seizure of power", C: "The revolution was caused entirely by a German military invasion of Russia", D: "The Russian Revolution occurred before Russia entered the war" },
    correct: 'B',
    explanation: "By 1917, Russia had suffered over 5 million military casualties, faced severe food shortages, and the tsar's government had lost all credibility. The February Revolution overthrew the tsar; the Provisional Government fatally continued the war. Lenin's Bolsheviks promised 'Peace, Land, and Bread' and seized power in the October Revolution. Germany did transport Lenin to Russia in a sealed train, hoping he would destabilize Russia — which he did.",
  },
  {
    id: 'ac_w1_009', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 1,
    text: "'Total war' during World War I involved:",
    choices: { A: "Only professional soldiers with civilians completely protected", B: "Mobilizing entire national economies and populations — men, women, industrial capacity — for the war effort", C: "The use of nuclear weapons for the first time in history", D: "Naval warfare exclusively without significant land battles" },
    correct: 'B',
    explanation: "World War I was the first industrial-scale total war. Nations mobilized entire economies: women entered the workforce to replace men at the front; factories switched from consumer goods to weapons; governments rationed food; propaganda mobilized civilian morale. The distinction between military and civilian spheres essentially collapsed.",
  },
  {
    id: 'ac_w1_010', zoneId: 'age_of_crisis', levelId: 'wwi', skillTag: 'wwi', difficulty: 2,
    text: "Which of the following was the most significant long-term consequence of World War I?",
    choices: { A: "The permanent peace it established through the League of Nations", B: "The destruction of the German, Ottoman, Austro-Hungarian, and Russian empires, creating nationalist tensions and ideological conflicts that contributed to World War II", C: "The immediate democratization of all European nations", D: "The end of colonialism as European powers lost their empires" },
    correct: 'B',
    explanation: "World War I destroyed four empires, redrew the map of Europe and the Middle East, created new nations based on contested ethnic boundaries, generated economic chaos, and produced the political extremism that led to totalitarianism. John Maynard Keynes predicted that the Versailles settlement would produce another war. World War II can be understood as the unfinished business of World War I.",
  },
  // Level: totalitarianism
  {
    id: 'ac_to_001', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 1,
    text: "Totalitarianism is best defined as:",
    choices: { A: "A democratic government with a very strong executive power", B: "A political system where the state seeks total control over all aspects of public and private life", C: "A constitutional monarchy with extensive social welfare programs", D: "A one-party state that tolerates limited political opposition" },
    correct: 'B',
    explanation: "Political theorist Hannah Arendt defined totalitarianism as a novel form of government that differs from ordinary tyranny in seeking to transform human nature itself through ideology, terror, and mass mobilization. Unlike traditional autocracies that demand obedience, totalitarian states demand enthusiastic participation in official ideology.",
  },
  {
    id: 'ac_to_002', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "Italian Fascism under Mussolini is best described as:",
    choices: { A: "A Marxist movement focused on worker control of the means of production", B: "Ultranationalism combined with glorification of violence, rejection of both liberalism and communism, and a corporatist economy", C: "Traditional conservatism seeking to restore the pre-1914 social order", D: "Liberal democracy with strong state economic intervention" },
    correct: 'B',
    explanation: "Fascism glorified the nation and state above the individual, celebrated violence and war as purifying forces, rejected parliamentary democracy as weak and corrupt, and organized the economy into state-controlled corporations representing different economic sectors. Mussolini's famous formula: 'Everything within the state, nothing outside the state, nothing against the state.'",
  },
  {
    id: 'ac_to_003', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "Stalin's collectivization of Soviet agriculture (1929-1933) resulted primarily in:",
    choices: { A: "Dramatic increases in food production that ended hunger in the Soviet Union", B: "Famine, especially in Ukraine (the Holodomor), killing an estimated 5-7 million people", C: "Willing peasant acceptance of collective farming as an improvement", D: "Rapid industrialization with minimal casualties" },
    correct: 'B',
    explanation: "Forced collectivization eliminated private farming and created state-run collective farms (kolkhozy). Peasants who resisted — labeled kulaks (rich peasants) — were killed, imprisoned, or deported. Agricultural production collapsed; the state extracted grain even as peasants starved. In Ukraine, the resulting famine (Holodomor) killed millions in what many historians and governments classify as genocide.",
  },
  {
    id: 'ac_to_004', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "The rise of Hitler and National Socialism in Germany was made possible primarily by:",
    choices: { A: "Military force to seize power without popular support", B: "Resentment from the Versailles Treaty, economic devastation of the Great Depression, and weakness of the Weimar Republic", C: "Foreign intervention and financial support from Mussolini's Italy", D: "Germany's economic prosperity in the late 1920s creating confidence for radical change" },
    correct: 'B',
    explanation: "The Nazi Party was a fringe movement until the Great Depression. Unemployment rose to 30% by 1932; middle-class savings were wiped out; the Weimar Republic seemed incapable of responding. Hitler offered scapegoats (Jews, Marxists, the Versailles 'stab in the back'), national glory, and economic revival. He was legally appointed chancellor in January 1933 and moved quickly to establish dictatorship.",
  },
  {
    id: 'ac_to_005', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "Nazi racial ideology was rooted primarily in:",
    choices: { A: "A belief that all races are culturally distinct but inherently equal", B: "Pseudo-scientific racism asserting Aryan/Germanic superiority and the biological inferiority of Jews and others", C: "Social Darwinism applied only to economic competition between nations", D: "Traditional Christian theology that viewed Jews as spiritually corrupted" },
    correct: 'B',
    explanation: "Nazi ideology drew on late 19th century racial pseudoscience that claimed to have identified biological racial hierarchies. It portrayed Jews not as a religious group but as a biological 'race' whose existence threatened German racial purity. This biological racism — the idea that Jews were inherently dangerous parasites — provided the ideological foundation for the Holocaust.",
  },
  {
    id: 'ac_to_006', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "How did totalitarian states use mass media and propaganda?",
    choices: { A: "They had no access to mass media and relied entirely on word of mouth", B: "They used radio, film, rallies, and print media to spread ideology and generate enthusiastic mass support for the regime", C: "They allowed completely free press as a democratic show for foreign audiences", D: "They used propaganda only during wartime, not in peacetime" },
    correct: 'B',
    explanation: "Goebbels's Nazi Ministry of Propaganda mastered radio, film (Leni Riefenstahl), and mass rallies (Nuremberg). The Soviet Union used socialist realist art, state-controlled media, and public ceremonies. Both regimes understood that modern industrial states required active public consent or enthusiasm, not just passive obedience — and invested enormous resources in manufacturing it.",
  },
  {
    id: 'ac_to_007', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 3,
    text: "What most fundamentally distinguished Soviet ideology from German and Italian fascist ideology?",
    choices: { A: "The Soviet Union was more tolerant of internal political opposition", B: "Soviet ideology was internationally oriented and officially anti-racist, while fascism was aggressively nationalist and accepted racial hierarchy", C: "The Soviet Union never used state violence against its own citizens", D: "Nazi Germany and the Soviet Union had essentially identical economic policies" },
    correct: 'B',
    explanation: "Soviet communism claimed to represent all workers worldwide and officially rejected racism (while practicing ethnic discrimination). Fascism was explicitly nationalist — glorifying the nation-state and racial community. In the 1930s, the Communist International recruited anti-fascists internationally; fascist movements explicitly rejected internationalism. This ideological difference shaped their different international alliances, despite both being authoritarian.",
  },
  {
    id: 'ac_to_008', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 3,
    text: "Which of the following best explains why totalitarian movements attracted mass support in the interwar period?",
    choices: { A: "Most people genuinely preferred authoritarian rule to democracy on principle", B: "Economic crisis, national humiliation, fear of communism, and apparent weakness of democratic governments made extreme solutions attractive to many", C: "Totalitarian governments relied purely on terror with no genuine popular appeal", D: "Democratic governments had completely failed before totalitarians rose to power" },
    correct: 'B',
    explanation: "Totalitarianism offered appealing answers to genuine crises. In Germany, Nazism promised economic recovery, national restoration after Versailles humiliation, and protection against communist revolution. In Italy, Fascism promised national greatness and an end to post-war chaos. In Russia, communism promised liberation from tsarist oppression. Understanding the genuine appeal of totalitarianism is essential to preventing its recurrence.",
  },
  {
    id: 'ac_to_009', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "Stalin's Great Purge (1936-1938) targeted primarily:",
    choices: { A: "Foreign spies and enemy agents working for Germany and Japan", B: "Communist Party members, military officers, and ordinary citizens accused of disloyalty — often tortured into false confessions", C: "Religious leaders and institutions opposing communist atheism", D: "Economic criminals who hoarded food during collectivization" },
    correct: 'B',
    explanation: "The Great Purge (Yezhovshchina) killed approximately 750,000 people and sent millions to the Gulag labor camps. Stalin targeted Communist Party members, Red Army officers (executing most senior commanders), intellectuals, and ordinary people denounced by neighbors. Show trials extracted confessions to absurd conspiracy charges. The purge left the Soviet military dangerously weakened when Germany invaded in 1941.",
  },
  {
    id: 'ac_to_010', zoneId: 'age_of_crisis', levelId: 'totalitarianism', skillTag: 'totalitarian', difficulty: 2,
    text: "The Spanish Civil War (1936-1939) served as a precursor to World War II primarily because:",
    choices: { A: "It was fought directly between Germany and France", B: "It allowed Germany and Italy to test new military tactics while democracies failed to effectively respond", C: "Spain's defeat directly led Germany to invade Poland", D: "The Soviet Union used Spain as a base for attacking Germany" },
    correct: 'B',
    explanation: "Germany tested its Blitzkrieg tactics and Luftwaffe capabilities in Spain, most infamously at Guernica (1937). The democracies' non-intervention policy (which in practice aided Franco's Nationalists by allowing German and Italian intervention while blocking Soviet aid through blockade) revealed Western weakness that emboldened Hitler. The war also radicalized international politics.",
  },
  // Level: great_depression
  {
    id: 'ac_gd_001', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 1,
    text: "The Great Depression was triggered most directly by:",
    choices: { A: "German hyperinflation destroying the European financial system", B: "The U.S. stock market crash of 1929 followed by cascading bank failures", C: "The economic provisions of the Versailles Treaty", D: "A global agricultural collapse due to drought" },
    correct: 'B',
    explanation: "The Wall Street Crash of October 1929 wiped out billions in stock value. As banks failed and credit contracted, businesses collapsed, investment dried up, and unemployment soared. Because the United States was the world's largest economy and creditor, the crisis spread globally — American banks recalled loans from Europe, collapsing German and Austrian banks.",
  },
  {
    id: 'ac_gd_002', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "How did the Great Depression spread from the United States to other nations?",
    choices: { A: "Through deliberate currency manipulation by the United States", B: "Via interconnected financial and trade networks — American bank failures reduced imports and recalled foreign loans", C: "Through a global drought that destroyed harvests worldwide simultaneously", D: "Only through colonial regions economically dependent on the United States" },
    correct: 'B',
    explanation: "The Depression spread through multiple channels: American banks recalled loans to Europe (collapsing European banks); American demand for imports collapsed (devastating export economies); falling commodity prices hurt agricultural producers worldwide; the gold standard forced deflationary policies on countries that maintained it. Economic integration that had created prosperity now transmitted crisis.",
  },
  {
    id: 'ac_gd_003', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "Many nations responded to the Great Depression by raising tariffs. This policy most likely:",
    choices: { A: "Helped nations recover quickly by protecting domestic industries from foreign competition", B: "Had no significant measurable effect on the global economy", C: "Worsened the depression by triggering retaliatory tariffs and collapsing international trade further", D: "Benefited only the United States which had the largest domestic market" },
    correct: 'C',
    explanation: "The U.S. Smoot-Hawley Tariff (1930) raised duties on thousands of imports. Other nations retaliated with their own tariffs. International trade fell by roughly 65% between 1929 and 1934. This trade collapse turned a severe recession into a global catastrophe, demonstrating that economic nationalism in an interdependent world can be self-defeating.",
  },
  {
    id: 'ac_gd_004', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "Franklin Roosevelt's New Deal in the United States represented:",
    choices: { A: "An abandonment of capitalism for socialism", B: "Expanded government intervention in the economy to provide relief, recovery, and reform while preserving capitalism", C: "A purely military solution to the economic crisis", D: "Strict adherence to laissez-faire policy of minimal government intervention" },
    correct: 'B',
    explanation: "The New Deal created social security, the FDIC (bank deposit insurance), the SEC (securities regulation), rural electrification, and public works employment. It did not end the Depression (which required World War II military spending) but it stabilized the banking system, restored confidence, and created the framework of the American welfare state. It preserved capitalism by reforming it.",
  },
  {
    id: 'ac_gd_005', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "How did the Great Depression contribute to the rise of fascism in Europe?",
    choices: { A: "Economic desperation made authoritarian promises of national revival and scapegoating attractive", B: "Fascists provided genuine economic solutions that actually worked better than democratic alternatives", C: "The Depression had no causal relationship to the rise of fascism", D: "Democratic governments voluntarily transferred power to fascists to avoid disorder" },
    correct: 'A',
    explanation: "The Depression hit Germany catastrophically — 30% unemployment by 1932. In this climate, the Nazi Party's electoral share rose from 2.6% (1928) to 37.4% (July 1932). Hitler offered economic revival, national restoration, and a scapegoat (Jewish people and Marxists). The Depression demonstrated that liberal democracy could fail to protect ordinary people, making extremist alternatives politically viable.",
  },
  {
    id: 'ac_gd_006', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "Keynes's economic response to the Great Depression argued that governments should:",
    choices: { A: "Balance budgets by cutting spending during recessions to restore market confidence", B: "Increase government spending to stimulate demand even if it required borrowing (deficit spending)", C: "Allow markets to self-correct without any government interference", D: "Raise taxes dramatically to fund relief programs without borrowing" },
    correct: 'B',
    explanation: "In The General Theory of Employment, Interest, and Money (1936), Keynes argued that capitalist economies can get trapped in low-demand equilibria with high unemployment, and that only government spending can provide the stimulus to break the cycle. His ideas influenced the New Deal and became the basis of post-WWII economic policy in Western democracies.",
  },
  {
    id: 'ac_gd_007', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "How did the Great Depression affect Latin American economies?",
    choices: { A: "Latin America was largely insulated as it traded primarily with other developing regions", B: "Falling commodity prices devastated Latin American export economies that depended on selling raw materials to industrialized nations", C: "Latin American economies actually grew as Europeans and Americans bought more cheap Latin American goods", D: "Latin American governments successfully used protectionism to avoid the depression" },
    correct: 'B',
    explanation: "Latin American economies depended heavily on exporting commodities (coffee, rubber, copper, wheat) to industrialized nations. When demand collapsed and prices fell, national revenues crashed. Brazil saw coffee prices fall 75%; Chile's nitrate and copper exports collapsed. The resulting political instability brought new authoritarian governments to power across Latin America.",
  },
  {
    id: 'ac_gd_008', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "Which of the following was a major social consequence of the Great Depression in the United States?",
    choices: { A: "The rapid expansion of the middle class as government jobs increased", B: "A dramatic reduction in racial inequality through emergency programs", C: "Mass unemployment, widespread poverty, and large-scale internal migration such as the Dust Bowl migration to California", D: "The elimination of organized labor as workers accepted wage cuts to keep their jobs" },
    correct: 'C',
    explanation: "At its peak, U.S. unemployment reached 25%. The Dust Bowl (drought combined with poor farming practices) displaced 2.5 million people from the Great Plains. Hundreds of thousands migrated to California, as documented in Steinbeck's The Grapes of Wrath. The psychological trauma of the Depression shaped an entire generation's attitudes toward risk, savings, and government responsibility.",
  },
  {
    id: 'ac_gd_009', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 2,
    text: "How did the Great Depression affect colonial economies in Asia and Africa?",
    choices: { A: "Colonial economies were largely insulated from the Depression", B: "Falling commodity prices devastated export-dependent colonial economies, increasing poverty and political discontent", C: "Colonial peoples benefited as European demand for their goods temporarily increased", D: "Colonial governments invested heavily in infrastructure to protect their economies" },
    correct: 'B',
    explanation: "Colonial economies were structured to export primary commodities to industrialized nations. When those markets collapsed, so did colonial revenues. In West Africa, cocoa and palm oil prices fell catastrophically. In Southeast Asia, rubber and tin prices collapsed. Colonial governments responded with austerity, cutting services and increasing taxation — deepening poverty and fueling anti-colonial nationalism.",
  },
  {
    id: 'ac_gd_010', zoneId: 'age_of_crisis', levelId: 'great_depression', skillTag: 'depression', difficulty: 3,
    text: "The Great Depression's most significant long-term political legacy was:",
    choices: { A: "The permanent elimination of market capitalism", B: "A global return to balanced budget policies and free markets after the crisis passed", C: "The expansion of the welfare state as Western governments accepted ongoing responsibility for economic security", D: "The strengthening of international economic cooperation through new global trade agreements" },
    correct: 'C',
    explanation: "The Depression demonstrated that unregulated capitalism could catastrophically fail and that governments had both the responsibility and capacity to intervene. Post-WWII Western governments built welfare states — unemployment insurance, social security, healthcare systems, bank regulation — based on this lesson. The assumption that government should manage macroeconomic conditions became foundational to post-war Western politics.",
  },
  // Level: wwii
  {
    id: 'ac_w2_001', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 1,
    text: "Which of the following was the PRIMARY cause of World War II in Europe?",
    choices: { A: "The assassination of a European leader as in 1914", B: "German aggression driven by Nazi ideology and expansionism, enabled by Allied appeasement", C: "A naval conflict between Britain and Germany over Atlantic trade routes", D: "Soviet invasion of Western Europe forcing a defensive Allied response" },
    correct: 'B',
    explanation: "World War II in Europe resulted directly from Nazi Germany's territorial expansion — rearmament, remilitarization of the Rhineland, annexation of Austria and Czechoslovakia — enabled by the policy of appeasement. Hitler's invasion of Poland on September 1, 1939 finally provoked the Allied declaration of war.",
  },
  {
    id: 'ac_w2_002', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 1,
    text: "The Holocaust was the systematic murder of approximately:",
    choices: { A: "1 million Jewish people only", B: "6 million Jewish people and 5-6 million others including Roma, disabled people, gay people, and political prisoners", C: "Only Jewish people, with other groups unaffected by Nazi persecution", D: "50 million European civilians" },
    correct: 'B',
    explanation: "The Holocaust — the Nazis' genocide of the Jewish people — killed approximately 6 million Jews (two-thirds of European Jewry). The Nazi regime also systematically murdered Roma (250,000-500,000), people with disabilities (200,000+), gay men (thousands), Jehovah's Witnesses, and political opponents. The total death toll in the Nazi camp and extermination system was 11-12 million.",
  },
  {
    id: 'ac_w2_003', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "The policy of appeasement, exemplified by the Munich Agreement (1938), failed primarily because:",
    choices: { A: "Hitler was satisfied with the Sudetenland and sought no further territory, but Britain and France still went to war", B: "Appeasement encouraged further Nazi aggression rather than satisfying demands", C: "The Soviet Union refused to support the agreement", D: "France refused to honor the terms of the agreement" },
    correct: 'B',
    explanation: "At Munich, Britain (Chamberlain) and France (Daladier) allowed Hitler to annex Czechoslovakia's Sudetenland, hoping to prevent another world war. Six months later, Hitler seized the rest of Czechoslovakia — demonstrating that his expansionist aims had no natural stopping point. Appeasement taught Hitler that Western democracies would retreat before threats, emboldening further aggression.",
  },
  {
    id: 'ac_w2_004', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "World War II was a genuinely global conflict because:",
    choices: { A: "It was fought exclusively in Europe and North Africa", B: "Combat occurred across multiple continents and oceans, with European and Pacific theaters connected by the same ideological struggle", C: "It was merely called global because it used planes for the first time", D: "Only because the United States fought in both the European and Pacific theaters" },
    correct: 'B',
    explanation: "World War II involved fighting in Europe, North Africa, the Pacific, East Asia, Southeast Asia, the Atlantic and Pacific Oceans, and involved forces from every inhabited continent. The Chinese theater (1937-45) preceded the European war and killed an estimated 14 million Chinese. The ideological connection — fascism vs. democracy and communism — and the alliance systems made these disparate conflicts parts of a single global war.",
  },
  {
    id: 'ac_w2_005', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "The atomic bombings of Hiroshima and Nagasaki (August 1945) are historically controversial because:",
    choices: { A: "There is no controversy; all historians agree they were both necessary and justified", B: "They ended the war but caused massive civilian casualties, raising enduring ethical questions about targeting civilian populations", C: "They were militarily ineffective and Japan surrendered due to Soviet entry into the war", D: "They were not truly nuclear weapons but the largest conventional bombs ever used" },
    correct: 'B',
    explanation: "The bombings killed an estimated 110,000-210,000 people immediately and thousands more from radiation. They ended World War II in the Pacific rapidly. The controversy involves whether they were necessary (given Japan's willingness to discuss peace, the imminent Soviet entry into the Pacific war, and planned conventional invasion alternatives) and whether deliberately targeting civilian populations is ever ethically justifiable.",
  },
  {
    id: 'ac_w2_006', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "How did World War II affect European colonial empires?",
    choices: { A: "Colonial empires were strengthened by wartime economic extraction from colonies", B: "The war devastated European economies, weakened their capacity to maintain colonies, and inspired anti-colonial movements", C: "All colonial peoples uniformly supported their colonial rulers during the war", D: "All European colonies were liberated during the war itself" },
    correct: 'B',
    explanation: "World War II accelerated decolonization through several mechanisms: Japanese military victories in Southeast Asia destroyed the myth of European invincibility; colonial soldiers who fought for 'freedom' demanded their own; European nations were economically exhausted; and the Cold War superpowers (US and USSR) both opposed European colonialism (for different reasons). Independence movements intensified after 1945.",
  },
  {
    id: 'ac_w2_007', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "The Nuremberg Trials (1945-1946) established which important legal precedent?",
    choices: { A: "That war itself is inherently illegal under international law", B: "That only military leaders who gave direct orders could be tried for war crimes", C: "That individual leaders could be held criminally responsible for crimes against humanity and genocide", D: "That all German citizens were collectively guilty and equally liable for the Holocaust" },
    correct: 'C',
    explanation: "The Nuremberg Trials established that 'following orders' was not an absolute defense against charges of war crimes and crimes against humanity. This created the foundations of modern international criminal law, eventually leading to the International Criminal Court. The principle that individuals — including heads of state — can be held personally criminally responsible for atrocities is a cornerstone of international humanitarian law.",
  },
  {
    id: 'ac_w2_008', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 2,
    text: "How did World War II's outcome shape the Cold War?",
    choices: { A: "The defeat of fascism permanently united all nations in cooperative peace", B: "The destruction of German and Japanese power created a vacuum that the U.S. and Soviet Union competed to fill", C: "The Soviet Union and United States were not rivals until decades after the war ended", D: "The United Nations successfully prevented superpower competition" },
    correct: 'B',
    explanation: "Before WWII, multiple great powers balanced each other. The war destroyed Germany, Japan, and weakened Britain, France, and others. Only two superpowers emerged intact — and they had fundamentally incompatible ideologies (liberal capitalism vs. Soviet communism). The struggle to fill the power vacuum in Europe and Asia became the Cold War.",
  },
  {
    id: 'ac_w2_009', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 1,
    text: "The Battle of Stalingrad (1942-1943) is considered a turning point because:",
    choices: { A: "It was the first use of atomic weapons in warfare", B: "It was the first German defeat and began Germany's strategic retreat on the Eastern Front", C: "It opened the second front in Western Europe that Stalin had demanded", D: "It ended the war in the Pacific theater" },
    correct: 'B',
    explanation: "Stalingrad was one of history's bloodiest battles (approximately 2 million casualties). The Soviet encirclement and destruction of the German 6th Army was the first major German defeat and fundamentally shifted momentum on the Eastern Front, where 80% of German casualties occurred. After Stalingrad, Germany was strategically on the defensive.",
  },
  {
    id: 'ac_w2_010', zoneId: 'age_of_crisis', levelId: 'wwii', skillTag: 'wwii', difficulty: 3,
    text: "The most significant factor in Allied victory in World War II was:",
    choices: { A: "Tactically superior generalship by American and British commanders", B: "A combination of Soviet human sacrifice, American industrial production, British intelligence, and coordination across multiple theaters", C: "The failure of German technology to match Allied weapons", D: "The early entry of the United States into the war in 1939" },
    correct: 'B',
    explanation: "Allied victory required multiple contributions: the Soviet Union absorbed the majority of German military power at enormous human cost (27 million Soviet deaths); American 'arsenal of democracy' production outpaced Axis industry; British code-breaking (ULTRA) provided intelligence advantage; Allied coordination of European and Pacific strategies was ultimately effective. No single factor is sufficient.",
  },
  // Level: resistance_movements
  {
    id: 'ac_rm_001', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "Gandhi's non-violent resistance strategy in India was effective primarily because:",
    choices: { A: "The British Empire had no military capacity to respond to protests", B: "It generated mass mobilization and exposed the moral contradictions of British colonial rule to both Indian and international audiences", C: "It was fully endorsed by the British government as legitimate political activity", D: "The Japanese Empire supported the movement financially and diplomatically" },
    correct: 'B',
    explanation: "Satyagraha (truth-force) was strategically effective because it put British authorities in an impossible position: either allow protest, which encouraged further activism, or use violence against peaceful protesters, which exposed the violent foundation of colonial rule and delegitimized it internationally. Events like the Amritsar Massacre (1919) and the Salt March (1930) generated massive moral and political pressure.",
  },
  {
    id: 'ac_rm_002', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "The 1919 Amritsar Massacre is significant in the history of Indian nationalism because:",
    choices: { A: "It ended the Indian independence movement by killing its major leaders", B: "British forces killing unarmed protesters massively delegitimized British rule and galvanized Indian nationalist sentiment", C: "It was the first use of British military force against Indian civilians", D: "Gandhi organized the massacre to demonstrate British brutality to the world" },
    correct: 'B',
    explanation: "On April 13, 1919, British General Dyer ordered troops to fire on an unarmed crowd at Jallianwala Bagh, killing at least 379 and wounding over 1,000. The massacre shocked Indians across the political spectrum and radicalized the independence movement. Winston Churchill condemned it in Parliament. Rabindranath Tagore renounced his British knighthood in protest.",
  },
  {
    id: 'ac_rm_003', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "Which of the following best characterizes anti-colonial organizing in Africa during c. 1919-1945?",
    choices: { A: "Armed revolution throughout the continent", B: "Complete passivity as Africans accepted colonial rule", C: "Educated African elites organizing political parties and using journalism to challenge colonial rule", D: "Mass strikes and industrial action by African factory workers" },
    correct: 'C',
    explanation: "Between the wars, Western-educated African elites formed political organizations — the African National Congress (1912), National Council of Nigeria and the Cameroons (1944), and many others — using petitions, journalism, and legal advocacy to challenge colonial policies. These elite movements preceded but laid the groundwork for mass independence movements after World War II.",
  },
  {
    id: 'ac_rm_004', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "The Pan-African movement associated with W.E.B. Du Bois and Marcus Garvey contributed to anti-colonialism primarily by:",
    choices: { A: "Organizing armed rebellions across Africa and the Caribbean", B: "Creating a sense of shared African and African diaspora identity that challenged racist colonial ideology", C: "Seeking the voluntary assimilation of Africans into European civilization", D: "Being primarily a religious movement opposing Christianity" },
    correct: 'B',
    explanation: "Pan-Africanism countered colonial ideology's claim that Africans were inferior and incapable of self-governance by asserting a shared African heritage and dignity. Du Bois organized Pan-African Congresses (1919-1945); Garvey's 'Back to Africa' movement mobilized Black people in the Americas and Africa. This ideological work created the intellectual foundations for post-war African nationalism.",
  },
  {
    id: 'ac_rm_005', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "How did World Wars I and II affect anti-colonial movements?",
    choices: { A: "Wars weakened anti-colonial movements by killing their leaders", B: "Colonial subjects who fought for freedom and democracy exposed the hypocrisy of being denied these same rights", C: "Colonial powers voluntarily granted independence before the wars to secure colonial loyalty", D: "The wars had no significant effect on anti-colonial movements" },
    correct: 'B',
    explanation: "Colonial subjects were asked to fight for Wilson's self-determination, Churchill's Atlantic Charter, and the 'Four Freedoms' while being denied these rights themselves. Ho Chi Minh quoted the American Declaration of Independence; Nehru invoked the Atlantic Charter. This ideological contradiction — fighting for freedom while being colonized — became a powerful argument that European powers struggled to answer.",
  },
  {
    id: 'ac_rm_006', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "The Vietnamese resistance movement against French colonialism, led by Ho Chi Minh, drew on which ideological sources?",
    choices: { A: "Purely traditional Vietnamese nationalism with no foreign ideological influences", B: "A combination of Vietnamese nationalism and Marxist-Leninist ideology", C: "Liberal democratic principles modeled on the American Revolution alone", D: "Buddhist religious teachings applied directly to political organization" },
    correct: 'B',
    explanation: "Ho Chi Minh was a founding member of the French Communist Party who studied both Marxism and Vietnamese nationalism. He combined these: Marxism explained colonial exploitation as class struggle at a global scale; Vietnamese nationalism provided the emotional appeal of liberation from foreign rule. The Viet Minh (1941) mobilized this synthesis against Japanese occupation, then French recolonization.",
  },
  {
    id: 'ac_rm_007', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "What was the primary obstacle facing anti-colonial resistance movements c. 1900-1945?",
    choices: { A: "Lack of any contact or communication between different colonial regions", B: "The overwhelming military, economic, and administrative power of colonial states", C: "Internal divisions among colonial peoples that prevented effective organizing", D: "European colonial powers willingly reformed before resistance could organize" },
    correct: 'B',
    explanation: "Colonial states had industrial-military technology (machine guns, artillery, aircraft), economic control of railroads and communications, and legal systems that criminalized organized opposition. Most anti-colonial movements of this period were ultimately suppressed. The successful movements (Indian independence, Vietnam) required decades of organizing, significant casualties, and ultimately favorable international conditions after 1945.",
  },
  {
    id: 'ac_rm_008', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 3,
    text: "The Indian National Congress (founded 1885) is best characterized as:",
    choices: { A: "An organization that exclusively used armed revolution to achieve independence", B: "A political organization that evolved from moderate petitioning toward mass civil disobedience and eventually independence demand", C: "An organization that consistently collaborated with British authorities", D: "A religious organization representing only Hindu interests" },
    correct: 'B',
    explanation: "The Congress began as a moderate organization of Western-educated lawyers and professionals seeking reforms within the British Empire. Under Gandhi's leadership after 1920, it transformed into a mass movement using non-cooperation, civil disobedience, and boycotts. By 1929 it officially demanded full independence (purna swaraj). This evolution from elite petition to mass movement is a model for many later independence movements.",
  },
  {
    id: 'ac_rm_009', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 2,
    text: "The Maji Maji Rebellion (1905-1907) in German East Africa is historically significant because:",
    choices: { A: "It was the first time Africans used modern firearms against a European army", B: "It demonstrated widespread African resistance to colonial rule despite military suppression", C: "It successfully expelled German colonial forces from the region", D: "It was organized by the Indian National Congress as part of a global anti-colonial strategy" },
    correct: 'B',
    explanation: "The Maji Maji Rebellion united people from diverse ethnic groups across a vast area in armed resistance against German forced cotton cultivation and harsh taxation. German military suppression killed an estimated 200,000-300,000 Africans (mostly from famine following military destruction). Despite defeat, the rebellion demonstrated the breadth of anti-colonial sentiment and became a symbol of Tanzanian national identity after independence.",
  },
  {
    id: 'ac_rm_010', zoneId: 'age_of_crisis', levelId: 'resistance_movements', skillTag: 'resistance', difficulty: 3,
    text: "Which of the following best explains the long-term historical significance of interwar anti-colonial movements?",
    choices: { A: "They achieved immediate independence for most colonized nations by 1945", B: "They built the organizational frameworks, ideological foundations, and leadership that made post-WWII decolonization possible", C: "They convinced European powers to voluntarily begin decolonization before World War II", D: "They had minimal impact as colonialism ended primarily due to European exhaustion after World War II" },
    correct: 'B',
    explanation: "Anti-colonial movements between the wars rarely achieved independence (India being the major exception in 1947). But they created political parties, trained leaders, developed ideologies, built mass organizations, and established international connections (Pan-Africanism, League Against Imperialism). When conditions changed after 1945 — European weakness, Cold War pressure, new UN norms — these movements were ready to press for and achieve independence.",
  },
];
'''

with open('/home/user/ascend/client/src/data/apWorldHistory.js', 'a') as f:
    f.write(content)

print("Zone 4 appended successfully")
