content = '''
  // ── Zone 2: global_contact ────────────────────────────────────────────────
  // Level: columbian_exchange
  {
    id: 'gc_ce_001', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 1,
    text: "The Columbian Exchange refers to:",
    choices: { A: "Columbus trading silk with Native Americans", B: "The transfer of plants, animals, diseases, and ideas between the Old and New Worlds after 1492", C: "The Spanish exchange of gold for European manufactured goods", D: "Columbus's trade agreement with the Portuguese crown" },
    correct: 'B',
    explanation: "Historian Alfred Crosby coined the term 'Columbian Exchange' to describe the broad biological and cultural transfer that followed Columbus's 1492 voyage. It included crops like maize, potatoes, and tomatoes moving to the Old World; wheat, horses, and cattle moving to the Americas; and devastating Old World diseases moving to the Americas.",
  },
  {
    id: 'gc_ce_002', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 1,
    text: "Which crops introduced from the Americas had the greatest impact on population growth in China and Europe?",
    choices: { A: "Corn (maize) and potatoes", B: "Tomatoes and chili peppers", C: "Cacao and vanilla", D: "Tobacco and rubber" },
    correct: 'A',
    explanation: "Maize and potatoes could grow in poor soils and climates unsuited to wheat, dramatically increasing caloric output per acre. In China, maize and sweet potatoes enabled cultivation of previously unusable hilly land. In Europe, the potato allowed Ireland and other regions to support far larger populations. Both crops contributed to the global population explosion of the 18th–19th centuries.",
  },
  {
    id: 'gc_ce_003', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 1,
    text: "The most devastating element of the Columbian Exchange for Indigenous peoples of the Americas was:",
    choices: { A: "European military technology such as guns and cannons", B: "Forced labor in Spanish silver mines", C: "Old World epidemic diseases such as smallpox, measles, and influenza", D: "Deliberate destruction of indigenous agricultural systems" },
    correct: 'C',
    explanation: "Indigenous Americans had no prior exposure to Old World diseases and therefore no immune defenses. Epidemics swept through populations before European colonizers even arrived in some regions. Historians estimate that 50–90% of the pre-contact population of the Americas died within a century of contact — perhaps the greatest demographic catastrophe in human history.",
  },
  {
    id: 'gc_ce_004', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 2,
    text: "Cassava (manioc), introduced to West Africa from the Americas, had which significant historical effect?",
    choices: { A: "It replaced all traditional African crops within a generation", B: "It became a dietary staple that helped feed growing populations in tropical Africa", C: "It was primarily used as animal feed rather than human food", D: "It was rejected by African farmers who preferred familiar crops" },
    correct: 'B',
    explanation: "Cassava is drought-resistant, grows in poor tropical soils, and produces high caloric yields. It spread rapidly across tropical Africa after Portuguese traders introduced it from Brazil. Along with maize (corn), cassava became a dietary staple that helped support population growth in many African regions.",
  },
  {
    id: 'gc_ce_005', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 2,
    text: "The introduction of Old World animals such as horses and cattle to the Americas most significantly:",
    choices: { A: "Had minimal impact as indigenous peoples quickly domesticated local animals instead", B: "Was resisted by all indigenous peoples who viewed the animals as threats", C: "Transformed many indigenous economies and cultures, particularly among Plains peoples who adopted equestrian buffalo hunting", D: "Led directly to the military collapse of all indigenous empires" },
    correct: 'C',
    explanation: "The horse, which had gone extinct in the Americas thousands of years earlier, was reintroduced by Spaniards. By the 18th century, Plains peoples like the Comanche and Lakota had built powerful cultures centered on mounted buffalo hunting that had not existed before European contact. This demonstrates that the Columbian Exchange created new cultures, not just destroyed old ones.",
  },
  {
    id: 'gc_ce_006', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 2,
    text: "How did the Columbian Exchange affect Old World population growth c. 1500–1800?",
    choices: { A: "Old World populations declined as New World diseases ravaged Europe", B: "American food crops increased caloric availability and contributed significantly to Old World population growth", C: "The exchange had no measurable demographic impact on the Old World", D: "European populations declined as millions emigrated to the Americas" },
    correct: 'B',
    explanation: "While the Americas suffered devastating population loss, the Old World experienced population growth partly fueled by American crops. High-calorie foods like maize and potatoes expanded the food supply in Europe, Africa, and Asia, supporting larger populations — the foundation for eventual industrialization.",
  },
  {
    id: 'gc_ce_007', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 1,
    text: "Which of the following was NOT transferred from the Old World to the Americas via the Columbian Exchange?",
    choices: { A: "Smallpox", B: "Horses", C: "Potatoes", D: "Wheat" },
    correct: 'C',
    explanation: "Potatoes are a New World crop that originated in the Andes. They were transferred from the Americas to the Old World, not the other way around. Smallpox, horses, and wheat all originated in the Old World and were brought to the Americas after 1492.",
  },
  {
    id: 'gc_ce_008', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 2,
    text: "Tobacco, introduced from the Americas to Europe, is historically significant because:",
    choices: { A: "It became a major cash crop driving colonial plantation economies and the labor demand behind the Atlantic slave trade", B: "It replaced sugar as the primary trade good from the Caribbean", C: "It was immediately banned in most European countries due to health concerns", D: "It was exclusively grown in North America with no impact on the Caribbean" },
    correct: 'A',
    explanation: "Tobacco cultivation in Virginia and the Caribbean required intensive labor on large plantations, driving demand for enslaved African workers. It was one of the first cash crops to create the plantation model that later expanded to sugar, cotton, and indigo. By the 17th century, tobacco was one of the most valuable commodities in Atlantic trade.",
  },
  {
    id: 'gc_ce_009', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 3,
    text: "How did Caribbean indigenous populations respond to European contact after 1492?",
    choices: { A: "They largely survived and integrated into European colonial society", B: "They were nearly wiped out within decades due to disease, violence, and forced labor", C: "They successfully resisted European colonization for over a century", D: "They were relocated to the American mainland where they survived" },
    correct: 'B',
    explanation: "The Taino people of the Caribbean, numbering perhaps 1 million at contact, were nearly extinct within 50 years of Columbus's arrival. A combination of epidemic diseases, brutal forced labor in mines and fields (encomienda), violence, and starvation caused catastrophic population collapse. This demographic disaster created the labor vacuum that drove the Atlantic slave trade.",
  },
  {
    id: 'gc_ce_010', zoneId: 'global_contact', levelId: 'columbian_exchange', skillTag: 'columbian', difficulty: 2,
    text: "The Columbian Exchange most directly contributed to the Atlantic slave trade by:",
    choices: { A: "Creating demand for tropical cash crops requiring large labor forces that indigenous peoples could not supply after population collapse", B: "Introducing diseases that killed European indentured servants in the tropics", C: "Providing African merchants with new crops they exchanged for enslaved captives", D: "Supplying the ships needed for transatlantic slave voyages" },
    correct: 'A',
    explanation: "The combination of indigenous population collapse from disease and the enormous profitability of tropical cash crops (sugar, tobacco, coffee, cotton) created an unsustainable labor gap. European colonizers turned to the Atlantic slave trade to fill this gap, importing millions of enslaved Africans to work plantations in the Americas.",
  },
  // Level: atlantic_slave_trade
  {
    id: 'gc_as_001', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 1,
    text: "The Atlantic slave trade involved the forced transportation of enslaved Africans primarily to:",
    choices: { A: "Europe and Asia for domestic service", B: "The Americas to provide plantation labor for cash crop production", C: "The Middle East to replace enslaved people in Arab households", D: "Australia and Southeast Asia as colonial laborers" },
    correct: 'B',
    explanation: "The Atlantic slave trade (c. 1500–1867) transported approximately 12.5 million Africans across the Atlantic, with the vast majority going to the Caribbean and South America to work on sugar, tobacco, coffee, and cotton plantations. Only about 4% went to North America.",
  },
  {
    id: 'gc_as_002', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 1,
    text: "Approximately how many Africans were forcibly transported across the Atlantic between c. 1500 and 1867?",
    choices: { A: "500,000", B: "3 million", C: "12.5 million", D: "50 million" },
    correct: 'C',
    explanation: "The Trans-Atlantic Slave Trade Database documents approximately 12.5 million enslaved Africans transported to the Americas, of whom roughly 10.7 million survived the Middle Passage. This represents the largest forced migration in human history before the 20th century.",
  },
  {
    id: 'gc_as_003', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 1,
    text: "Which European nation initiated the Atlantic slave trade?",
    choices: { A: "Britain", B: "France", C: "Portugal", D: "Spain" },
    correct: 'C',
    explanation: "Portugal began transporting enslaved Africans to sugar plantations on Atlantic islands (Madeira, Cape Verde, Sao Tome) in the 1440s, then to Brazil after 1500. Portugal remained the largest single carrier in the Atlantic slave trade, responsible for transporting roughly 5.8 million of the 12.5 million enslaved Africans.",
  },
  {
    id: 'gc_as_004', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 2,
    text: "The 'triangular trade' of the Atlantic slave trade consisted of:",
    choices: { A: "Three ships trading with three different continents simultaneously", B: "Europeans carrying manufactured goods to Africa, enslaved people to the Americas, and raw materials back to Europe", C: "Three European nations sharing control of the slave trade equally", D: "A three-stop trade route connecting Africa, the Middle East, and Asia" },
    correct: 'B',
    explanation: "The triangular trade involved European ships carrying firearms, textiles, and other goods to West Africa; trading these for enslaved people who were transported across the Atlantic (the Middle Passage); then returning to Europe loaded with colonial goods — sugar, tobacco, coffee, cotton — produced by enslaved labor in the Americas.",
  },
  {
    id: 'gc_as_005', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 1,
    text: "The 'Middle Passage' refers to:",
    choices: { A: "The overland route through the American interior", B: "The passage of enslaved people through African coastal ports", C: "The transatlantic voyage of enslaved Africans from Africa to the Americas", D: "A mountain pass used by Spanish explorers in the Andes" },
    correct: 'C',
    explanation: "The Middle Passage was the central leg of the triangular trade — the ocean crossing from West Africa to the Americas. Enslaved people were packed into ships under horrific conditions; mortality rates during the crossing ranged from 10–20%. Resistance, disease, and deliberate cruelty made it one of history's most brutal human experiences.",
  },
  {
    id: 'gc_as_006', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 2,
    text: "How did African political elites participate in the Atlantic slave trade?",
    choices: { A: "They universally resisted and fought against European slave traders", B: "Many African rulers and merchants actively sold captives (prisoners of war, criminals, debtors) to European traders", C: "African elites were themselves the primary victims of European kidnapping raids", D: "African states had no role and were entirely passive victims" },
    correct: 'B',
    explanation: "The Atlantic slave trade required African cooperation. African rulers and merchants supplied the enslaved people, typically war captives from conflicts with neighboring states. Some kingdoms like Dahomey and Asante built their power partly on slave-trading. This does not reduce European responsibility but complicates simplistic narratives.",
  },
  {
    id: 'gc_as_007', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 2,
    text: "How did the Atlantic slave trade most significantly affect West and Central African societies?",
    choices: { A: "It brought wealth equally to all West Africans through trade profits", B: "It caused massive population loss and destabilized regional political structures through increased warfare", C: "Its effects were limited to coastal areas with minimal impact on the interior", D: "It led to the strengthening of all African kingdoms without exception" },
    correct: 'B',
    explanation: "Historians estimate Africa lost 12.5 million people to the Atlantic trade alone (plus millions more to the trans-Saharan and Indian Ocean slave trades). The trade incentivized African rulers to make war on neighbors to capture enslaved people, creating cycles of instability. Some regions were depopulated; demographic and social damage persisted for generations.",
  },
  {
    id: 'gc_as_008', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 2,
    text: "The survival of African cultural practices in the Americas — music, religious traditions, foodways, language elements — demonstrates:",
    choices: { A: "That enslaved people fully assimilated into European colonial culture", B: "That cultural exchange only flowed from Europeans to Africans", C: "The resilience of African cultural traditions even under conditions of extreme oppression", D: "That most enslaved people came from the same specific African region" },
    correct: 'C',
    explanation: "Despite systematic efforts to erase African identity, enslaved people maintained and adapted cultural practices. African musical traditions contributed to jazz, blues, and samba; African religious practices blended with Christianity to create Vodou and Candomble; African food plants and cooking techniques shaped American cuisines. This cultural persistence represents remarkable human resilience.",
  },
  {
    id: 'gc_as_009', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 3,
    text: "What most distinguished the Atlantic slave trade from earlier forms of slavery in world history?",
    choices: { A: "It was more humane than slavery in ancient Rome or Greece", B: "It was the first time enslaved people were used for agricultural labor", C: "It was racially based, involving unprecedented scale, and created a permanent hereditary enslaved caste", D: "It was universally condemned by all European governments from the start" },
    correct: 'C',
    explanation: "While slavery existed in many earlier societies, the Atlantic trade created something historically distinctive: a racial system of chattel slavery in which African descent itself marked a person as potentially enslaved, children of enslaved women were automatically enslaved, and enslaved people had no legal personhood. The scale (12.5 million people over 400 years) was also historically unprecedented.",
  },
  {
    id: 'gc_as_010', zoneId: 'global_contact', levelId: 'atlantic_slave_trade', skillTag: 'slavery', difficulty: 2,
    text: "The Atlantic slave trade's most significant long-term global economic impact was:",
    choices: { A: "Enriching African rulers who sold enslaved captives", B: "Generating capital and cheap raw materials that contributed to European industrialization and the growth of the Atlantic economy", C: "Developing the economies of the regions where enslaved people were held", D: "Stimulating technological innovation in Africa" },
    correct: 'B',
    explanation: "Historians like Eric Williams argued that profits from the slave trade and slave-produced goods (sugar, cotton, tobacco) provided capital for British industrialization. Whether this causal link is direct is debated, but the plantation complex undeniably generated enormous wealth that flowed primarily to European merchants, manufacturers, and investors.",
  },
  // Level: gunpowder_empires
  {
    id: 'gc_ge_001', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 1,
    text: "The term 'Gunpowder Empires' most commonly refers to which group of early modern empires?",
    choices: { A: "The British, French, and Spanish empires", B: "The Ottoman, Safavid, and Mughal empires", C: "The Ming, Qing, and Joseon empires", D: "The Aztec, Inca, and Maya empires" },
    correct: 'B',
    explanation: "Historian Marshall Hodgson coined this term to describe three Islamic empires — Ottoman (Turkey/Middle East), Safavid (Persia), and Mughal (India) — that used gunpowder weapons (cannon and firearms) to conquer and consolidate large territories. The Ming and Qing dynasties also used gunpowder extensively but are not typically included in this grouping.",
  },
  {
    id: 'gc_ge_002', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 1,
    text: "The Ottoman conquest of Constantinople in 1453 was historically significant because it:",
    choices: { A: "Ended the Christian Crusades permanently", B: "Ended the Byzantine Empire and gave the Ottomans control over the eastern Mediterranean", C: "Gave the Ottomans control of Atlantic trade routes", D: "Was the first use of gunpowder weapons in siege warfare" },
    correct: 'B',
    explanation: "Constantinople had been the capital of the Byzantine (Eastern Roman) Empire for over a thousand years. Its fall ended the last remnant of the Roman Empire. Ottoman control of the Bosphorus gave them leverage over Black Sea trade and threatened European access to eastern markets — a factor that motivated European exploration of alternative routes to Asia.",
  },
  {
    id: 'gc_ge_003', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "Emperor Akbar of the Mughal Empire (r. 1556–1605) is notable for his policy of:",
    choices: { A: "Forcibly converting all Hindus to Islam", B: "Religious tolerance that incorporated Hindu, Jain, and other traditions into Mughal governance", C: "Complete separation of religious and political authority", D: "Military alliance with the Safavid Empire against the Ottomans" },
    correct: 'B',
    explanation: "Akbar ruled over a Hindu-majority population as a Muslim emperor. He abolished the jizya tax on non-Muslims, married Hindu Rajput princesses, incorporated Hindu nobles into his administration, and created a syncretic personal philosophy called Din-i-Ilahi. His religious tolerance was politically practical and made him one of the most celebrated rulers in Indian history.",
  },
  {
    id: 'gc_ge_004', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "The Safavid Empire in Persia is historically distinctive for:",
    choices: { A: "Conquering the Ottoman Empire and unifying the Muslim world", B: "Establishing Twelver Shia Islam as the state religion, creating a lasting Sunni-Shia divide", C: "Building the largest maritime empire in the Indian Ocean", D: "Uniting all Muslims under a single caliphate after 1501" },
    correct: 'B',
    explanation: "Shah Ismail I forcibly converted Persia from predominantly Sunni to Shia Islam after 1501, creating a distinct Persian/Shia identity that still defines Iran today. The Safavid-Ottoman rivalry became partly a sectarian conflict between Shia and Sunni Islam, shaping the political geography of the Middle East.",
  },
  {
    id: 'gc_ge_005', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "The Ottoman devshirme system was:",
    choices: { A: "A tax collection method from non-Muslim subjects", B: "The practice of recruiting Christian boys, converting them, and training them as elite soldiers (Janissaries) and administrators", C: "Trade privileges granted to European merchants in Ottoman ports", D: "Land grants (timar) given to Ottoman cavalry soldiers" },
    correct: 'B',
    explanation: "The devshirme ('collection' in Turkish) recruited boys from Christian families in the Balkans, converted them to Islam, and educated them for imperial service. Some became Janissaries (elite infantry); others became top administrators, even grand viziers. This system gave the sultan a loyal bureaucracy that owed everything to him and had no independent power base.",
  },
  {
    id: 'gc_ge_006', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 3,
    text: "How did the Gunpowder Empires compare to contemporary European states in terms of size and population?",
    choices: { A: "They were economically and militarily weaker than European empires", B: "They were roughly equal to the largest European states in power", C: "They were generally larger, wealthier, and more populous than any single European state through the 17th century", D: "They were significant powers but declined before European empires rose" },
    correct: 'C',
    explanation: "In the 16th and 17th centuries, the Ottoman, Safavid, and Mughal empires dominated their respective regions. The Mughal Empire under Aurangzeb (late 17th century) ruled roughly 100 million people — more than all of Western Europe combined. European powers began to surpass these empires in the 18th century as industrialization shifted the balance of power.",
  },
  {
    id: 'gc_ge_007', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "The conflict between the Ottoman and Safavid empires was primarily driven by:",
    choices: { A: "Competition for control of Indian Ocean trade routes", B: "The Sunni-Shia religious divide combined with territorial disputes over Mesopotamia and Azerbaijan", C: "Competition for control of Mediterranean sea lanes", D: "European powers encouraging the two empires to fight each other" },
    correct: 'B',
    explanation: "The Ottoman-Safavid Wars (1514–1639) were a series of conflicts fought over both religious supremacy (Sunni vs. Shia) and territory. The Battle of Chaldiran (1514) was an early decisive Ottoman victory, but the conflict continued for over a century. The border they eventually agreed upon in 1639 largely corresponds to the modern Iran-Iraq border.",
  },
  {
    id: 'gc_ge_008', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "How did the Ming Dynasty's response to European contact differ from the Mughal and Ottoman responses?",
    choices: { A: "The Ming eagerly embraced European trade and missionaries", B: "The Ming restricted maritime trade and eventually limited European contact to specific ports", C: "The Ming formed military alliances with Portugal against the Ottomans", D: "The Ming conquered European trading posts in Southeast Asia" },
    correct: 'B',
    explanation: "The Ming Dynasty had a complex relationship with maritime trade. After ending Zheng He's voyages, the dynasty restricted private maritime trade, though it was never fully stopped. When Europeans arrived, China allowed limited trade through specified ports (like Macau for Portuguese) while maintaining strict controls. The Qing Dynasty continued similar policies.",
  },
  {
    id: 'gc_ge_009', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 3,
    text: "What was a common feature shared by the Ottoman, Safavid, and Mughal empires in terms of governance?",
    choices: { A: "All three were governed by elected assemblies of nobles", B: "All three used bureaucratic administration combined with military force, justified by Islamic religious authority", C: "All three allowed complete religious freedom without state religion", D: "All three were primarily maritime empires dependent on naval power" },
    correct: 'B',
    explanation: "All three Gunpowder Empires governed through a combination of military might (enabled by firearms), bureaucratic administration, and Islamic religious legitimacy. Their rulers claimed both political and religious authority — the Ottoman sultan held the title of caliph, Safavid shahs claimed descent from Shia imams, and Mughal emperors used Islamic imagery in their titles.",
  },
  {
    id: 'gc_ge_010', zoneId: 'global_contact', levelId: 'gunpowder_empires', skillTag: 'empires', difficulty: 2,
    text: "The long-term decline of the Gunpowder Empires after c. 1700 was most directly connected to:",
    choices: { A: "Military defeat by Mongol successor states", B: "A combination of European industrial and military advances, internal succession conflicts, and fiscal strain", C: "Conversion of their populations away from Islam", D: "Climate change destroying agricultural productivity" },
    correct: 'B',
    explanation: "All three empires faced similar challenges: European powers with industrially produced weapons gained military advantages; internal succession crises weakened central authority; the cost of maintaining large armies strained treasuries; and regional elites captured increasing autonomy. These factors combined differently in each empire but drove a general decline in the 18th–19th centuries.",
  },
  // Level: maritime_silver
  {
    id: 'gc_ms_001', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 1,
    text: "The Manila Galleon trade, established in 1565, created a direct trading link between:",
    choices: { A: "Portugal and China via the Indian Ocean", B: "Spanish Americas and the Philippines/China via the Pacific", C: "Britain and Japan via the North Pacific", D: "India and the Americas via both oceans" },
    correct: 'B',
    explanation: "The Manila Galleon trade connected Acapulco (Mexico) to Manila (Philippines) annually. Silver from Potosi and Mexican mines flowed across the Pacific to China in exchange for Chinese silk, porcelain, and other luxury goods. This created the first direct commercial link across the Pacific and made silver a truly global commodity.",
  },
  {
    id: 'gc_ms_002', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "Why did China eagerly import large quantities of American silver during c. 1550–1750?",
    choices: { A: "To build up military reserves for expansion into Central Asia", B: "The Ming Dynasty had switched to a silver-based tax system, creating enormous domestic demand for silver", C: "The Chinese emperor personally collected silver as a tribute payment from all provinces", D: "To trade with Japan for silk and porcelain that China lacked" },
    correct: 'B',
    explanation: "The Ming Dynasty's Single Whip Reform (1581) required that taxes be paid in silver rather than in goods or labor. Since China's domestic silver production was limited, it created insatiable demand. American silver arrived via Manila, fueling Chinese commerce while causing inflation in Spain and contributing to the price revolution in Europe.",
  },
  {
    id: 'gc_ms_003', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 1,
    text: "Potosi (in modern Bolivia) was historically significant during c. 1545–1800 because:",
    choices: { A: "It was the site of the first Spanish colonial government in the Americas", B: "It was one of the largest cities in the world and home to the most productive silver mines in history", C: "It was the primary Caribbean port for exporting sugar to Europe", D: "It was the location where the first Columbian Exchange of crops occurred" },
    correct: 'B',
    explanation: "At its peak in the early 17th century, Potosi had a population of 160,000 — one of the world's largest cities. The silver mountain (Cerro Rico) produced roughly 60% of the world's silver. This silver transformed global commerce but came at horrific human cost: the mita labor system forced indigenous men to work in deadly conditions, and mortality rates were catastrophic.",
  },
  {
    id: 'gc_ms_004', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "How did the massive influx of American silver affect the Spanish economy by the late 16th century?",
    choices: { A: "It made Spain economically self-sufficient and debt-free", B: "It caused significant inflation (the Price Revolution) while Spain became dependent on imports rather than developing domestic industry", C: "It allowed Spain to industrialize before other European nations", D: "It had minimal impact as silver was redistributed equally among European nations" },
    correct: 'B',
    explanation: "The flood of silver caused the Price Revolution — inflation that eroded the purchasing power of wages and fixed incomes across Europe. Spain, rather than investing in manufacturing, used silver to buy foreign goods. Spain repeatedly went bankrupt despite controlling the world's largest silver supply because it spent more than it received. The silver ultimately flowed to China and other Asian economies.",
  },
  {
    id: 'gc_ms_005', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "The Portuguese Estado da India (State of India) was primarily designed to:",
    choices: { A: "Colonize India with Portuguese settlers", B: "Control key ports and straits to extract tolls and dominate Indian Ocean trade by force", C: "Convert all Indians to Christianity", D: "Establish a land empire in the Indian interior" },
    correct: 'B',
    explanation: "Portugal's strategy in the Indian Ocean was commercial rather than territorial. They built fortified trading posts (feitorias) at key chokepoints — Hormuz, Goa, Malacca, Mozambique — and used cannon-armed ships to demand that merchants pay them for passage. This strategy inserted Portuguese power into existing trade networks without the expense of territorial conquest.",
  },
  {
    id: 'gc_ms_006', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "Which of the following best describes the role of American silver in the global economy c. 1550–1750?",
    choices: { A: "Silver connected regional economies into a genuinely global trading system for the first time", B: "Silver replaced gold entirely as the universal medium of exchange", C: "Silver was primarily used for jewelry with little macroeconomic impact", D: "Only China and Spain used silver as currency" },
    correct: 'A',
    explanation: "American silver flowed across both the Atlantic (to Europe and Africa) and Pacific (to Asia), creating the first truly integrated global economy. Silver mined in Bolivia could buy Chinese silk, which could be sold in Mexico, whose silver funded European wars that drew in African slaves. Historian Dennis Flynn calls this the birth of globalization.",
  },
  {
    id: 'gc_ms_007', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "The Dutch East India Company (VOC), founded in 1602, was historically innovative because:",
    choices: { A: "It was the first company to trade in the Indian Ocean", B: "It was one of the first joint-stock companies, allowing investors to share risk and was backed by state power", C: "It colonized India entirely and displaced the Portuguese", D: "It monopolized the Atlantic slave trade from 1602 onward" },
    correct: 'B',
    explanation: "The VOC issued shares to investors, distributing both the risk of long ocean voyages and the enormous potential profits. It was granted quasi-governmental powers — the right to wage war, negotiate treaties, establish colonies, and coin money. This model of joint-stock company backed by state power became a template for later European imperial ventures.",
  },
  {
    id: 'gc_ms_008', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 3,
    text: "How did the rise of European maritime empires affect the Indian Ocean trade network?",
    choices: { A: "European ships immediately dominated and replaced all earlier trade within decades", B: "Europeans gradually inserted themselves into existing networks using cannon-armed ships to control key ports while trade volumes actually grew", C: "The Indian Ocean networks collapsed permanently within a century of Portuguese arrival", D: "Trade volumes declined as Europeans restricted competition from Asian merchants" },
    correct: 'B',
    explanation: "The Portuguese disrupted but did not destroy the Indian Ocean trade. They forced merchants to purchase cartazes (passes) and diverted some trade through Portuguese-controlled ports. However, Asian merchants adapted, found alternative routes, and total trade volumes grew. The Dutch and British later expanded trade further. European dominance was more about controlling profits than destroying commerce.",
  },
  {
    id: 'gc_ms_009', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 2,
    text: "The encomienda system in Spanish colonial America was:",
    choices: { A: "A form of indirect rule where indigenous rulers governed under Spanish supervision", B: "A labor system where Spanish colonists were granted indigenous labor in exchange for supposed Christianization and protection", C: "A plantation system using exclusively African enslaved labor", D: "A tax system requiring indigenous people to pay silver tributes to the Spanish crown" },
    correct: 'B',
    explanation: "Encomienda granted Spanish colonists (encomenderos) the labor of indigenous people in a specific area. In theory, encomenderos were supposed to provide instruction in Christianity and 'civilization.' In practice, it was brutal forced labor that contributed to indigenous population collapse. It was gradually replaced by the mita and repartimiento systems as populations declined.",
  },
  {
    id: 'gc_ms_010', zoneId: 'global_contact', levelId: 'maritime_silver', skillTag: 'silver', difficulty: 3,
    text: "The silver trade's greatest historical significance for world history is that it:",
    choices: { A: "Made Spain the permanent dominant power in global affairs", B: "Created the first genuinely global economy linking the Americas, Europe, Africa, and Asia through trade", C: "Eliminated economic inequality between European and Asian nations", D: "Led to the immediate collapse of the Ottoman and Mughal empires" },
    correct: 'B',
    explanation: "American silver was the commodity that first truly integrated the world economy. It flowed from mines in Bolivia and Mexico around the globe — funding European wars, purchasing Chinese goods, enabling the Atlantic slave trade, and integrating previously separate regional economies into a single interconnected system. This early globalization had profound effects on every region it touched.",
  },
  // Level: cultural_encounters
  {
    id: 'gc_cu_001', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 1,
    text: "The term 'syncretism' in the context of cultural encounters c. 1450–1750 refers to:",
    choices: { A: "The complete replacement of one culture by another through conquest", B: "The blending of different cultural or religious traditions into new hybrid forms", C: "The peaceful coexistence of cultures without any mixing or exchange", D: "The violent conflict between two incompatible cultural systems" },
    correct: 'B',
    explanation: "Syncretism describes the merging of different cultural, religious, or philosophical traditions into new hybrid forms. It was common wherever cultures came into sustained contact — colonial Americas, Swahili East Africa, and Mughal India all produced rich syncretic cultures that blended elements from multiple traditions.",
  },
  {
    id: 'gc_cu_002', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "The Virgin of Guadalupe in colonial Mexico represents religious syncretism because:",
    choices: { A: "She is a purely European Catholic figure transplanted unchanged to Mexico", B: "She blends Catholic Marian devotion with elements of indigenous religious traditions", C: "She was created by Spanish missionaries to completely replace indigenous religion", D: "She was rejected by Spanish church authorities as heretical" },
    correct: 'B',
    explanation: "The Virgin of Guadalupe — said to have appeared to indigenous man Juan Diego in 1531 on a site previously sacred to the Aztec goddess Tonantzin — became the most powerful religious symbol in Mexican Catholicism. Scholars interpret her as a syncretic figure that merged Catholic and indigenous traditions, enabling genuine conversion rather than mere surface compliance.",
  },
  {
    id: 'gc_cu_003', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "Jesuit missionaries in China (c. 1580–1700) attempted to spread Christianity by:",
    choices: { A: "Demanding Chinese converts abandon all Confucian practices", B: "Adapting Christian teachings to Chinese cultural context, incorporating Confucian concepts (the accommodation strategy)", C: "Relying on Portuguese military force to compel conversions", D: "Restricting their mission to translating the New Testament into Chinese" },
    correct: 'B',
    explanation: "Matteo Ricci and other Jesuits learned Chinese, adopted Confucian dress, and argued that Chinese ancestor veneration was compatible with Christianity. They won favor at the imperial court through their scientific knowledge (astronomy, mathematics). This accommodation strategy was controversial — eventually condemned by the Pope in the Chinese Rites Controversy — but reflected a broader Jesuit approach of cultural adaptation.",
  },
  {
    id: 'gc_cu_004', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "Japan's decision to severely restrict European contact (sakoku policy, 1630s) was primarily motivated by:",
    choices: { A: "Fear of European military conquest", B: "Economic reasons as European trade had become unprofitable", C: "Concern that Christian missionaries and European traders undermined political stability and Tokugawa authority", D: "Buddhist opposition to interaction with non-Buddhist foreigners" },
    correct: 'C',
    explanation: "The Tokugawa shogunate saw Christianity as a subversive ideology that gave Japanese Christians loyalty to a foreign power (the Pope) above the shogun. European traders also brought firearms that could arm opponents. The sakoku policy expelled Portuguese missionaries, banned Christianity, and restricted trade to Dutch merchants at Dejima — who were kept in a small artificial island — and Chinese merchants.",
  },
  {
    id: 'gc_cu_005', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "The spread of Catholicism in Spanish Latin America is best described as:",
    choices: { A: "A purely voluntary conversion with no coercion involved", B: "Entirely forced conversion achieved exclusively through violence", C: "A complex process involving both coercion and genuine conversion that often produced syncretic religious practices", D: "A complete failure to convert indigenous populations" },
    correct: 'C',
    explanation: "Catholicism spread through a combination of violent coercion (destruction of indigenous temples, criminalization of indigenous religion) and genuine spiritual appeal. Many indigenous people found meaning in Catholic ritual and incorporated indigenous elements into their practice. The result was neither pure European Catholicism nor unchanged indigenous religion, but hybrid forms.",
  },
  {
    id: 'gc_cu_006', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 3,
    text: "Why were some Japanese daimyo (lords) initially receptive to Portuguese missionaries c. 1550–1600?",
    choices: { A: "Japanese culture was already monotheistic and found Christianity familiar", B: "Portuguese missionaries came with trade goods and firearms that daimyo wanted for their military conflicts", C: "The Japanese emperor ordered acceptance of Christianity as a diplomatic gesture", D: "Portuguese missionaries spoke fluent Japanese and seemed to understand Japanese culture" },
    correct: 'B',
    explanation: "Portuguese missionaries arrived with merchants carrying firearms (arquebuses) that were transformative military technology in Japan's Sengoku (Warring States) period. Daimyo who allowed missionaries to operate in their territories gained preferential access to these weapons. Christianity may have appealed to some on spiritual grounds, but the political-military calculus drove initial acceptance.",
  },
  {
    id: 'gc_cu_007', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "How did European colonization most significantly affect indigenous knowledge systems?",
    choices: { A: "Europeans universally preserved and systematically documented indigenous knowledge", B: "European colonizers frequently suppressed indigenous knowledge while also adapting some practices (especially medical and agricultural knowledge)", C: "Indigenous knowledge systems were completely and permanently destroyed within a generation", D: "Indigenous knowledge fully absorbed and transformed European science" },
    correct: 'B',
    explanation: "Colonial encounters produced a paradox: European colonizers destroyed indigenous libraries (like Bishop Landa burning Maya codices in 1562), criminalized indigenous religious practice, and dismissed indigenous knowledge as superstition — while simultaneously adopting indigenous crops, medicines, and agricultural techniques. European botany, medicine, and cartography all benefited from indigenous knowledge even as colonial systems suppressed it.",
  },
  {
    id: 'gc_cu_008', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "The concept of 'cultural diffusion' as illustrated by the spread of crops, religions, and technologies c. 1450–1750 most directly shows:",
    choices: { A: "That cultures only change when conquered by external powers", B: "That contact between cultures produces the exchange and adaptation of ideas, practices, and goods", C: "That stronger cultures always replace weaker ones", D: "That trade has no cultural consequences beyond economics" },
    correct: 'B',
    explanation: "Cultural diffusion — the spread of cultural elements from one society to another — was dramatically accelerated by the connections forged in c. 1450–1750. Crops, religions, languages, technologies, art forms, and diseases all moved across previously separate cultural zones. This diffusion created both new hybrid cultures and violent conflicts.",
  },
  {
    id: 'gc_cu_009', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 3,
    text: "The Protestant Reformation's relationship to European overseas colonization is best described as:",
    choices: { A: "Having no connection to colonization patterns", B: "Protestant nations rejected overseas colonization as sinful or wasteful", C: "Religious competition between Catholic and Protestant nations partly motivated and shaped European expansion and colonial rivalry", D: "All European colonies became Protestant after the Reformation" },
    correct: 'C',
    explanation: "The Reformation created new Protestant powers (England, the Netherlands) that competed with Catholic Spain and Portugal for colonial territory. Protestant missionaries competed with Catholic ones for converts. Religious identity shaped colonial cultures differently — English Protestant colonies differed from Spanish Catholic ones in governance, settlement patterns, and attitudes toward indigenous peoples.",
  },
  {
    id: 'gc_cu_010', zoneId: 'global_contact', levelId: 'cultural_encounters', skillTag: 'culture', difficulty: 2,
    text: "Which of the following best illustrates the historical concept of 'creolization' in the context of c. 1500–1750?",
    choices: { A: "Europeans maintaining their culture unchanged in colonial settings", B: "Indigenous cultures surviving without any European influence", C: "New hybrid cultures emerging in colonial settings that drew on African, European, and indigenous elements", D: "African cultures being completely replaced by European ones in the Americas" },
    correct: 'C',
    explanation: "Creolization describes the creation of new cultures in colonial contexts — particularly in the Caribbean and Americas — that blended African, indigenous American, and European elements in unique combinations. Creole languages, religions, music, and foodways all emerged from this forced multicultural encounter and represent some of the most distinctive cultural innovations of the early modern period.",
  },
];
'''

with open('/home/user/ascend/client/src/data/apWorldHistory.js', 'a') as f:
    f.write(content)

print("Zone 2 appended successfully")
