content = '''// AP World History Modern — zones and questions (c. 1200–present)

export const zones = [
  {
    id: 'crossroads_world',
    name: 'The Crossroads World',
    theme: 'Silk Roads, Mongols, Indian Ocean, African kingdoms',
    bossName: 'The Mongol Warlord',
    bossDescription: 'Master of the vast steppe empire',
    emoji: '🏰',
    color: '#FFB830',
    levels: [
      { id: 'silk_roads', name: 'Silk Roads & Trade', skillTag: 'trade' },
      { id: 'mongol_empire', name: 'The Mongol Empire', skillTag: 'mongols' },
      { id: 'indian_ocean', name: 'Indian Ocean Network', skillTag: 'maritime' },
      { id: 'african_kingdoms', name: 'African Kingdoms', skillTag: 'africa' },
      { id: 'black_death', name: 'Black Death & Plague', skillTag: 'plague' },
    ],
  },
  {
    id: 'global_contact',
    name: 'Age of Global Contact',
    theme: 'Columbian Exchange, Atlantic slave trade, gunpowder empires',
    bossName: 'The Sea Admiral',
    bossDescription: 'Commander of the maritime empire',
    emoji: '⛵',
    color: '#7B4FE9',
    levels: [
      { id: 'columbian_exchange', name: 'Columbian Exchange', skillTag: 'columbian' },
      { id: 'atlantic_slave_trade', name: 'Atlantic Slave Trade', skillTag: 'slavery' },
      { id: 'gunpowder_empires', name: 'Gunpowder Empires', skillTag: 'empires' },
      { id: 'maritime_silver', name: 'Maritime Empires & Silver', skillTag: 'silver' },
      { id: 'cultural_encounters', name: 'Cultural Encounters', skillTag: 'culture' },
    ],
  },
  {
    id: 'revolution_industry',
    name: 'Revolution & Industry',
    theme: 'Atlantic revolutions, industrialization, imperialism',
    bossName: 'The Iron Chancellor',
    bossDescription: 'Architect of nationalist industrial power',
    emoji: '⚔️',
    color: '#E8445A',
    levels: [
      { id: 'atlantic_revolutions', name: 'Atlantic Revolutions', skillTag: 'revolution' },
      { id: 'industrial_revolution', name: 'Industrial Revolution', skillTag: 'industry' },
      { id: 'nationalism', name: 'Nationalism & Unification', skillTag: 'nationalism' },
      { id: 'imperialism', name: 'Imperialism & Colonialism', skillTag: 'imperialism' },
      { id: 'social_reform', name: 'Social Reform Movements', skillTag: 'reform' },
    ],
  },
  {
    id: 'age_of_crisis',
    name: 'The Age of Crisis',
    theme: 'World wars, totalitarianism, depression, resistance',
    bossName: 'The Totalitarian',
    bossDescription: 'Ruler who demands total loyalty',
    emoji: '💣',
    color: '#5B9CF6',
    levels: [
      { id: 'wwi', name: 'World War I', skillTag: 'wwi' },
      { id: 'totalitarianism', name: 'Rise of Totalitarianism', skillTag: 'totalitarian' },
      { id: 'great_depression', name: 'The Great Depression', skillTag: 'depression' },
      { id: 'wwii', name: 'World War II & Holocaust', skillTag: 'wwii' },
      { id: 'resistance_movements', name: 'Resistance & Decolonization', skillTag: 'resistance' },
    ],
  },
  {
    id: 'modern_world',
    name: 'The Contemporary World',
    theme: 'Cold War, decolonization, globalization, technology',
    bossName: 'The Final Arbiter',
    bossDescription: 'Judge of the modern global order',
    emoji: '🌍',
    color: '#2ECC71',
    levels: [
      { id: 'cold_war', name: 'The Cold War', skillTag: 'coldwar' },
      { id: 'decolonization', name: 'Decolonization', skillTag: 'decolonization' },
      { id: 'globalization', name: 'Globalization & Trade', skillTag: 'globalization' },
      { id: 'environment_demography', name: 'Environment & Demography', skillTag: 'environment' },
      { id: 'technology_contemporary', name: 'Technology & Today', skillTag: 'technology' },
    ],
  },
];

export const questions = [
  // ── Zone 1: crossroads_world ──────────────────────────────────────────────
  // Level: silk_roads
  {
    id: 'cr_sr_001', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 1,
    text: "What was the primary commodity traded along the Silk Roads that gave the trade network its name?",
    choices: { A: "Silk", B: "Spices", C: "Gold", D: "Gunpowder" },
    correct: 'A',
    explanation: "Silk, a luxury textile produced only in China, gave the routes their name. Chinese silk was highly prized in Central Asia, the Middle East, and eventually Europe, making it a dominant trade good that motivated long-distance exchange across Eurasia.",
  },
  {
    id: 'cr_sr_002', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 1,
    text: "Which religion spread most extensively along the Silk Roads during c. 1200–1450?",
    choices: { A: "Christianity", B: "Hinduism", C: "Islam", D: "Buddhism" },
    correct: 'C',
    explanation: "Islam spread widely through merchant and Sufi missionary activity along overland and maritime trade routes. Muslim merchants established communities from West Africa to Southeast Asia, and many rulers converted partly for the commercial advantages of belonging to an Islamic trading network.",
  },
  {
    id: 'cr_sr_003', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 2,
    text: "The Pax Mongolica facilitated long-distance trade primarily by:",
    choices: { A: "Eliminating all tariffs across Eurasia", B: "Providing relative peace and security along trade routes under unified Mongol control", C: "Requiring all merchants to convert to Buddhism", D: "Restricting trade to Mongol merchants only" },
    correct: 'B',
    explanation: "The Pax Mongolica (Mongol Peace) describes the relative stability across the Mongol Empire during the 13th–14th centuries. Unified Mongol rule over Central Asia reduced banditry and political fragmentation, allowing merchants, diplomats, and missionaries like Marco Polo and Ibn Battuta to travel more safely across Eurasia.",
  },
  {
    id: 'cr_sr_004', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 2,
    text: "Ibn Battuta's extensive travels (c. 1325–1354) most directly demonstrate which historical pattern?",
    choices: { A: "That the Silk Roads had collapsed under Mongol rule", B: "That Islamic networks connected much of Afro-Eurasia", C: "That Europe dominated long-distance trade", D: "That maritime routes had replaced overland trade entirely" },
    correct: 'B',
    explanation: "Ibn Battuta traveled roughly 75,000 miles across the Islamic world — from Morocco to Mali, East Africa, Persia, India, and China — staying in Muslim communities throughout. His journey reveals how Islamic commercial and cultural networks knit together much of Afro-Eurasia in the 14th century.",
  },
  {
    id: 'cr_sr_005', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 2,
    text: "How did Mongol-era paper money most significantly affect long-distance trade?",
    choices: { A: "It replaced barter in agricultural villages", B: "It made large commercial transactions lighter and more practical across vast distances", C: "It was only used within China and had no effect on trade", D: "It caused inflation that destroyed the Silk Roads economy" },
    correct: 'B',
    explanation: "Paper money (jiaochao in China) reduced the need to transport heavy silver or copper coins across long distances. Merchants under Mongol patronage could use state-backed paper currency to conduct large transactions, facilitating the scale of commerce across the empire.",
  },
  {
    id: 'cr_sr_006', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 1,
    text: "Samarkand's importance in the Silk Roads network c. 1200–1450 was primarily due to its role as:",
    choices: { A: "A major trading hub and cultural center at the crossroads of Central Asian routes", B: "The primary source of silk production in Central Asia", C: "The administrative capital of the Mongol Empire", D: "A port city connecting caravans to maritime trade" },
    correct: 'A',
    explanation: "Samarkand was a key oasis city where multiple overland trade routes converged. Under Mongol and later Timurid rule it became a vibrant center of commerce, art, and Islamic scholarship, benefiting from its central position between China, Persia, and the Mediterranean world.",
  },
  {
    id: 'cr_sr_007', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 3,
    text: "Arab and Persian merchants gradually replaced earlier Sogdian merchants as the dominant middlemen of Silk Roads trade because:",
    choices: { A: "They had superior ships and navigation tools", B: "Their extensive religious and commercial networks across the Islamic world gave them structural advantages", C: "Sogdian merchants were forcibly expelled by the Mongols", D: "They offered lower prices than their competitors" },
    correct: 'B',
    explanation: "As Islam spread from the 7th century onward, Arab and Persian merchants built networks of trust, credit, and shared legal frameworks across the Islamic world. These networks — reinforced by religious community (ummah) — made it easier to conduct business across vast distances, gradually displacing the earlier Sogdian commercial networks.",
  },
  {
    id: 'cr_sr_008', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 2,
    text: "Which of the following best describes how the Black Death relates to Silk Roads trade?",
    choices: { A: "The Mongols deliberately spread plague as a biological weapon", B: "The same trade and military networks that carried goods also carried disease westward", C: "The plague originated in Europe and spread east along trade routes", D: "The Black Death caused such devastation that Silk Roads trade never recovered" },
    correct: 'B',
    explanation: "Bubonic plague bacteria traveled along the same routes as merchants and armies. The Mongol network's efficiency in connecting Central Asia to the Middle East and Europe — a commercial advantage in peacetime — became a deadly vector as plague moved west during the 14th century.",
  },
  {
    id: 'cr_sr_009', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 2,
    text: "What distinguished Silk Roads trade from purely local exchange?",
    choices: { A: "Silk Roads trade carried only luxury goods for elite consumers, while local trade was in necessities", B: "Silk Roads trade was state-controlled; local trade was private", C: "Silk Roads trade required no middlemen", D: "Silk Roads trade was exclusively maritime" },
    correct: 'A',
    explanation: "Long-distance overland trade was expensive and risky, making it economical primarily for high-value, low-weight luxury goods like silk, spices, precious metals, and glassware. Everyday necessities like grain were traded locally or regionally because transportation costs would exceed their value over long distances.",
  },
  {
    id: 'cr_sr_010', zoneId: 'crossroads_world', levelId: 'silk_roads', skillTag: 'trade', difficulty: 3,
    text: "How did the fragmentation of the Mongol Empire into competing khanates after c. 1260 affect Silk Roads trade?",
    choices: { A: "Trade immediately ended as warfare made routes impassable", B: "Trade continued and in some regions flourished, though growing conflict between khanates added risk and cost", C: "Trade shifted entirely to maritime routes", D: "The khanates cooperated more effectively than the unified empire had" },
    correct: 'B',
    explanation: "The division into four khanates (Yuan, Ilkhanate, Chagatai, Golden Horde) created political tensions and occasional warfare that raised costs and risks for merchants. However, trade continued — particularly within each khanate — and the routes were not entirely closed until the later 14th–15th centuries, when the fall of various Mongol states and the rise of new powers disrupted the network.",
  },
  // Level: mongol_empire
  {
    id: 'cr_me_001', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 1,
    text: "The Mongol Empire at its height was historically notable as:",
    choices: { A: "The largest contiguous land empire in history", B: "The most populous empire ever", C: "The longest-lasting empire in world history", D: "The wealthiest empire per capita" },
    correct: 'A',
    explanation: "At its peak in the late 13th century, the Mongol Empire stretched from the Pacific coast of China to Eastern Europe, encompassing roughly 24 million square kilometers. It remains the largest contiguous land empire ever assembled.",
  },
  {
    id: 'cr_me_002', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 1,
    text: "Chinggis (Genghis) Khan unified the Mongol tribes primarily through:",
    choices: { A: "Conversion of all tribes to Islam", B: "Military conquest and strategic marriage alliances", C: "Trade agreements that created economic interdependence", D: "A democratic council giving equal voice to all tribes" },
    correct: 'B',
    explanation: "Chinggis Khan used a combination of military force against resistant tribes and strategic alliances (including marriage diplomacy) to unite the fragmented steppe peoples. He also reorganized the Mongol military into units based on loyalty rather than kinship, breaking older tribal loyalties.",
  },
  {
    id: 'cr_me_003', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 2,
    text: "Which of the following best describes Mongol governance in conquered territories?",
    choices: { A: "They imposed Mongol culture and language universally", B: "They typically maintained existing administrative structures while extracting tribute", C: "They enslaved all conquered peoples", D: "They converted all subjects to Tibetan Buddhism" },
    correct: 'B',
    explanation: "The Mongols were pragmatic rulers who generally kept existing bureaucratic systems, tax structures, and local officials in place. They were primarily interested in stable tribute flows. In Persia they worked through Persian administrators; in China they used elements of the Chinese bureaucracy while reserving top posts for Mongols.",
  },
  {
    id: 'cr_me_004', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 2,
    text: "The Mongol sack of Baghdad in 1258 is historically significant because it:",
    choices: { A: "Ended the Byzantine Empire", B: "Ended the Abbasid Caliphate, the symbolic center of Sunni Islam for five centuries", C: "Ended the Song Dynasty in China", D: "Ended the Delhi Sultanate in India" },
    correct: 'B',
    explanation: "The Mongols under Hulagu Khan destroyed Baghdad, killing the last Abbasid caliph. The Abbasid Caliphate had served as the symbolic religious and political center of the Sunni Muslim world since 750 CE. Its destruction was a major psychological and political shock to the Islamic world.",
  },
  {
    id: 'cr_me_005', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 1,
    text: "Which Mongol ruler established the Yuan Dynasty in China?",
    choices: { A: "Chinggis Khan", B: "Ogedei Khan", C: "Kublai Khan", D: "Timur (Tamerlane)" },
    correct: 'C',
    explanation: "Kublai Khan, grandson of Chinggis Khan, completed the conquest of the Southern Song Dynasty in 1279 and established the Yuan Dynasty, ruling as Emperor of China while also claiming the title of Great Khan.",
  },
  {
    id: 'cr_me_006', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 2,
    text: "The Mongol conquests most severely affected population levels through:",
    choices: { A: "Disease deliberately spread along trade routes", B: "Mass deportations of skilled workers to Mongol territories", C: "Widespread destruction of cities and agricultural infrastructure causing famine and flight", D: "Forced religious conversions leading to social collapse" },
    correct: 'C',
    explanation: "Mongol warfare frequently involved destroying cities, irrigation systems, and agricultural infrastructure when populations resisted. Persia, Central Asia, and northern China saw dramatic population declines — some regions did not recover for generations. The destruction of Baghdad's extensive irrigation network contributed to long-term economic decline in Mesopotamia.",
  },
  {
    id: 'cr_me_007', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 2,
    text: "The division of the Mongol Empire into four khanates most directly illustrates:",
    choices: { A: "The failure of Mongol military power after Chinggis Khan", B: "The difficulty of maintaining centralized control over vast, diverse territories", C: "The success of Islamic conversion among Mongol rulers", D: "The influence of Chinese bureaucratic models on Mongol governance" },
    correct: 'B',
    explanation: "After Mongke Khan's death in 1259, the empire fractured into the Yuan Dynasty, Ilkhanate, Chagatai Khanate, and Golden Horde. The sheer geographic scale, diversity of conquered peoples, and lack of shared communication infrastructure made unified rule increasingly impractical.",
  },
  {
    id: 'cr_me_008', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 3,
    text: "How did the Mongol yam (relay station) system most directly affect communication and trade?",
    choices: { A: "It created a postal relay network that dramatically accelerated communication across the empire", B: "It was primarily used to collect taxes from merchants", C: "It replaced all private merchants with state-employed traders", D: "It connected the empire to maritime trade routes" },
    correct: 'A',
    explanation: "The yam system consisted of relay stations spaced roughly a day's ride apart across the empire, stocked with horses, riders, and supplies. Official messages could travel thousands of miles in days rather than months. The system also facilitated merchant travel under state protection (paiza safe-conduct passes).",
  },
  {
    id: 'cr_me_009', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 3,
    text: "The Mongol Empire's long-term historical legacy is best assessed as:",
    choices: { A: "Purely destructive with no lasting positive contributions", B: "A mixed legacy — devastating to conquered populations but facilitating cultural and commercial exchange across Eurasia", C: "Primarily positive as it created lasting peace and prosperity", D: "Limited to Central Asia with little effect on the broader world" },
    correct: 'B',
    explanation: "Historians debate the Mongol legacy. The conquests caused massive death and destruction. Yet Mongol rule also facilitated the movement of people, goods, technologies, and ideas across Eurasia at unprecedented scale — including the spread of papermaking, printing, and gunpowder westward, and Islamic science and art eastward.",
  },
  {
    id: 'cr_me_010', zoneId: 'crossroads_world', levelId: 'mongol_empire', skillTag: 'mongols', difficulty: 2,
    text: "Why did the Mongols fail to conquer Japan (1274, 1281) and Vietnam?",
    choices: { A: "The Mongols lacked any naval capability", B: "A combination of fierce local resistance, difficult terrain, and in Japan's case, typhoons ('divine winds') destroyed invasion fleets", C: "The Mongols chose not to invade as the territories were considered valueless", D: "European crusaders came to Japan's defense" },
    correct: 'B',
    explanation: "Japan's invasions were defeated by samurai resistance and storms the Japanese called kamikaze (divine winds) that wrecked Mongol fleets. Vietnam's tropical terrain, guerrilla tactics, and climate exhausted Mongol armies. These failures reveal the limits of steppe cavalry-based warfare against determined resistance in challenging environments.",
  },
  // Level: indian_ocean
  {
    id: 'cr_io_001', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 1,
    text: "Which natural phenomenon most enabled the Indian Ocean trade network?",
    choices: { A: "Ocean currents that flowed in one direction year-round", B: "Seasonal monsoon winds that reversed direction, allowing predictable round-trip voyages", C: "The absence of storms in the Indian Ocean", D: "Shallow waters that made navigation easy" },
    correct: 'B',
    explanation: "The Indian Ocean monsoon system blows northeast from October to April and southwest from June to September. Sailors could use the summer monsoon to sail from Arabia or India to East Africa or Southeast Asia, then return on the winter monsoon — making reliable, scheduled voyages possible centuries before European oceanic exploration.",
  },
  {
    id: 'cr_io_002', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 2,
    text: "The city of Malacca (founded c. 1400) became a dominant commercial hub because:",
    choices: { A: "It was the center of Buddhist pilgrimage routes", B: "It controlled the strait connecting the Indian Ocean to the South China Sea", C: "It was the primary source of cotton textiles", D: "It served as the capital of the Yuan Dynasty's maritime expansion" },
    correct: 'B',
    explanation: "The Strait of Malacca is the narrow passage between the Malay Peninsula and Sumatra through which virtually all maritime trade between the Indian Ocean and South China Sea must pass. Malacca's rulers taxed this trade and created a favorable commercial environment that attracted merchants from across Asia.",
  },
  {
    id: 'cr_io_003', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 1,
    text: "Which religion spread most extensively through Indian Ocean trade networks c. 1200–1450?",
    choices: { A: "Hinduism", B: "Buddhism", C: "Christianity", D: "Islam" },
    correct: 'D',
    explanation: "Muslim merchants dominated much of the Indian Ocean trade from the 9th century onward. As they established trading communities in port cities from East Africa to Southeast Asia, they spread Islam through commerce and intermarriage rather than conquest. Many rulers of Malacca, the Swahili coast, and coastal India converted to Islam partly for commercial reasons.",
  },
  {
    id: 'cr_io_004', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 2,
    text: "The East African Swahili Coast city-states (such as Kilwa and Mombasa) c. 1200–1450 are best characterized by:",
    choices: { A: "Isolation from Indian Ocean trade networks", B: "Political domination by Arab colonizers", C: "A hybrid African-Islamic culture created through centuries of trade", D: "Control by the Mongol Empire via maritime routes" },
    correct: 'C',
    explanation: "The Swahili people and their language emerged from centuries of intermarriage and cultural exchange between Bantu African peoples and Arab, Persian, and Indian traders. Swahili city-states practiced Islam but maintained distinctly African cultural elements — a clear example of cultural synthesis through trade.",
  },
  {
    id: 'cr_io_005', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 2,
    text: "What were the primary exports of East African city-states like Kilwa in c. 1300–1450?",
    choices: { A: "Spices and silks", B: "Gold and enslaved people", C: "Cotton textiles", D: "Iron weapons and tools" },
    correct: 'B',
    explanation: "Kilwa controlled the trade in gold from the Zimbabwean plateau (via Great Zimbabwe and later the Mutapa state) and was a major node in the Indian Ocean slave trade. Ibn Battuta visited Kilwa in 1331 and praised it as one of the finest cities in the world, built on profits from this trade.",
  },
  {
    id: 'cr_io_006', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 2,
    text: "Zheng He's Chinese treasure voyages (1405–1433) most directly demonstrated:",
    choices: { A: "That China sought to establish permanent colonies in Africa and Arabia", B: "China's capacity for large-scale maritime expeditions and the desire to project imperial prestige", C: "That Chinese maritime technology was inferior to Arab naval technology", D: "That China dominated Indian Ocean trade throughout the 15th century" },
    correct: 'B',
    explanation: "Zheng He commanded fleets of enormous 'treasure ships' carrying silk, porcelain, and other gifts to impress foreign rulers and bring them into the Chinese tribute system. The voyages were about prestige projection rather than colonization or trade profit, and were discontinued after the Yongle Emperor's death.",
  },
  {
    id: 'cr_io_007', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 3,
    text: "The Indian Ocean trade network differed from the Silk Roads overland network primarily in that:",
    choices: { A: "It carried only agricultural products rather than luxury goods", B: "It was dominated by a single empire", C: "It was entirely maritime and used monsoon winds, enabling larger cargo volumes at lower cost per unit", D: "European merchants controlled it from the beginning" },
    correct: 'C',
    explanation: "Ships can carry far more cargo than camel caravans at lower cost per unit weight, making maritime trade especially suitable for bulk goods as well as luxuries. The Indian Ocean network thus carried not only high-value spices and silks but also cotton textiles, ceramics, and food staples — a more economically diverse trade than overland routes.",
  },
  {
    id: 'cr_io_008', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 2,
    text: "Indian merchants' primary role in the Indian Ocean network was as:",
    choices: { A: "Military protectors of trade routes", B: "Middlemen connecting Southeast Asian, East African, and Middle Eastern markets", C: "Producers who monopolized the spice trade", D: "State-employed traders for the Delhi Sultanate" },
    correct: 'B',
    explanation: "Indian merchants (particularly from Gujarat and the Malabar Coast) occupied a central geographic and commercial position, connecting the spice-producing islands of Southeast Asia with the Arab world and East Africa. They acted as intermediaries who created value through their networks, credit systems, and knowledge of diverse markets.",
  },
  {
    id: 'cr_io_009', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 1,
    text: "Why were spices so valuable in the Indian Ocean trade c. 1200–1500?",
    choices: { A: "Spices were used as currency in all Indian Ocean societies", B: "Spices were rare in Europe and Asia and served as flavoring, medicine, and preservatives commanding high prices", C: "Spices were required for religious rituals across all major religions", D: "Spices were raw materials for manufacturing textiles" },
    correct: 'B',
    explanation: "Pepper, cloves, nutmeg, and cinnamon grew only in specific regions (primarily South and Southeast Asia) but were in high demand across Eurasia as food preservatives, flavor enhancers, medicines, and status goods. The price differential between production zones and European markets could be 100-fold, making the spice trade enormously profitable.",
  },
  {
    id: 'cr_io_010', zoneId: 'crossroads_world', levelId: 'indian_ocean', skillTag: 'maritime', difficulty: 3,
    text: "The absence of a single dominant political power controlling the Indian Ocean network before c. 1500 is historically significant because:",
    choices: { A: "It made the network unstable and prone to collapse", B: "It allowed diverse merchants from many cultures to participate without exclusion, creating a cosmopolitan commercial world", C: "It prevented any technological innovation in shipbuilding", D: "It meant trade volumes remained small compared to overland routes" },
    correct: 'B',
    explanation: "Unlike land-based trade routes that could be controlled by single empires, the Indian Ocean network was a decentralized system. Arab, Indian, Malay, Swahili, and Chinese merchants all participated without one power monopolizing trade. This openness fostered cultural exchange and innovation — and also made the network vulnerable when Portuguese naval power arrived with cannon-armed ships in 1498.",
  },
  // Level: african_kingdoms
  {
    id: 'cr_ak_001', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 1,
    text: "The Mali Empire's extraordinary wealth during c. 1200–1450 was primarily based on:",
    choices: { A: "Maritime trade in the Indian Ocean", B: "Control of trans-Saharan gold and salt trade routes", C: "Agricultural surplus from the Niger River irrigation systems", D: "Military tribute extracted from European traders" },
    correct: 'B',
    explanation: "Mali sat between West African gold fields in the south and the Saharan salt mines of Taghaza in the north. By controlling the routes connecting these resources to North African and Mediterranean markets, Mali's rulers became fabulously wealthy. Salt was as valuable as gold in sub-Saharan Africa because it was essential for preserving food.",
  },
  {
    id: 'cr_ak_002', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 1,
    text: "Mansa Musa's pilgrimage to Mecca in 1324–1325 is historically significant primarily because:",
    choices: { A: "It was the first time a West African ruler converted to Islam", B: "He gave away so much gold in Cairo and Mecca that he temporarily deflated gold prices across the Mediterranean region", C: "It resulted in a military alliance between Mali and Egypt", D: "He discovered new overland trade routes through the Sahara" },
    correct: 'B',
    explanation: "Mansa Musa traveled with an enormous entourage and distributed so much gold in Egypt that he caused inflation — the price of gold in Cairo reportedly did not recover for over a decade. The pilgrimage put Mali on European maps and demonstrated the empire's extraordinary wealth to the wider world.",
  },
  {
    id: 'cr_ak_003', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 2,
    text: "Great Zimbabwe's role in regional trade c. 1200–1400 is best described as:",
    choices: { A: "A primarily agricultural center that exported grain to coastal cities", B: "A political and commercial center that channeled inland gold to Indian Ocean traders via Swahili coast ports", C: "The administrative capital of the Mongol Empire's African operations", D: "A direct trading partner of China via its own maritime fleet" },
    correct: 'B',
    explanation: "Great Zimbabwe was the political center of a state that controlled gold production from the Zimbabwean plateau. This gold traveled via trade networks to Swahili Coast ports like Sofala and Kilwa, where it entered the Indian Ocean trade network. Chinese porcelain and Persian pottery found at Great Zimbabwe confirm this connection.",
  },
  {
    id: 'cr_ak_004', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 2,
    text: "The adoption of Islam by Mali's rulers was primarily driven by:",
    choices: { A: "Military conquest by Arab armies from North Africa", B: "Commercial and political advantages — Islamic networks facilitated trade and legitimacy among Muslim merchants", C: "Forced conversion by Mansa Musa after his pilgrimage to Mecca", D: "Egyptian missionaries converting the population starting in the 10th century" },
    correct: 'B',
    explanation: "Islam spread to West Africa primarily through trade connections with Muslim merchants from North Africa. Rulers who converted gained access to Islamic commercial networks, literate administrators (using Arabic for record-keeping), and legitimacy in the eyes of powerful Muslim trading partners — without necessarily imposing Islam on their predominantly non-Muslim subjects.",
  },
  {
    id: 'cr_ak_005', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 1,
    text: "The city of Timbuktu was important in c. 1300–1450 primarily as:",
    choices: { A: "A military fortress protecting Mali from Saharan raiders", B: "A center of Islamic scholarship and trans-Saharan trade", C: "The capital city of the Mali Empire's central government", D: "A port city connecting West Africa to the Indian Ocean network" },
    correct: 'B',
    explanation: "Timbuktu became a major commercial and intellectual center. The Sankore mosque and associated madrasas drew scholars from across the Islamic world. At its peak, Timbuktu may have had 25,000 students and a trade in manuscripts that rivaled the gold trade — making it one of the world's great centers of learning.",
  },
  {
    id: 'cr_ak_006', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 2,
    text: "Ibn Battuta's account of his visit to Mali in 1352 is most valuable to historians because:",
    choices: { A: "It proves Mali had rejected Islamic practice by the 14th century", B: "It provides a contemporary outside observer's description of Mali's governance, culture, and Islamic practices", C: "It documents the collapse of the Mali Empire under Mongol invasion", D: "It reveals that Mali was a purely secular state" },
    correct: 'B',
    explanation: "Ibn Battuta's Rihla (travels) is one of the primary written sources on medieval Mali. He both praised Mali's security, justice, and Islamic observance and criticized practices he found un-Islamic (such as women appearing unveiled). His account shows a sophisticated society that blended Islamic governance with indigenous African traditions.",
  },
  {
    id: 'cr_ak_007', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 3,
    text: "How did the spread of Islam affect governance in West African kingdoms c. 1200–1450?",
    choices: { A: "It replaced all traditional governance structures with full Islamic sharia law", B: "It was completely rejected by African rulers as a foreign imposition", C: "It provided rulers with administrative tools and wider commercial connections while local traditions persisted alongside Islamic practice", D: "It unified all West African kingdoms under a single Islamic caliphate" },
    correct: 'C',
    explanation: "West African rulers typically practiced a syncretic form of Islam — they used Arabic literacy for administration, performed Islamic rituals, and built mosques, but also continued indigenous ceremonial practices and maintained traditional social structures. Ibn Battuta criticized this blending, but it reflects how religions adapt as they spread through trade rather than conquest.",
  },
  {
    id: 'cr_ak_008', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 2,
    text: "The trans-Saharan trade route primarily connected West Africa to:",
    choices: { A: "East African coastal cities via overland routes", B: "The Mediterranean world via North African cities like Cairo and Tunis", C: "The Indian subcontinent via Arabia", D: "The Mongol Empire via Central Asia" },
    correct: 'B',
    explanation: "Camel caravans carrying gold and salt crossed the Sahara from West African cities like Timbuktu and Djenné to North African coastal cities like Cairo, Tunis, and Tripoli. From there goods entered Mediterranean trade networks reaching Europe and the Middle East. The camel's ability to survive without water for long periods made trans-Saharan trade possible.",
  },
  {
    id: 'cr_ak_009', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 2,
    text: "Great Zimbabwe's decline c. 1420–1450 was most likely caused by:",
    choices: { A: "Mongol invasion from the north", B: "Environmental degradation and a shift in regional trade routes toward the Zambezi River", C: "Portuguese military conquest of the interior", D: "Internal religious conflict between Christian and traditional communities" },
    correct: 'B',
    explanation: "Scholars debate Great Zimbabwe's decline, but most point to a combination of overuse of local resources (deforestation, soil exhaustion) and a shift in gold trade routes to the north via the Zambezi Valley, where the Mutapa state rose to prominence. Portuguese arrival in the region came decades after Great Zimbabwe's decline.",
  },
  {
    id: 'cr_ak_010', zoneId: 'crossroads_world', levelId: 'african_kingdoms', skillTag: 'africa', difficulty: 3,
    text: "What does the diversity of African kingdoms c. 1200–1450 (Mali, Great Zimbabwe, Swahili city-states) most directly demonstrate?",
    choices: { A: "That African societies were all part of a single unified civilization", B: "That African political development lagged behind other world regions", C: "That sub-Saharan Africa developed diverse, complex political and economic systems connected to wider global networks", D: "That Africa's development was entirely dependent on external trade" },
    correct: 'C',
    explanation: "Mali, Great Zimbabwe, and the Swahili city-states all represent independently developed responses to local environments and opportunities. Together they demonstrate that sub-Saharan Africa was home to sophisticated, interconnected civilizations — not the isolated, static societies that later European colonial ideology falsely claimed.",
  },
  // Level: black_death
  {
    id: 'cr_bd_001', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 1,
    text: "The Black Death (bubonic plague) that swept Eurasia c. 1346–1353 most likely originated in:",
    choices: { A: "Western Europe", B: "The Middle East", C: "Central Asia", D: "Chinese coastal cities" },
    correct: 'C',
    explanation: "Modern DNA analysis of ancient plague victims confirms the bacterium Yersinia pestis originated in Central Asian rodent populations, likely in the region of modern Kyrgyzstan. The disease spread westward along Mongol trade and military routes, reaching the Black Sea by the 1340s and then exploding across Europe and the Middle East.",
  },
  {
    id: 'cr_bd_002', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 1,
    text: "Approximately what proportion of Europe's population died during the Black Death c. 1347–1353?",
    choices: { A: "One-tenth", B: "One-quarter", C: "One-third to one-half", D: "Three-quarters" },
    correct: 'C',
    explanation: "Modern demographic historians estimate that between 30–50% of Europe's population died during the initial outbreak of the Black Death between 1347 and 1353 — one of the deadliest demographic catastrophes in human history. Some regions lost more than half their population; others less.",
  },
  {
    id: 'cr_bd_003', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "How did the Black Death spread from Central Asia to Western Europe?",
    choices: { A: "Via Arab merchants along trans-Saharan trade routes", B: "Through Mongol armies and merchants moving along Silk Road trade networks", C: "Through Christian Crusader armies returning from the Holy Land", D: "Via Viking ships traveling northern sea routes" },
    correct: 'B',
    explanation: "The plague moved along established trade routes from Central Asia through the Mongol-controlled territories to Crimea, then to Italian merchant ships in the Black Sea. The 1346 Mongol siege of Caffa — where plague-infected corpses were reportedly catapulted over the walls — may have helped spread disease to Italian merchants who then carried it to Mediterranean ports.",
  },
  {
    id: 'cr_bd_004', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "Which of the following was a major long-term economic consequence of the Black Death in Western Europe?",
    choices: { A: "Wages decreased permanently as desperate survivors competed for scarce work", B: "Agricultural production expanded rapidly as surviving farmers claimed more land", C: "Surviving laborers gained economic leverage, leading to higher wages and weakened serfdom", D: "Feudal lords strengthened their control over serfs by filling positions vacated by plague deaths" },
    correct: 'C',
    explanation: "With fewer workers available, surviving peasants and artisans could demand higher wages and better conditions. This labor scarcity accelerated the decline of serfdom in Western Europe — landlords competed for labor rather than compelling it. The economic disruption pushed elites to find alternative labor sources and contributed to later Atlantic slavery.",
  },
  {
    id: 'cr_bd_005', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "The flagellant movement that spread during the Black Death represents:",
    choices: { A: "A rational scientific response to the epidemic", B: "A religious response where groups publicly self-flagellated to atone for sins they believed caused the plague", C: "An early public health quarantine movement", D: "A political movement against the authority of the Catholic Church" },
    correct: 'B',
    explanation: "Flagellants traveled through towns publicly whipping themselves to demonstrate penance before God, believing the plague was divine punishment for sin. The movement spread rapidly across Europe but was condemned by Pope Clement VI in 1349. The flagellant movement illustrates how populations sought religious explanations and solutions for catastrophic events.",
  },
  {
    id: 'cr_bd_006', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "How did the Black Death affect the Jewish communities of Europe?",
    choices: { A: "Jewish communities were unaffected due to better hygiene", B: "Jewish people were widely blamed for the plague and faced persecution and massacres", C: "Jewish communities helped lead medical responses that saved thousands", D: "Jewish people fled Europe entirely as a result of the plague" },
    correct: 'B',
    explanation: "Throughout Europe, Jewish communities were accused of poisoning wells to spread the plague. This led to mass killings and expulsions in hundreds of towns. Pope Clement VI issued a papal bull condemning the violence, noting that Jewish communities were dying of plague at the same rate as others, but persecution continued. This represents scapegoating during crisis.",
  },
  {
    id: 'cr_bd_007', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 3,
    text: "How did the Black Death affect the Islamic world compared to Europe?",
    choices: { A: "It had no significant effect on the Islamic world", B: "It was far less severe due to Islamic medical knowledge", C: "It devastated the Middle East and North Africa similarly, with Egypt losing perhaps one-third of its population", D: "Islamic medicine successfully contained the disease to coastal cities" },
    correct: 'C',
    explanation: "The Black Death struck the Islamic world as severely as Europe. Egypt, Syria, and North Africa lost massive portions of their populations. Islamic scholars like Ibn Khaldun, who lost his parents to the plague, wrote about the catastrophe. Some historians argue the plague struck the Islamic world harder than Europe in the long run due to continued recurrent outbreaks.",
  },
  {
    id: 'cr_bd_008', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "How did the Black Death affect long-distance trade networks?",
    choices: { A: "It had minimal effect as merchants were immune to the disease", B: "It temporarily disrupted trade as merchants died and cities depopulated, but networks eventually recovered", C: "It stimulated trade as merchants rushed to sell the goods of those who had died", D: "It caused permanent collapse of all Eurasian trade networks for centuries" },
    correct: 'B',
    explanation: "The Black Death severely disrupted trade in the short term — merchant communities were devastated, markets contracted, and some trade routes were abandoned. However, the underlying commercial infrastructure gradually recovered. In some regions, the plague paradoxically increased per-capita wealth among survivors, eventually stimulating new commercial activity.",
  },
  {
    id: 'cr_bd_009', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 3,
    text: "The Black Death spread so rapidly c. 1346–1353 most directly because:",
    choices: { A: "Medieval governments made no effort to contain the disease", B: "The same Mongol-facilitated trade networks that accelerated commerce also accelerated disease transmission", C: "The plague had an unusually long incubation period that hid its spread", D: "European cities were uniquely vulnerable because they had never experienced any epidemic disease before" },
    correct: 'B',
    explanation: "The Mongol network's efficiency was a double-edged sword. The same infrastructure — relay stations, merchant caravans, diplomatic missions — that connected Eurasia commercially provided transmission pathways for disease. This is a recurring historical pattern: connectivity that enables economic growth also enables pandemic spread.",
  },
  {
    id: 'cr_bd_010', zoneId: 'crossroads_world', levelId: 'black_death', skillTag: 'plague', difficulty: 2,
    text: "The most accurate historical assessment of the Black Death's long-term impact is that it:",
    choices: { A: "Primarily affected population levels with minimal social or economic consequences", B: "Caused temporary disruption that societies quickly forgot", C: "Catalyzed long-term social, economic, and cultural transformations including labor market shifts, religious questioning, and new attitudes toward death", D: "Had effects confined largely to Western Europe" },
    correct: 'C',
    explanation: "The Black Death's long-term effects were profound. It accelerated the decline of serfdom, contributed to the questioning of Church authority (when prayer failed to stop the plague), inspired new artistic and literary themes focused on death (the Danse Macabre), and forced economic adaptation. Ibn Khaldun used it as a lens for his theories of civilizational rise and fall.",
  },
];
'''

with open('/home/user/ascend/client/src/data/apWorldHistory.js', 'w') as f:
    f.write(content)

print("Zone 1 written successfully")
