content = '''
  // ── Zone 3: revolution_industry ──────────────────────────────────────────
  // Level: atlantic_revolutions
  {
    id: 'ri_ar_001', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 1,
    text: "Which of the following was the FIRST successful colonial revolution in the Americas?",
    choices: { A: "The American Revolution (1776)", B: "The Haitian Revolution (1791-1804)", C: "The Mexican War of Independence (1810-1821)", D: "The Brazilian Declaration of Independence (1822)" },
    correct: 'A',
    explanation: "The American Revolution, beginning in 1776, was the first successful colonial independence movement in the Americas. It established the precedent that colonies could successfully break from European empires and create independent nations.",
  },
  {
    id: 'ri_ar_002', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 2,
    text: "The Haitian Revolution (1791-1804) is historically unique because:",
    choices: { A: "It was the first revolution inspired by Enlightenment ideals", B: "It was the only successful slave revolution that created an independent nation-state", C: "It received full French military support throughout the conflict", D: "It was led by white creole planters opposing French taxation" },
    correct: 'B',
    explanation: "The Haitian Revolution was the only successful large-scale slave revolt in history that produced an independent state. Enslaved people on Saint-Domingue (Haiti) defeated French, Spanish, and British forces to establish Haiti in 1804. This terrified slave-holding societies throughout the Americas and became a powerful symbol for abolitionists worldwide.",
  },
  {
    id: 'ri_ar_003', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 1,
    text: "Which Enlightenment idea most directly inspired the Atlantic Revolutions of the late 18th and early 19th centuries?",
    choices: { A: "The divine right of kings to govern without consent", B: "The social contract — that governments derive legitimacy from the consent of the governed", C: "Mercantilism and economic nationalism", D: "Social Darwinism — the survival of the fittest nations" },
    correct: 'B',
    explanation: "Thinkers like Locke, Rousseau, and Montesquieu argued that governments exist to protect natural rights, derive their authority from the people, and can be legitimately overthrown if they fail in this duty. These ideas directly influenced the American Declaration of Independence, the French Declaration of the Rights of Man, and Latin American independence declarations.",
  },
  {
    id: 'ri_ar_004', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 1,
    text: "Simon Bolivar led independence movements primarily in:",
    choices: { A: "Brazil and the Rio de la Plata region", B: "Mexico and Central America", C: "Northern and western South America (Venezuela, Colombia, Ecuador, Peru, Bolivia)", D: "The Caribbean islands" },
    correct: 'C',
    explanation: "Simon Bolivar, known as El Libertador, led independence campaigns across northern South America. He freed Venezuela, Colombia, Ecuador, Peru, and Bolivia (named after him) from Spanish rule. His dream was to unite all of Spanish South America into a single nation, which was ultimately not achieved due to regional rivalries.",
  },
  {
    id: 'ri_ar_005', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 2,
    text: "The French Revolution of 1789 differed from the American Revolution primarily in its:",
    choices: { A: "Rejection of Enlightenment ideas that the Americans embraced", B: "More radical social transformation that challenged the aristocracy and Catholic Church", C: "Support for maintaining a constitutional monarchy throughout", D: "Limited impact on other countries and later revolutions" },
    correct: 'B',
    explanation: "The American Revolution largely preserved existing social hierarchies — slaveholders remained powerful, women gained no new rights — while establishing political independence. The French Revolution went further, executing the king, attacking the nobility and Church, and declaring legal equality for all male citizens. This radicalism inspired and terrified Europe.",
  },
  {
    id: 'ri_ar_006', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 2,
    text: "The Latin American independence movements of c. 1810-1830 were largely led by:",
    choices: { A: "Indigenous peoples who were the primary beneficiaries of independence", B: "Enslaved Africans seeking freedom from plantation labor", C: "Creoles (American-born Europeans) resentful of Spanish trade restrictions and political exclusion", D: "Catholic missionaries opposing Spanish colonial rule" },
    correct: 'C',
    explanation: "Creoles — people of Spanish descent born in the Americas — were the primary leaders of independence movements. They resented the exclusion from high colonial offices (reserved for peninsulares, Spanish-born Spaniards), restrictions on trade with non-Spanish nations, and the economic extraction that flowed to Spain. Independence transferred power to creole elites without fundamentally changing the social structure.",
  },
  {
    id: 'ri_ar_007', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 2,
    text: "How did Napoleon's invasion of Spain in 1808 contribute to Latin American independence?",
    choices: { A: "Napoleon immediately recognized all Spanish American colonies as independent nations", B: "Spanish Americans used the resulting power vacuum to begin independence movements", C: "Spanish Americans rallied to support the Spanish crown against Napoleon", D: "The Catholic Church organized independence movements to resist French atheism" },
    correct: 'B',
    explanation: "When Napoleon forced the Spanish king to abdicate in 1808 and placed his brother on the Spanish throne, Spanish Americans faced a crisis of legitimacy — whom did they owe loyalty to? This opened political space for independence movements. Many juntas (governing councils) formed claiming to rule in the name of the deposed king, which gradually evolved into independence movements.",
  },
  {
    id: 'ri_ar_008', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 3,
    text: "Why did many Latin American independence movements largely fail to address the rights of enslaved people and indigenous populations?",
    choices: { A: "The leaders genuinely believed these issues were unimportant to national sovereignty", B: "The independence movements were led by creole elites who benefited from existing racial and labor hierarchies", C: "European nations threatened military intervention if social reforms were attempted", D: "Enslaved and indigenous peoples had no desire for freedom or political rights" },
    correct: 'B',
    explanation: "Creole independence leaders sought to transfer political power from Spain to themselves without disrupting the social order that benefited them. Plantation owners feared that abolition would destroy the agricultural economy; elites feared that indigenous rights would undermine land ownership. Haiti's radical example terrified creole elites and made them even more cautious about social revolution.",
  },
  {
    id: 'ri_ar_009', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 2,
    text: "The Toussaint Louverture's role in the Haitian Revolution is most accurately described as:",
    choices: { A: "A French general sent to suppress the slave rebellion", B: "A formerly enslaved man who became a key revolutionary leader, skillful general, and administrator", C: "A free Black plantation owner who opposed the revolution", D: "A Spanish advisor who provided military assistance to the revolutionaries" },
    correct: 'B',
    explanation: "Toussaint Louverture was born enslaved but freed as a young man. He joined the revolutionary forces, proved himself a brilliant military commander, and eventually controlled much of Saint-Domingue. Though he was captured and died in French imprisonment in 1803, his leadership established the foundation for Haitian independence the following year.",
  },
  {
    id: 'ri_ar_010', zoneId: 'revolution_industry', levelId: 'atlantic_revolutions', skillTag: 'revolution', difficulty: 3,
    text: "What was the most significant long-term impact of the Atlantic Revolutions on world history?",
    choices: { A: "They ended all monarchies in the Western Hemisphere", B: "They established popular sovereignty and nationalism as powerful political ideologies that inspired later movements worldwide", C: "They immediately extended full political rights to all people including women and enslaved people", D: "They caused the collapse of European colonial empires by 1850" },
    correct: 'B',
    explanation: "The Atlantic Revolutions established that ordinary people could overthrow existing governments in the name of popular sovereignty and natural rights. These ideas became templates for nationalist movements in Europe, anti-colonial movements in Asia and Africa, and social revolutions worldwide. The limitations of these revolutions — their failure to fully extend rights to women, enslaved people, and indigenous peoples — also set the agenda for later reform movements.",
  },
  // Level: industrial_revolution
  {
    id: 'ri_ir_001', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 1,
    text: "The Industrial Revolution began in which country during the late 18th century?",
    choices: { A: "France", B: "Germany", C: "United States", D: "Britain" },
    correct: 'D',
    explanation: "Britain industrialized first for several reasons: it had abundant coal and iron deposits, an empire providing raw materials and markets, a stable property-rights legal system, a well-developed financial sector, and coal-driven textile innovations like the spinning jenny and water frame that concentrated production in factories.",
  },
  {
    id: 'ri_ir_002', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "James Watt's improved steam engine most directly transformed which sectors?",
    choices: { A: "Agriculture and food production", B: "Mining and manufacturing by providing a flexible, powerful, and relatively portable mechanical energy source", C: "Naval warfare and exploration", D: "Communication through early telegraph systems" },
    correct: 'B',
    explanation: "Watt's separate condenser (1769) made the steam engine far more efficient. Applied first to pumping water from mines, it quickly moved into textile factories and iron foundries. Steam-powered machinery allowed factories to locate near coal supplies rather than rivers, and later steam locomotives and steamships revolutionized transportation.",
  },
  {
    id: 'ri_ir_003', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "The factory system of the Industrial Revolution differed from previous production methods primarily because:",
    choices: { A: "Workers received higher wages than in any previous production system", B: "It concentrated production in facilities using powered machinery and wage labor rather than dispersed home-based craft production", C: "It relied entirely on enslaved labor rather than wage workers", D: "It required workers to own their tools and equipment" },
    correct: 'B',
    explanation: "Before industrialization, most manufacturing used the 'putting-out system' where merchants supplied raw materials to workers in their homes, then collected finished goods. The factory system concentrated workers under one roof with employer-owned machinery. This enabled supervision, specialization, and the use of power-driven machines — but also subjected workers to new disciplines of clock-time and constant supervision.",
  },
  {
    id: 'ri_ir_004', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "How did the Industrial Revolution affect the global balance of power?",
    choices: { A: "It spread wealth more evenly among all nations within a generation", B: "European nations gained dramatic economic and military advantages over non-industrialized societies worldwide", C: "It made colonial empires unprofitable and led to their rapid abandonment", D: "It weakened European states by creating class conflicts that led to immediate revolution" },
    correct: 'B',
    explanation: "Industrial production allowed European nations to produce weapons (rifles, artillery, steamships, railroads) far superior to those of non-industrialized societies. This military advantage enabled the rapid expansion of European imperialism in the 19th century. The gap between industrialized and non-industrialized nations grew dramatically, reshaping global power relations.",
  },
  {
    id: 'ri_ir_005', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 1,
    text: "Urbanization during the Industrial Revolution primarily resulted from:",
    choices: { A: "Government policies requiring people to move to cities", B: "Collapse of agricultural systems that drove rural people off the land", C: "Workers migrating to cities where factories offered paid employment", D: "Mass immigration from Asia and Africa to European cities" },
    correct: 'C',
    explanation: "Industrial cities grew explosively as workers moved to find factory employment. Manchester grew from 25,000 in 1772 to over 300,000 by 1850. This rapid urbanization created severe problems — overcrowding, pollution, disease (cholera epidemics), child labor — that eventually drove the social reform movements of the 19th century.",
  },
  {
    id: 'ri_ir_006', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "Which of the following was a major social consequence of industrialization in 19th century Europe?",
    choices: { A: "The elimination of class distinctions as factory wages equalized incomes", B: "The emergence of a new industrial working class (proletariat) and a new middle class (bourgeoisie) as the primary social forces", C: "The strengthening of feudal social structures as lords employed factory workers", D: "The rapid improvement of living standards for all workers within a generation" },
    correct: 'B',
    explanation: "Industrialization created new class structures. Factory owners and managers formed a bourgeoisie defined by capital ownership rather than inherited land. Industrial workers formed a proletariat defined by selling their labor. These new classes became the central subject of 19th century politics, social reform, and eventually Marxist ideology.",
  },
  {
    id: 'ri_ir_007', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "How did the Industrial Revolution affect women's roles in 19th century society?",
    choices: { A: "Women immediately gained full legal and political equality in industrialized societies", B: "Women were excluded from all paid employment and confined entirely to domestic roles", C: "Working-class women worked in factories while middle-class women were idealized as domestic managers (separate spheres ideology)", D: "Industrialization had no significant effect on gender roles" },
    correct: 'C',
    explanation: "Industrialization created contradictory pressures on women. Working-class women and children worked in factories under terrible conditions. Middle-class ideology created the 'cult of domesticity' that celebrated women as moral guardians of the home. Both patterns represented departures from pre-industrial arrangements where women worked in household production alongside men.",
  },
  {
    id: 'ri_ir_008', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "The Luddite movement in early 19th century Britain represented:",
    choices: { A: "Workers enthusiastically embracing new industrial technologies", B: "A political movement for democratic representation", C: "Skilled textile workers resisting mechanization that threatened their livelihoods and craft traditions", D: "A religious revival opposing secular industrialism" },
    correct: 'C',
    explanation: "Luddites were skilled weavers and framework knitters who destroyed machinery that replaced their craft skills with cheaper, less-skilled factory labor. They were not anti-technology in the abstract — they opposed specific machines that transferred skill and income from workers to factory owners. The movement was violently suppressed, and 'Luddite' has since become a pejorative term that obscures their legitimate economic grievances.",
  },
  {
    id: 'ri_ir_009', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 2,
    text: "How did industrialization spread from Britain to other regions?",
    choices: { A: "It spread simultaneously to all European nations by 1820", B: "It spread unevenly — continental Europe and North America next, then Japan, while much of the world remained non-industrialized until the 20th century", C: "It remained confined to Britain until the 20th century", D: "Only Protestant Christian nations were able to industrialize" },
    correct: 'B',
    explanation: "Belgium industrialized first in continental Europe (1820s), followed by France, the German states, and the American Northeast. Japan industrialized rapidly after the Meiji Restoration (1868) as the only non-Western nation to fully industrialize before the 20th century. Most of Asia, Africa, and Latin America remained largely non-industrialized, creating the economic gap that defined global inequality.",
  },
  {
    id: 'ri_ir_010', zoneId: 'revolution_industry', levelId: 'industrial_revolution', skillTag: 'industry', difficulty: 3,
    text: "The environmental consequences of early industrialization included:",
    choices: { A: "No significant environmental change as factories were efficient", B: "Local pollution of rivers and air but no effects on global climate", C: "Massive air and water pollution in industrial cities plus the beginning of human-caused atmospheric carbon increase", D: "Improved environmental quality as coal replaced wood, reducing deforestation" },
    correct: 'C',
    explanation: "Industrial cities in 19th century Britain had severe air pollution (coal smoke caused London's famous 'pea soup' fogs), polluted rivers, and contaminated water supplies that spread cholera. At a global level, the Industrial Revolution initiated the large-scale burning of fossil fuels that began accumulating atmospheric CO2 — the foundation of contemporary climate change.",
  },
  // Level: nationalism
  {
    id: 'ri_na_001', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 1,
    text: "Nationalism as a political ideology primarily asserts that:",
    choices: { A: "All people should be governed by a universal global government", B: "People sharing common culture, language, or history should form their own independent states", C: "Traditional monarchies are the natural and best form of government", D: "Economic prosperity is the only valid basis of political legitimacy" },
    correct: 'B',
    explanation: "Nationalism holds that the 'nation' — a group with shared cultural, linguistic, ethnic, or historical identity — is the natural unit of political organization and should have its own state. This seemingly simple idea had explosive consequences, driving independence movements, unification campaigns, and later, ethnic conflicts and genocide.",
  },
  {
    id: 'ri_na_002', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "Otto von Bismarck's approach to German unification (1864-1871) relied primarily on:",
    choices: { A: "Democratic elections and peaceful diplomatic persuasion", B: "'Blood and iron' — deliberately engineered wars against Denmark, Austria, and France to forge national unity", C: "Popular revolution by the German working classes", D: "Economic integration through the Zollverein customs union alone" },
    correct: 'B',
    explanation: "Bismarck deliberately provoked wars with Denmark (1864), Austria (1866), and France (1870-71) to unify the German states under Prussian leadership. He understood that shared military success would create emotional German nationalist unity more effectively than liberal constitutional arguments. The Franco-Prussian War culminated in the proclamation of the German Empire in the Hall of Mirrors at Versailles in 1871.",
  },
  {
    id: 'ri_na_003', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "How did nationalism contribute to the decline of the Ottoman and Austro-Hungarian empires in the 19th century?",
    choices: { A: "Nationalist movements strengthened these empires by creating loyalty to the central state", B: "Subject peoples within these multi-ethnic empires demanded independence based on ethnic or cultural identity, fragmenting imperial authority", C: "Nationalism in these empires was always quickly and permanently suppressed", D: "Economic nationalism in these empires created internal trade barriers that weakened them" },
    correct: 'B',
    explanation: "Both empires ruled diverse populations — the Ottomans governed Bulgarians, Serbs, Greeks, Armenians, Arabs, and Turks; Austria-Hungary governed Germans, Hungarians, Czechs, Slovaks, Poles, Croatians, and others. As nationalism spread, each group sought its own state, creating centrifugal forces that the empires struggled to contain. The Balkans became the 'powder keg of Europe.'",
  },
  {
    id: 'ri_na_004', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "Romantic nationalism of the 19th century emphasized:",
    choices: { A: "Scientific and rational approaches to defining national identity", B: "Economic productivity as the basis of national unity", C: "Shared cultural heritage, language, history, folklore, and emotional attachment to a homeland", D: "Legal and constitutional foundations for nationhood" },
    correct: 'C',
    explanation: "Romantic nationalism reacted against Enlightenment rationalism by emphasizing emotion, history, culture, and organic community. Figures like Herder celebrated folk cultures, languages, and traditions. Brothers Grimm collected German fairy tales as expressions of national spirit (Volksgeist). This cultural nationalism provided the emotional raw material that political nationalists later mobilized.",
  },
  {
    id: 'ri_na_005', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "The Congress of Vienna (1815) attempted to deal with the challenge of nationalism by:",
    choices: { A: "Encouraging nationalist movements to create stable nation-states", B: "Restoring the pre-Napoleonic balance of power and suppressing revolutionary nationalist movements", C: "Creating a League of Nations to peacefully manage nationalist conflicts", D: "Supporting the immediate unification of Germany and Italy" },
    correct: 'B',
    explanation: "The conservative statesmen at Vienna — Metternich, Castlereagh, Talleyrand — sought to restore monarchical legitimacy and suppress the revolutionary nationalism Napoleon had unleashed. The Concert of Europe system maintained a balance of power but struggled increasingly to contain nationalist pressures throughout the 19th century.",
  },
  {
    id: 'ri_na_006', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "The role of the printing press and mass literacy in the development of nationalism is best explained as:",
    choices: { A: "Having no significant connection to nationalist movements", B: "Enabling the spread of standardized national languages and nationalist ideas to wider populations through newspapers, novels, and political pamphlets", C: "Undermining nationalism by exposing people to foreign ideas", D: "Being controlled by governments to suppress nationalist sentiment" },
    correct: 'B',
    explanation: "Benedict Anderson's concept of 'imagined communities' argues that nationalism became possible when people could imagine themselves as part of a community they would never personally meet — made possible by print capitalism. Newspapers allowed people in distant cities to read the same stories simultaneously; novels created shared emotional narratives of national life.",
  },
  {
    id: 'ri_na_007', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 3,
    text: "Which of the following best describes the relationship between nationalism and imperialism in the 19th century?",
    choices: { A: "Nationalism and imperialism were completely contradictory ideologies", B: "Nationalist pride and competition among European nations fueled imperial expansion as nations competed for colonies", C: "Nationalist movements always opposed imperialism as a form of oppression", D: "Nationalism declined as imperialism expanded" },
    correct: 'B',
    explanation: "European nationalism generated intense competition between nations — in trade, military power, and territorial expansion. Colonial empires became symbols of national greatness and sources of national pride. The scramble for colonies was partly driven by nationalist competition: France and Britain acquired territory partly to prevent the other from having it. Nationalism that celebrated European superiority also justified the subjugation of non-European peoples.",
  },
  {
    id: 'ri_na_008', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "Anti-colonial nationalism in Asia and Africa during the 19th century was:",
    choices: { A: "Rare, as most colonized peoples supported European rule", B: "Common but generally unsuccessful in achieving independence during this period", C: "Absent until the 20th century", D: "Always inspired by Western nationalist ideology rather than local traditions" },
    correct: 'B',
    explanation: "Resistance to colonialism was widespread throughout the 19th century — the Indian Rebellion of 1857, the Mahdi Revolt in Sudan, Zulu resistance in South Africa, the Boxer Rebellion in China. But the military superiority conferred by industrialization allowed European powers to suppress these movements. Anti-colonial nationalism drew on both indigenous traditions and, increasingly, Western political ideas.",
  },
  {
    id: 'ri_na_009', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 2,
    text: "The Greek War of Independence (1821-1829) is significant in the history of nationalism because:",
    choices: { A: "It was the first successful nationalist movement anywhere in the world", B: "It was the first successful nationalist independence movement in Europe after the Napoleonic Wars", C: "It was supported by the Ottoman Empire to weaken European powers", D: "It created the first unified Balkan state" },
    correct: 'B',
    explanation: "Greek independence demonstrated that the conservative order established at Vienna could not permanently suppress nationalism. Western Europeans, influenced by romantic philhellenism (admiration for ancient Greece), supported the cause; poets like Byron died fighting for Greek independence. The movement inspired other Balkan nationalist movements and began the long 'Eastern Question' of Ottoman decline.",
  },
  {
    id: 'ri_na_010', zoneId: 'revolution_industry', levelId: 'nationalism', skillTag: 'nationalism', difficulty: 3,
    text: "What is the most historically accurate assessment of nationalism's long-term global impact?",
    choices: { A: "Nationalism was primarily a positive force that created stable, democratic nation-states worldwide", B: "Nationalism was entirely negative, causing only conflict and genocide", C: "Nationalism was a powerful but double-edged force that created national unity while also justifying exclusion, discrimination, and conflict against those defined as outside the nation", D: "Nationalism's effects were confined to Europe with no lasting impact on other regions" },
    correct: 'C',
    explanation: "Nationalism's historical legacy is profoundly ambiguous. It inspired independence movements, democratic participation, and cultural revival. It also drove the ethnic cleansing of minorities who did not fit the dominant national identity, justified imperialism against 'inferior' peoples, and in its most extreme 20th century form (Nazism), fueled genocide. Understanding this dual nature is essential for historical analysis.",
  },
  // Level: imperialism
  {
    id: 'ri_im_001', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 1,
    text: "The 'Scramble for Africa' during c. 1880-1914 resulted in:",
    choices: { A: "African nations successfully resisting European colonization through military force", B: "Nearly the entire African continent being partitioned among European powers", C: "Only North Africa being colonized while sub-Saharan Africa remained independent", D: "African leaders voluntarily welcoming European colonization as modernization" },
    correct: 'B',
    explanation: "By 1914, only Ethiopia and Liberia remained independent African states. The pace of African colonization was extraordinary — in 1880, Europeans controlled roughly 10% of Africa; by 1914, they controlled 90%. The Berlin Conference (1884-85) established rules for this partition without any African representation.",
  },
  {
    id: 'ri_im_002', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "Social Darwinism, as applied to justify imperialism, argued that:",
    choices: { A: "All human societies are equally capable of development given the right conditions", B: "European conquest was justified by the natural superiority of European peoples and races", C: "Colonial peoples should be immediately granted independence to fulfill their natural development", D: "Competition between species leads to evolutionary progress that helps everyone" },
    correct: 'B',
    explanation: "Social Darwinism misapplied Darwin's biological evolution to human societies, claiming that European dominance proved European racial and cultural superiority. This pseudoscientific racism provided ideological justification for imperialism: colonizing 'inferior' peoples was portrayed as natural, even benevolent. It also justified brutal policies like Leopold's Congo Free State, where millions died under forced labor.",
  },
  {
    id: 'ri_im_003', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "The Indian Rebellion of 1857 is significant because:",
    choices: { A: "It successfully ended British colonial rule in India", B: "It was purely a military mutiny with no political dimensions", C: "It revealed tensions in British colonial rule and led to the Crown directly governing India, replacing the East India Company", D: "It was the first armed resistance to colonialism anywhere in Asia" },
    correct: 'C',
    explanation: "The 1857 Rebellion (called the Sepoy Mutiny by the British) began as a military revolt but quickly became a broader uprising against British rule. After suppressing it with overwhelming force, the British Crown dissolved the East India Company and took direct control of India (the British Raj). The rebellion also hardened British racial attitudes and increased segregation between British and Indian society.",
  },
  {
    id: 'ri_im_004', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "Ethiopia's defeat of Italy at the Battle of Adwa (1896) is historically significant because:",
    choices: { A: "It drove all European colonizers out of Africa", B: "It demonstrated that African military forces could defeat a European imperial power", C: "It was the only military battle fought during the Scramble for Africa", D: "It led Ethiopia to rapidly industrialize and become a regional power" },
    correct: 'B',
    explanation: "Ethiopia's victory at Adwa, where Emperor Menelik II's forces defeated an Italian army, was the only decisive African military victory against European colonization in the Scramble era. It preserved Ethiopian independence and became a powerful symbol for African and Pan-African movements throughout the 20th century. Italy did not colonize Ethiopia until 1935-36 under Mussolini.",
  },
  {
    id: 'ri_im_005', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "The Berlin Conference of 1884-1885 is historically significant because:",
    choices: { A: "It was a meeting where African leaders negotiated with European powers about colonial boundaries", B: "European powers divided Africa among themselves without any African representation", C: "It established free trade zones that benefited African merchants", D: "It condemned the Atlantic slave trade and made it internationally illegal" },
    correct: 'B',
    explanation: "The Berlin Conference established rules for European colonization of Africa — primarily that a nation claiming African territory must effectively occupy it. No African representatives were present. The conference accelerated the Scramble for Africa and drew the arbitrary colonial boundaries that still largely define African nation-state borders today, often cutting through ethnic and cultural territories.",
  },
  {
    id: 'ri_im_006', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "How did imperialism affect economic development in colonized regions?",
    choices: { A: "Colonized regions rapidly industrialized under European investment and guidance", B: "Colonized regions developed export-oriented economies dependent on primary goods for European industries, creating lasting economic dependency", C: "Economic conditions in colonized regions were largely unchanged by colonization", D: "Colonized peoples benefited equally with European colonizers from economic development" },
    correct: 'B',
    explanation: "Colonial economic policy transformed subject territories into suppliers of raw materials (cotton, rubber, palm oil, minerals) for European industries while creating markets for European manufactured goods. This prevented industrialization in colonized regions and created economic structures — monoculture exports, dependence on foreign capital, underdeveloped infrastructure — whose legacies persisted after independence.",
  },
  {
    id: 'ri_im_007', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "Japan responded to Western imperialism after the Meiji Restoration (1868) primarily by:",
    choices: { A: "Remaining isolated and rejecting all Western influence", B: "Being colonized by Britain which then helped Japan modernize", C: "Rapidly industrializing and modernizing to resist Western imperialism, eventually becoming an imperial power itself", D: "Forming an alliance with China to expel all Western powers from Asia" },
    correct: 'C',
    explanation: "Japan's leaders consciously studied Western industrial and military technology to build a modern state capable of resisting colonization. The slogan 'rich country, strong army' (fukoku kyohei) guided rapid industrialization, railroad construction, and military modernization. By 1905, Japan defeated Russia in war and began its own colonial expansion into Korea and Manchuria.",
  },
  {
    id: 'ri_im_008', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 3,
    text: "The 'civilizing mission' ideology used to justify European imperialism claimed that:",
    choices: { A: "Africans and Asians had superior moral knowledge that Europeans sought to learn", B: "European powers had a moral duty to spread European 'civilization' to peoples they deemed incapable of self-governance", C: "Colonialism was purely motivated by economic self-interest with no ideological component", D: "All peoples are equally civilized but have different cultural customs" },
    correct: 'B',
    explanation: "The 'civilizing mission' (mission civilisatrice in French, 'white man's burden' in Kipling's phrase) argued that European colonialism was a selfless humanitarian project. This ideology provided moral justification for conquest, slavery, and forced labor. Historians today recognize it as ideological cover for economic exploitation, though some colonial administrators genuinely believed in it.",
  },
  {
    id: 'ri_im_009', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 2,
    text: "Anti-colonial resistance movements of the 19th century were most often:",
    choices: { A: "Completely absent as colonized peoples accepted European rule", B: "Immediately successful in achieving full independence", C: "Suppressed militarily but laid social and political foundations for later 20th century independence movements", D: "Peaceful and achieved significant concessions through negotiation alone" },
    correct: 'C',
    explanation: "Most 19th century anti-colonial resistance was ultimately suppressed by superior European military technology. However, these movements preserved cultural identity, created political traditions, identified leaders and strategies, and demonstrated that resistance was possible. The Indian National Congress (1885), Zulu wars, and other resistance forms created the organizational and ideological foundations for 20th century independence movements.",
  },
  {
    id: 'ri_im_010', zoneId: 'revolution_industry', levelId: 'imperialism', skillTag: 'imperialism', difficulty: 3,
    text: "What is the most historically accurate assessment of European imperialism's overall global impact?",
    choices: { A: "Imperialism was primarily beneficial, bringing technology and education to colonized regions", B: "Imperialism was purely destructive with no lasting positive consequences", C: "Imperialism created complex, deeply unequal transformations — economic extraction and cultural suppression alongside infrastructure and unintended exposure to liberal ideas that fueled independence movements", D: "Imperialism had minimal lasting impact as colonized regions quickly recovered after independence" },
    correct: 'C',
    explanation: "Evaluating imperialism requires acknowledging multiple truths simultaneously: colonial economic policies created lasting underdevelopment; colonial violence caused enormous suffering; colonial education systems imposed European values while also exposing colonized elites to liberal ideas about rights and self-determination that they used against colonial powers. The legacy is neither simply positive nor negative but deeply ambivalent.",
  },
  // Level: social_reform
  {
    id: 'ri_sr_001', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "Karl Marx and Friedrich Engels argued in the Communist Manifesto (1848) that:",
    choices: { A: "Industrial capitalism would eventually benefit all workers through rising wages", B: "Class struggle between bourgeoisie and proletariat would lead to inevitable revolution and communist society", C: "Reform through democratic elections was the best path to worker liberation", D: "Nationalism was the primary cause of worker suffering" },
    correct: 'B',
    explanation: "Marx and Engels argued that history is driven by class conflict over the means of production. Industrial capitalism concentrated wealth in the hands of the bourgeoisie while the proletariat owned nothing but their labor. This fundamental contradiction would inevitably produce revolution, the dictatorship of the proletariat, and ultimately a classless communist society.",
  },
  {
    id: 'ri_sr_002', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "The abolition of slavery in the British Empire (1833) was most directly driven by:",
    choices: { A: "Economic decline of the slave trade making abolition profit-neutral", B: "A combination of abolitionist moral arguments, enslaved peoples' resistance, and shifting economic interests", C: "Military pressure from the United States threatening trade sanctions", D: "The exclusive influence of Catholic missionaries condemning slavery" },
    correct: 'B',
    explanation: "British abolition resulted from a long campaign. Abolitionists like William Wilberforce argued from Christian morality; enslaved people's resistance (uprisings, self-emancipation) demonstrated that slavery could not be maintained without enormous violence; and some economists argued that free wage labor was more efficient. The Slavery Abolition Act of 1833 included compensation — to slave owners, not enslaved people.",
  },
  {
    id: 'ri_sr_003', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 1,
    text: "The women's suffrage movement of the 19th and early 20th centuries primarily demanded:",
    choices: { A: "Equal pay for equal work in factories", B: "The right of women to vote in elections", C: "Access to universities and professional careers only", D: "Legal equality in marriage and divorce" },
    correct: 'B',
    explanation: "The suffrage movement focused primarily on voting rights, recognizing the vote as the foundation of political power. Women in New Zealand gained suffrage in 1893 (first country), followed by Australia (1902), Finland (1906), and many others after World War I. American women gained the vote with the 19th Amendment in 1920.",
  },
  {
    id: 'ri_sr_004', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "How did evangelical Christianity affect social reform movements in 19th century Britain and America?",
    choices: { A: "Evangelical groups universally opposed social reforms as challenges to God-ordained social order", B: "Evangelical movements motivated many reformers who saw poverty and slavery as sinful systems requiring Christian action", C: "Religion remained completely separate from social reform movements", D: "Only the Catholic Church was involved in 19th century social reform" },
    correct: 'B',
    explanation: "Evangelical Christianity drove many reform movements. The abolition movement in Britain was led largely by Quakers and evangelical Christians. The temperance movement, prison reform, and campaigns against child labor all drew on Christian moral arguments. The belief that individuals and institutions could be reformed — that sin could be overcome — provided the moral energy for sustained activism.",
  },
  {
    id: 'ri_sr_005', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "The settlement house movement, associated with Jane Addams and Hull House (1889), represented:",
    choices: { A: "Rural agricultural reform to help poor farmers", B: "Urban social work where educated reformers lived in poor neighborhoods to provide services and advocate for change", C: "Colonial reform movements in British India", D: "Housing reform for formerly enslaved people in the American South" },
    correct: 'B',
    explanation: "Settlement houses planted educated middle-class reformers in urban immigrant and working-class neighborhoods. They provided education, childcare, health clinics, and job training while also using their observations of poverty to advocate for broader social reforms — labor laws, housing regulations, public health measures. Hull House became a model for social work as a profession.",
  },
  {
    id: 'ri_sr_006', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "Which of the following BEST describes the relationship between industrialization and social reform movements?",
    choices: { A: "Social reform movements preceded industrialization and enabled it", B: "Industrialization created social problems — poverty, child labor, unsafe conditions — that inspired organized reform movements", C: "Industrialization and reform movements were entirely unrelated phenomena", D: "Reform movements consistently slowed industrialization by reducing profits" },
    correct: 'B',
    explanation: "The problems of industrialization — child labor, 12-hour workdays, industrial accidents, urban poverty, pollution — created the conditions that reform movements addressed. Early factory acts regulated child labor (1833, 1844 in Britain); public health acts addressed cholera; labor unions organized for better wages. Reform and industry developed in dialectical tension.",
  },
  {
    id: 'ri_sr_007', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 3,
    text: "How did colonialism affect social reform movements in colonized regions?",
    choices: { A: "Colonial rule had no effect on reform movements in subject nations", B: "Colonial subjects often adapted Western liberal ideas against colonial rule, demanding for themselves the rights Europeans claimed universally", C: "Colonialism eliminated all forms of social protest in colonized regions", D: "European reformers extended their movements equally to colonial territories" },
    correct: 'B',
    explanation: "Colonial education systems taught Enlightenment ideals of liberty, equality, and natural rights — but reserved these rights for Europeans. Educated colonial subjects like Gandhi, Ho Chi Minh, and Kwame Nkrumah exposed this hypocrisy, demanding that the universal principles Europeans claimed actually be applied universally. Anti-colonial nationalism thus drew heavily on Western liberal ideology against Western power.",
  },
  {
    id: 'ri_sr_008', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "How did Marxist ideas spread beyond Europe during the late 19th and early 20th centuries?",
    choices: { A: "Marx personally traveled to Asia and Africa to spread his ideas", B: "International socialist organizations and translated texts spread Marxist ideas to intellectuals worldwide", C: "European governments promoted Marxism in colonies to pacify working-class populations", D: "Marxism remained an exclusively European phenomenon until 1917" },
    correct: 'B',
    explanation: "The First and Second Internationals (socialist organizations) connected labor movements across borders. Marx's works were translated into many languages. Asian and Latin American intellectuals read and adapted Marxism — Ho Chi Minh studied in Paris, Mao read Marx in translated texts, Latin American labor movements adopted socialist ideas. Marxism became a genuinely global intellectual movement before 1917.",
  },
  {
    id: 'ri_sr_009', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 2,
    text: "19th century social reform movements most commonly shared which characteristic?",
    choices: { A: "Rejection of industrialization as inherently destructive", B: "Belief that government action and social organization could improve human conditions", C: "Hostility toward liberal democracy and voting rights", D: "Complete indifference to religion" },
    correct: 'B',
    explanation: "Despite their differences in tactics and goals, reform movements — abolitionist, suffragist, socialist, settlement house — shared the belief that human suffering was not natural or inevitable but could be reduced through deliberate action. This faith in human agency to reshape social conditions represents a key intellectual departure from earlier fatalistic acceptance of poverty and hierarchy.",
  },
  {
    id: 'ri_sr_010', zoneId: 'revolution_industry', levelId: 'social_reform', skillTag: 'reform', difficulty: 3,
    text: "The 19th century abolitionist movement's most significant long-term legacy was:",
    choices: { A: "The immediate global elimination of all forms of unfree labor", B: "Establishing that moral arguments could successfully challenge powerful economic interests and create international humanitarian law", C: "Proving that democratic majorities always support human rights causes", D: "Demonstrating that colonial powers would voluntarily give up profitable institutions when pressured" },
    correct: 'B',
    explanation: "Abolitionism pioneered many tactics of modern human rights advocacy: international networking, mass petitioning, using personal testimony of those who suffered (Frederick Douglass, Olaudah Equiano), economic boycotts. Its success despite the enormous economic interests in slavery demonstrated that organized moral campaigns could change national and international law — a precedent for later movements from women's suffrage to decolonization.",
  },
];
'''

with open('/home/user/ascend/client/src/data/apWorldHistory.js', 'a') as f:
    f.write(content)

print("Zone 3 appended successfully")
