// CHAPTER 16: Organization and Order (25 encounters)
const chapter16 = {
  chapter_number: 16,
  encounters: [
    {
      encounter_number: 1,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Order Obliterator',
      enemy_type: 'Archive Specter',
      pre_narrative: `You descend into a lower level of the Rhetoric Ruins where the archive chambers lie. Here the Order Obliterator reigns, a ghost that scrambles inscriptions by rearranging their sentences into nonsense. It floats before a stone panel, proud of its chaos. The panel describes the founding of the Grammar Guild — but the sentences are in the wrong order.`,
      passage: `[1] The Guild of Rhetoric Scholars was officially recognized by the Grammar Council in the Keep's Third Age. [2] Its founding members drafted a charter that outlined three core principles: clarity, precision, and purpose. [3] For years before the founding, small groups of like-minded scholars had been meeting informally in the Library's back rooms. [4] Those early conversations laid the groundwork for everything that followed.`,
      question_stem: `To improve the organization of this paragraph, sentence [3] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [2].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'A',
      explanation: `The paragraph traces the Guild's development in chronological order. The logical sequence is: (1) informal meetings preceded the founding, (2) the Guild was formally recognized, (3) the charter was drafted. Currently, sentence [3] — about the informal pre-founding meetings — appears after the charter was drafted, which is chronologically backward. Sentence [3] describes events that happened BEFORE sentence [1], so it should be placed before sentence [1]. Option A is correct. Option B places it after the formal recognition but before the charter, which is still chronologically wrong — the informal meetings happened before the Guild existed at all. Option C places it after the charter, which is the current wrong position. Option D keeps the wrong order.`,
      success_narrative: `The stone panel rearranges itself into perfect chronological sequence. The Order Obliterator howls and backs away from the restored inscription.`,
      failure_narrative: `The Order Obliterator scrambles the panel even further. Now the Guild is founded after its charter was written and before the meetings that inspired it.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'organization',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 2,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Sequence Sorcerer',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Sequence Sorcerer has scrambled a chronicle of the Comma Plague's containment. The events are described in completely the wrong order, and the ghost gleefully insists the paragraph "makes just as much sense this way." It does not. You must restore it.`,
      passage: `[1] Warden Holt distributed the comma guide to every district scribe within two weeks, and clarity was restored to official Keep documents. [2] At the height of the Comma Plague, public documents had become nearly unreadable due to the overuse of commas. [3] In response, Warden Holt spent three months writing a definitive guide to comma usage. [4] The Grammar Council recognized the Plague as a formal crisis and appointed Holt to lead the containment effort.`,
      question_stem: `To improve the organization of this paragraph, sentence [1] should be placed:`,
      option_a: `before sentence [2].`,
      option_b: `after sentence [2].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'D',
      explanation: `Wait — let us read the current order carefully. [1] describes the resolution; [2] describes the problem; [3] describes writing the guide; [4] describes the Council's response. The logical order of events is: [2] problem arose → [4] Council appointed Holt → [3] Holt wrote the guide → [1] Holt distributed the guide and order was restored. Sentence [1] currently appears first, which puts the resolution before the problem — that is wrong. However, the question asks where sentence [1] should be placed. It should come AFTER sentence [3] (after the guide was written, it was distributed). Option C places it after sentence [3], which is correct. Wait — re-reading: the question asks about sentence [1], and option D says "where it currently is." Currently [1] is first, which is wrong. The correct placement is after [3]. Option C is correct.`,
      success_narrative: `The Comma Plague chronicle flows in perfect causal order: problem, appointment, solution, resolution. The Sequence Sorcerer's spell shatters.`,
      failure_narrative: `The Sequence Sorcerer casts another spell and the chronicle now describes the resolution before the plague even began. Historical cause and effect are completely inverted.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'organization',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 3,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Paragraph Phantom',
      enemy_type: 'Archive Specter',
      pre_narrative: `A memorial inscription for Scholar-Medic Orin Falc has been scrambled by the Paragraph Phantom. The facts of her life are all present, but they are in such disorder that the memorial reads like a riddle. The Phantom drifts near, pleased with itself.`,
      passage: `[1] Her colleagues remembered Falc as a teacher first and a medic second, always with a red pen in her hand. [2] Scholar-Medic Orin Falc was born in the Keep's Outer Quarter, the daughter of a district scribe. [3] She trained as a medic at the Keep's Academy but never lost her original passion for grammar instruction. [4] By the time of the Ink War, Falc had spent twenty years combining battlefield medicine with active writing instruction.`,
      question_stem: `To improve the organization of this paragraph, sentence [1] should be placed:`,
      option_a: `before sentence [2].`,
      option_b: `after sentence [2].`,
      option_c: `after sentence [4].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'C',
      explanation: `The paragraph traces Falc's life in chronological order: birth and origins [2], training [3], her twenty-year career [4], and how colleagues remembered her [1]. Sentence [1] — the memorial tribute — is a conclusion/characterization that belongs at the end, after the life story has been told. Currently it appears first, before we know anything about Falc, which weakens its impact and disrupts the biographical narrative. Placing it after sentence [4] creates a natural arc: origins → training → career → legacy tribute. Option C is correct. Option A puts the tribute before even her birth, which makes no narrative sense. Option B places it right after her birth and before her training, also too early. Option D keeps the current wrong placement.`,
      success_narrative: `The memorial inscription flows from birth to tribute, a life story told in proper order. The Paragraph Phantom dissolves, unable to haunt a text that has found its shape.`,
      failure_narrative: `The Paragraph Phantom scrambles the inscription further. The memorial now begins with a tribute to someone the reader has not yet met.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'organization',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 4,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Arrangement Annihilator',
      enemy_type: 'Archive Specter',
      pre_narrative: `A traveler's account of arriving at Grammar Keep has been rearranged by the Arrangement Annihilator. The sequence of the traveler's observations — what they saw first, what they felt, what they concluded — is now backwards. Restore it.`,
      passage: `[1] Finally, passing beneath the gate's inscribed motto, she felt the strange weight of being measured by language itself. [2] The traveler approached Grammar Keep from the eastern road, seeing the great stone walls rise from the plain before anything else. [3] At the gate, she read the Keep's founding motto carved into the arch: "Every word must earn its place." [4] The walls were closer than they appeared, she realized — carved with sentences in a dozen ancient languages.`,
      question_stem: `To improve the organization of this paragraph, sentence [2] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `where it currently is (no change).`,
      option_c: `after sentence [3].`,
      option_d: `after sentence [4].`,
      correct_answer: 'B',
      explanation: `The paragraph already begins with sentence [2] — the traveler approaching and seeing the walls. The current order is [1], [2], [3], [4], and the question asks where [2] should be placed. Currently [2] is second. The logical sequence should be: [2] approaches from eastern road, sees walls → [4] walls are closer, carved with sentences → [3] at the gate, reads the motto → [1] feels the weight of being measured. So [2] should be first, not second — it needs to move before sentence [1]. Option A places [2] before [1], creating the correct order: [2][1]... wait, no. If [2] moves before [1] and [1] is currently first, the order becomes [2][1][3][4], but the correct order is [2][4][3][1]. The question only asks about [2]'s position. [2] currently is in position 2 (after [1]). [2] should be in position 1 (before [1]). Option A says "before sentence [1]" which would make [2] first — that is the correct move. Option A is correct.`,
      success_narrative: `The traveler's account flows in perfect perceptual order: approach, discovery, reading, feeling. The Arrangement Annihilator sputters and retreats.`,
      failure_narrative: `The Arrangement Annihilator is thrilled. The traveler now feels the full weight of the motto before she has even seen the walls.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'organization',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 5,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Structure Scrambler',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Structure Scrambler has scrambled a passage from the philosophical treatise on Grammar and Logic. The argument used to build carefully from premise to conclusion. Now it concludes before it has begun. The ghost challenges you to add a new sentence in the right place.`,
      passage: `[1] The First Scholars believed that mastering grammar was not merely a technical skill but a form of moral discipline. [2] A writer who could control language, they argued, had demonstrated the ability to control thought itself. [3] This belief became the philosophical foundation for every educational policy the Keep adopted over the next five centuries.`,
      question_stem: `The writer wants to add the following sentence to the paragraph: "Sloppy writing, in their view, was evidence of a sloppy mind — and a sloppy mind was a danger to any community that depended on shared understanding." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `Before sentence [1].`,
      correct_answer: 'B',
      explanation: `The new sentence — explaining that sloppy writing indicated a sloppy mind, which endangered the community — extends the reasoning of sentence [2]. Sentence [2] says controlling language means controlling thought; the new sentence explains the negative consequence of failing to do so: a sloppy mind endangers communal understanding. This cause-and-consequence relationship means the new sentence should follow immediately after sentence [2], before sentence [3] draws the historical conclusion. Option B is correct. Option A places it after sentence [1] (the general belief), but the new sentence is specifically about the consequences of failure — it elaborates on [2]'s claim about thought control, not on [1]'s general belief. Option C places it after the conclusion, which breaks the logical flow: you cannot extend an argument after you have already drawn the conclusion. Option D puts it before the paragraph's opening premise, where it has no context.`,
      success_narrative: `The philosophical argument expands perfectly, the new sentence adding causal weight exactly where needed. The Structure Scrambler cannot find a flaw to exploit.`,
      failure_narrative: `The Structure Scrambler places the sentence after the conclusion. The paragraph now argues from consequence to premise, which is exactly backward.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'organization',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 6,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Logic Looter',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Logic Looter robs paragraphs of their logical connective tissue, leaving sentences in an order that seems plausible but actually reverses cause and effect. It has attacked a passage about the Punctuation Quarter's reforms.`,
      passage: `[1] Quarter-Master Desh introduced a mandatory clarity review for all public postings in the Punctuation Quarter. [2] Within a year, citizen complaints about confusing official notices had dropped by half. [3] The Grammar Council praised Desh's initiative and recommended it as a model for other districts. [4] Desh had been appointed Quarter-Master specifically because of her reputation for innovative administrative solutions.`,
      question_stem: `To improve the organization of this paragraph, sentence [4] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [2].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'A',
      explanation: `The paragraph currently describes Desh's reform [1], its positive results [2], and the Council's praise [3] — a clean cause-effect-recognition sequence. Then sentence [4] suddenly provides background about why Desh was appointed in the first place. This background logically belongs at the beginning, before we learn what she did, so we understand who she is and why she was in this role. Option A is correct: sentence [4] should precede sentence [1] to establish context before the action. Option B places it after the introduction of the reform, but the background should come before the reform is introduced. Option C places it after the results, which is strange — explaining who someone is after describing their accomplishments disrupts the narrative. Option D keeps the current placement, which interrupts the clean cause-effect-recognition arc.`,
      success_narrative: `The Punctuation Quarter report flows from context to action to result to recognition. The Logic Looter cannot find a logical seam to exploit.`,
      failure_narrative: `The Logic Looter celebrates. The paragraph now introduces Desh's background after her work is done, as if the reader were being told an afterthought.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 7,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Coherence Crusher',
      enemy_type: 'Archive Specter',
      pre_narrative: `A passage about the Oxford Comma Debate has been disordered by the Coherence Crusher. The passage still contains all the right information, but the logical sequence of the argument has been destroyed. You must identify where a new sentence should be inserted to restore clarity.`,
      passage: `[1] The Oxford Comma Debate reached its peak intensity when the Grammar Council was forced to issue a formal ruling on the matter. [2] Warden Holt's compromise — allowing districts to choose their own convention — was seen by Logicians as an admission of defeat. [3] Grammarians, for their part, accepted the compromise as a practical acknowledgment that stylistic variation is legitimate.`,
      question_stem: `The writer wants to add the following sentence to the paragraph: "The two factions had argued for over a decade without resolution, making Council intervention unavoidable." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `Before sentence [1].`,
      correct_answer: 'A',
      explanation: `The new sentence — explaining that the decade-long deadlock made Council intervention unavoidable — serves as a causal bridge. Sentence [1] announces that the Council was "forced to issue a formal ruling." The reader naturally wonders: why was it forced? The new sentence answers that question: a decade without resolution required intervention. It should follow sentence [1] immediately, explaining why the forced ruling occurred before the paragraph moves on to describe Holt's specific compromise. Option A is correct. Option D places it before sentence [1], but without sentence [1] establishing the Council ruling first, the "making Council intervention unavoidable" clause has no immediate referent. Option B places it after Holt's compromise is described, which is too late — the explanation of why the Council had to intervene should precede the description of the ruling, not follow it. Option C places it at the very end, after both factions' reactions, where it is simply backwards.`,
      success_narrative: `The Oxford Comma passage now flows from cause to decision to reaction, the causal bridge connecting everything. The Coherence Crusher breaks apart.`,
      failure_narrative: `The Coherence Crusher shuffles the new sentence to the end of the paragraph. The Council was now forced to intervene after both sides had already accepted the compromise.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 8,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Flow Fiend',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Flow Fiend disrupts the natural momentum of prose by putting general statements where specific examples belong, and specific examples where conclusions belong. It has attacked a passage describing a scholar's field notes. This question asks you to find the best opening sentence.`,
      passage: `The Modifier Marshes are never the same twice. After three weeks of fieldwork, I had documented forty-seven distinct species of grammatical error, each with its own habitat and behavior. The dangling participle, for instance, clusters near complex sentences; the misplaced modifier prefers to lurk at the beginnings of clauses. Understanding the ecology of these errors, I have come to believe, is the only way to correct them sustainably.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `The field researcher who enters the Modifier Marshes unprepared will not survive the first week.`,
      option_b: `Grammatical errors are more common in the Modifier Marshes than in any other district of the Keep.`,
      option_c: `The Modifier Marshes have been a subject of scholarly interest for centuries, drawing researchers from across the Keep.`,
      option_d: `My first morning in the Modifier Marshes, I found seventeen grammatical errors in a single posted notice.`,
      correct_answer: 'D',
      explanation: `The paragraph is a first-person field researcher's account. It moves from observation to documentation to pattern-recognition to conclusion. The existing opening — "The Modifier Marshes are never the same twice" — is fine, but the question asks us to replace it with something better. The paragraph's voice is personal, vivid, and grounded in specific field experience. Option D matches this voice perfectly: it is first-person, specific (seventeen errors in one notice, first morning), and immediately establishes the richness of the research environment. Option A is dramatic but shifts to a survival tone that does not match the scientific-observational voice of the paragraph. Option B makes a general comparative claim that sounds like encyclopedia background rather than a field researcher's voice. Option C describes the Marshes' general scholarly popularity — also encyclopedia-style, not matching the first-person observational register.`,
      success_narrative: `The field notes open with vivid, immediate specificity. The Flow Fiend cannot slow down a paragraph that launches with such purposeful energy.`,
      failure_narrative: `The Flow Fiend replaces the opening with a vague encyclopedic sentence. The first-person field account now begins with the tone of a tourism brochure.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 9,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Disarray Daemon',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Disarray Daemon has shuffled a paragraph from the Keep's founding chronicle into four plausible orderings, only one of which is logically correct. It demands you restore the proper sequence.`,
      passage: `[1] The second generation of Keep scholars began constructing the Library before the Guild Hall was complete. [2] Their haste reflected a philosophical conviction: knowledge could not wait for perfect infrastructure. [3] The first stones of the Library's foundation were laid the same week the founding charter was signed. [4] Generations of scholars after them would cite this impatience as evidence of the founders' true priorities.`,
      question_stem: `To improve the organization of this paragraph, sentence [1] should be placed:`,
      option_a: `before sentence [3].`,
      option_b: `after sentence [3].`,
      option_c: `after sentence [2].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'B',
      explanation: `The logical sequence should be: the foundation was laid immediately after the charter [3] → construction of the Library began even before the Guild Hall was finished [1] → the haste reflected a philosophical conviction [2] → later generations cited this as evidence of priorities [4]. Currently, [1] comes before [3], which is out of order: we learn about the general Library construction before the specific founding week detail. Sentence [3] establishes when the project began (founding week), and sentence [1] elaborates on how the project progressed (before Guild Hall was complete). [3] should come first as the chronological anchor, then [1] elaborates. Option B places [1] after [3], which is correct. Option A moves [1] before [3], which is the current (wrong) order. Options C and D keep or worsen the disarray.`,
      success_narrative: `The founding chronicle resettles into perfect chronological logic. The Disarray Daemon dissolves in the order it spent centuries fighting.`,
      failure_narrative: `The Disarray Daemon shuffles the paragraph once more. Now the Library's foundation is laid after construction is already underway.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 10,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Muddle Master',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Muddle Master has removed the concluding sentence from a passage about Warden Sollis's structural review mandate and replaced it with something that almost wraps things up — but not quite. You must identify the best closing sentence.`,
      passage: `Warden Sollis's structural review mandate changed the way Grammar Keep thought about official writing. Before the mandate, documents were evaluated on grammatical correctness alone; after it, they were evaluated on whether a reader could actually understand them. The shift was subtle but consequential: it moved the standard from the writer's competence to the reader's experience.`,
      question_stem: `Which of the following best serves as the CONCLUDING sentence for this paragraph?`,
      option_a: `Warden Sollis retired from the Keep's service three years after the mandate took effect.`,
      option_b: `In doing so, Sollis had quietly transformed a grammar institution into something closer to a communication institution.`,
      option_c: `The Grammar Council voted in favor of the mandate by a margin of five to two.`,
      option_d: `Similar reforms were later attempted in other districts, with mixed results.`,
      correct_answer: 'B',
      explanation: `The paragraph traces the mandate's philosophical shift: from grammatical correctness to communicability, from writer-focused to reader-focused. A strong closing sentence should synthesize this shift and articulate its larger significance. Option B does this perfectly: "Sollis had quietly transformed a grammar institution into something closer to a communication institution" — this is the logical culmination of everything the paragraph has argued. It names the larger transformation that the shift in standards represents. Option A is a biographical fact (retirement) that is irrelevant to the paragraph's argument about the mandate's impact. Option C is a procedural fact (vote margin) that tells us nothing about the shift in standards. Option D gestures toward future implications but is vague and does not synthesize the paragraph's specific argument about the writer-to-reader shift.`,
      success_narrative: `The passage closes with a resonant, synthesizing conclusion. The Muddle Master cannot muddle a paragraph that ends exactly as it should.`,
      failure_narrative: `The Muddle Master places the retirement sentence at the end. The paragraph's powerful philosophical argument ends with a biographical footnote.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 11,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Sequence Slayer',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Sequence Slayer has disassembled a description of the Keep's apprenticeship system into five sentences that are nearly in the right order — but not quite. The misplaced sentence ruins the paragraph's cause-and-effect logic.`,
      passage: `[1] Apprentice Scholars at the Keep begin their training with a three-month immersion in the Grammar Archives, reading original documents from every historical period. [2] After the immersion, each apprentice is assigned to a Senior Warden for hands-on instruction in a specific grammar discipline. [3] The pairing is based on a diagnostic assessment conducted at the end of the immersion period. [4] Most apprentices consider the Warden pairing the most formative experience of their early training. [5] Senior Wardens report that apprentices who have completed the full immersion are significantly more prepared than those who have not.`,
      question_stem: `To improve the organization of this paragraph, sentence [5] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'C',
      explanation: `The paragraph's sequence is: immersion [1] → assignment to Warden [2] → diagnostic assessment that determines pairing [3] → apprentices find the Warden pairing formative [4] → Senior Wardens say immersion-completers are more prepared [5]. The logical issue is that sentence [5] — Wardens' testimony about the value of the immersion — should follow immediately after sentence [3], which establishes the link between immersion and Warden pairing, before sentence [4] describes the apprentices' experience of the pairing. Sentence [5] explains WHY the pairing works so well (immersion preparation), and this evidence should come before we hear that apprentices find it formative. Option C is correct. Options A and B place it too early, before the context is established. Option D keeps the current placement at the end, which is acceptable but weaker — the Warden's testimony about immersion effectiveness is more logically connected to sentence [3] than to sentence [4].`,
      success_narrative: `The apprenticeship description flows from immersion to assessment to pairing to outcomes. The Sequence Slayer cannot find a logical break to exploit.`,
      failure_narrative: `The Sequence Slayer is satisfied with the current arrangement. The paragraph describes why the pairing is formative after the evidence for it has been presented out of sequence.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 12,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Thread Thief',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Thread Thief cuts the connective thread between paragraphs, leaving passages that feel like separate, unrelated documents. It has challenged you with a best-opening-sentence question about a passage from the scholarly debate on grammar and logic.`,
      passage: `Yet it was not always so. For the Keep's first century, Logic and Grammar were taught in separate wings by separate faculties who rarely communicated. Students who studied both disciplines did so through personal initiative, not institutional design. The separation persisted until the Second Reform, when Warden Callus argued that the two disciplines were so intertwined that teaching them apart was a form of intellectual fraud.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `The debate between Logicians and Grammarians has never been fully resolved.`,
      option_b: `The unified teaching of Logic and Grammar that defines Grammar Keep today was not always considered obvious or desirable.`,
      option_c: `Warden Callus is one of the most controversial figures in the Keep's educational history.`,
      option_d: `Many scholars outside the Keep failed to understand why Logic and Grammar were taught together.`,
      correct_answer: 'B',
      explanation: `The paragraph describes how the current unified approach to Logic and Grammar was not always the practice — for the Keep's first century, the disciplines were separated. The existing opening ("Yet it was not always so") works as a pivot from a previous paragraph, but the question asks for the best standalone opener. Option B establishes the paragraph's premise directly: the unified teaching is the current reality, but it was not always seen as obvious. This gives the reader the context to understand what "yet it was not always so" implies. Option A describes an unresolved debate, but the paragraph is not about an ongoing debate — it is about a historical separation that was eventually changed by reform. Option C focuses on Warden Callus's controversy, but the paragraph describes a longer historical situation before mentioning Callus; opening with Callus makes the early history feel like backstory rather than the main subject. Option D speculates about outside scholars' reactions, which the paragraph does not address at all.`,
      success_narrative: `The passage opens with clear, contextualizing purpose. The Thread Thief cannot sever a thread that is clearly established from the very first sentence.`,
      failure_narrative: `The Thread Thief replaces the opening with a vague observation about debates. The reader has no idea what historical situation the paragraph is about to describe.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 13,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Continuity Crook',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Continuity Crook has stolen the logical continuity from a passage about the Punctuation Quarter's history. A new sentence needs to be added, but its placement will determine whether the paragraph holds together.`,
      passage: `[1] The Punctuation Quarter was established as an independent district of Grammar Keep in the Keep's Fourth Age. [2] Before that, punctuation instruction was handled haphazardly by individual Wardens with no unified standard. [3] The new Quarter introduced a standardized curriculum and a licensing system for Punctuation Wardens. [4] Within a generation, the quality and consistency of punctuation in official Keep documents had improved dramatically.`,
      question_stem: `The writer wants to add the following sentence: "The lack of standardization had led to regional variations so pronounced that documents from the Eastern Quarter were sometimes unreadable by Western Quarter scholars." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `After sentence [4].`,
      correct_answer: 'B',
      explanation: `The new sentence — describing how the lack of standardization caused regional incomprehensibility — elaborates on the "haphazard" situation described in sentence [2]. Sentence [2] says punctuation was handled without unified standard; the new sentence provides a specific, dramatic example of what this meant in practice. It should follow sentence [2] immediately, before sentence [3] introduces the solution. Option B is correct: it places the new sentence as an elaboration of the problem, creating the pattern "problem stated → problem illustrated → solution introduced → result." Option A places it after the Quarter's establishment, where it is too late — the problem is being described after the solution. Option C places it after the solution is described, which inverts cause and effect. Option D places it after the positive results, which is completely backward.`,
      success_narrative: `The Punctuation Quarter's history gains clarity: problem, illustration, solution, result. The Continuity Crook cannot steal the logic of a well-sequenced paragraph.`,
      failure_narrative: `The Continuity Crook places the sentence after the solution. The reader learns the Quarter improved things before understanding what it was improving.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 14,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Transition Trickster',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Transition Trickster has muddled the closing sentence of a passage about the Keep's educational reforms. You must choose the best concluding sentence — one that synthesizes the paragraph's argument rather than merely trailing off.`,
      passage: `The Second Reform of Grammar Keep's educational system was driven by a simple but radical idea: that students who understood WHY grammar rules existed would follow them more reliably than students who had merely memorized them. The reformers replaced rote drills with analytical exercises, asking students to compare correct and incorrect sentences and articulate the difference. The results of the reform exceeded even the reformers' expectations.`,
      question_stem: `Which of the following best serves as the CONCLUDING sentence for this paragraph?`,
      option_a: `The Second Reform took approximately five years to fully implement across all of the Keep's educational institutions.`,
      option_b: `Some scholars argued at the time that the analytical approach was too demanding for younger students.`,
      option_c: `Students trained under the new system not only wrote with greater accuracy but could explain and teach the rules they followed, multiplying the reform's impact across generations.`,
      option_d: `The Grammar Council approved the Second Reform by a unanimous vote, which was unusual for such a contentious body.`,
      correct_answer: 'C',
      explanation: `The paragraph argues that teaching grammar analytically (understanding WHY) produces better results than rote memorization. The closing sentence should amplify this argument and show its full implication. Option C does this powerfully: students not only wrote better but could explain and teach the rules — meaning the understanding they gained multiplied itself across generations. This directly extends the paragraph's core claim that understanding produces deeper, more durable competence. Option A gives an implementation timeline — a procedural detail that doesn't synthesize the argument. Option B introduces a counterargument that was apparently disproven by the results, which is interesting but interrupts the positive arc the paragraph has been building. Option D notes the unanimous vote, a political/procedural fact that says nothing about the reform's educational impact.`,
      success_narrative: `The paragraph closes with a conclusion that amplifies its core argument beautifully. The Transition Trickster cannot trick a paragraph with a conclusion this purposeful.`,
      failure_narrative: `The Transition Trickster ends the paragraph with a vote count. A powerful educational argument concludes with parliamentary procedure.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 15,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Paragraph Pillager',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Paragraph Pillager has looted the opening sentence of a passage from the Keep's philosophical treatise. Without the right opening, the paragraph's argument hangs in the air, untethered. You must restore it.`,
      passage: `They insisted that a thought not yet written was a thought not yet fully formed, and that the act of writing forced a kind of intellectual discipline that interior reflection alone could not achieve. For this reason, the Guild required every member to write a daily argument on any topic of their choosing — not to produce scholarship, but to maintain the discipline of articulation. The practice became known as the Morning Proof, and it was considered as essential as any formal debate.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `The Guild of Rhetoric Scholars held unusual views about the relationship between writing and thinking.`,
      option_b: `The Morning Proof was one of the most distinctive traditions of the Guild of Rhetoric Scholars.`,
      option_c: `Daily writing was required of all members at institutions throughout the Keep during the Third Age.`,
      option_d: `Not all scholars agreed with the Guild's emphasis on written articulation over oral debate.`,
      correct_answer: 'A',
      explanation: `The paragraph describes the Guild's belief that writing disciplines thought, and the Morning Proof practice that followed from this belief. The paragraph uses "They insisted..." at the start — implying a referent (the Guild) that should be introduced in the opening sentence. Option A introduces the Guild and signals that it held unusual views about writing and thinking — this is exactly the frame that "They insisted..." elaborates. Option B introduces the Morning Proof immediately, but the Morning Proof is not described until the second half of the paragraph; starting with it buries the philosophical premise that motivates it. Option C broadens the scope to general Keep institutions, but the paragraph is specifically about the Guild. Option D introduces opposition to the Guild's views, but the paragraph never mentions opposition — it describes the Guild's practice without acknowledging dissent.`,
      success_narrative: `The philosophical treatise opens with a clear frame that makes everything that follows coherent. The Paragraph Pillager retreats empty-handed.`,
      failure_narrative: `The Paragraph Pillager replaces the opening with a sentence about all institutions in the Keep. The passage now describes a general practice, and the Guild's specific philosophy is lost.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 16,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Order Ogre',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Order Ogre has scrambled a five-sentence passage about the Comma Plague's spread through the Keep's districts. The events are all present, but the causal chain has been destroyed. This one is trickier than it looks.`,
      passage: `[1] The Comma Plague spread from the Scholar-Quarter to the Merchant District when a contaminated proclamation was distributed city-wide. [2] Once the Merchant District was affected, commercial contracts became legally ambiguous, triggering a wave of disputes. [3] The plague originated with a single rogue Scholar who added commas to a template used for all official proclamations. [4] The Grammar Council declared a state of grammatical emergency and suspended all official document production. [5] Legal disputes overwhelmed the Council's capacity to adjudicate, forcing the emergency declaration.`,
      question_stem: `To improve the organization of this paragraph, sentence [3] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [2].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'A',
      explanation: `The correct causal sequence is: [3] origin (rogue Scholar with template) → [1] spread to Merchant District via proclamation → [2] commercial contracts become ambiguous → [5] legal disputes overwhelm Council → [4] emergency declaration. Sentence [3] is the origin of the plague and must appear first. Currently it sits in position 3 (after the plague has already spread), which makes the paragraph describe the effect before the cause. Option A places [3] before [1], making it the paragraph's first sentence and establishing the origin before describing the spread. This is the only logically correct sequence. Options B and C keep [3] after [1], which means the plague spreads before the origin is established. Option D keeps the current wrong order.`,
      success_narrative: `The Comma Plague chronicle flows in perfect causal order from origin to spread to consequence to emergency. The Order Ogre stomps in frustration and retreats.`,
      failure_narrative: `The Order Ogre is delighted. The plague now spreads across two districts before the rogue Scholar who started it has even touched the template.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 17,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Opening Obliterator',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Opening Obliterator specializes in destroying the opening sentences of paragraphs, replacing them with options that seem appropriate but fail on inspection. It has attacked a passage about the Keep's founding scholars.`,
      passage: `Each clan was proud, fiercely independent, and deeply skeptical of the others' methods. The Grammarians believed the Logicians' obsession with formal structure produced rigid, lifeless prose. The Logicians believed the Grammarians' focus on style obscured the real business of argumentation. The Rhetoricians were distrusted by both, who suspected their emphasis on persuasion was simply manipulation dressed in elegant language. That three such groups managed to found anything together remains one of the Keep's enduring mysteries.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `The three Scholar-clans that founded Grammar Keep shared a common goal but almost nothing else.`,
      option_b: `The Grammarians, Logicians, and Rhetoricians were the three most important intellectual movements in the Keep's history.`,
      option_c: `Cooperation between rival scholarly groups has always been rare at Grammar Keep.`,
      option_d: `The founding of Grammar Keep required each clan to compromise its most deeply held convictions.`,
      correct_answer: 'A',
      explanation: `The paragraph vividly portrays three clans that deeply distrusted one another, then ends with the mystery of how they managed to cooperate at all. The opening sentence needs to establish this fundamental tension: a shared goal despite profound differences. Option A does this precisely — "shared a common goal but almost nothing else" sets up the tension that every subsequent sentence illustrates. Option B describes the three movements as "important" but says nothing about their mutual hostility, which is what the paragraph is about. Option C says cooperation has "always been rare," which is too general and implies the pattern continues — but the paragraph is specifically about the founding moment when it somehow did happen. Option D says they had to compromise their convictions, which assumes a resolution the paragraph never describes; the paragraph ends by calling their cooperation a "mystery," not an achieved compromise.`,
      success_narrative: `The passage opens with the precise tension that everything else illustrates. The Opening Obliterator cannot destroy an opening sentence this well-chosen.`,
      failure_narrative: `The Opening Obliterator replaces the opening with a vague statement about scholarly importance. The mutual distrust that follows it now seems to come from nowhere.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 18,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Closing Crusher',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Closing Crusher has removed the final sentence of a biographical passage about Warden Holt and replaced it with four options, only one of which truly closes the paragraph. This ghost knows that weak endings destroy strong paragraphs.`,
      passage: `Warden Holt's career spanned forty years and three distinct phases. In his first decade, he served as a district scribe, learning how documents functioned in practice. In his second, he became a trainer of Punctuation Wardens, developing the methodologies that would define his later reforms. In his third, he rose to Chief Warden and implemented the structural review mandate that transformed the Keep's approach to official writing.`,
      question_stem: `Which of the following best serves as the CONCLUDING sentence for this paragraph?`,
      option_a: `Holt was known as a careful, systematic thinker who never acted without thorough preparation.`,
      option_b: `Each phase built deliberately on the last, so that by the time Holt reached the Keep's highest office, he had already spent thirty years preparing for it.`,
      option_c: `Holt's successor as Chief Warden was Senior Warden Desh, who continued many of his reforms.`,
      option_d: `The structural review mandate remains in effect today, having survived three subsequent administrations.`,
      correct_answer: 'B',
      explanation: `The paragraph describes three phases of Holt's career in explicit sequence, each building on the previous. The logical conclusion synthesizes this three-phase structure by making the cumulative argument explicit: each phase was preparation for the next. Option B does this directly — "each phase built deliberately on the last" — and adds the resonant observation that Holt spent thirty years preparing for the role in which he made his greatest contribution. This conclusion makes the structural argument the paragraph has been implying. Option A describes Holt as systematic and careful, which is character description that doesn't synthesize the three-phase argument. Option C introduces his successor, which shifts focus away from Holt entirely. Option D describes the mandate's durability, which is a legacy fact but does not conclude the argument about how Holt's career built toward his peak achievement.`,
      success_narrative: `Holt's biography closes with a sentence that crystallizes the entire three-phase structure into one elegant insight. The Closing Crusher cannot crush a conclusion this well-fitted.`,
      failure_narrative: `The Closing Crusher ends the paragraph with information about Holt's successor. A biography about Holt ends by pivoting to someone else.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'organization',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 19,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Pattern Phantom',
      enemy_type: 'Archive Specter',
      pre_narrative: `Deeper in the archive, the Pattern Phantom has scrambled a complex five-sentence philosophical passage. Unlike the earlier puzzles, the wrong order here is seductive — it seems almost right. Only a Scholar with mastery of logical argument structure will see the correct sequence.`,
      passage: `[1] Warden Callus's famous argument was elegant: if you cannot explain a grammar rule to a child, you do not understand it yourself. [2] This principle, he argued, was the reason so many scholars failed to teach effectively — they had learned rules without understanding them. [3] The implications were radical: the entire curriculum would need to be rebuilt from the ground up around explanatory rather than prescriptive instruction. [4] Callus spent the remaining fifteen years of his career attempting to do exactly that. [5] His methods were controversial, but the scholars who trained under him became the Keep's most effective teachers.`,
      question_stem: `To improve the organization of this paragraph, sentence [3] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [4].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'D',
      explanation: `The paragraph traces an argument → diagnosis → implication → response → result arc. [1] states Callus's elegant principle; [2] explains what problem this principle reveals (scholars who learned rules without understanding them); [3] draws the radical implication (curriculum must be rebuilt); [4] describes Callus's response (fifteen years of work); [5] gives the result (controversial but effective). This is the correct logical sequence. Sentence [3] is already where it belongs — after the diagnosis [2] and before the response [4]. Option D is correct. Option A would place the implication before the argument, which inverts the logical order. Option B would place the implication immediately after the principle is stated, before the diagnosis — the implication follows from the diagnosis, not directly from the principle alone. Option C would place the implication after Callus began his fifteen-year project, which would mean he started building before knowing what he was building toward.`,
      success_narrative: `The philosophical passage stands in perfect logical sequence. The Pattern Phantom cannot find a flaw in an argument this well-ordered.`,
      failure_narrative: `The Pattern Phantom scrambles the argument. Callus now draws implications from a diagnosis he has not yet made.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 20,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Structural Specter',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Structural Specter haunts the archive's deepest chambers, rearranging texts so they tell completely different stories. It has challenged you with a complex sentence-placement question where the new sentence changes the paragraph's entire argumentative direction depending on where it lands.`,
      passage: `[1] The Grammar Council's handling of the Oxford Comma Debate has been criticized by historians as an example of institutional paralysis. [2] For over a decade, the Council heard arguments, commissioned studies, and formed committees, all without reaching a decision. [3] Warden Holt's compromise ruling, when it finally came, was widely criticized as a non-answer — it resolved nothing but merely deferred the question to individual districts. [4] Historians sympathetic to the Council, however, argue that the compromise was precisely the correct response to a genuinely intractable problem.`,
      question_stem: `The writer wants to add the following sentence: "Yet the fact that Holt's compromise has remained in place for two centuries without causing any of the crises its opponents predicted suggests the critics may have been wrong." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `After sentence [4].`,
      correct_answer: 'D',
      explanation: `The paragraph moves from criticism of the Council [1] to specific evidence of that criticism [2] to the specific critique of Holt's ruling [3] to a sympathetic defense of the compromise [4]. The new sentence — arguing that two centuries of stability prove the critics wrong — is a logical extension of sentence [4]'s sympathetic position. It provides evidence for the claim that the compromise "was precisely the correct response": it has lasted two centuries without the predicted crises. This sentence belongs after sentence [4], where it supports and extends the pro-compromise argument. Option D is correct. Option A places it right after the initial criticism, before any evidence is presented — the rebuttal would come before the case being rebutted. Option B places it mid-paragraph, after the Council's paralysis is described but before Holt's ruling is introduced — the new sentence is about Holt's ruling specifically, so it cannot come before the ruling is mentioned. Option C places it right after the criticism of Holt's ruling, which is plausible but would interrupt the transition to sentence [4]'s sympathetic defense; better to have both defenses together.`,
      success_narrative: `The Council history closes with a powerful, evidence-based rebuttal of its critics. The Structural Specter shatters — it cannot haunt a text whose structure is this airtight.`,
      failure_narrative: `The Structural Specter places the rebuttal before the criticism it is rebutting. The paragraph now defends a position that has not yet been attacked.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 21,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Chain Breaker',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Chain Breaker destroys the logical chains that connect ideas within paragraphs. It has presented you with a passage that has been stripped of its opening sentence and replaced with four very plausible options. This one will require careful reading of what the paragraph is actually arguing.`,
      passage: `The dispute was not about grammar at all, in the end. It was about authority — specifically, about who had the right to determine what counted as correct language: trained scholars with formal credentials, or the common citizens whose daily use of language gave it its actual meaning. The Prescriptivists held the first position; the Descriptivists held the second. The debate between them, which began in the Fifth Age and has never truly ended, remains the Keep's most fundamental unresolved question.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `The Oxford Comma Debate ultimately revealed a deeper division within the Keep's scholarly community.`,
      option_b: `The Prescriptivist and Descriptivist traditions have long competed for dominance in the Keep's grammar curriculum.`,
      option_c: `Grammar Keep has always struggled to define its own institutional mission.`,
      option_d: `Many scholars have argued that the real purpose of grammar instruction is not correctness but clarity.`,
      correct_answer: 'A',
      explanation: `The paragraph argues that a particular dispute (implied to be the Oxford Comma Debate, given the chapter context) revealed something deeper: a philosophical schism about authority over language. The opening sentence needs to identify that dispute and signal that it revealed something deeper. Option A does both: it names the Oxford Comma Debate and identifies it as the surface event that revealed a deeper division. Option B jumps straight to the Prescriptivist/Descriptivist competition without establishing that a specific dispute brought it to a head. Option C makes a vague institutional claim that could open any number of paragraphs — it doesn't specify what dispute or what deeper question. Option D introduces a correctness-vs-clarity distinction that is related but not what the paragraph is about; the paragraph is about who has authority over language, not about what the goal of grammar instruction is.`,
      success_narrative: `The passage opens with surgical precision, identifying the surface dispute before revealing the deeper schism. The Chain Breaker cannot break what is so clearly connected.`,
      failure_narrative: `The Chain Breaker opens the paragraph with a vague institutional observation. The reader has no idea what dispute revealed the deeper schism.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 22,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Argument Arranger',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Argument Arranger does not destroy paragraphs — it rearranges them just slightly, in ways that seem harmless but undermine the logical force of the argument. You face a five-sentence passage and must restore one misplaced sentence to its correct position.`,
      passage: `[1] The most common mistake in teaching grammar is presenting rules without exceptions. [2] A rule presented without its exceptions teaches students that language is simpler than it is, which makes them worse grammarians, not better. [3] The exceptions to a rule are not failures of the rule — they are evidence of the rule's boundaries, and understanding those boundaries is what mastery looks like. [4] Students who memorize rules without exceptions consistently perform worse on complex writing tasks than those who learn the full rule with its complications. [5] The Keep's most effective grammar instructors have always taught exceptions first, as a way of showing students what the rule is actually protecting against.`,
      question_stem: `To improve the organization of this paragraph, sentence [4] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'B',
      explanation: `The paragraph's logical sequence should be: [1] state the mistake (rules without exceptions) → [4] provide evidence that this mistake produces worse outcomes → [2] explain why (oversimplification creates worse grammarians) → [3] reframe exceptions as proof of mastery → [5] describe how effective instructors respond. Sentence [4] — the empirical finding that students who memorize rules without exceptions perform worse — is evidence for the claim in sentence [1]. It belongs right after sentence [1] states the mistake, before sentence [2] explains the mechanism. Currently, sentence [4] appears fourth, after the explanation and reframing, which means the evidence comes after the conclusion it supports. Option B places [4] after [1], providing evidence immediately after the claim. Option A is wrong — putting evidence before the claim it supports is illogical. Options C and D keep [4] too late in the sequence.`,
      success_narrative: `The pedagogical argument flows from claim to evidence to explanation to reframing to practice. The Argument Arranger cannot rearrange what is now so evidently correct.`,
      failure_narrative: `The Argument Arranger keeps sentence [4] where it is. The evidence for the paragraph's central claim now appears after the conclusion has already been drawn.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 23,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Text Toppler',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Text Toppler topples entire paragraphs by removing the sentence that holds everything else up. It has deleted the concluding sentence from a complex philosophical argument about the Keep's debate traditions. You must find the sentence that truly closes this paragraph.`,
      passage: `Scholar-debates in the Keep's Fifth Age were designed not to produce winners but to produce understanding. A participant who "won" by overwhelming an opponent was considered to have failed — the goal was always to advance the collective understanding of the question, not to defeat the individual who held the opposing view. This is why the debate records from the Fifth Age read so differently from those of the Sixth: in the Fifth, even lost arguments feel generative.`,
      question_stem: `Which of the following best serves as the CONCLUDING sentence for this paragraph?`,
      option_a: `The Fifth Age produced more published scholarly treatises than any other period in the Keep's history.`,
      option_b: `In the Sixth Age, debates became more competitive and the quality of collective reasoning visibly declined.`,
      option_c: `The question of what debates are FOR — competition or understanding — remains unresolved in the Keep to this day.`,
      option_d: `Modern scholars who study these records consistently remark that Fifth Age participants seemed more interested in getting things right than in being right.`,
      correct_answer: 'D',
      explanation: `The paragraph argues that Fifth Age debates were oriented toward collective understanding rather than individual victory. The existing final sentence already notes that even lost arguments "feel generative" in the debate records. A strong conclusion should extend or synthesize this observation. Option D does this perfectly: it provides the reader perspective (modern scholars' consistent observation) and articulates the precise quality that "getting things right" versus "being right" captures — this is a resonant restatement of the paragraph's core distinction. Option A introduces a publication count — a historical quantitative fact that does not follow from or synthesize the paragraph's qualitative argument. Option B describes the Sixth Age's decline — this is a comparison that shifts focus to a different age; the paragraph's final existing sentence already briefly mentions the Sixth Age contrast, so a full sentence on it would be redundant. Option C raises a new, unresolved question — which is interesting, but a concluding sentence should close, not open.`,
      success_narrative: `The debate passage closes with a modern scholars' insight that crystallizes the paragraph's argument. The Text Toppler cannot topple what ends so firmly.`,
      failure_narrative: `The Text Toppler ends the paragraph with a publication count. The argument about competition versus understanding now concludes with a statistic about treatises.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 24,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Layout Looter',
      enemy_type: 'Archive Specter',
      pre_narrative: `The Layout Looter has stolen the logical framework from a passage about the Keep's annual grammar review. A new sentence must be added, but its placement is deceptively difficult — the wrong choice will create a logical non sequitur even while appearing to fit.`,
      passage: `[1] The Grammar Council's annual review process begins with data collection: every district submits a sample of five hundred documents from the previous year. [2] A committee of seven Senior Wardens analyzes the samples for patterns of error, categorizing mistakes by type, frequency, and district of origin. [3] Based on these patterns, the Council issues a set of targeted recommendations — specific interventions for specific error types in specific districts. [4] Districts that implement the recommendations consistently show measurable improvement within two years.`,
      question_stem: `The writer wants to add the following sentence: "This targeted approach stands in sharp contrast to earlier systems, which issued blanket mandates that applied the same remedy to every district regardless of their specific weaknesses." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `After sentence [4].`,
      correct_answer: 'C',
      explanation: `The new sentence explains that the targeted, district-specific approach is better than earlier blanket mandates. The word "this targeted approach" must refer to something previously described. Sentence [3] is the sentence that introduces the targeted nature of the recommendations: "specific interventions for specific error types in specific districts." The new sentence's opening phrase — "this targeted approach" — directly refers to sentence [3]'s description of targeted, specific recommendations. It should follow sentence [3] immediately, before we move to sentence [4]'s evidence of effectiveness. Option C is correct. Option A places it after data collection, before the targeted recommendations have even been introduced — "this targeted approach" would have no referent. Option B places it after the error-pattern analysis, also before the targeted recommendations are described. Option D places the contrast after the effectiveness evidence, which is logical but weaker — the contrast belongs with the description of the approach, not after its results.`,
      success_narrative: `The review process is described with perfect structural logic. The Layout Looter cannot loot the framework of a paragraph this carefully organized.`,
      failure_narrative: `The Layout Looter places the comparison sentence before targeted recommendations have been described. "This targeted approach" now refers to nothing that has been mentioned.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 25,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Organization Omen',
      enemy_type: 'Archive Specter',
      pre_narrative: `The final guardian of Chapter 16 rises from the deepest archive: the Organization Omen, a specter so powerful it can make completely disordered paragraphs appear coherent to the untrained eye. It has assembled a passage whose order seems natural — but is subtly and fatally wrong. Only true mastery will see the correct placement.`,
      passage: `[1] The Descriptivist movement's most radical claim was that no grammar form is inherently incorrect — only inappropriate for its context. [2] This position alarmed the Prescriptivists, who argued that without objective standards, the Keep's entire editorial function would become meaningless. [3] The Descriptivists countered that their position did not eliminate standards but relocated them: from abstract rules to contextual appropriateness. [4] This reframing, paradoxically, required more grammatical sophistication, not less — because judging contextual appropriateness demands a deeper understanding of language than rule-following alone provides. [5] The debate, in the end, was not about whether standards should exist, but about what kind of standards could adequately describe how language actually works.`,
      question_stem: `To improve the organization of this paragraph, sentence [5] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [2].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'D',
      explanation: `This question tests whether you can recognize when a paragraph is already correctly ordered. The sequence is: [1] Descriptivist radical claim → [2] Prescriptivist alarm and counterargument → [3] Descriptivist rebuttal → [4] deeper implication of the rebuttal → [5] synthesis of what the debate was really about. Sentence [5] is a conclusion that synthesizes the entire exchange — it belongs at the end, which is where it currently sits. Option D is correct. Option A would place the synthesis/conclusion before the debate has even begun — the reader would have nothing to synthesize. Option B places the conclusion right after the Prescriptivist alarm, before the Descriptivists have even rebutted — the synthesis would be premature. Option C places it after the rebuttal but before the deeper implication — but the synthesis should come after all the argumentative moves, including [4].`,
      success_narrative: `The paragraph stands in perfect order, its logical sequence from claim to alarm to rebuttal to implication to synthesis completely intact. The Organization Omen dissolves — it cannot haunt a text that was never disordered. You have mastered Chapter 16.`,
      failure_narrative: `The Organization Omen celebrates your incorrect move. The synthesis now appears before the argument it is summarizing, making it a prediction rather than a conclusion.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
  ]
};

module.exports = chapter16;
