// CHAPTER 19: BOSS — The Irrelevant Lord (20 encounters)
const chapter19 = {
  chapter_number: 19,
  encounters: [
    // ===== RELEVANCE QUESTIONS (E1-5) =====
    {
      encounter_number: 1,
      type: 'boss',
      difficulty: 2,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord rises from his throne — a massive pile of disorganized scrolls. "You have come this far, Scholar. Impressive. Also, did I mention the Keep was founded in spring? Irrelevant! The point is—" He gestures wildly. "Twenty questions stand between you and my defeat. Also, the east tower has a leak. Prepare yourself." He hurls a passage at your feet.`,
      passage: `[1] The Prescriptivist tradition in Grammar Keep holds that language has an inherent logical structure that educated writers are obligated to reflect. [2] Prescriptivists believe that grammar rules are not arbitrary conventions but are derived from the underlying structure of thought itself. [3] The word "Prescriptivist" derives from the Latin "praescribere," meaning to write beforehand. [4] This position makes the Keep's grammar instruction not merely a technical exercise but a form of intellectual discipline — a training of the mind to align with the structure of reality.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the etymology of the word "Prescriptivist" does not contribute to the paragraph's philosophical argument about what Prescriptivism holds.`,
      option_b: `Yes, because the Latin definition contradicts the paragraph's claim that Prescriptivism is about the structure of thought.`,
      option_c: `No, because understanding the word's origin helps readers understand what the Prescriptivist position actually means.`,
      option_d: `No, because it provides important historical context about when Prescriptivism first developed.`,
      correct_answer: 'A',
      explanation: `The paragraph makes a philosophical argument about Prescriptivism: it holds that grammar reflects thought's logical structure, making instruction a form of intellectual discipline. Sentence [3] provides the Latin etymology of "Prescriptivist" — "praescribere," to write beforehand. This is a lexicographical fact that tells us nothing about the philosophical position the paragraph is describing. Option A correctly identifies this: the etymology does not advance the philosophical argument. Option B is wrong — the Latin meaning does not contradict the thought-structure claim; it simply has nothing to do with it. Option C argues etymology helps readers understand the position, but "write beforehand" (prescribe) does not illuminate the philosophical claim that grammar reflects the structure of thought. Option D invents a historical claim about the word's origin indicating when Prescriptivism developed, which the etymology does not establish.`,
      success_narrative: `The philosophical argument stands cleaner and more focused. The Irrelevant Lord sputters — "But the etymology! Also, the library was built on a Wednesday!" You ignore him.`,
      failure_narrative: `The Irrelevant Lord claps. "Excellent! Leave the etymology in. Also, would you like to hear about the history of the word 'grammar'? No? Irrelevant! Moving on."`,
      xp_reward: 100,
      rune_reward: 5,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 2,
      type: 'boss',
      difficulty: 2,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord paces his scroll-covered throne room. "The second question! Also, I should mention that I had an excellent breakfast this morning. Porridge. Irrelevant! Focus! The passage is about the Comma Plague. Which, by the way, is unrelated to the Great Ink Drought of the Eighth Age. Completely different crisis. Irrelevant!"`,
      passage: `[1] The Comma Plague's most lasting damage was not to official documents but to public trust in written communication. [2] For years after Warden Holt's guide restored technical accuracy to Keep documents, ordinary citizens remained skeptical of any document that used complex punctuation. [3] This skepticism led some districts to adopt simplified writing standards for public notices — short sentences, minimal punctuation, maximum clarity. [4] Warden Holt was also known for his work on semicolon standardization, which he completed a decade before the Plague. [5] The legacy of the Plague, paradoxically, was a permanent improvement in the accessibility of public communication.`,
      question_stem: `The writer is considering deleting sentence [4] from the paragraph. Should sentence [4] be deleted?`,
      option_a: `Yes, because the reference to Holt's earlier semicolon work is unrelated to the paragraph's focus on the Comma Plague's long-term effects on public trust and communication accessibility.`,
      option_b: `Yes, because it undermines the paragraph's argument by suggesting Holt was involved in punctuation problems before the Plague.`,
      option_c: `No, because it establishes Holt's expertise, making the paragraph's references to his Plague response more credible.`,
      option_d: `No, because it provides important context about the Keep's punctuation problems that preceded the Comma Plague.`,
      correct_answer: 'A',
      explanation: `The paragraph traces the Comma Plague's lasting effects: damage to public trust [1], lasting skepticism [2], simplified standards [3], and improved accessibility [5]. Sentence [4] introduces a different project of Holt's — semicolon standardization from a decade before the Plague — which has no connection to the Plague's effects or to public trust. Option A correctly identifies this as a digression. Option B misreads the sentence — Holt's semicolon work does not imply he caused problems; it is simply irrelevant. Option C argues the earlier work establishes Holt's expertise, but the paragraph does not need to establish his credentials — it is about the Plague's effects, not Holt's biography. Option D fabricates a contextual claim: semicolon standardization from a decade before the Plague does not explain the Plague or what preceded it.`,
      success_narrative: `The Plague's legacy narrative flows from trust damage to adaptive simplification to paradoxical improvement. The Irrelevant Lord clutches his semicolon notes defensively.`,
      failure_narrative: `The Irrelevant Lord beams. "Excellent! Keep the semicolon sentence. Irrelevant context is my favorite kind of context."`,
      xp_reward: 100,
      rune_reward: 5,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 3,
      type: 'boss',
      difficulty: 2,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Question three!" the Irrelevant Lord announces, knocking over a stack of scrolls. "This one is about relevance, which is ironic, given that I am the master of irrelevance. Also, the scroll I just knocked over was about the history of sandals. Completely unrelated to grammar. Moving on!"`,
      passage: `The founding charter of Grammar Keep was ratified at a moment of unusual political unity among the three Scholar-clans. All three clan leaders signed the document on the same day, in the same hall, before the same assembled witnesses — a ceremony designed to eliminate any future claim that one clan had been coerced into agreement. The ceremony lasted three hours and concluded with a formal reading of the charter's preamble by each clan leader in turn.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `The hall where the signing took place had been constructed only six months earlier, using stone from all three clans' traditional territories.`,
      option_b: `The charter's preamble was written in a formal archaic dialect that was equally foreign to all three clans, so that no single group could claim linguistic ownership of the document.`,
      option_c: `The three clan leaders had previously met on four separate occasions without reaching agreement before this final signing.`,
      option_d: `Grammar Keep's founding charter is housed today in a climate-controlled archive chamber in the Keep's eastern wing.`,
      correct_answer: 'B',
      explanation: `The paragraph's main idea is that the charter's ratification was designed to prevent any future claim of coercion — the simultaneous signing, same location, same witnesses, and individual readings were all procedural safeguards for political legitimacy. Option B supports this directly by adding another such safeguard: the archaic dialect ensured no clan could claim linguistic ownership. This is precisely the kind of deliberate neutralizing measure the paragraph is describing. Option A describes the hall's construction materials — a detail about origins that does not contribute to the argument about political legitimacy. Option C mentions previous failed meetings — this is historical context but not evidence of safeguards against coercion. Option D describes the current location of the charter — a preservation detail entirely irrelevant to the political legitimacy of the signing ceremony.`,
      success_narrative: `The argument about political safeguards gains another precise example. The Irrelevant Lord scowls. "You found the relevant sentence! Annoying. Also, the signing hall has excellent acoustics. Irrelevant!"`,
      failure_narrative: `The Irrelevant Lord is delighted with your choice of the hall's construction materials. "Perfect! Completely beside the point. Just like everything I love."`,
      xp_reward: 100,
      rune_reward: 5,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 4,
      type: 'boss',
      difficulty: 2,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord rifles through a pile of scrolls looking for the right passage. "Fourth question! Ah, here. A philosophical treatise. Excellent. Also, did you know that the treatise's author had a dog named Syntax? Completely true. Also completely irrelevant. Proceed."`,
      passage: `[1] The greatest obstacle to the Descriptivist movement was not the Prescriptivists' intellectual opposition but their institutional power. [2] Prescriptivists controlled the Grammar Council, the curriculum committees, and the official standards review boards for most of the Keep's history. [3] Descriptivist scholars were often denied access to the Keep's publishing resources, preventing their work from reaching wider scholarly audiences. [4] The Descriptivist movement originated in the Fourth Age, when scholars began systematically cataloguing actual usage patterns in documents from across the Keep's districts. [5] Without institutional support, the Descriptivists had to build their arguments from the margins — through correspondence, informal lectures, and quietly circulated manuscripts.`,
      question_stem: `The writer is considering deleting sentence [4] from the paragraph. Should sentence [4] be deleted?`,
      option_a: `Yes, because the paragraph is about the Descriptivists' institutional disadvantages, and sentence [4]'s historical origin information is not relevant to that argument.`,
      option_b: `Yes, because the Fourth Age origin date contradicts the paragraph's claim that Prescriptivists controlled the Keep for most of its history.`,
      option_c: `No, because knowing when the movement originated helps the reader understand how long the institutional struggle lasted.`,
      option_d: `No, because sentence [4] explains why the Descriptivists were denied access to publishing resources.`,
      correct_answer: 'A',
      explanation: `The paragraph is a sustained argument about the Descriptivists' institutional marginalization: Prescriptivists held institutional power [1][2], Descriptivists were denied resources [3], and this forced them to work from the margins [5]. Sentence [4] introduces the origin story of Descriptivism in the Fourth Age — when and how it began. This is historical background about the movement's development, not about their institutional disadvantage. Option A correctly identifies this as irrelevant to the paragraph's specific argument. Option B is wrong — knowing the movement started in the Fourth Age does not contradict the Prescriptivists' control; the two facts are compatible. Option C argues the origin date helps calculate the struggle's duration, but the paragraph never makes a claim about duration; it makes a claim about power dynamics. Option D is wrong — the origin story does not explain why Descriptivists were denied resources; Prescriptive institutional control explains that.`,
      success_narrative: `The institutional power argument flows uninterrupted. The Irrelevant Lord is visibly frustrated. "The dog, though — surely the dog is relevant to something?"`,
      failure_narrative: `The Irrelevant Lord celebrates. "Excellent! Historical origin mixed in with institutional disadvantage — maximum confusion achieved."`,
      xp_reward: 100,
      rune_reward: 5,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 5,
      type: 'boss',
      difficulty: 2,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Five questions in!" the Irrelevant Lord announces. "You have done well. Also, I should mention that this hall was once used for storage. Barrels, mainly. Absolutely irrelevant. Now. The fifth relevance question — and this one has a trap."`,
      passage: `[1] The Grammar Council's decision to commission a permanent written record of the Oxford Comma Debate was itself a statement about the debate's significance. [2] By creating an official archive of the arguments on both sides, the Council implicitly endorsed the idea that the question of serial comma usage was too complex for a single definitive ruling. [3] The archive fills fourteen volumes and is consulted by scholars studying the history of prescriptive versus descriptive grammar disputes. [4] The archive's existence has had an unintended consequence: it has preserved the Descriptivist arguments in a form that allowed later generations to rediscover and build upon them.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the physical description of the archive's size and its current scholarly use does not contribute to the paragraph's argument about what the archive's creation reveals about the Council's position.`,
      option_b: `Yes, because fourteen volumes suggests the archive is too large to be practically useful, which contradicts the paragraph's positive view of the archive.`,
      option_c: `No, because sentence [3] provides evidence that the archive has lasting scholarly value, which supports the paragraph's argument about the debate's significance.`,
      option_d: `No, because sentence [3] serves as a transition between the archive's creation [2] and its unintended consequence [4].`,
      correct_answer: 'A',
      explanation: `This is the hardest type: a "keep it or delete it" question where the "no" options are very plausible. The paragraph argues that creating the archive was itself a statement — an implicit acknowledgment of complexity. Sentence [3] tells us the archive fills fourteen volumes and is consulted by grammar historians. This is factual bibliographic information about the archive's physical size and scholarly use. The paragraph's argument is about what the archive's existence means philosophically (the Council's implicit position); sentence [3] describes what the archive looks like and who reads it now. Option A correctly identifies this as irrelevant to the philosophical argument. Option B invents a negative reading not in the text. Option C argues the archive's scholarly use supports the significance claim, but the paragraph establishes significance through the Council's decision, not through how many volumes the archive fills. Option D argues sentence [3] transitions between [2] and [4], but [2] and [4] connect naturally: the archive was created → the archive had an unintended consequence. No transition through [3] is needed.`,
      success_narrative: `The philosophical argument about the archive's meaning flows cleanly. The Irrelevant Lord groans. "But the fourteen volumes! So many volumes! Surely that is relevant to SOMETHING." It is not.`,
      failure_narrative: `The Irrelevant Lord cheers. "Option C! The archive's scholarly use supports its significance! But you missed the trap — that was about current use, not about what the archive's creation revealed."`,
      xp_reward: 100,
      rune_reward: 5,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    // ===== ORGANIZATION QUESTIONS (E6-10) =====
    {
      encounter_number: 6,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Organization questions!" the Irrelevant Lord bellows. "My second favorite type of chaos! Also, the Archive of Disordered Texts is located on the north side of the building. Irrelevant. But did you know that the north side gets less sunlight? Also irrelevant! Now. This paragraph has been scrambled."`,
      passage: `[1] The three Scholar-clans' agreement to found Grammar Keep was secured not by trust but by mutual exhaustion. [2] For thirty years, they had attempted to establish separate institutions, each failing for lack of resources. [3] A joint institution was the last option remaining — and all three clans knew it. [4] The decision to cooperate, therefore, was not an act of idealism but of pragmatic necessity. [5] Historians have sometimes romanticized the founding as a moment of scholarly unity, missing the desperation that actually drove it.`,
      question_stem: `To improve the organization of this paragraph, sentence [5] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'A',
      explanation: `The paragraph makes a revisionist historical argument: the founding was driven by exhaustion and pragmatic necessity, not idealism. The correct sequence should establish the revisionist frame first, then provide the evidence. Sentence [5] — historians have romanticized the founding, missing the desperation — is a framing sentence that sets up the paragraph's argument. It should appear at the beginning, before the argument is made, so the reader understands the paragraph is correcting a common misreading. Currently, [5] appears at the end as an afterthought. Placing it before [1] makes the structure: here is the myth → [1] here is the reality → [2][3] here is the evidence → [4] here is the conclusion. Option A is correct. Options B and C place the framing sentence inside the argument rather than before it, which is awkward. Option D keeps it at the end, where it functions as a commentary on what was just said rather than a frame for what is about to be said.`,
      success_narrative: `The paragraph now opens with the revisionist frame, making the evidence that follows feel like a correction of a common error. The Irrelevant Lord is flustered. "The sentences were fine where they were! Also, who romanticizes things? Historians. Irrelevant!"`,
      failure_narrative: `The Irrelevant Lord is pleased. "Leave the framing sentence at the end, where it arrives too late to frame anything. Maximum organizational inefficiency."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 7,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord produces a scroll from somewhere inside his robes. "This passage about Warden Callus has been reorganized. Or rather, disorganized. By me. Also, Callus had an interesting hat. Completely irrelevant. Now answer."`,
      passage: `[1] The result was a generation of scholars who could not explain why any rule was true — only that it was. [2] Warden Callus inherited an educational system that had calcified around rote memorization. [3] Students were drilled on correct forms without any instruction in the principles that made those forms correct. [4] Callus diagnosed this as a failure of understanding masquerading as a success of training. [5] His response was to dismantle the rote curriculum entirely and replace it with an explanatory one.`,
      question_stem: `To improve the organization of this paragraph, sentence [1] should be placed:`,
      option_a: `before sentence [2].`,
      option_b: `after sentence [2].`,
      option_c: `after sentence [3].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'C',
      explanation: `The logical sequence should be: [2] Callus inherited a calcified system → [3] students were drilled without understanding WHY → [1] result: a generation who could not explain rules → [4] Callus diagnosed this failure → [5] his response was to dismantle the rote curriculum. Sentence [1] describes the result of the situation described in sentence [3] — after students are drilled on forms without principles, the result is scholars who cannot explain the rules. So [1] should follow directly from [3], before Callus's diagnosis in [4]. Currently [1] appears first, before we know the context that produced this result. Option C is correct: [1] follows [3] as its direct consequence. Options A and B place [1] before the cause [3] is established. Option D keeps the wrong first-position placement.`,
      success_narrative: `The causal chain flows perfectly: system → practice → consequence → diagnosis → response. "Hmph," says the Irrelevant Lord. "The hat was still interesting."`,
      failure_narrative: `The Irrelevant Lord claps. "The result appears before the cause! Perfect organizational chaos. Just how I like it."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 8,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"A sentence placement question!" the Irrelevant Lord declares. "I have removed the best sentence from this paragraph and replaced it with four options. Only one actually fits. Also, the Grammar Council once had a member named Gerald. Completely unimportant. Now choose."`,
      passage: `[1] The Descriptivist scholars of the Fifth Age faced a fundamental rhetorical challenge. [2] Their strongest evidence — that actual usage patterns showed enormous variety — was easily dismissed by Prescriptivists as evidence of widespread error. [3] Every example they offered of non-standard usage being widely understood was met with the reply: "widespread understanding of an error does not make it acceptable." [4] The Descriptivists needed a framework that shifted the grounds of the debate entirely.`,
      question_stem: `The writer wants to add the following sentence: "They were, in effect, playing on their opponents' field, using their opponents' rules — and losing." Where would this sentence most logically fit?`,
      option_a: `After sentence [1].`,
      option_b: `After sentence [2].`,
      option_c: `After sentence [3].`,
      option_d: `After sentence [4].`,
      correct_answer: 'C',
      explanation: `The new sentence — "playing on their opponents' field, using their opponents' rules" — is a figurative synthesis of the rhetorical situation described in sentences [2] and [3]. It describes the Descriptivists' fundamental problem: they were arguing using the Prescriptivists' framework (correct/incorrect) and therefore losing. This synthesis belongs after sentence [3], which completes the description of the rhetorical trap (every example dismissed as widespread error), and before sentence [4], which says they needed a different framework. The new sentence bridges [3] and [4] perfectly: here is the trap ([3]) → here is the diagnosis of the trap (new sentence) → here is what they needed to do ([4]). Option C is correct. Option A places it after the general statement of challenge, before the specific trap is described. Option B places it after [2] but before [3] completes the pattern — better to have the full description of the trap first. Option D places it after the need for a new framework is stated, which makes it redundant.`,
      success_narrative: `The sentence slots perfectly between the trap and the need for escape. The Irrelevant Lord scowls. "Fine. Also, Gerald was a very competent Council member. Completely irrelevant."`,
      failure_narrative: `The Irrelevant Lord is delighted that you placed the bridging sentence after the solution. "The diagnosis now follows the cure. Maximum organizational disorder."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 9,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord sweeps a stack of scrolls off a table dramatically. "Best opening sentence question! Also, I once tried to write a best opening sentence for my autobiography. It read: 'I was born.' Very strong. Also irrelevant. Now: this passage about the Keep's debate tradition has lost its opening."`,
      passage: `There was no shame in losing a debate — only in losing it badly. "Losing badly" meant failing to advance the argument, failing to acknowledge strong counter-evidence, or resorting to rhetorical tricks when one's position could not be defended on its merits. A scholar who lost a well-argued debate against a stronger position was respected. A scholar who won through cleverness while conceding nothing to the evidence was held in contempt.`,
      question_stem: `Which of the following best serves as the OPENING sentence for this paragraph?`,
      option_a: `Grammar Keep's Fifth Age was famous for the quality of its scholarly debates.`,
      option_b: `The debates of Grammar Keep's Fifth Age were governed by an unusual ethical code that prioritized intellectual honesty over victory.`,
      option_c: `Many scholars have written about the debate culture of Grammar Keep's Fifth Age.`,
      option_d: `Winning debates was considered very important at Grammar Keep.`,
      correct_answer: 'B',
      explanation: `The paragraph describes a specific ethical code that governed Fifth Age debates: the focus was on intellectual honesty and advancing the argument, not on winning. The opening sentence must frame this ethical code as the paragraph's subject. Option B does this precisely: "governed by an unusual ethical code that prioritized intellectual honesty over victory" introduces exactly the framework the paragraph will explain and illustrate. Option A notes the debates were famous for quality but does not signal the ethical dimension that the paragraph actually describes. Option C is a vague scholarly framing ("many scholars have written") that commits to nothing specific. Option D says winning was "very important" — but the paragraph's entire point is that winning was not the primary value; intellectual honesty was. Option D would directly contradict the paragraph's argument.`,
      success_narrative: `The debate passage opens by establishing the ethical framework that all the examples illustrate. The Irrelevant Lord is annoyed. "Option D was so close to right. But backwards."`,
      failure_narrative: `The Irrelevant Lord is pleased. "Option A! Famous for quality! Now the ethical code described afterward has no frame to fit into."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 10,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Ten questions!" the Irrelevant Lord announces. "Halfway there. You are doing annoyingly well. Also, the Rhetoric Ruins were renovated in the Sixth Age. The east wall has newer stone. Completely irrelevant. Now. Best closing sentence."`,
      passage: `The founding of Grammar Keep required each of the three Scholar-clans to relinquish something precious. The Grammarians gave up exclusive control over language standards. The Logicians gave up the claim that their discipline was primary. The Rhetoricians gave up the most — their independence, their reputation for persuasive cunning, their image as the Keep's most sophisticated thinkers.`,
      question_stem: `Which of the following best serves as the CONCLUDING sentence for this paragraph?`,
      option_a: `The founding process was difficult and took many years to complete.`,
      option_b: `The three clans contributed different disciplines that together formed the intellectual foundation of the institution.`,
      option_c: `In giving up these things, each clan received something the others could not provide alone: the permanence and credibility of a shared institution.`,
      option_d: `The Grammarians eventually came to dominate the Keep's administrative structure.`,
      correct_answer: 'C',
      explanation: `The paragraph describes a series of sacrifices — each clan gave up something precious. A strong closing sentence should complete the argument by answering the implicit question: what did they get in return? Option C does this: in exchange for their sacrifices, each clan received what none could provide alone — permanence and credibility through shared institution. This creates a satisfying argumentative arc: sacrifice → reward. Option A is vague and descriptive ("difficult and took many years") — it does not synthesize the sacrifice theme. Option B describes the complementary disciplines, which is a different point about what each contributed, not about what each gave up and gained. Option D introduces a later historical development about Grammarian dominance — interesting but irrelevant to the founding sacrifices theme.`,
      success_narrative: `The paragraph closes with the answer to its own implicit question. The Irrelevant Lord sighs. "Very well. Also, the east wall stone is limestone, not granite. Still irrelevant."`,
      failure_narrative: `The Irrelevant Lord applauds your choice of Option B. "The complementary disciplines! But that is a different paragraph's conclusion, not this one's."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    // ===== TRANSITION QUESTIONS (E11-15) =====
    {
      encounter_number: 11,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Transitions!" the Irrelevant Lord roars. "My third favorite form of disorder! Logical relationships misrepresented — nothing brings me more joy. Also, did you know that contrast and cause-and-effect are different things? Of course you do. That is why this will be hard."`,
      passage: `The Descriptivist scholars knew their argument was correct in theory. Their field data showed conclusively that so-called "incorrect" usages were consistently understood by native speakers. [______], this empirical evidence failed to move the Prescriptivists, who argued that the ability to understand an error does not make it acceptable.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Therefore`,
      option_b: `In addition`,
      option_c: `Nevertheless`,
      option_d: `Specifically`,
      correct_answer: 'C',
      explanation: `The paragraph sets up a contrast: the Descriptivists had strong empirical evidence → but this evidence failed to move the Prescriptivists. The transition must signal this concession: despite the evidence, the result was not persuasion. "Nevertheless" is a concession/contrast transition that correctly signals: the evidence was there and should have persuaded, and yet it did not. This is precisely the logical relationship. "Therefore" would imply the evidence's failure to persuade was a logical consequence of the evidence being correct — which is backwards. "In addition" would treat the Prescriptivists' resistance as additional information rather than a contrary outcome. "Specifically" would imply the resistance is a specification of something already said, which makes no sense here.`,
      success_narrative: `"Nevertheless" reveals the gap between evidence and persuasion. The Irrelevant Lord drums his fingers. "You understood the concession. Annoying. Also, concession transitions are my least favorite."`,
      failure_narrative: `The Irrelevant Lord is pleased with "Therefore." The Prescriptivists' resistance is now a logical consequence of the evidence — which implies evidence causes people to resist evidence.`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 12,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"The underlined transition in this passage is wrong," the Irrelevant Lord announces. "Or is it? Mwahaha. Also, I lied — it is wrong. But only subtly. You must read the entire paragraph to see why."`,
      passage: `Warden Callus began his educational reform by eliminating multiple-choice grammar tests. He replaced them with open-ended questions that required students to explain why a sentence was correct or incorrect. Student performance initially dropped — the new format was harder. [However], students who completed two semesters under the new system showed dramatically higher scores on complex writing assessments than their predecessors had.`,
      question_stem: `The underlined transition "However" should be replaced with:`,
      option_a: `LEAVE IT AS IS`,
      option_b: `Furthermore`,
      option_c: `For instance`,
      option_d: `Ultimately`,
      correct_answer: 'A',
      explanation: `The paragraph describes: reform implemented → performance dropped initially → but two semesters in, higher scores. "However" signals a contrast/reversal: after the initial drop, the scores eventually improved. This is a classic "however" structure: immediate negative outcome → however, longer-term positive outcome. The contrast is between short-term performance drop and long-term performance gain. "However" is correct here — it signals the reversal. Option A, leaving it as is, is correct. Option B, "Furthermore," would add the long-term gains as additional information rather than as a reversal, making the initial drop and the long-term gains sound compatible and additive rather than contrasting. Option C, "For instance," would make the long-term gains an example of the initial drop, which is incoherent. Option D, "Ultimately," adds a temporal marker but loses the contrast signal — "ultimately" says when, while "however" says in contrast to what came before.`,
      success_narrative: `"However" is correct — it signals the reversal from short-term drop to long-term gain. The Irrelevant Lord stomps. "You saw through my 'or is it wrong?' trick! Infuriating."`,
      failure_narrative: `The Irrelevant Lord celebrates your changed answer. "You changed it to 'Furthermore'! Now the long-term gains are just additional information, with no signal of the reversal. Beautiful disorder."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 13,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"A complex transition question!" the Lord roars. "This one requires understanding the entire argumentative arc of the paragraph — not just a pair of sentences. Also, the entire paragraph is about something important. And I have lost the thread of my own sentence. Irrelevant! Answer the question."`,
      passage: `The Grammar Council's official history presents the founding of Grammar Keep as a triumph of scholarly cooperation. This account has never been seriously challenged — not because it is accurate, but because challenging it requires access to primary documents that the Council controls. The primary documents, when accessed by independent researchers, tell a different story: negotiations were bitter, the founding charter went through forty-seven drafts, and two of the three clan leaders signed only under significant political pressure. [______], the official history is not a neutral record but an institutionally maintained myth.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Moreover`,
      option_b: `In short`,
      option_c: `Nevertheless`,
      option_d: `For instance`,
      correct_answer: 'B',
      explanation: `The paragraph has been building an argument: the official history is unchallenged not because it is true, but because challenging it requires access the Council controls. When independent researchers do access primary documents, they find bitter negotiations, forty-seven drafts, and coerced signatures. The final sentence draws the conclusion from all of this: the official history is an institutionally maintained myth. The transition must signal that this final sentence is the synthesis and conclusion of everything that preceded it. "In short" is a summary/conclusion transition that correctly signals: all of the above evidence points to this conclusion. Option A, "Moreover," would add the conclusion as additional information rather than as a synthesis. Option C, "Nevertheless," would imply the conclusion contradicts something just said — but it follows from it. Option D, "For instance," would make the myth conclusion an example of something, which inverts the relationship (it is the conclusion, not an example).`,
      success_narrative: `"In short" synthesizes the investigative evidence into a decisive conclusion. The Irrelevant Lord is visibly rattled. "You are surprisingly good at transitions. Also, the east wall is still limestone. Still irrelevant."`,
      failure_narrative: `The Irrelevant Lord cheers at "Moreover." The conclusion about institutional mythology is now just another item of information rather than the synthesis the entire paragraph was building toward.`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 14,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"This transition question has a trap," the Lord says, almost admiringly. "One of the answer options is tempting because it is not wrong — just less precise than the correct answer. Also, I respect precision. Not enough to practice it. But enough to respect it in others. Proceed."`,
      passage: `Warden Holt's compromise ruling on the serial comma was initially dismissed by both sides. [______], by the end of the Fifth Age, the compromise had become the operative standard across all but two of the Keep's districts, not because either faction had been persuaded of its philosophical merit, but because it worked in practice.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Nevertheless`,
      option_b: `Yet`,
      option_c: `However`,
      option_d: `Despite this`,
      correct_answer: 'A',
      explanation: `The two sentences present a contrast: initial dismissal by both sides → eventual broad adoption despite no philosophical persuasion. The transition needs to signal this contrast/concession. Options B ("Yet"), C ("However"), and A ("Nevertheless") all signal contrast, so the question becomes which is most precise for this specific context. "Nevertheless" is strongest for this context because the passage is making a strong argumentative point: despite being dismissed, the compromise prevailed through pragmatic adoption. "Nevertheless" carries more argumentative weight and formality than "Yet" (which is more casual) or "However" (which is neutral contrast). The academic register of the passage calls for "Nevertheless." Additionally, "Nevertheless" more emphatically signals that the outcome is surprising or strong in spite of the initial dismissal — which is the key claim of the sentence. Option D, "Despite this," is also a contrast marker but is less formal and creates an awkward sentence structure ("Despite this, by the end...").`,
      success_narrative: `"Nevertheless" carries exactly the right argumentative weight for this concession. The Irrelevant Lord nods begrudgingly. "Precise. I hate precise."`,
      failure_narrative: `The Irrelevant Lord is pleased with "Yet" or "However." "Technically not wrong! But less precise. I will accept the imprecision."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 15,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"The fifteenth question!" the Irrelevant Lord shouts. "Only five remain after this. You are making me work harder than I have in decades. Also, I have not worked hard in decades. Also that is irrelevant. The transition question is about an unnecessary transition. The hardest kind."`,
      passage: `The founding charter of Grammar Keep was ratified unanimously. [Moreover], all three clan leaders signed it in the same ceremony on the same day.`,
      question_stem: `Which version of the underlined transition is BEST?`,
      option_a: `Moreover`,
      option_b: `Indeed`,
      option_c: `Consequently`,
      option_d: `OMIT the transition (begin: "All three clan leaders...")`,
      correct_answer: 'D',
      explanation: `The first sentence says the charter was ratified unanimously. The second sentence says all three leaders signed in the same ceremony on the same day. The second sentence is not adding additional information beyond what "unanimous" already implies — it is elaborating on what "unanimous" means in practice. Because the second sentence simply specifies how the unanimous ratification occurred (same ceremony, same day), it flows naturally from the first without needing a transition word. "Moreover" implies a significant additional claim is being added. "Indeed" would signal emphasis or confirmation. "Consequently" would imply cause and effect. All of these transitions would over-signal a relationship that flows naturally. The sentences are better without a transition because the second sentence is simply completing the picture painted by the first, and no logical relationship needs to be marked. Option D is correct.`,
      success_narrative: `The sentences flow naturally without a transition. The Irrelevant Lord is appalled. "You chose OMIT! But transitions are so satisfying to add unnecessarily! This is a personal insult."`,
      failure_narrative: `The Irrelevant Lord loves "Moreover." An unnecessary addition transition now makes "all three leaders signed together" sound like a major separate claim rather than simply a description of what unanimous ratification looked like.`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    // ===== WORD CHOICE / TONE QUESTIONS (E16-18) =====
    {
      encounter_number: 16,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Word choice!" the Irrelevant Lord snarls. "Three of these. I find word choice questions personally offensive. Every word should mean approximately whatever the reader wants it to mean. Also, imprecision is my third favorite thing, after irrelevance and disorder. Now. Choose your word carefully."`,
      passage: `The Grammar Council's handling of the Comma Plague was widely praised in official accounts. Independent scholars, however, have [______] that the Council's slow initial response allowed the Plague to spread to districts that might have been protected by earlier intervention.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in the blank?`,
      option_a: `mentioned`,
      option_b: `argued`,
      option_c: `demonstrated`,
      option_d: `suggested`,
      correct_answer: 'C',
      explanation: `The sentence describes independent scholars presenting a critical counter-narrative to the official account. The word in the blank must characterize the epistemic strength of their claim: that the slow response allowed the Plague to spread to otherwise-protectable districts. The key is that the sentence says "might have been protected" — the scholars are making a conditional, evidential claim, not just an opinion. Option C, "demonstrated," implies the scholars provided evidence sufficient to show this — which fits a scholarly counter-argument based on evidence. Option A, "mentioned," is far too weak — it implies the scholars noted this in passing without argument. Option B, "argued," is plausible but "argued" implies making a case based on reasoning, while "demonstrated" implies presenting evidence that establishes the claim. Option D, "suggested," implies a tentative or speculative claim, which understates the force of an independent scholarly finding.`,
      success_narrative: `"Demonstrated" gives the independent scholars' finding the evidential weight it carries. The Irrelevant Lord scowls. "Precision. In my throne room. Disgusting."`,
      failure_narrative: `The Irrelevant Lord is delighted with "mentioned." The independent scholars' critical finding is now just a casual aside they brought up in conversation.`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 17,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Tone question!" the Irrelevant Lord announces. "My least favorite, because tone is something I have never possessed. Also, I once attempted a solemn tone in a speech and accidentally made everyone laugh. Irrelevant! This passage is from the Keep's founding philosophical treatise. One sentence breaks the register."`,
      passage: `The founding scholars understood that institutions, like arguments, must be built from the ground up. Every structural element must be justified by the principles it embodies, not by tradition or convenience. An institution that cannot explain why it does what it does is not an institution — it is a habit. You really have to hand it to them for figuring all this out. The founding charter was, in this sense, not merely a legal document but a philosophical proof: evidence that an institution built on explicit principles could exist.`,
      question_stem: `The passage is written in a formal philosophical tone. Which sentence is most inconsistent with this tone?`,
      option_a: `Every structural element must be justified by the principles it embodies, not by tradition or convenience.`,
      option_b: `An institution that cannot explain why it does what it does is not an institution — it is a habit.`,
      option_c: `You really have to hand it to them for figuring all this out.`,
      option_d: `The founding charter was, in this sense, not merely a legal document but a philosophical proof.`,
      correct_answer: 'C',
      explanation: `Sentences A, B, and D are all consistently in formal philosophical register — abstract claims, complex structures, measured analytical language. Sentence C — "You really have to hand it to them for figuring all this out" — is a colloquial, conversational aside that belongs in informal discourse, not formal philosophical prose. "You really have to hand it to them" is an idiomatic expression of informal admiration; "figuring all this out" is colloquially vague. The sentence shatters the formal register that the surrounding sentences maintain with complete consistency.`,
      success_narrative: `The treatise's formal register is restored. The Irrelevant Lord reviews the offending sentence. "That was one of my best insertions. 'Hand it to them.' Devastating to formal prose."`,
      failure_narrative: `The Irrelevant Lord is pleased. "You chose the wrong sentence! The colloquial interjection stays. The founding philosophical treatise now contains the phrase 'hand it to them.'"`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 18,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"The final word choice question," the Irrelevant Lord says, and his voice drops to something that might almost be called respect. "This one is the hardest. The difference between the correct answer and the wrong answer is a single degree of precision. I genuinely do not expect you to get this right."`,
      passage: `The Descriptivist movement's lasting contribution was not a new set of grammar rules but a new way of asking questions about language. Instead of asking "Is this correct?" the Descriptivists taught scholars to ask "Does this communicate effectively, and why?" This shift in questioning was [______] — it did not eliminate standards but relocated them from authority to evidence.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in the blank?`,
      option_a: `significant`,
      option_b: `transformative`,
      option_c: `important`,
      option_d: `radical`,
      correct_answer: 'B',
      explanation: `The sentence describes what the shift in questioning was — a shift from authority-based to evidence-based standards. The word must precisely characterize the nature of this shift. The passage specifies: it "did not eliminate standards but relocated them." This is not just a large change (significant, important) or an extreme change (radical); it is a change that fundamentally transformed how the enterprise worked — a change in the underlying framework. Option B, "transformative," precisely captures this: a transformative change is one that changes the nature or structure of something, not just its degree. Option A, "significant," means notable or large in scale but does not describe the fundamental restructuring. Option C, "important," is even vaguer. Option D, "radical," means extreme or going to the root — and while the shift was foundational, "radical" typically implies more aggressive or disruptive change than a careful "relocation" of standards implies; "transformative" is more precise for a change that fundamentally restructured an existing practice rather than overthrowing it.`,
      success_narrative: `"Transformative" captures the structural nature of the Descriptivists' contribution precisely. The Irrelevant Lord stares. Then, quietly: "I genuinely did not expect that. Well done, Scholar."`,
      failure_narrative: `The Irrelevant Lord is relieved. "You chose 'significant.' Accurate, but imprecise. The structural nature of the shift — its relocation rather than elimination of standards — is not captured. I accept this small victory."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    // ===== MEGA-COMBO (E19-20) =====
    {
      encounter_number: 19,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `"Two questions remain," the Irrelevant Lord says. The scroll-pile throne seems to deflate slightly. "These final two are drawn from a single passage. Read it carefully. It contains a relevance problem AND an organizational problem, and they are related. Also, I inserted both of them. I am rather proud." He presents a long passage.`,
      passage: `[1] The most consequential moment in Grammar Keep's intellectual history was not the founding but the First Schism, when the Prescriptivists and Descriptivists formally separated into distinct scholarly factions. [2] The Schism produced the keep's most vibrant period of scholarship — each faction, sharpened against the other, produced arguments of unprecedented rigor. [3] It also produced decades of institutional dysfunction, as the two factions competed for resources, positions, and the ear of the Grammar Council. [4] The First Schism occurred in the year 412 of the Keep's calendar. [5] What is remarkable about this period is that the institutional dysfunction and the intellectual vibrancy were not separate phenomena — the dysfunction was the engine of the vibrancy. [6] Without the competition, the friction, and the urgency of having a credible opponent, neither faction might have developed the sophistication of argument that the Keep's Fifth Age is remembered for.`,
      question_stem: `The writer is considering deleting sentence [4] from the paragraph. Should sentence [4] be deleted? (Question 1 of 2)`,
      option_a: `Yes, because the specific year of the Schism is not relevant to the paragraph's argument about the Schism's intellectual and institutional consequences.`,
      option_b: `Yes, because the year 412 is inconsistent with the paragraph's other historical references.`,
      option_c: `No, because knowing when the Schism occurred helps the reader understand how long it influenced the Keep's scholarship.`,
      option_d: `No, because it provides a necessary transition between the institutional consequences [3] and the synthesizing observation [5].`,
      correct_answer: 'A',
      explanation: `The paragraph makes a sophisticated argument about the relationship between institutional dysfunction and intellectual vibrancy. It does not depend on when the Schism occurred — only on what it produced and why. Sentence [4] provides the year (412) — a specific calendar fact that adds no argumentative force. Option A correctly identifies this: the year is not relevant to the consequences-and-synthesis argument the paragraph makes. Option B invents a factual inconsistency that is not present. Option C argues that knowing the year tells us about duration, but the paragraph never makes a claim about how long the influence lasted — it is about what the influence was. Option D claims [4] transitions between [3] and [5], but [3] and [5] connect naturally: institutional dysfunction → what is remarkable is that dysfunction and vibrancy were the same phenomenon. No year is needed as a bridge.`,
      success_narrative: `The paragraph's argument flows cleanly without the date. The Irrelevant Lord watches the year dissolve from the passage. "One more," he says quietly.`,
      failure_narrative: `The Irrelevant Lord is briefly delighted. "The year stays! For no reason! Also, the question continues."`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 20,
      type: 'boss',
      difficulty: 3,
      enemy_name: 'The Irrelevant Lord',
      enemy_type: 'Rhetoric Warden',
      pre_narrative: `The Irrelevant Lord rises from his scroll-pile throne for the final time. "Twenty," he says. "The last question uses the same passage. An organization problem I planted carefully. If you solve it, you defeat me. If you fail—" He straightens slightly. "Then the Rhetoric Ruins remain mine. Choose carefully, Scholar."`,
      passage: `[1] The most consequential moment in Grammar Keep's intellectual history was not the founding but the First Schism, when the Prescriptivists and Descriptivists formally separated into distinct scholarly factions. [2] The Schism produced the keep's most vibrant period of scholarship — each faction, sharpened against the other, produced arguments of unprecedented rigor. [3] It also produced decades of institutional dysfunction, as the two factions competed for resources, positions, and the ear of the Grammar Council. [5] What is remarkable about this period is that the institutional dysfunction and the intellectual vibrancy were not separate phenomena — the dysfunction was the engine of the vibrancy. [6] Without the competition, the friction, and the urgency of having a credible opponent, neither faction might have developed the sophistication of argument that the Keep's Fifth Age is remembered for.`,
      question_stem: `(The year sentence [4] has been removed.) To improve the organization of this paragraph, sentence [5] should be placed:`,
      option_a: `before sentence [1].`,
      option_b: `after sentence [1].`,
      option_c: `after sentence [6].`,
      option_d: `where it currently is (no change).`,
      correct_answer: 'D',
      explanation: `With sentence [4] removed, the paragraph's sequence is: [1] the Schism was the most consequential moment → [2] it produced vibrancy → [3] it also produced dysfunction → [5] what is remarkable is that these were not separate — dysfunction was the engine of vibrancy → [6] without competition, neither faction would have reached such sophistication. This is the correct argumentative order: establish the two outcomes ([2][3]) → synthesize them ([5]) → explain the causal mechanism ([6]). Sentence [5] is already exactly where it belongs — it synthesizes the contrast between vibrancy and dysfunction that [2] and [3] established, and it sets up the explanation in [6]. Moving [5] anywhere else would destroy this arc. Option D, leaving it in place, is correct. Option A would place the synthesis before the examples it synthesizes. Options B and C would place it either too early or too late in the argumentative sequence.`,
      success_narrative: `The passage stands in perfect order: claim, examples, synthesis, explanation. The Irrelevant Lord pauses. The scroll-pile throne shivers. And then, slowly, impossibly, the Irrelevant Lord bows. "The Rhetoric Ruins are yours, Scholar. You have answered twenty questions without missing a single relevant point. I am — though it pains me to say it — genuinely impressed." He dissolves into a cloud of perfectly organized, completely purposeful dust. The ancient inscriptions blaze with golden light.`,
      failure_narrative: `The Irrelevant Lord straightens. "You moved the synthesis before its examples. The paragraph now argues before it has shown what it is arguing about. The Ruins remain mine." He settles back onto his throne of disorganized scrolls.`,
      xp_reward: 150,
      rune_reward: 10,
      concept_tag: 'organization',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
  ]
};

module.exports = chapter19;
