// CHAPTER 18: Author's Craft and Tone (20 encounters)
const chapter18 = {
  chapter_number: 18,
  encounters: [
    {
      encounter_number: 1,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Tone Twister',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `You enter the inner sanctum of the Rhetoric Ruins, where the stonework is finer and the torches burn in colors you have never seen. Here the Rhetoric Revenants dwell — ghosts that corrupt not just what is said but how it is said. The Tone Twister has replaced a precise word in a description of Warden Sollis with a vague one. You must restore the precision.`,
      passage: `Warden Sollis reviewed every official Keep document with [remarkable] attention, catching errors that her colleagues had missed for years.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined word "remarkable"?`,
      option_a: `impressive`,
      option_b: `meticulous`,
      option_c: `unusual`,
      option_d: `serious`,
      correct_answer: 'B',
      explanation: `The sentence describes Sollis catching errors her colleagues had missed — this is a description of systematic, detail-oriented carefulness. The word needed is specific to the type of attention: focused, careful, exact attention to detail. Option B, "meticulous," means extremely careful about small details, which precisely captures both the nature of the attention and explains why it caught errors others missed. Option A, "impressive," is evaluative (it tells us we should be impressed) but does not describe what kind of attention she paid. Option C, "unusual," describes frequency or typicality rather than quality of attention. Option D, "serious," suggests gravity or earnestness but not the detail-oriented precision that produces error-catching; a person can be serious without being meticulous.`,
      success_narrative: `The stone inscription sharpens as "meticulous" settles into place. The Tone Twister shudders — it cannot twist the tone of a word chosen this precisely.`,
      failure_narrative: `The Tone Twister is satisfied with your vague answer. "Impressive" attention tells the reader nothing about how Sollis actually worked.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 2,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Connotation Crook',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Connotation Crook has swapped a carefully chosen word in a passage about the Comma Plague with a word that seems similar but carries the wrong connotation. The passage now sounds subtly wrong. You must restore the precise word.`,
      passage: `The Comma Plague did not simply confuse readers — it [changed] the Keep's legal and administrative systems, making contracts unenforceable and decrees unreadable.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined word "changed"?`,
      option_a: `altered`,
      option_b: `modified`,
      option_c: `disrupted`,
      option_d: `transformed`,
      correct_answer: 'C',
      explanation: `The sentence describes the Comma Plague making contracts unenforceable and decrees unreadable — these are harmful breakdowns of functioning systems. The word needed must convey harmful interference with normal functioning. Option C, "disrupted," means to interrupt or destabilize normal operations — precisely what making contracts unenforceable does to a legal system. Option A, "altered," is neutral — it means changed in some direction, but does not convey the harmful, destabilizing quality. Option B, "modified," is even more neutral and suggests intentional, controlled adjustment rather than harmful breakdown. Option D, "transformed," implies a fundamental change in nature that produced a new form — but the plague did not fundamentally transform these systems into something new; it simply broke them.`,
      success_narrative: `"Disrupted" settles into the inscription with destructive precision. The Connotation Crook cannot steal the precise negative connotation this word carries.`,
      failure_narrative: `The Connotation Crook is pleased with "altered." The Comma Plague now merely changed the legal system in some unspecified way, rather than breaking it.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 3,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Word Choice Wraith',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Word Choice Wraith haunts a passage from the Keep's founding chronicle, replacing vivid, specific verbs with flat, general ones. A sentence that once had life is now inert. You must restore the verb that best fits the passage's tone.`,
      passage: `In the final hours before the founding charter's ratification, the three Scholar-clan leaders [met] in the Keep's central hall to settle their last remaining disagreements.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined word "met"?`,
      option_a: `gathered`,
      option_b: `convened`,
      option_c: `assembled`,
      option_d: `congregated`,
      correct_answer: 'B',
      explanation: `The passage describes the final, formal meeting of three clan leaders immediately before ratifying a founding document — this is a high-stakes, institutional, formal gathering for a specific official purpose. The verb must convey official, purposeful assembly. Option B, "convened," means to come together for a formal, official purpose — it is specifically used for formal, institutional meetings and carries the appropriate gravity for a ratification session. Option A, "gathered," is informal and suggests casual or informal assembly rather than a formal proceeding. Option C, "assembled," is more formal than "gathered" but is often used for large groups coming together rather than three specific leaders meeting for a deliberate official purpose. Option D, "congregated," typically implies a crowd or large group coming together and carries religious/communal connotations that are too casual for this specific formal meeting.`,
      success_narrative: `"Convened" restores the formal gravity to the founding moment. The Word Choice Wraith dissolves — it cannot haunt a passage where every word earns its place.`,
      failure_narrative: `The Word Choice Wraith is pleased. "Gathered" makes the ratification of a founding charter sound like a casual meetup in the hallway.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 4,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Craft Crusher',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Craft Crusher does not destroy passages — it flattens them. It replaces passages written with a consistent formal, academic tone with options that introduce sudden, jarring informality. The Keep's philosophical treatise has been targeted. You must identify which version maintains the passage's tone.`,
      passage: `The First Scholars of Grammar Keep argued that language was not merely a tool for communication — it was the medium through which thought itself achieved clarity. Without precise language, they believed, even the most brilliant mind remained trapped in a fog of inarticulate intuition.`,
      question_stem: `The writer wants to add a sentence to this paragraph that is consistent with its formal, philosophical tone. Which of the following options is most consistent with the tone of the passage?`,
      option_a: `Basically, if you can't write clearly, you probably aren't thinking clearly either.`,
      option_b: `This idea was pretty revolutionary for its time and really shook things up in the scholarly community.`,
      option_c: `Language, in this view, was the instrument by which human intellect became legible to itself.`,
      option_d: `The scholars felt strongly that words were super important for thinking good thoughts.`,
      correct_answer: 'C',
      explanation: `The passage is written in formal, academic philosophical prose — complex sentence structures, abstract concepts (clarity, inarticulate intuition), and elevated vocabulary. A new sentence must match this register. Option C maintains the exact tone: it uses abstract philosophical language ("instrument," "legible to itself"), complex sentence construction, and continues the meditation on language and intellect without any conversational intrusion. Option A is blatantly informal ("basically," "probably aren't thinking clearly either") — it shatters the passage's philosophical register. Option B uses colloquialisms ("pretty revolutionary," "shook things up") that are entirely incompatible with formal academic prose. Option D is absurdly informal ("super important," "thinking good thoughts") and grammatically incorrect.`,
      success_narrative: `The philosophical passage maintains its elevated register throughout. The Craft Crusher cannot flatten prose that knows exactly what tone it should be in.`,
      failure_narrative: `The Craft Crusher is thrilled. The passage now contains "basically" and "super important" alongside "inarticulate intuition." The tonal whiplash is violent.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 5,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Register Rogue',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Register Rogue has inserted a tonal intruder into a carefully crafted passage from the traveler's account of Grammar Keep. One sentence breaks the register — the intimate, observational first-person voice of a thoughtful traveler. You must identify it.`,
      passage: `The walls of Grammar Keep rose before me like a geological formation — ancient, inevitable, and entirely indifferent to my presence. I had traveled eight days to reach this place, and I felt, as I approached, that the Keep had not been waiting for me at all. It simply was, as it had been for centuries before my birth and would be for centuries after. The inscription above the gate is considered one of the most important documents in the Keep's history by leading scholars across three disciplines.`,
      question_stem: `The passage is written in a consistent intimate, first-person observational tone. Which sentence is most inconsistent with this tone?`,
      option_a: `The walls of Grammar Keep rose before me like a geological formation — ancient, inevitable, and entirely indifferent to my presence.`,
      option_b: `I had traveled eight days to reach this place, and I felt, as I approached, that the Keep had not been waiting for me at all.`,
      option_c: `It simply was, as it had been for centuries before my birth and would be for centuries after.`,
      option_d: `The inscription above the gate is considered one of the most important documents in the Keep's history by leading scholars across three disciplines.`,
      correct_answer: 'D',
      explanation: `The first three sentences share a consistent register: intimate, first-person, reflective, lyrical — a traveler meditating on her smallness before an ancient institution. The fourth sentence shifts to third-person academic register: "is considered one of the most important documents in the Keep's history by leading scholars across three disciplines." This is encyclopedia or critical assessment language, not traveler observation. Option D is the intruder: it sounds like a footnote or scholarly citation, completely at odds with the personal, philosophical tone of the previous three sentences. Options A, B, and C are all in the same voice — first-person, observational, meditative — and all maintain the intimate register consistently.`,
      success_narrative: `The traveler's voice flows unbroken — intimate, meditative, perfectly consistent. The Register Rogue cannot smuggle academic prose into a lyrical first-person account.`,
      failure_narrative: `The Register Rogue keeps its academic sentence in place. A passage about the feeling of approaching the Keep now contains a footnote about scholarly consensus.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 6,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Vague Villain',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Vague Villain attacks passages by replacing specific, precise language with vague, general substitutes. It has struck a historical account of the Comma Plague's most destructive phase. The underlined phrase needs to be replaced with something precise enough to convey the actual danger.`,
      passage: `At the height of the Comma Plague, the Keep's district administrators found themselves in [a very bad situation], as contaminated decrees had rendered dozens of property transfers legally ambiguous.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined phrase "a very bad situation"?`,
      option_a: `a challenging predicament`,
      option_b: `a serious administrative crisis`,
      option_c: `an acute legal and administrative paralysis`,
      option_d: `a problematic state of affairs`,
      correct_answer: 'C',
      explanation: `The sentence describes a specific problem: contaminated decrees making property transfers legally ambiguous. The phrase replacing "a very bad situation" must precisely characterize this specific problem. Option C, "an acute legal and administrative paralysis," does this precisely: it identifies the type of crisis (legal and administrative), the severity (acute, meaning sharp and severe), and the nature (paralysis, meaning inability to function). This directly matches the described situation: the decrees were legally ambiguous, which means the administrative system could not process property transfers — paralysis. Option A, "a challenging predicament," is slightly more precise than the original but still vague. Option B, "a serious administrative crisis," captures the administrative dimension but misses the specifically legal nature of the problem (property transfers). Option D, "a problematic state of affairs," is essentially no better than the original vague phrase.`,
      success_narrative: `The inscription now precisely names the nature of the Plague's worst phase. The Vague Villain shrieks — it cannot survive in the presence of precise language.`,
      failure_narrative: `The Vague Villain is satisfied with "a serious administrative crisis." The specifically legal dimension of the problem is lost.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 7,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Precision Phantom',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Precision Phantom haunts passages about the Keep's scholarly debates, replacing words that carry precise philosophical connotations with near-synonyms that are just slightly wrong. This ghost knows that the difference between words often lives in nuance.`,
      passage: `The Prescriptivists did not merely disagree with the Descriptivists — they considered the Descriptivist position a [threat] to the entire purpose of the Keep.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined word "threat"?`,
      option_a: `risk`,
      option_b: `challenge`,
      option_c: `danger`,
      option_d: `repudiation`,
      correct_answer: 'D',
      explanation: `The sentence describes how the Prescriptivists viewed the Descriptivist position in relation to the Keep's entire purpose. The word needed must convey the specific nature of the Descriptivist threat: they were not merely endangering the Keep — they were fundamentally rejecting its core mission. Option D, "repudiation," means an outright rejection or denial — the Descriptivists' claim that grammar rules are conventions (not truths) would be seen by Prescriptivists as repudiating the very foundation on which the Keep justified its existence. Option A, "risk," is too mild and implies potential future harm rather than a philosophical rejection happening now. Option B, "challenge," implies opposition but not the fundamental denial implied by the Prescriptivists' view — a challenge can be overcome; a repudiation attacks the very legitimacy of the enterprise. Option C, "danger," is stronger than "risk" but still implies physical or institutional harm rather than philosophical rejection.`,
      success_narrative: `"Repudiation" gives the Prescriptivists' alarm its true philosophical weight. The Precision Phantom dissolves in the precision of a word chosen this carefully.`,
      failure_narrative: `The Precision Phantom keeps "challenge." The Prescriptivists now merely disagree with the Descriptivists rather than viewing them as fundamentally rejecting everything the Keep stands for.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 8,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Tone Thief',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Tone Thief has challenged you with a passage written in the tone of a formal historical chronicle. One of the four options it presents introduces a tonal break — a word that would shift the register from chronicle to something else. You must identify which option maintains the tone.`,
      passage: `The Third Reform of the Grammar Council was not proposed lightly. Senior members had debated its necessity for a decade before reaching consensus. When the proposal was finally submitted, it passed by the narrowest possible margin, [reflecting/showing] the deep reservations that remained even among its supporters.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in the underlined blank, while maintaining the formal historical tone of the passage?`,
      option_a: `demonstrating`,
      option_b: `showing`,
      option_c: `betraying`,
      option_d: `making obvious`,
      correct_answer: 'C',
      explanation: `The passage describes a narrow vote despite a decade of debate, and says the vote reflected "deep reservations" among even the supporters. The word in the blank describes how the narrow vote revealed those reservations. Option C, "betraying," is the most precise choice: "betraying" in this context means revealing something that was not intended to be shown — the narrow margin involuntarily revealed the depth of the lingering doubts. This is exactly the right nuance: even supporters who voted yes were betraying their reservations through the narrowness of the margin. Option A, "demonstrating," is accurate but more neutral — it implies intentional showing. Option B, "showing," is even more neutral and less precise. Option D, "making obvious," is too informal for a formal historical chronicle and implies the reservations were blatantly apparent, when the passage is making a more subtle point about what the narrow margin reveals.`,
      success_narrative: `"Betraying" adds precise nuance to the historical account — the vote revealed what even the supporters were trying not to show. The Tone Thief cannot steal precision this carefully chosen.`,
      failure_narrative: `The Tone Thief installs "showing." The subtle involuntary revelation of lingering doubt is replaced with neutral, uninformative language.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 9,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Style Sorcerer',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Style Sorcerer has presented a passage about the Keep's debate culture with a blank where a specific detail should appear. The writer wants to create a sense of intellectual intensity. Only one option achieves this through specific, concrete detail rather than vague assertion.`,
      passage: `Debate preparation in the Keep's Fifth Age was not a casual affair. Scholars spent weeks researching their opponents' published positions, constructing counter-arguments, and anticipating objections. In the hours before a major debate, [the atmosphere in the preparation rooms ______].`,
      question_stem: `The writer wants to add a specific detail that creates a vivid sense of intellectual intensity. Which option best accomplishes this?`,
      option_a: `was very tense and focused`,
      option_b: `was filled with scholars quietly muttering arguments to themselves, ink-stained and hollow-eyed from days of preparation`,
      option_c: `showed how seriously the scholars took their work`,
      option_d: `indicated that everyone was prepared and ready`,
      correct_answer: 'B',
      explanation: `The question asks for a specific detail that creates a vivid sense of intellectual intensity. Option B does this through concrete sensory detail: scholars "quietly muttering arguments to themselves" (action), "ink-stained" (physical evidence of long writing sessions), and "hollow-eyed from days of preparation" (physical consequence of exhaustion). Each detail is specific and visual, and together they create a vivid scene that makes the reader feel the intensity rather than merely being told about it. Option A says the atmosphere "was very tense and focused" — this is assertion, not detail. Option C tells the reader how to interpret the atmosphere ("showed how seriously they took their work") rather than showing it. Option D is the flattest option — "prepared and ready" adds nothing vivid.`,
      success_narrative: `The preparation room comes to life with ink-stained scholars muttering arguments. The Style Sorcerer's vague spell is broken by the power of specific detail.`,
      failure_narrative: `The Style Sorcerer keeps "very tense and focused." The reader is told about intensity but shown nothing — the scene remains flat and lifeless.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 10,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Register Robber',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Register Robber has inserted a phrase into a formal academic passage about the founding of Grammar Keep that breaks the register. The passage is from a philosophical treatise — formal, analytical, third-person. One phrase does not belong.`,
      passage: `The founding scholars understood that an institution dedicated to language would inevitably become a site of political struggle. Every decision about what counted as "correct" language was, at bottom, a decision about whose language would be treated as the standard — and this was not, when you think about it, a neutral choice. The Keep's charter explicitly acknowledged this by requiring that all grammar standards be reviewed by representatives of every district.`,
      question_stem: `The passage is written in a formal, academic tone. Which phrase is most inconsistent with this tone?`,
      option_a: `"inevitably become a site of political struggle"`,
      option_b: `"at bottom, a decision about whose language would be treated as the standard"`,
      option_c: `"when you think about it, a neutral choice"`,
      option_d: `"explicitly acknowledged this by requiring that all grammar standards be reviewed"`,
      correct_answer: 'C',
      explanation: `The passage is formal academic writing throughout, examining the political dimensions of language standardization. Option C — "when you think about it" — is a conversational, colloquial interjection that would be appropriate in an informal essay or speech but is inappropriate in formal academic prose. "When you think about it" invites the reader into a casual, interactive stance that breaks the passage's formal third-person analytical register. Options A, B, and D all maintain the formal register: "inevitably become a site of political struggle" is formal sociopolitical analysis; "at bottom, a decision about whose language" uses "at bottom" (meaning "fundamentally") as a formal analytical qualifier; "explicitly acknowledged this by requiring" is clear formal academic language.`,
      success_narrative: `The treatise maintains its formal register throughout. The Register Robber cannot steal academic authority from a passage that knows its own tone.`,
      failure_narrative: `The Register Robber is pleased. A formal philosophical treatise now casually asks the reader to "think about it" — undermining its own authority.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 11,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Nuance Nemesis',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Nuance Nemesis destroys nuance by replacing words that carry precise, layered meaning with words that are technically similar but flattened. It has struck a description of Scholar-Medic Falc's battlefield work.`,
      passage: `In the chaos of the Ink War, Scholar-Medic Falc moved through the battlefield with [calm] efficiency, tending wounds with one hand and correcting manuscripts with the other.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in place of the underlined word "calm"?`,
      option_a: `quiet`,
      option_b: `unhurried`,
      option_c: `unruffled`,
      option_d: `peaceful`,
      correct_answer: 'C',
      explanation: `The sentence describes Falc working in "chaos" — she is in the middle of a battle, not a peaceful environment. The word modifying "efficiency" must convey that Falc was not disturbed or agitated by the chaos around her — she remained composed despite it. Option C, "unruffled," precisely captures this: it means not agitated or disturbed, and it specifically implies composure maintained in the face of external disorder. This is the right word for chaos-amid-composure. Option A, "quiet," describes noise level rather than emotional or behavioral composure. Option B, "unhurried," means moving slowly or without urgency — but Falc was not unhurried; she was efficient, which implies effective speed. "Unruffled" modifies her composure, not her speed. Option D, "peaceful," contradicts the setting (she is in a battle) and describes the environment rather than her internal state.`,
      success_narrative: `"Unruffled" precisely captures Falc's composure in the face of battlefield chaos. The Nuance Nemesis cannot survive in the presence of a word chosen with this much care.`,
      failure_narrative: `The Nuance Nemesis keeps "unhurried." Falc now appears to be moving slowly through a battlefield, which is both confusing and impractical.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 12,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Diction Demon',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Diction Demon has placed a blank in a passage about the Keep's most controversial architectural decision: building the Grammar Archive before the walls were fully complete. The writer wants to add a detail that creates a sense of urgency. You must choose the option that achieves this.`,
      passage: `The Grammar Council voted to begin construction of the Archive before the outer walls were finished. [______] This decision alarmed the Keep's military advisors, who argued that an unfinished perimeter left the entire institution vulnerable.`,
      question_stem: `The writer wants to add a specific detail in the blank that creates a sense of urgency about the Council's decision. Which option best accomplishes this?`,
      option_a: `The vote was recorded in the Council's official minutes.`,
      option_b: `The motion passed on a Tuesday afternoon.`,
      option_c: `The vote took place while enemy forces had already been spotted less than three days' march from the Keep.`,
      option_d: `Several Council members had strong opinions about the matter.`,
      correct_answer: 'C',
      explanation: `The question asks for a detail that creates a sense of urgency. Option C achieves this by introducing a time-sensitive threat: enemy forces spotted three days away. This detail immediately makes the decision consequential — the Council was building a library while an army approached. The urgency is specific, concrete, and directly relevant to the military advisors' concerns mentioned in the next sentence. Option A is a procedural fact (minutes recording) that adds no urgency. Option B gives a day of the week, which is trivial and creates no urgency whatsoever. Option D is vague and says nothing specific — "strong opinions" is a placeholder, not a detail.`,
      success_narrative: `The decision now carries the weight of an existential threat three days away. The Diction Demon cannot flatten the urgency of a detail this precisely chosen.`,
      failure_narrative: `The Diction Demon is satisfied with the procedural fact about minutes. The Council's risky decision now seems routine and unthreatening.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 13,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Voice Vandal',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Voice Vandal has presented you with four ways to express the same idea about the founding of Grammar Keep. Only one uses figurative language effectively. The others are literal, flat, or use figurative language poorly.`,
      passage: null,
      question_stem: `The writer wants to describe how Grammar Keep's founding charter created a lasting intellectual framework for the institution. Which of the following uses figurative language most effectively to express this idea?`,
      option_a: `The founding charter was very important and influenced the Keep for a long time.`,
      option_b: `The founding charter was like a document that mattered a lot to scholars.`,
      option_c: `The founding charter was the skeleton of Grammar Keep: every institutional muscle, every policy, every reform, had grown around the bones it had laid down.`,
      option_d: `The founding charter was similar to other important founding documents of the era.`,
      correct_answer: 'C',
      explanation: `Effective figurative language creates a vivid, illuminating comparison that reveals something about the subject. Option C uses an extended metaphor — the charter as a skeleton. This metaphor is precise and illuminating: it conveys that the charter provides the structural framework (bones) that everything else (muscles, policies, reforms) grew around. The metaphor helps the reader visualize the charter's role as an invisible structural foundation. Option A is entirely literal and vague ("very important," "long time") with no figurative language. Option B attempts a simile ("was like a document that mattered a lot") but is circular — comparing the charter to a document that matters says nothing figurative or illuminating. Option D makes a comparison to similar documents of the era, which is a literal historical comparison, not figurative language.`,
      success_narrative: `The skeleton metaphor makes the charter's structural role vivid and unforgettable. The Voice Vandal cannot vandalize prose that speaks with this kind of precision and power.`,
      failure_narrative: `The Voice Vandal is pleased with the vague literal description. The founding charter is "very important" — a statement that illuminates nothing.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 14,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Tone Traitor',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Tone Traitor has inserted a sentence into a passage from the Keep's formal commemorative inscription for Scholar-Medic Falc. The passage is solemn and dignified. One sentence betrays the register.`,
      passage: `Scholar-Medic Orin Falc served the Keep with uncommon dedication. She died in service, her manuscripts still bearing the corrections of her final hours. The Keep mourns her absence and honors her example. She will be remembered for her contributions to both healing and writing, which she somehow managed to do simultaneously in pretty crazy circumstances.`,
      question_stem: `The passage is written in a formal, solemn commemorative tone. Which sentence is most inconsistent with this tone?`,
      option_a: `Scholar-Medic Orin Falc served the Keep with uncommon dedication.`,
      option_b: `She died in service, her manuscripts still bearing the corrections of her final hours.`,
      option_c: `The Keep mourns her absence and honors her example.`,
      option_d: `She will be remembered for her contributions to both healing and writing, which she somehow managed to do simultaneously in pretty crazy circumstances.`,
      correct_answer: 'D',
      explanation: `The first three sentences are consistently formal and solemn — appropriate for a commemorative inscription. Sentence D breaks the register with colloquial language: "somehow managed to do simultaneously in pretty crazy circumstances." "Somehow managed" implies surprise or skepticism, "pretty crazy" is casual slang entirely at odds with formal commemoration. The rest of the sentence describes her work accurately, but the colloquial phrasing destroys the dignity of the tribute. Options A, B, and C all maintain the formal, dignified register: "uncommon dedication," "bearing the corrections of her final hours," and "mourns her absence and honors her example" are all formally appropriate.`,
      success_narrative: `The commemorative inscription maintains its solemn dignity throughout. The Tone Traitor cannot betray a passage once its colloquial intrusion has been identified.`,
      failure_narrative: `The Tone Traitor celebrates. A solemn memorial inscription now describes Falc's battlefield work as "pretty crazy circumstances."`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 15,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Clarity Crusher',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The deeper you go, the more sophisticated the attacks become. The Clarity Crusher has placed a blank in a passage about the Prescriptivist-Descriptivist debate where a precise word is needed — and the correct answer requires distinguishing between near-synonyms that differ only in a subtle philosophical dimension.`,
      passage: `The Descriptivists did not celebrate all language use equally. They [______] that some usages were more effective than others at conveying precise meaning — they simply refused to describe this difference in terms of correctness and incorrectness.`,
      question_stem: `Which of the following most precisely expresses the writer's intended meaning in the blank?`,
      option_a: `admitted`,
      option_b: `conceded`,
      option_c: `acknowledged`,
      option_d: `recognized`,
      correct_answer: 'D',
      explanation: `The sentence describes the Descriptivists' intellectual position: they did not deny that some usages were more effective — they simply declined to use the Prescriptivist framework of correctness to describe that difference. The word in the blank must convey how the Descriptivists related to this fact about differential effectiveness. Option D, "recognized," is the most precise: it implies the Descriptivists actively understood and accepted this fact as part of their framework. "Recognized" conveys intellectual comprehension with no defensiveness. Option A, "admitted," implies reluctant concession — as if this fact were something they preferred not to say, which misrepresents the Descriptivist position. Option B, "conceded," also implies reluctant admission of a point to an opponent, which is too adversarial and defensive. Option C, "acknowledged," is close to "recognized" but carries a slightly more formal, external quality — "acknowledged" often implies acknowledging something to others, while "recognized" captures internal intellectual acceptance.`,
      success_narrative: `The Descriptivist position is articulated with philosophical precision. The Clarity Crusher cannot cloud the meaning of a word chosen with this much care.`,
      failure_narrative: `The Clarity Crusher installs "admitted." The Descriptivists now appear to be reluctantly confessing something they preferred to hide.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 16,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Expression Eraser',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Expression Eraser has targeted a passage about the Keep's most controversial reform. The passage is formal and analytical, but the writer wants to add a sentence that creates a sense of formality and institutional gravity. The options are subtle — only careful reading will identify which one succeeds.`,
      passage: `The Third Reform was not simply a policy change — it was a reorientation of the Keep's fundamental purpose. Where the previous system had measured success by scholars' ability to reproduce correct forms, the Third Reform measured success by scholars' ability to explain and apply principles. [______] This shift had consequences that the reformers themselves only partially anticipated.`,
      question_stem: `The writer wants to add a detail in the blank that creates a sense of institutional gravity and formal significance. Which option best accomplishes this?`,
      option_a: `It was a significant change that people talked about for a long time.`,
      option_b: `The reform took effect on the first day of the academic year following its passage.`,
      option_c: `The distinction between these two measurements of success — reproduction versus application — was, the Council noted in its official record, "the most consequential educational revision in two centuries."`,
      option_d: `Everyone in the Keep knew something big was changing, and there was a lot of discussion about it.`,
      correct_answer: 'C',
      explanation: `The question asks for a detail that creates institutional gravity and formal significance. Option C achieves this by quoting the Council's official record — a formal institutional source — which characterizes the reform as "the most consequential educational revision in two centuries." This creates institutional gravity through: (1) the authority of a formal official record, (2) the precision of the quoted language, and (3) the historical scope of the claim (two centuries). Option A is vague and informal ("talked about for a long time"). Option B provides a procedural date — this adds specificity but not gravity; knowing the effective date does not convey the reform's significance. Option D is entirely informal and vague ("something big," "a lot of discussion").`,
      success_narrative: `The official record's quotation gives the passage the institutional weight it needed. The Expression Eraser cannot erase the authority of a formal source quoted with precision.`,
      failure_narrative: `The Expression Eraser keeps the vague statement about people "talking about it." The institutional gravity the writer wanted is entirely absent.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 17,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Metaphor Mangler',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Metaphor Mangler has presented four ways to describe the relationship between grammar and logic in the Keep's educational philosophy. Only one uses figurative language that is both apt and illuminating. The others are either literal, mixed, or use figurative language in ways that confuse rather than clarify.`,
      passage: null,
      question_stem: `The writer wants to describe how grammar and logic relate to each other in the Keep's educational system using figurative language. Which of the following uses figurative language most effectively?`,
      option_a: `Grammar and logic are both important parts of the curriculum, and students who study one tend to do better in the other.`,
      option_b: `Grammar and logic are the two rails of a single track — run them parallel, and the train of thought moves forward; pull them apart, and it derails.`,
      option_c: `Grammar is like a tool that you use, and logic is also a kind of tool, and together they are like using tools at the same time.`,
      option_d: `Grammar and logic complement each other in the way that all related disciplines complement each other in academic settings.`,
      correct_answer: 'B',
      explanation: `Option B uses an extended metaphor — grammar and logic as two rails of a track, with thought as the train — that is precise, visual, and illuminating. The metaphor captures the key relationship: both rails are necessary (remove either and the train fails), they must be parallel (aligned rather than in conflict), and their purpose is to enable forward movement. Each element of the metaphor maps meaningfully onto the philosophical relationship. Option A is entirely literal and describes a correlation without illuminating the relationship's nature. Option C attempts a metaphor ("like a tool") but immediately collapses into repetition ("logic is also a kind of tool") and awkward mixing ("like using tools at the same time") — it clarifies nothing. Option D is a general comparative claim that applies to any related academic disciplines, making the grammar-logic relationship seem ordinary rather than distinctive.`,
      success_narrative: `The two-rails metaphor captures the grammar-logic relationship with precision and clarity. The Metaphor Mangler cannot mangle a metaphor this carefully constructed.`,
      failure_narrative: `The Metaphor Mangler is satisfied with "like tools." Grammar and logic now appear to be tools in the vague way that everything is sort of like a tool.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 18,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Simile Slayer',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Simile Slayer has targeted a passage about Warden Holt's approach to comma reform. The writer wants to use figurative language to describe how Holt approached the problem — but only one option creates a simile that is both accurate to the content and genuinely illuminating.`,
      passage: null,
      question_stem: `The writer wants to add a sentence describing Holt's approach to the Comma Plague using figurative language. Which of the following uses figurative language most effectively?`,
      option_a: `Holt approached the Comma Plague like a doctor diagnosing a patient: he identified the source of the infection before prescribing the remedy.`,
      option_b: `Holt worked on the Comma Plague like a person working very hard on a problem.`,
      option_c: `Holt was like a man who dealt with commas in a way that was effective and methodical.`,
      option_d: `Holt was like a surgeon who performed surgery to fix the issue.`,
      correct_answer: 'A',
      explanation: `Option A uses a precise, illuminating simile: Holt is like a doctor diagnosing before prescribing. This figurative comparison is apt (identifying the template as the source before distributing the guide — diagnosis then remedy) and illuminating (it reframes a grammar problem as a medical one, highlighting the systematic, diagnostic nature of Holt's approach). Each element of the simile maps clearly: source identification = diagnosis, guide distribution = remedy. Option B uses a simile ("like a person working very hard") that is entirely vacuous — comparing someone to "a person" working hard illuminates nothing. Option C begins a simile ("was like a man") but completes it with literal description ("dealt with commas in an effective and methodical way") rather than with a figurative comparison. Option D uses a simile ("like a surgeon") but provides no information about what the surgery involved, making the comparison vague.`,
      success_narrative: `The doctor-patient simile illuminates Holt's diagnostic methodology with precision and clarity. The Simile Slayer cannot slay a simile this purposeful.`,
      failure_narrative: `The Simile Slayer keeps the empty comparison. Holt worked "like a person working very hard" — a simile that illuminates absolutely nothing.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 19,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Craft Crook',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The Craft Crook has placed a blank in a passage describing the experience of reading the founding charter for the first time. The writer wants to add a detail that creates a specific sense of intellectual awe — not general admiration, but the particular feeling of encountering a text that reorganizes how you think.`,
      passage: `Every Scholar who reads the founding charter for the first time describes the same experience: a feeling of [______] — as if the principles had always been obvious, but you had needed the charter to show them to you.`,
      question_stem: `The writer wants to create a specific sense of intellectual awe — the feeling of encountering a thought that seems both new and inevitable. Which option best accomplishes this?`,
      option_a: `great admiration for the founders' wisdom`,
      option_b: `being very impressed by the document's age and historical significance`,
      option_c: `recognition — not of having seen these ideas before, but of having always believed them without knowing it`,
      option_d: `satisfaction that the Keep was founded on such good principles`,
      correct_answer: 'C',
      explanation: `The question asks for a detail that creates the specific feeling of encountering a thought that seems both new and inevitable — the philosophical experience of recognition without prior conscious knowledge. Option C precisely captures this: "recognition — not of having seen these ideas before, but of having always believed them without knowing it." This describes a specific phenomenological experience — the charter does not teach you something entirely new; it articulates what you already somehow knew but could not formulate. This perfectly matches the second half of the sentence ("the principles had always been obvious, but you had needed the charter to show them to you"). Option A is vague ("great admiration") and describes an evaluative reaction rather than a specific experiential quality. Option B focuses on historical significance and age — externally verifiable facts rather than the internal experience being described. Option D expresses satisfaction about principle quality but not the specific recognition experience.`,
      success_narrative: `The description of reading the charter captures the precise phenomenology of intellectual recognition. The Craft Crook drops the passage, unable to steal a description this exactly right.`,
      failure_narrative: `The Craft Crook replaces the precise description with "great admiration." The specific, strange experience of intellectual recognition is replaced with a generic compliment.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 20,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Artistry Annihilator',
      enemy_type: 'Rhetoric Revenant',
      pre_narrative: `The final guardian of Chapter 18 rises with terrible purpose: the Artistry Annihilator, a Rhetoric Revenant that has existed since the first poorly chosen word was carved into stone. It presents a passage where tone, word choice, and figurative language all intersect — and getting one thing wrong means getting everything wrong.`,
      passage: `To read the founding charter of Grammar Keep is to understand that its authors were not simply writing a legal document. They were making a claim about what human beings are — that we are, at our core, language-making creatures, and that our capacity to arrange words with precision is not a skill but a dignity. The charter does not merely found an institution; it [______].`,
      question_stem: `The writer wants to conclude this sentence with figurative language that captures the charter's philosophical ambition — the idea that it claims something about human nature, not just institutional rules. Which option best accomplishes this?`,
      option_a: `lists the rules that scholars should follow`,
      option_b: `provides a useful framework for institutional governance`,
      option_c: `asserts a kind of grammar-based vision of what it means to be human`,
      option_d: `stakes a claim about what it means to use language well — and therefore, what it means to be fully human`,
      correct_answer: 'D',
      explanation: `The passage builds toward a philosophical culmination: the charter is not about rules but about a vision of human dignity rooted in language. The final clause must complete this thought with equivalent philosophical weight and rhetorical power. Option D does this: "stakes a claim about what it means to use language well — and therefore, what it means to be fully human." The phrase "stakes a claim" uses figurative language (claiming territory) that conveys the assertive, philosophical ambition of the charter. The structure "what it means to use language well — and therefore, what it means to be fully human" echoes the passage's progression from grammar to human nature. Option A (lists rules) is literal and contradicts the paragraph's entire argument. Option B ("useful framework for governance") is institutional and neutral, entirely at odds with the passage's philosophical register. Option C is accurate but weaker — "asserts a kind of grammar-based vision of what it means to be human" is more academic and less rhetorically powerful than D.`,
      success_narrative: `The passage concludes with a sentence that carries the full philosophical weight of everything that preceded it. The Artistry Annihilator shatters — beauty and precision together are too much for it to bear. You have mastered Chapter 18.`,
      failure_narrative: `The Artistry Annihilator annihilates the artistry. The charter now "provides a useful framework for institutional governance" — a sentence about parking regulations could say the same.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'rhetoric_craft',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
  ]
};

module.exports = chapter18;
