// CHAPTER 15: Purpose and Relevance (25 encounters)
const chapter15 = {
  chapter_number: 15,
  encounters: [
    {
      encounter_number: 1,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Irrelevant Insurgent',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `You enter the Rhetoric Ruins through a crumbling archway, torchlight flickering across inscriptions half-buried in dust. The first ghost you meet drifts beside a stone tablet, whispering nonsense into the carved text. It is the Irrelevant Insurgent — a specter that inserts sentences that have nothing to do with anything.`,
      passage: `[1] The Guild of Rhetoric Scholars was founded to preserve the art of clear, purposeful writing. [2] Its members spent decades cataloguing every logical fallacy known to the ancient world. [3] The Guild's main hall featured beautiful stained-glass windows depicting famous arguments. [4] Above all, the Guild believed that every sentence in a text must earn its place.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it introduces a detail about architecture that is unrelated to the paragraph's focus on the Guild's scholarly mission.`,
      option_b: `Yes, because it contradicts the claim that the Guild believed in purposeful writing.`,
      option_c: `No, because it provides important context about the Guild's resources and influence.`,
      option_d: `No, because it supports the paragraph's argument that the Guild valued both logic and beauty.`,
      correct_answer: 'A',
      explanation: `The paragraph is about the Guild of Rhetoric Scholars and its mission: preserving clear writing, cataloguing fallacies, and believing every sentence must earn its place. Sentence [3] describes the decorative windows in the Guild's hall — an architectural detail that has nothing to do with the Guild's intellectual purpose. Option A correctly identifies this: the sentence is irrelevant to the paragraph's focus on scholarly mission. Option B is wrong because sentence [3] does not contradict anything — it simply has nothing to do with the topic. Option C is wrong because architectural descriptions do not tell us about the Guild's resources or influence in any meaningful, relevant way. Option D tries to invent a connection between beauty and purposeful writing, but the paragraph never makes that argument, so this reason is fabricated.`,
      success_narrative: `The ghost screams as the irrelevant sentence dissolves from the stone. The inscription tightens into clear, purposeful lines, and the Insurgent retreats into the shadows of the ruin.`,
      failure_narrative: `The Irrelevant Insurgent laughs and carves three more pointless sentences into the tablet. The stone inscription becomes a jumbled mess, and the torchlight dims around you.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'relevance',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 2,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Off-Topic Oracle',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `An ancient oracle-stone glows at the center of a collapsed courtyard, its prophecies garbled by a hovering wraith. The Off-Topic Oracle pretends to know all things but actually says nothing relevant. It challenges you with a test of purpose.`,
      passage: `[1] The founding of Grammar Keep required the cooperation of three ancient scholar-clans. [2] Each clan contributed a different discipline: the Grammarians brought syntax, the Logicians brought argument structure, and the Rhetoricians brought persuasion. [3] Scholars of the era also debated whether semicolons should be taught before colons. [4] Together, these three disciplines formed the intellectual foundation that Grammar Keep still stands upon today.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it shifts focus to a punctuation debate that is unrelated to the paragraph's main point about the founding of Grammar Keep.`,
      option_b: `Yes, because it weakens the argument by introducing disagreement among scholars.`,
      option_c: `No, because it adds useful information about the academic culture of the era.`,
      option_d: `No, because it helps explain why the three clans needed to cooperate.`,
      correct_answer: 'A',
      explanation: `The paragraph is about how three scholar-clans cooperated to found Grammar Keep, each contributing a distinct discipline. Sentence [3] introduces a debate about semicolons and colons — a punctuation technicality that has no connection to the founding story or the roles of the three clans. Option A is correct: the sentence is off-topic and should be deleted. Option B is wrong because the sentence does not weaken an argument — it simply fails to support the paragraph's topic at all. Option C is wrong because while the sentence describes academic culture, "useful" is not the standard; the question is whether the information is relevant to the paragraph's specific focus. Option D is flatly wrong — a semicolon debate has nothing to do with explaining inter-clan cooperation.`,
      success_narrative: `The oracle-stone pulses with light and the garbled sentence vanishes from its face. The Off-Topic Oracle wails and shatters into harmless fragments of irrelevant prophecy.`,
      failure_narrative: `The oracle-stone absorbs the wrong answer and grows darker. The Off-Topic Oracle smiles and adds a sentence about the history of inkwells to the inscription.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'relevance',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 3,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Purpose Phantom',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `A ruined archway stands ahead, its keystone inscription faded but still legible. Perched atop it is the Purpose Phantom, a wraith that haunts paragraphs and robs them of their point. It dares you to identify which sentence below truly belongs.`,
      passage: `[1] Warden Elara Voss became the most decorated Grammar Warden in the Keep's history by enforcing clarity in all official documents. [2] Her campaign against vague language reduced misunderstandings between the Keep's districts by forty percent. [3] Voss was known to enjoy long walks along the Punctuation Quarter's canals after her evening meals. [4] Her legacy endures in the Voss Standard, a set of writing guidelines still used by every Scholar in the Keep.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it introduces a personal habit unrelated to Voss's professional accomplishments, which is the paragraph's focus.`,
      option_b: `Yes, because it makes Voss seem ordinary, which contradicts the paragraph's admiring tone.`,
      option_c: `No, because it shows Voss was a well-rounded person and adds depth to her character.`,
      option_d: `No, because it provides context for understanding how Voss developed her writing standards.`,
      correct_answer: 'A',
      explanation: `The paragraph is a focused account of Warden Voss's professional legacy: her enforcement of clarity, measurable results, and enduring written guidelines. Sentence [3] describes her habit of walking along canals after dinner — a personal detail that has no connection to any of those professional accomplishments. Option A is correct because the sentence is simply off-topic for a paragraph about career achievements. Option B is wrong because making someone seem ordinary is not the reason for deletion — irrelevance is. Option C argues for "depth of character," but character development is not the paragraph's purpose; its purpose is to describe Voss's professional impact. Option D fabricates a causal connection (walking = writing standards) that the passage never establishes.`,
      success_narrative: `The archway inscription glows gold as the off-topic sentence crumbles away. The Purpose Phantom dissolves into a purposeful silence, and the path forward becomes clear.`,
      failure_narrative: `The Purpose Phantom multiplies the irrelevant sentence across every stone in the archway. Each step you take seems to lead somewhere unrelated.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'relevance',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 4,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Tangent Terror',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `Deep in the ruins, a stone lectern holds an ancient scroll — but a spectral hand keeps adding sentences to it. The Tangent Terror feeds on digressions, pulling readers off the main road of an argument and into endless side paths. The scroll reads poorly. You must fix it.`,
      passage: `[1] The Comma Plague of the Fourth Age spread through Grammar Keep when a rogue Scholar added commas to every sentence without reason or rule. [2] Within a week, readers across the Keep could no longer parse basic instructions, causing widespread confusion. [3] Commas are also commonly misused in lists containing three or more items. [4] The Plague was eventually contained when Warden Holt published a definitive guide to comma usage, restoring order to the written word.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it shifts to a general grammar rule that interrupts the historical narrative about the Comma Plague.`,
      option_b: `Yes, because it is factually incorrect about comma usage in lists.`,
      option_c: `No, because it explains what kind of comma errors the rogue Scholar was making.`,
      option_d: `No, because it provides background knowledge that helps readers understand the Plague's impact.`,
      correct_answer: 'A',
      explanation: `The paragraph tells a specific historical story: the Comma Plague, its cause, its effect, and its resolution. Sentence [3] steps outside that narrative to offer a general grammar tip about commas in lists. This is a classic tangent — it may be true, but it is not relevant to this story. Option A correctly identifies the interruption of the historical narrative. Option B is wrong because the sentence is not factually incorrect — it is simply out of place. Option C tries to connect the sentence to the rogue Scholar's errors, but the sentence mentions list commas specifically, while the Plague involved commas added to every sentence "without reason or rule" — so the connection is not accurate. Option D is wrong because general comma rules do not help the reader understand the specific historical events being described.`,
      success_narrative: `The scroll tightens into a clean historical account. The Tangent Terror shrieks as its favorite digression disappears, retreating through a crack in the ruin wall.`,
      failure_narrative: `The Tangent Terror adds four more grammar tangents to the scroll. It now takes twenty minutes to read a three-sentence story about a plague.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'relevance',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 5,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Support Saboteur',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `A memorial inscription for a fallen Scholar has been defaced. The Support Saboteur wanders nearby, proud of its work — it has added a sentence that undermines the inscription's clear purpose. You must identify which sentence should be added to strengthen the paragraph's main idea.`,
      passage: `The Scholar-Medic Orin Falc died defending the Punctuation Quarter during the Ink War, her body found beside a stack of corrected manuscripts. Her colleagues remembered her as someone who never stopped teaching, even in the chaos of battle. She is honored every year at the Festival of Clear Prose.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `The Ink War lasted approximately three years and resulted in significant structural damage to the eastern districts.`,
      option_b: `Even her final manuscripts bore her characteristic red-ink corrections, evidence that she was editing until the very end.`,
      option_c: `Scholar-Medics were a unique class of practitioners who combined writing instruction with battlefield medicine.`,
      option_d: `The Festival of Clear Prose was established in the second year after the Ink War concluded.`,
      correct_answer: 'B',
      explanation: `The paragraph's main idea is that Scholar-Medic Orin Falc was utterly devoted to her work — teaching and correcting prose even in death. The central claim is that she "never stopped teaching, even in the chaos of battle." Option B directly reinforces this idea by providing a vivid, specific detail: her manuscripts still bore red-ink corrections, proving she was editing until she died. This is the strongest possible support for the paragraph's main claim. Option A introduces background about the Ink War's duration and damage — relevant to the war generally but not to Falc's character or mission. Option C provides context about Scholar-Medics as a class, which might be useful elsewhere but does not directly support the claim that Falc specifically never stopped teaching. Option D gives a founding date for the festival, which is a historical trivia point that adds nothing to the portrait of Falc's dedication.`,
      success_narrative: `The memorial inscription glows as the supporting sentence settles into place. The Support Saboteur retreats, muttering — it cannot corrupt a paragraph this well-defended.`,
      failure_narrative: `The Support Saboteur cackles and stuffs an irrelevant sentence about weather conditions into the memorial. The inscription becomes muddy and forgettable.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'relevance',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 6,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Digression Demon',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Digression Demon haunts the Hall of Philosophical Texts, where scholars once debated the relationship between Grammar and Logic. It has infected a passage from their most famous treatise. The demon feeds on confusion — you must find the sentence that does not belong.`,
      passage: `[1] The ancient philosophers of Grammar Keep argued that a well-structured sentence is the foundation of a well-structured mind. [2] They believed that the ability to arrange words with precision reflected the ability to arrange thoughts with precision. [3] Warden Castellan's treatise on this subject ran to four hundred pages and was considered difficult reading even by scholars. [4] To think clearly, they insisted, one must first learn to write clearly.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because information about a treatise's length and difficulty level does not support the paragraph's philosophical argument about language and thought.`,
      option_b: `Yes, because the reference to Warden Castellan introduces a new figure who contradicts the philosophers' main claim.`,
      option_c: `No, because Warden Castellan's treatise is the primary source for the philosophical views described in the paragraph.`,
      option_d: `No, because noting that the subject was considered difficult reinforces the paragraph's point that clear thinking requires effort.`,
      correct_answer: 'A',
      explanation: `The paragraph makes a philosophical argument: precise writing reflects precise thinking. Sentences [1], [2], and [4] all advance this argument in a coherent chain. Sentence [3] mentions that a treatise on this subject was four hundred pages long and difficult to read — but this is a bibliographic footnote, not a philosophical contribution. The length and difficulty of the treatise tells us nothing about whether the argument is correct. Option A correctly identifies that the detail is irrelevant to the philosophical argument. Option B is wrong — sentence [3] does not contradict the philosophers' claim; it simply fails to support it. Option C is wrong because the paragraph does not identify Castellan's treatise as the source for the ideas; it presents the ideas independently. Option D invents a reading: "difficult" in sentence [3] refers to the treatise's complexity, not to the process of developing clear thinking — these are not the same thing.`,
      success_narrative: `The treatise passage clarifies itself, the irrelevant footnote dissolving into dust. The Digression Demon howls and retreats deeper into the Hall of Philosophical Texts.`,
      failure_narrative: `The Digression Demon adds a paragraph about the treatise's binding materials and publication history. The philosophical argument is now completely buried.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 7,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Focus Fiend',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `A Scholar's field notes lie open on a broken pedestal, the pages fluttering in a wind from nowhere. The Focus Fiend has added sentences that scatter the Scholar's observations in every direction. You must identify which sentence would best support the notes' central argument.`,
      passage: `The Modifier Marshes present a unique challenge to field researchers: every landmark looks identical from a distance, making navigation by sight unreliable. Experienced Scholars learn to navigate by sound instead, using the distinct calls of the Syntax Frogs to triangulate their position. The Marshes reward patience and careful observation above all other virtues.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `The Modifier Marshes were first mapped by Scholar-Cartographer Daven in the Second Age.`,
      option_b: `Syntax Frogs are also known for their unusually long lifespans, sometimes exceeding forty years.`,
      option_c: `A Scholar who rushes through the Marshes without listening carefully risks becoming hopelessly lost within minutes.`,
      option_d: `The Marshes cover approximately two hundred square miles of the Keep's western territories.`,
      correct_answer: 'C',
      explanation: `The paragraph's main idea is that the Modifier Marshes require patient, attentive navigation — specifically, that researchers must rely on careful listening rather than sight. Option C directly reinforces this by showing the consequence of failing to do so: a Scholar who rushes and does not listen carefully becomes lost. This adds a concrete, logical extension of the paragraph's core argument. Option A introduces the history of cartography in the Marshes, which is a background fact unrelated to the challenges of navigation by sound. Option B discusses the lifespan of Syntax Frogs — an interesting natural history detail, but completely unrelated to navigation or the paragraph's central point. Option D gives the geographic size of the Marshes, which is another background fact that does not support the argument about patience and careful listening.`,
      success_narrative: `The field notes snap shut with a satisfying click, the supporting sentence neatly inserted. The Focus Fiend scatters into a thousand unfocused whispers that fade into the marsh wind.`,
      failure_narrative: `The Focus Fiend floods the field notes with irrelevant measurements and historical footnotes. The Scholar's central insight is completely lost.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 8,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Topic Thief',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Topic Thief has stolen the main idea from a paragraph about the Punctuation Quarter's annual report and replaced it with scattered, purposeless facts. You face a writer's goal question — you must identify what the paragraph is actually trying to accomplish.`,
      passage: `The Punctuation Quarter submitted its annual report to the Grammar Council with unusual efficiency this year, completing the process two weeks ahead of schedule. The report detailed a fifteen-percent increase in correctly punctuated public documents, a reduction in comma splices across all official correspondence, and the successful training of forty new Punctuation Wardens. Quarter-Master Desh credited the improvements to a new training protocol introduced in the spring.`,
      question_stem: `The writer's main purpose in this paragraph is to:`,
      option_a: `argue that the Punctuation Quarter deserves more funding from the Grammar Council.`,
      option_b: `present a balanced account of both the successes and failures of the Punctuation Quarter.`,
      option_c: `summarize the achievements and organizational efficiency of the Punctuation Quarter in its annual report.`,
      option_d: `explain how Quarter-Master Desh's training protocol works in detail.`,
      correct_answer: 'C',
      explanation: `The paragraph reports specific accomplishments (efficiency, improved punctuation rates, trained Wardens) and attributes them to organizational leadership. Its purpose is informational and summative: it describes what the Quarter achieved and how efficiently it reported those achievements. Option C accurately captures this as a summary of achievements and efficiency. Option A is wrong because the paragraph does not make any argument about funding — there is no request, no comparison to other quarters, and no evaluative claim about resources. Option B is wrong because the paragraph presents only successes; there is no mention of failures or a "balanced" perspective. Option D is wrong because the paragraph only mentions the training protocol as the credited cause — it does not explain how the protocol works.`,
      success_narrative: `The annual report reassembles itself into a clear, purposeful document. The Topic Thief flees, clutching a stack of stolen main ideas it can no longer use here.`,
      failure_narrative: `The Topic Thief celebrates by scattering the report's pages across the ruin floor. Every page now discusses a different, unrelated subject.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 9,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Relevance Rogue',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `A traveler's account of arriving at Grammar Keep has been tampered with. The Relevance Rogue has inserted a sentence designed to look like it fits — but it does not. Your task is to find and condemn it.`,
      passage: `[1] A traveler's first sight of Grammar Keep is unforgettable: the great stone walls rise from the plain without warning, carved with sentences in a dozen ancient languages. [2] The main gate bears the Keep's founding motto: "Every word must earn its place." [3] Grammar Keep was built over the ruins of an older fortress that predates the Scholar-clans by centuries. [4] Travelers who pass beneath that motto for the first time often report a sudden sense that their words — all their words, spoken and unspoken — are being measured.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the geological and historical origin of the Keep's site is not relevant to the paragraph's focus on a traveler's emotional first impression.`,
      option_b: `Yes, because the claim about an older fortress contradicts the idea that the Scholar-clans founded the Keep.`,
      option_c: `No, because knowing the Keep's ancient origins makes the traveler's awe more understandable.`,
      option_d: `No, because the paragraph is about Grammar Keep's history, and sentence [3] provides important historical context.`,
      correct_answer: 'A',
      explanation: `The paragraph creates a sensory and emotional portrait of a traveler's first experience arriving at Grammar Keep — the visual impact, the motto, and the psychological effect of passing beneath it. Sentence [3] pivots to a historical fact about the Keep being built on older ruins, which is a piece of architectural history with no connection to the traveler's first impression. Option A correctly identifies the mismatch: the paragraph is about emotional experience, not origin history. Option B is wrong because sentence [3] does not contradict anything — the Scholar-clans can still have founded the Keep on that older site. Option C argues that knowing the ancient origins enhances the awe, but the paragraph never establishes that connection; the traveler's awe comes from the walls and the motto, not from the Keep's geological history. Option D is wrong because the paragraph is not about history at all — it is about a traveler's experience.`,
      success_narrative: `The traveler's account flows cleanly from sight to motto to feeling, unburdened by the historical digression. The Relevance Rogue vanishes in a puff of irrelevant context.`,
      failure_narrative: `The Relevance Rogue stuffs the traveler's account with footnotes about foundation stones and ancient fortresses. The sense of awe is completely buried.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 10,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Point Pilferer',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Point Pilferer has hollowed out a paragraph from the philosophical treatise on Grammar and Logic, stealing its supporting details and replacing them with vague gestures. You must identify which sentence would best restore the paragraph's argument.`,
      passage: `The First Scholars of Grammar Keep believed that logic and grammar were not merely related disciplines — they were two expressions of the same underlying truth. A thought that could not be clearly written, they argued, was a thought that had not yet been fully formed. The relationship between the two disciplines remained central to the Keep's educational mission for centuries.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `Logic was taught in the East Wing of the Keep, while Grammar was taught in the West Wing.`,
      option_b: `The First Scholars required every student to demonstrate grammatical fluency before advancing to formal logical study, arguing that you cannot reason well if you cannot write well.`,
      option_c: `The Keep's library held thousands of volumes on both logic and grammar, making it the largest repository of scholarly texts in the known world.`,
      option_d: `Many scholars outside the Keep disputed the idea that grammar and logic were related, preferring to treat them as entirely separate fields.`,
      correct_answer: 'B',
      explanation: `The paragraph argues that the First Scholars saw grammar and logic as two expressions of the same truth, and that clear writing was a prerequisite for clear thinking. Option B directly strengthens this argument by providing a concrete institutional example: the requirement to master grammar before advancing to logic. The embedded reasoning ("you cannot reason well if you cannot write well") directly echoes the paragraph's central claim. Option A describes the physical layout of the Keep, which is a logistical detail unrelated to the philosophical argument. Option C discusses the library's size, which speaks to the Keep's resources but not to the relationship between grammar and logic. Option D introduces outside scholars who disputed the claim — which might be useful for a counterargument paragraph, but it would weaken rather than support the main idea here.`,
      success_narrative: `The philosophical treatise pulses with renewed argumentative force. The Point Pilferer drops its stolen sentences and dissolves, unable to maintain form against such well-supported prose.`,
      failure_narrative: `The Point Pilferer escapes with the paragraph's best evidence, leaving only weak gestures and vague assertions behind.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 11,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Drift Daemon',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Drift Daemon causes paragraphs to slowly wander away from their own subject, like a boat with no rudder. It has infected an account of a famous Grammar Warden, inserting a sentence that drifts far from shore. Find it.`,
      passage: `[1] Chief Warden Maren Sollis revolutionized the Keep's approach to run-on sentences during her thirty-year tenure. [2] Before Sollis, run-ons were treated as minor stylistic errors; under her administration, they became a matter of civic urgency — a run-on in a public decree could, she argued, change its meaning entirely. [3] Sollis also served briefly as the Keep's Ambassador to the Southern Trading Guilds, a role she found less satisfying than her grammatical work. [4] Her landmark ruling of the Third Reform established that all official Keep documents must pass a structural review before publication.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the brief mention of Sollis's ambassadorial role is unrelated to the paragraph's focus on her contributions to grammar policy.`,
      option_b: `Yes, because it undermines the paragraph's argument by suggesting Sollis was not fully committed to her role as Warden.`,
      option_c: `No, because it adds important context about Sollis's full range of responsibilities and public service.`,
      option_d: `No, because it explains why Sollis was motivated to prioritize grammar over other concerns.`,
      correct_answer: 'A',
      explanation: `The paragraph is specifically about Sollis's contributions to grammar policy: her elevation of run-ons to civic urgency and her landmark structural review ruling. Sentence [3] mentions a brief ambassadorial role that Sollis found "less satisfying" — which is interesting biography, but it has nothing to do with grammar policy, the paragraph's subject. Option A correctly identifies this as irrelevant. Option B misreads sentence [3]: noting that Sollis found ambassadorial work "less satisfying" than her grammatical work does not suggest a lack of commitment — if anything, it suggests she preferred grammar. But regardless, irrelevance is the reason for deletion, not this misreading. Option C argues that "full range of responsibilities" is useful context, but the paragraph is not a general biography — it has a specific focus. Option D invents a motivation: the paragraph never claims that the ambassadorial experience motivated her grammar work.`,
      success_narrative: `The Warden's account sharpens into a focused portrait of professional achievement. The Drift Daemon loses its current and fades, unable to pull the paragraph off course.`,
      failure_narrative: `The Drift Daemon floods the paragraph with biographical tangents. By the end, you have learned a great deal about Sollis's diplomatic career and nothing about her grammar reforms.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 12,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Sidebar Specter',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Sidebar Specter haunts a carved column in the main hall, whispering parenthetical asides into every inscription it touches. It has added a sentence to a scholarly debate on Oxford commas. The sentence looks almost relevant. It is not.`,
      passage: `The great Oxford Comma Debate of the Keep's Fifth Age was not merely a punctuation dispute — it was a philosophical crisis. Scholars argued that the serial comma was either a guarantee of logical clarity or an unnecessary redundancy, and the debate split the Guild into two irreconcilable factions. The controversy was finally resolved — provisionally — by Warden Holt's compromise ruling that allowed district scribes to choose their own convention.`,
      question_stem: `Which sentence, if added to this paragraph, would BEST support its main idea?`,
      option_a: `The Oxford comma takes its name from the Oxford University Press, which used it as a standard element of its house style.`,
      option_b: `At the height of the debate, two senior Guild members resigned in protest — one from each faction — rather than accept a compromise.`,
      option_c: `Warden Holt had previously presided over a similarly contentious debate about the em-dash in the Fourth Age.`,
      option_d: `The serial comma appears in lists of three or more items and is placed before the coordinating conjunction.`,
      correct_answer: 'B',
      explanation: `The paragraph's main idea is that the Oxford Comma Debate was a serious philosophical crisis that split the Guild into irreconcilable factions. Option B best supports this by providing specific evidence of how deep the division ran: two senior members resigned rather than accept compromise. This directly corroborates the claim that the factions were "irreconcilable." Option A provides etymology for the term "Oxford comma" — an interesting historical footnote but irrelevant to the paragraph's argument about the debate's intensity. Option C mentions a previous controversy Warden Holt presided over — this might be relevant in a paragraph about Holt's career, but not in one about the Oxford Comma Debate's depth and significance. Option D defines what a serial comma is — a definitional fact that does not support the argument about the debate's philosophical stakes.`,
      success_narrative: `The column inscription crackles with argumentative energy. The Sidebar Specter shrieks as its parenthetical asides are rejected, dissolving into an irrelevant footnote that no one will read.`,
      failure_narrative: `The Sidebar Specter carves an etymology lesson into the column. The debate's philosophical gravity is now buried under a definition.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 13,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Main Idea Mangler',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `A philosophical treatise on Logic and Grammar has been mangled by the Main Idea Mangler, a ghost that scrambles what a paragraph is trying to say. It presents you with a passage and demands you identify the writer's true purpose.`,
      passage: `The relationship between grammar and logic in the Keep's educational system was always contested. Logicians insisted their discipline was primary — you could not express a valid argument without understanding logical structure first. Grammarians countered that logic was merely thought, while grammar was thought made communicable. Neither side fully prevailed, but the tension between them produced some of the Keep's most rigorous scholarship.`,
      question_stem: `The writer's main purpose in this paragraph is to:`,
      option_a: `prove that the Grammarians' position was more intellectually defensible than the Logicians' position.`,
      option_b: `describe the ongoing dispute between Logicians and Grammarians and note its productive scholarly consequences.`,
      option_c: `explain the specific courses that were taught in the Grammar Keep curriculum.`,
      option_d: `argue that the tension between logic and grammar should be resolved by adopting a unified discipline.`,
      correct_answer: 'B',
      explanation: `The paragraph presents both sides of the debate — Logicians' view, Grammarians' view — without endorsing either, and then notes that the productive tension generated rigorous scholarship. This is a balanced, descriptive account of an intellectual dispute and its outcomes. Option B captures this purpose precisely. Option A is wrong because the writer does not take sides; both positions are presented with equal weight. Option C is wrong because the paragraph says nothing about curriculum or specific courses — it discusses philosophy, not pedagogy. Option D is wrong because the paragraph does not argue for resolution; it concludes that the unresolved tension was actually productive.`,
      success_narrative: `The treatise reasserts its balanced, purposeful voice. The Main Idea Mangler shudders and disappears, unable to mangle a paragraph that knows exactly what it is doing.`,
      failure_narrative: `The Main Idea Mangler celebrates and rewrites the treatise so that it simultaneously argues all four positions at once, making it entirely incoherent.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 14,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Goal Ghost',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Goal Ghost haunts paragraphs that have lost their purpose, feeding on unfocused prose. It has intercepted an excerpt from a traveler's account and is demanding to know: what is this paragraph FOR? Answer correctly, or the paragraph will wander forever.`,
      passage: `The Scholar-Quarter inns near the Rhetoric Ruins are not comfortable by any standard. The beds are narrow, the candles are rationed, and the dining hall serves a single dish each evening regardless of preference. Yet every Scholar who has spent a season in that quarter describes it as among the most intellectually productive periods of their life. The discomfort, it seems, is the point.`,
      question_stem: `The writer's main purpose in this paragraph is to:`,
      option_a: `warn travelers that the Scholar-Quarter inns are poorly managed and should be avoided.`,
      option_b: `compare the Scholar-Quarter inns unfavorably to accommodations in other districts of the Keep.`,
      option_c: `suggest that the Spartan conditions of the Scholar-Quarter inns contribute to, rather than detract from, scholarly productivity.`,
      option_d: `describe the full range of amenities and services available to Scholars staying in the Rhetoric Ruins quarter.`,
      correct_answer: 'C',
      explanation: `The paragraph builds a deliberate argument: the inns are uncomfortable (narrow beds, rationed candles, limited food), but Scholars consistently describe their stays as intellectually productive. The final sentence — "The discomfort, it seems, is the point" — makes the argument explicit: hardship drives productivity. Option C captures this purpose precisely. Option A is wrong because the paragraph does not warn travelers away — it actually suggests the inns are worthwhile. Option B is wrong because no comparison to other districts is made. Option D is wrong because the paragraph does not describe amenities — it deliberately describes the lack of them, and for a specific argumentative purpose.`,
      success_narrative: `The traveler's account crystallizes into a sharp, satisfying argument. The Goal Ghost wails as the paragraph's purpose becomes undeniable, and it fades into the torchlit dark.`,
      failure_narrative: `The Goal Ghost erases the paragraph's final sentence and leaves the account suspended — uncomfortable inns with no point at all.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 15,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Purpose Perverter',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Purpose Perverter twists good paragraphs into things that almost make sense but somehow mean the opposite of what was intended. It has challenged you with a question about a paragraph from the Keep's founding chronicle — and the answer requires you to read carefully.`,
      passage: `[1] The First Scholars did not build Grammar Keep to hoard knowledge — they built it to share it. [2] The Keep's gates were open to any traveler who could demonstrate basic literacy, regardless of rank or region of origin. [3] Even the children of the Keep's laborers were offered access to the public reading rooms, an unprecedented gesture for the era. [4] The founding charter explicitly states that the Keep's purpose is "the increase and diffusion of learning among all people."`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it narrows the paragraph's focus from all travelers to a specific group, weakening the universal claim.`,
      option_b: `Yes, because information about the children of laborers is not directly related to the Keep's scholarly mission.`,
      option_c: `No, because it provides a specific, concrete example that supports the paragraph's claim about the Keep's inclusive, open mission.`,
      option_d: `No, because it introduces a counterargument that makes the paragraph's overall case stronger through contrast.`,
      correct_answer: 'C',
      explanation: `The paragraph argues that the Keep was built to share knowledge with everyone. Sentence [3] — that even laborers' children had access to the reading rooms — is not a digression; it is one of the paragraph's best pieces of evidence, providing a concrete example of the Keep's inclusivity. Option C correctly identifies this: the sentence should stay because it directly supports the main idea. Option A misreads the paragraph: including a specific group (laborers' children) does not weaken the universal claim — it illustrates it. Option B argues that laborers' children are not related to the scholarly mission, but the paragraph is specifically arguing that the Keep's mission extended to everyone, including non-scholars. Option D is wrong because sentence [3] is not a counterargument — it is additional supporting evidence, not a contrasting case.`,
      success_narrative: `The founding chronicle stands firm, its inclusive argument intact. The Purpose Perverter recoils from a paragraph it cannot twist, dissolving in the light of clear reasoning.`,
      failure_narrative: `The Purpose Perverter succeeds in removing the concrete example. The paragraph now makes a grand claim about inclusivity with nothing to back it up.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 16,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Objective Obliterator',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Objective Obliterator has torn apart a Scholar's field notes on the Modifier Marshes. It demands you decide which sentence, if added, would best serve the paragraph's purpose. It expects you to get this wrong.`,
      passage: `Field researchers in the Modifier Marshes have developed a system of color-coded flags to mark the locations of rare grammatical specimens. Red flags indicate misplaced modifiers; yellow flags mark dangling participles; blue flags identify ambiguous pronoun references. The system has allowed the Keep's Grammar Wardens to conduct targeted interventions across the Marshes far more efficiently than before.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `The Modifier Marshes are named for the preponderance of misplaced and dangling modifiers found in texts that originate from that region.`,
      option_b: `Prior to the flag system, Wardens spent weeks searching for errors that could now be located and corrected within a single day.`,
      option_c: `The color-coding convention was proposed by Scholar-Cartographer Yenne, who had previously developed a similar system for the Punctuation Quarter.`,
      option_d: `Misplaced modifiers are among the most common grammatical errors found in student writing throughout the Keep.`,
      correct_answer: 'B',
      explanation: `The paragraph's main idea is that the color-coded flag system has made grammatical error-correction in the Marshes significantly more efficient. Option B directly supports this by providing a specific, quantifiable measure of the improvement: what once took weeks now takes a day. This is the strongest possible support for the efficiency claim in the final sentence. Option A explains the origin of the Marshes' name — interesting background, but not about the flag system's effectiveness. Option C gives credit for the system's invention to a specific Scholar, which is a historical footnote but does not support the claim about efficiency. Option D provides a general statement about misplaced modifiers in student writing, which is not about the Marshes or the flag system at all.`,
      success_narrative: `The field notes snap into order, well-supported and purposeful. The Objective Obliterator backs away from a paragraph that has everything it needs.`,
      failure_narrative: `The Objective Obliterator stuffs the notes with background etymology and attribution details. The efficiency argument is now buried in footnotes.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 17,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Thesis Thief',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Thesis Thief has stolen the central claim from a paragraph about the Oxford Comma Debate and replaced it with something that sounds right but says nothing. You must identify the writer's true purpose and rescue the paragraph.`,
      passage: `Warden Holt's compromise ruling on the serial comma was controversial not because it was logically flawed, but because it required the Keep's most principled scholars to accept ambiguity. For the Logicians, any ruling that permitted two contradictory conventions was an admission of logical failure. For the Grammarians, it was a pragmatic recognition that style, unlike logic, admits of legitimate variation. Both sides understood Holt's ruling — they simply disagreed about whether that understanding was a reason to accept it or reject it.`,
      question_stem: `The writer's main purpose in this paragraph is to:`,
      option_a: `demonstrate that Warden Holt made a mistake in issuing a compromise ruling on the serial comma.`,
      option_b: `explain that the controversy over Holt's ruling stemmed from a principled disagreement about whether ambiguity is acceptable, not from a flaw in the ruling itself.`,
      option_c: `argue that the Grammarians' position on stylistic variation is more intellectually sound than the Logicians' position.`,
      option_d: `summarize the technical details of Warden Holt's compromise ruling and its impact on Keep policy.`,
      correct_answer: 'B',
      explanation: `The paragraph opens by immediately ruling out one explanation for the controversy (logical flaw) and substituting a different one: the debate was about whether ambiguity is acceptable in principle. The paragraph then explains both sides' reactions in terms of that question. Option B accurately captures this purpose: the writer is explaining the nature and source of the controversy. Option A is wrong because the writer explicitly says the ruling was NOT logically flawed — so "demonstrate Holt made a mistake" is the opposite of the paragraph's opening move. Option C is wrong because the paragraph presents both positions with equal respect and does not endorse the Grammarians. Option D is wrong because the paragraph never actually describes the technical details of the ruling — it only addresses how people responded to it.`,
      success_narrative: `The paragraph reclaims its thesis. The Thesis Thief drops the stolen claim and evaporates into the ancient dust of the ruin floor.`,
      failure_narrative: `The Thesis Thief escapes with the paragraph's central purpose. What remains is a collection of observations about Wardens and commas that amount to nothing.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 18,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Central Claim Crusher',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Central Claim Crusher has weakened a paragraph from the Keep's founding chronicle by inserting a sentence that dilutes its argument. Only careful analysis will reveal which sentence is the problem.`,
      passage: `[1] The founding charter of Grammar Keep was not merely a legal document — it was a philosophical manifesto. [2] Its preamble declared that language was the only tool by which thought could be shared across time and distance, and therefore that protecting language was among the highest duties of a civilized society. [3] The charter was drafted over a period of eighteen months and underwent forty-seven revisions before its final ratification. [4] Every subsequent Keep policy — every reform, every ruling, every curriculum — has been justified by appeal to the principles established in that preamble.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the drafting timeline and revision count are procedural details that do not contribute to the paragraph's argument about the charter's philosophical importance.`,
      option_b: `Yes, because it implies the charter was difficult to write, which might suggest the philosophers were uncertain about their principles.`,
      option_c: `No, because the number of revisions demonstrates how seriously the founders took the charter's philosophical content.`,
      option_d: `No, because it provides a necessary transition between the charter's content in sentence [2] and its legacy in sentence [4].`,
      correct_answer: 'A',
      explanation: `The paragraph argues that the founding charter was a philosophical manifesto whose principles have governed all subsequent Keep policy. Sentences [1], [2], and [4] build this argument coherently. Sentence [3] mentions drafting time and revision count — procedural facts that tell us nothing about the charter's philosophical content or its enduring influence. Option A correctly identifies these as irrelevant procedural details. Option B invents a negative implication that the passage does not support — many revisions might just as easily indicate rigor as uncertainty. Option C tries to read the revision count as evidence of philosophical seriousness, but this interpretation is a stretch; the paragraph never makes that connection, and the sentence is simply a historical footnote. Option D is wrong because sentences [2] and [4] connect naturally without sentence [3]: the preamble's declaration flows directly into its enduring legacy.`,
      success_narrative: `The founding charter gleams with philosophical authority, uncluttered by procedural footnotes. The Central Claim Crusher staggers back, defeated by a paragraph that knows what it is arguing.`,
      failure_narrative: `The Central Claim Crusher celebrates and adds three more procedural sentences. The charter's philosophical manifesto now reads like a meeting agenda.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'relevance',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 19,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Evidence Eraser',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The deeper you go into the ruins, the colder and more hostile the ghosts become. The Evidence Eraser has destroyed the best supporting sentence from a crucial paragraph in the Keep's philosophical treatise. You must find which sentence, if added, would restore the paragraph's full argumentative power — and it will not be obvious.`,
      passage: `The scholars who opposed Warden Sollis's structural review mandate did not dispute its intellectual merit — they disputed its practicality. They argued that requiring every official document to pass a structural review would create bottlenecks that slowed governance to a crawl. Sollis responded that the cost of a slow document was far lower than the cost of a misunderstood one, and that governance built on ambiguous language was governance built on sand.`,
      question_stem: `Which sentence, if added to the paragraph, would BEST support its main idea?`,
      option_a: `Warden Sollis had spent fifteen years as a district scribe before becoming Chief Warden, giving her an intimate knowledge of how documents moved through the Keep's bureaucracy.`,
      option_b: `The structural review mandate required that all documents pass a clarity assessment before being filed with the Grammar Council.`,
      option_c: `Historical records show that in the decade following the mandate's adoption, legal disputes arising from ambiguous Keep documents dropped by sixty-three percent.`,
      option_d: `Several of Sollis's opponents eventually came to support the mandate after retiring from their administrative posts.`,
      correct_answer: 'C',
      explanation: `The paragraph is a debate about a practical policy: Sollis's opponents say structural review slows governance; Sollis responds that ambiguous documents cost more than slow ones. The paragraph needs evidence that Sollis was right — that clear documents produced better outcomes than fast ones. Option C provides exactly that: a sixty-three percent drop in legal disputes after the mandate's adoption. This is hard, concrete evidence that the policy worked, directly supporting Sollis's argument. Option A provides biographical context for Sollis's credibility — relevant to ethos, perhaps, but not to the actual argument about policy outcomes. Option B describes the mechanism of the review process, which is procedural background rather than argumentative support. Option D notes that some opponents changed their minds after retiring, which is vague and anecdotal — it doesn't tell us why or on what grounds, so it provides weak support.`,
      success_narrative: `Sollis's argument stands fully supported. The Evidence Eraser recoils from the restored statistic, which it cannot delete without destroying the entire paragraph.`,
      failure_narrative: `The Evidence Eraser successfully removes the data. Sollis's argument now rests entirely on a metaphor about sand, which the opposition finds laughably easy to dismiss.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 20,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Support Slayer',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Support Slayer is one of the most feared ghosts in the Rhetoric Ruins. It destroys the internal logic of passages by keeping every sentence but making them irrelevant to each other. It has infected a passage about the Comma Plague. This one requires very careful reading.`,
      passage: `[1] The Comma Plague spread fastest through the Keep's legal sector, where complex sentence structures made over-punctuation especially damaging. [2] A single misplaced comma in a property deed could reverse the intended ownership of an entire estate. [3] Comma usage had been debated by scholars since the Keep's founding, with no consensus ever fully established. [4] Warden Holt's emergency protocol, issued at the height of the Plague, required that all legal documents be reviewed by at least two Punctuation Wardens before filing.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the historical debate about comma usage is not relevant to this paragraph's focus on the Comma Plague's specific impact on the legal sector and the emergency response to it.`,
      option_b: `Yes, because it undermines the paragraph's argument by implying that even Warden Holt could not establish consensus.`,
      option_c: `No, because it provides important background explaining why the Comma Plague was able to spread so quickly.`,
      option_d: `No, because it shows that comma misuse was a longstanding problem, making the Plague's severity more understandable.`,
      correct_answer: 'A',
      explanation: `The paragraph tells a tight story: the Plague spread fastest in the legal sector (sentence [1]), a specific harmful consequence is given (sentence [2]), and an emergency response is described (sentence [4]). Sentence [3] introduces a historical debate about comma usage that has been ongoing since the Keep's founding — but this debate is not connected to the Plague specifically, the legal sector specifically, or Warden Holt's emergency response. It floats between the cause-and-effect chain without contributing to it. Option A correctly identifies this. Option B misreads the paragraph — sentence [3] says there was no scholarly consensus on commas generally, not that Holt failed to establish consensus on his protocol. Option C argues the historical debate explains why the Plague spread quickly, but sentence [1] already provides that explanation (complex legal sentences). The debate is not the mechanism. Option D's claim that "longstanding problem = severity is more understandable" is speculative reasoning not established by the paragraph; furthermore, explaining severity is not the same as supporting the paragraph's specific cause-effect-response structure.`,
      success_narrative: `The Comma Plague account tightens into a precise narrative of cause, consequence, and emergency response. The Support Slayer screams and retreats, its best insertion defeated.`,
      failure_narrative: `The Support Slayer succeeds. The paragraph now meanders from the Plague to a historical debate and back, losing its narrative momentum entirely.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 21,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Argument Annihilator',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Argument Annihilator does not simply add irrelevant sentences — it adds sentences that seem highly relevant but actually undermine the paragraph's logical structure. It has trapped a philosophical passage. You must see through its deception.`,
      passage: `[1] The philosophical tradition at Grammar Keep maintained that ambiguity in language was not merely an inconvenience — it was a moral failure. [2] When a writer leaves their meaning unclear, they force the reader to bear the burden of interpretation, which the Keep's scholars considered a form of intellectual cowardice. [3] Nonetheless, several influential scholars argued that some degree of ambiguity was inevitable and even creatively productive. [4] The Keep's entire system of editorial review was built on the premise that this moral failure could and should be corrected.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because it introduces a competing view that contradicts the paragraph's consistent argument that ambiguity is a moral failure requiring correction.`,
      option_b: `Yes, because it shifts the tone from philosophical argument to academic survey, which is inconsistent with the rest of the paragraph.`,
      option_c: `No, because acknowledging a counterargument strengthens the paragraph's overall persuasive case.`,
      option_d: `No, because it provides necessary context for understanding why the Keep's editorial review system was created.`,
      correct_answer: 'A',
      explanation: `This is the hardest type of relevance question: the sentence being considered for deletion is not merely irrelevant — it actively contradicts the paragraph's thesis. The paragraph argues coherently in sentences [1], [2], and [4] that ambiguity is a moral failure and that the Keep's editorial system was built to correct it. Sentence [3] pivots with "nonetheless" to say that some scholars found ambiguity inevitable and productive — a view directly opposed to the paragraph's claim. This creates an argumentative contradiction. Option A correctly identifies this: the sentence should be deleted because it introduces a competing view that undermines the paragraph's coherence. Option B notes the tone shift but is not precise enough — the problem is logical contradiction, not merely tonal inconsistency. Option C is tempting: acknowledging counterarguments CAN strengthen persuasion. But in this case, the counterargument is dropped immediately with no rebuttal — it simply floats there, contradicting the conclusion in sentence [4]. Option D is wrong: sentence [3] does not explain why the editorial review system was created; sentences [1] and [2] already do that.`,
      success_narrative: `The philosophical passage reclaims its logical coherence, the contradictory sentence dissolved. The Argument Annihilator is visibly shaken — it has never faced a Scholar who could see through its most sophisticated trap.`,
      failure_narrative: `The Argument Annihilator triumphs. The paragraph now simultaneously argues that ambiguity is a moral failure and that ambiguity is creatively productive, destroying its own thesis.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 22,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Detail Distorter',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Detail Distorter has taken a passage about a famous Grammar Warden and planted a sentence that looks like evidence but actually says something subtly different from what the paragraph claims. You must identify whether the sentence should stay or go — and choose the right reason.`,
      passage: `[1] Warden Elara Voss did not merely enforce grammar rules — she understood them as instruments of justice. [2] Her most celebrated ruling held that any official Keep document written in language that a common laborer could not understand was invalid, regardless of its grammatical correctness. [3] Voss spent considerable time in the Keep's outer districts, talking with laborers and craftspeople about how official documents affected their daily lives. [4] The ruling transformed the Keep's approach to civic writing, shifting the standard from technical correctness to genuine communicability.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because while it describes Voss's fieldwork, it does not directly connect to the paragraph's central argument about her ruling and its impact on civic writing standards.`,
      option_b: `Yes, because it suggests Voss was not confident in her ruling and needed outside validation.`,
      option_c: `No, because it explains the basis for Voss's landmark ruling, showing that her policy was grounded in firsthand research.`,
      option_d: `No, because it is essential for establishing Voss's authority as a Warden who understood conditions beyond the Keep's central halls.`,
      correct_answer: 'C',
      explanation: `This is a keep-it question: sentence [3] should NOT be deleted. The paragraph argues that Voss's ruling — that documents must be comprehensible to common laborers — was a transformation of civic writing standards. Sentence [3] explains why Voss understood this issue: she had gone out and talked to laborers directly. This is not merely biographical flavor; it establishes the empirical foundation for her ruling. Without it, her ruling seems arbitrary; with it, it seems grounded in firsthand observation. Option C correctly identifies this as the reason to keep sentence [3]. Option A argues the fieldwork "does not directly connect" to the ruling, but this misreads the paragraph — the connection is that Voss's fieldwork informed the ruling she is famous for. Option B invents a negative reading: consulting laborers is not evidence of uncertainty; it is evidence of rigor. Option D is partially correct (it says to keep the sentence) but gives a weak, vague reason about "authority" rather than accurately identifying that the sentence explains the evidential basis for the ruling.`,
      success_narrative: `Sentence [3] remains in place, fully justified. The Detail Distorter cannot distort a paragraph where every sentence earns its place, and it retreats in defeat.`,
      failure_narrative: `The Detail Distorter convinces you to remove the fieldwork sentence. Voss's ruling now appears arbitrary, with no visible basis in lived experience.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 23,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Context Crusher',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Context Crusher stands before the ruins' deepest chamber, guarding a passage from the Keep's founding chronicle. It has constructed an elaborate argument for why an irrelevant sentence should stay. You must see through its reasoning.`,
      passage: `The founding of Grammar Keep was not a single event but a process spanning three generations of scholars. The first generation established the physical site and wrote the founding charter. The second generation built the Keep's major institutions — the Library, the Guild Hall, and the Grammar Council. The third generation, inheriting these structures, turned the Keep's attention outward: they began training scholars from outside the Keep's founding clans, transforming a private institution into a public one.`,
      question_stem: `If the writer wanted to emphasize that Grammar Keep's founding was a collective, multi-generational achievement rather than the work of a single visionary, which sentence would BEST serve as the opening sentence of this paragraph?`,
      option_a: `The Scholar-Warden Aldric Vane is traditionally credited with founding Grammar Keep, though this attribution oversimplifies a complex historical process.`,
      option_b: `Grammar Keep stands today as one of the most enduring institutions in the known world.`,
      option_c: `The founding documents of Grammar Keep list over three hundred contributing scholars by name.`,
      option_d: `Building a new institution requires vision, resources, and patience in equal measure.`,
      correct_answer: 'A',
      explanation: `The paragraph argues that the founding of Grammar Keep was a multi-generational, collective process — not a single event and not the work of one person. The writer wants to open by emphasizing this collective nature. Option A does this most effectively by immediately naming the traditional single-founder narrative (Aldric Vane is credited), then challenging it ("oversimplifies a complex historical process"). This directly sets up the paragraph's multi-generational account as a correction to the oversimplified version. Option B mentions the Keep's endurance, which is a general compliment that does not set up the collective founding argument. Option C mentions three hundred scholars in the founding documents — this supports the collective theme, but it is a static fact that does not create the narrative tension of "the traditional story is wrong." Option D is a vague aphorism about institutional building that could open any paragraph about any institution — it does not specifically connect to the Keep's founding or the multi-generational argument.`,
      success_narrative: `The founding chronicle opens with perfect purpose, immediately correcting the myth of the lone founder. The Context Crusher's elaborate defense collapses, and it dissolves into the dust of the ancient floor.`,
      failure_narrative: `The Context Crusher succeeds in supplying a weak opening sentence. The paragraph's argument for collective founding now lacks the narrative setup that makes it powerful.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 24,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Purpose Predator',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The Purpose Predator hunts paragraphs that have nearly escaped it — paragraphs that are almost focused, almost purposeful, but not quite. It has your passage cornered. This question asks you to identify the writer's goal with precision.`,
      passage: `Scholar-debates in the Keep's Fifth Age were not polite academic exercises — they were gladiatorial. Participants were expected to defend their positions under relentless interrogation, concede only when their arguments were logically demolished, and never appeal to authority as a substitute for evidence. The debates were public, the records were permanent, and the intellectual reputations of participants rose or fell on their performance. Students who survived the gauntlet described the experience as the most terrifying and the most educational of their careers.`,
      question_stem: `The writer's main purpose in this paragraph is to:`,
      option_a: `criticize the hostile and intimidating culture of scholarly debate in the Keep's Fifth Age.`,
      option_b: `compare the Keep's Fifth Age debates to modern standards of academic discourse.`,
      option_c: `convey the intense, high-stakes nature of scholarly debate in the Keep's Fifth Age and its educational value for participants.`,
      option_d: `argue that the Keep should return to the adversarial debate format of the Fifth Age.`,
      correct_answer: 'C',
      explanation: `The paragraph describes the debates in vivid, intensifying terms — "gladiatorial," public, permanent, high-stakes — and concludes with students describing the experience as both terrifying and educational. The writer is clearly conveying how intense these debates were and implying that the intensity had educational value. Option C captures both dimensions: the intensity (high-stakes nature) and the payoff (educational value). Option A interprets the paragraph as a critique, but the tone is descriptive and the final sentence presents the experience positively ("most educational of their careers"). The paragraph does not condemn the debate culture. Option B mentions modern standards, but the paragraph makes no such comparison — it exists entirely within the Fifth Age. Option D reads the paragraph as an argument for policy change, but there is no call to action, no recommendation, and no normative claim — only description.`,
      success_narrative: `The paragraph stands purposeful and complete. The Purpose Predator lunges — and misses. A paragraph that knows exactly what it is doing cannot be hunted.`,
      failure_narrative: `The Purpose Predator latches onto the paragraph and tears away its final sentence, leaving the passage describing terror with no mention of education.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 25,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Relevance Reaper',
      enemy_type: 'Ruin Ghost',
      pre_narrative: `The final guardian of Chapter 15 materializes from the darkness: the Relevance Reaper, the most powerful relevance ghost in the Rhetoric Ruins. It presents the most deceptive of all relevance questions — one where the correct answer requires understanding not just what is relevant, but what kind of relevance matters.`,
      passage: `[1] The Keep's annual review of public grammar standards serves not as a punishment for poor writers, but as a diagnostic tool — its purpose is to identify systemic weaknesses in the Keep's educational outputs and correct them at their source. [2] This distinction between punitive and diagnostic review has been central to every Grammar Council policy for the past two centuries. [3] The review process itself involves a committee of seven Wardens who assess a sample of five hundred documents drawn from across the Keep's districts. [4] Maintaining this distinction, the current Council has argued, is what separates a functional grammar institution from a repressive one.`,
      question_stem: `The writer is considering deleting sentence [3] from the paragraph. Should sentence [3] be deleted?`,
      option_a: `Yes, because the procedural details of the review process (committee size, sample size) do not contribute to the paragraph's central argument about the distinction between punitive and diagnostic review.`,
      option_b: `Yes, because the number of Wardens and documents reviewed is insufficient information to evaluate the effectiveness of the review system.`,
      option_c: `No, because it provides the factual basis that makes the paragraph's argument credible and specific.`,
      option_d: `No, because it transitions logically between the historical claim in sentence [2] and the current Council's argument in sentence [4].`,
      correct_answer: 'A',
      explanation: `The paragraph argues that the distinction between punitive and diagnostic review is philosophically and institutionally significant — that it defines a functional versus repressive institution. Sentence [3] describes the mechanics of the review: seven Wardens, five hundred documents. These are procedural facts that describe how the review works, not why the punitive/diagnostic distinction matters. The paragraph's argument does not depend on the committee size or sample size; it depends on the philosophical distinction established in sentences [1], [2], and [4]. Option A correctly identifies the procedural details as irrelevant to the philosophical argument. Option B is wrong: the problem is not that the numbers are insufficient — the problem is that they are beside the point. Option C argues that procedural details add credibility, but credibility for what? The paragraph's argument is philosophical, not statistical — the committee size does not make the punitive/diagnostic distinction more or less valid. Option D argues sentence [3] transitions between [2] and [4], but sentences [2] and [4] connect naturally: the historical claim that the distinction has been central leads directly to the current Council's defense of it.`,
      success_narrative: `The Relevance Reaper shrieks as its most sophisticated trap is dismantled. The paragraph stands perfect — every sentence earning its place, as the Keep's founding motto demands. You have mastered Chapter 15.`,
      failure_narrative: `The Relevance Reaper claims its prize. You kept the procedural sentence, and the paragraph's philosophical argument is now distracted by committee logistics.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'relevance',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
  ]
};

module.exports = chapter15;
