// CHAPTER 17: Transitions (25 encounters)
const chapter17 = {
  chapter_number: 17,
  encounters: [
    {
      encounter_number: 1,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Transition Thief',
      enemy_type: 'Logic Phantom',
      pre_narrative: `You press deeper into the Rhetoric Ruins and find a gallery of stone inscriptions carved with philosophical arguments. The Transition Thief haunts this gallery, stealing the words that connect ideas and leaving gaps where logic should flow. The first inscription is incomplete — a word is missing that joins two contradictory observations.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"Grammar Keep's founding scholars believed that clear writing and clear thinking were inseparable. ________, modern neuroscience has produced evidence supporting exactly this claim."`,
      option_a: `Consequently`,
      option_b: `However`,
      option_c: `Remarkably`,
      option_d: `Therefore`,
      correct_answer: 'C',
      explanation: `The logical relationship between these sentences is one of emphasis and surprise: the ancient scholars believed something, and now modern science has confirmed it. The word needed signals that this confirmation is notable or surprising — a word of emphasis. Option C, "Remarkably," is an emphasis transition that flags the second sentence as worthy of attention, capturing the noteworthy quality of modern science confirming an ancient belief. Option A, "Consequently," implies cause and effect — that the scholars' belief caused modern neuroscience to produce evidence, which makes no logical sense. Option B, "However," signals contrast — implying the second sentence contradicts the first, but it does not; it agrees with it. Option D, "Therefore," signals that the second sentence is a logical conclusion drawn from the first, but modern scientific evidence is not logically derived from ancient scholars' beliefs.`,
      success_narrative: `The inscription glows with completed logic. The Transition Thief recoils, unable to steal a connection that has been correctly identified.`,
      failure_narrative: `The Transition Thief cackles and places "Consequently" in the gap. Now the ancient scholars have apparently caused modern neuroscience to exist.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'transitions',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 2,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The However Hexer',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The However Hexer inserts the word "however" into every text it touches, regardless of whether the ideas contrast. It has hexed a passage from the Keep's founding chronicle. You must identify the correct transition to replace the one it installed.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The First Scholars worked for three years to draft the Keep's founding charter. ________, they spent an additional six months revising it before presenting it to the district representatives."`,
      option_a: `Furthermore`,
      option_b: `However`,
      option_c: `As a result`,
      option_d: `For instance`,
      correct_answer: 'A',
      explanation: `The two sentences describe sequential steps in the same effort: drafting the charter (three years), then revising it (six more months). The second sentence adds an additional detail about the same process — it does not contrast, explain a cause, or give an example. The logical relationship is addition: here is more information about the same process. Option A, "Furthermore," is an addition transition that correctly signals the second sentence adds more to the same picture. Option B, "However," signals contrast — but the revision process does not contrast with the drafting; it continues it. Option C, "As a result," signals cause and effect — but the revision was not caused by the drafting in the way that requires "as a result"; it was simply the next step. Option D, "For instance," signals that the second sentence is an example of the first, but revising a charter is not an example of drafting a charter.`,
      success_narrative: `The charter chronicle flows smoothly from drafting to revision. The However Hexer's spell breaks, and all its misplaced contrasts dissolve from the stone.`,
      failure_narrative: `The However Hexer succeeds. The sentence now implies the scholars contradicted their own three-year drafting effort by then revising what they wrote.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'transitions',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 3,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Therefore Tyrant',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Therefore Tyrant demands that every sentence be a logical consequence of the previous one. It has imposed "therefore" on a passage where it does not belong. A Scholar who understands the relationship between ideas will see the problem immediately.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The Comma Plague contaminated official documents across every district of the Keep. ________, the eastern districts — which had more complex administrative documents — suffered the worst disruption."`,
      option_a: `Therefore`,
      option_b: `Nevertheless`,
      option_c: `In particular`,
      option_d: `Meanwhile`,
      correct_answer: 'C',
      explanation: `The first sentence establishes a general claim: the Plague affected every district. The second sentence narrows to a specific subset: the eastern districts suffered the worst. The logical relationship is specification — the second sentence gives a particular example within the general claim. Option C, "In particular," is an example/specification transition that correctly signals this narrowing from general to specific. Option A, "Therefore," implies that the eastern districts' particular suffering was a logical consequence of the general spread — but the spread across all districts did not logically cause the eastern districts to suffer more; their complex documents did. Option B, "Nevertheless," signals concession — that despite the general spread, something unexpected is true — but the eastern districts suffering more is not unexpected or contrary. Option D, "Meanwhile," signals that simultaneous events are happening, which does not match the relationship here.`,
      success_narrative: `The passage narrows correctly from general to specific. The Therefore Tyrant sputters — it cannot impose logical consequence where specification is the correct relationship.`,
      failure_narrative: `The Therefore Tyrant triumphantly carves "therefore" into the stone. The passage now implies that because all districts were affected, the eastern districts therefore suffered more — which is circular logic.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'transitions',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 4,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Furthermore Fiend',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Furthermore Fiend stuffs "furthermore" between sentences that are logically opposed, making every argument sound like it agrees with itself. It has infected a passage about the Oxford Comma Debate. The correct transition will restore the argument's honest conflict.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The Logicians argued that the Oxford comma was essential for preventing syntactic ambiguity. ________, the Grammarians maintained that skilled prose never needed the comma in the first place."`,
      option_a: `Moreover`,
      option_b: `On the other hand`,
      option_c: `Subsequently`,
      option_d: `Indeed`,
      correct_answer: 'B',
      explanation: `The two sentences present directly opposing positions: the Logicians say the comma is essential; the Grammarians say skilled writers don't need it. The logical relationship is contrast. Option B, "On the other hand," is a contrast transition that correctly signals the two sentences present opposing viewpoints. Option A, "Moreover," is an addition transition that would imply the Grammarians' position adds to or agrees with the Logicians' position — but they are in direct opposition. Option C, "Subsequently," is a sequence transition implying the Grammarians' position came after and was perhaps caused by the Logicians' — but neither of these implications is supported. Option D, "Indeed," is an emphasis transition that would imply the second sentence confirms or intensifies the first, but it contradicts the first.`,
      success_narrative: `The Oxford Comma Debate inscription now reads as a genuine argument with two opposing sides. The Furthermore Fiend collapses, unable to make contrasting ideas sound like agreement.`,
      failure_narrative: `The Furthermore Fiend places "Moreover" between the sentences. The Logicians and Grammarians now appear to agree with each other.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'transitions',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 5,
      type: 'standard',
      difficulty: 1,
      enemy_name: 'The Contrast Crusher',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Contrast Crusher hunts sentences that present consequences and pretends they are just adding information. It has replaced "therefore" with "additionally" in a passage about a Grammar Warden's most important ruling. You must restore the cause-and-effect relationship.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"Warden Sollis's structural review mandate required that every official document demonstrate communicability, not just technical correctness. ________, documents that met all grammar rules but confused average readers were sent back for revision."`,
      option_a: `Additionally`,
      option_b: `In contrast`,
      option_c: `As a result`,
      option_d: `For example`,
      correct_answer: 'C',
      explanation: `The first sentence establishes a rule: communicability is required, not just technical correctness. The second sentence describes a consequence of that rule: documents that are grammatically correct but confusing get sent back. The second sentence is the logical result of the policy described in the first. Option C, "As a result," is a cause-and-effect transition that correctly captures this relationship. Option A, "Additionally," treats the second sentence as additional information rather than as a consequence — it implies these are two separate, independent facts rather than a cause-and-effect pair. Option B, "In contrast," signals that the second sentence contradicts the first — but it does not; it illustrates the rule's application. Option D, "For example," would work if the second sentence were one example among many possible examples of the mandate's effects — but the sentence describes the direct consequence of the rule, not merely one illustrative instance.`,
      success_narrative: `The mandate passage flows from rule to consequence. The Contrast Crusher cannot destroy a cause-and-effect relationship this clearly established.`,
      failure_narrative: `The Contrast Crusher replaces the correct transition with "Additionally." The mandate's rule and its direct consequence now appear to be two separate, unrelated facts.`,
      xp_reward: 50,
      rune_reward: 0,
      concept_tag: 'transitions',
      difficulty_tag: 'guided',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 6,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Sequence Specter',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Sequence Specter scrambles the chronological transitions in historical passages, replacing sequence markers with logical connectors that make the timeline collapse. It has attacked a description of the Keep's founding process.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The three founding Scholar-clans spent the first year establishing physical infrastructure — walls, halls, and the Archive. ________, they turned their attention to the intellectual infrastructure: curriculum, debate protocols, and the founding charter."`,
      option_a: `However`,
      option_b: `Only then`,
      option_c: `Consequently`,
      option_d: `In fact`,
      correct_answer: 'B',
      explanation: `The passage describes a two-phase chronological process: first physical infrastructure, then intellectual infrastructure. The transition must signal that the second phase came after the first was completed — a temporal, sequential relationship. Option B, "Only then," is a sequence transition that captures both the chronological order and the dependency: the intellectual work began only after the physical work was done. Option A, "However," signals contrast — implying the intellectual infrastructure phase was somehow unexpected or contrary to the first phase, which is not the case. Option C, "Consequently," implies the intellectual infrastructure was a direct causal result of the physical infrastructure, which is an overstatement; the two phases were sequential, not strictly causal. Option D, "In fact," signals emphasis or clarification, implying the second sentence reveals something surprising or corrective about the first, which it does not.`,
      success_narrative: `The founding chronicle flows in proper temporal sequence. The Sequence Specter's chronological chaos is defeated by the clarity of "Only then."`,
      failure_narrative: `The Sequence Specter inserts "However." The Keep's intellectual infrastructure now seems to have been built in opposition to its physical foundations.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 7,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Cause Crook',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Cause Crook steals causal transitions and replaces them with contrasts, making causes and effects seem like opposites. It has struck a passage about the Comma Plague's containment. The cause-and-effect chain must be restored.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"Warden Holt's comma guide was distributed to every district scribe within two weeks of its publication. ________, citizens across the Keep noticed an immediate improvement in the clarity of official notices."`,
      option_a: `Nevertheless`,
      option_b: `For instance`,
      option_c: `Within days`,
      option_d: `As a result`,
      correct_answer: 'D',
      explanation: `The first sentence describes an action (wide, rapid distribution of the comma guide); the second describes its outcome (citizens notice improved clarity). The logical relationship is cause and effect: the distribution caused the improvement. Option D, "As a result," is a cause-and-effect transition that correctly captures this relationship. Option A, "Nevertheless," signals contrast/concession — implying that despite the distribution, something happened, which would suggest the improvement was unexpected or contrary. Option B, "For instance," treats the citizens' improvement as merely one example of the distribution's effects, but it is the direct, primary consequence. Option C, "Within days," adds a temporal marker but does not establish the causal relationship — it tells us when, not why. The question asks for the transition that BEST connects the two sentences logically, and "As a result" captures both the temporal sequence and the causal relationship.`,
      success_narrative: `The Comma Plague containment story reads as a clean cause-and-effect narrative. The Cause Crook flees, unable to steal the logical connection.`,
      failure_narrative: `The Cause Crook installs "Nevertheless." Despite Holt's guide being distributed everywhere, citizens noticed an improvement — as if this were a surprise.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 8,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Effect Eraser',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Effect Eraser has removed a transition from a passage about the philosophical debate on grammar and logic. Without it, the passage feels like two disconnected observations. You must choose the transition that reveals the relationship between them.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The Guild of Rhetoric Scholars maintained that a sentence structured illogically could not express a logically valid idea. ________, they required every member to take a course in formal logic before advancing to advanced rhetoric study."`,
      option_a: `In addition`,
      option_b: `For this reason`,
      option_c: `Although`,
      option_d: `Similarly`,
      correct_answer: 'B',
      explanation: `The first sentence states the Guild's philosophical belief (illogical sentences cannot express logical ideas). The second sentence describes a policy (members must take a logic course before advanced rhetoric). The policy is a direct institutional response to the belief: because they believed grammar and logic were intertwined, they required logic training. The second sentence follows from the first as a consequence. Option B, "For this reason," is a cause-and-effect transition that correctly signals the second sentence is the institutional response to the belief stated in the first. Option A, "In addition," treats the policy as merely additional information rather than as a consequence of the belief. Option C, "Although," signals contrast — implying the policy was implemented despite, or contrary to, the belief, which makes no sense. Option D, "Similarly," implies the policy is analogous to the belief rather than derived from it.`,
      success_narrative: `The inscription reveals a clear cause-and-effect relationship: belief drives policy. The Effect Eraser cannot erase the logic of a well-chosen transition.`,
      failure_narrative: `The Effect Eraser installs "In addition." The Guild's belief and its policy now appear to be two separate, unrelated facts.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 9,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Addition Annihilator',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Addition Annihilator eliminates the transitions that build upon ideas, replacing them with transitions that imply opposition. It has attacked a passage about the annual grammar review. Two ideas that belong together now seem to fight each other.`,
      passage: null,
      question_stem: `Which version of the underlined portion is BEST? "The annual grammar review assesses every district's documents for error patterns. [However], it also tracks year-over-year improvement to identify which districts are making progress."`,
      option_a: `However`,
      option_b: `Moreover`,
      option_c: `Therefore`,
      option_d: `OMIT the underlined word (begin: "It also tracks...")`,
      correct_answer: 'B',
      explanation: `The two sentences describe two related functions of the annual review: assessing for errors AND tracking improvement. These are complementary, additive functions — not contrasting or causal. The transition needed signals that the second sentence adds a second, related function to the first. Option B, "Moreover," is an addition transition that correctly signals the second sentence adds to the first. Option A, "However," signals contrast — implying that tracking improvement contradicts or is surprising given error assessment, which makes no sense. Option C, "Therefore," implies tracking improvement is a logical result of assessing error patterns — but these are two separate activities, not cause and effect. Option D would omit the transition and use only "also," but without a connecting word, the logical relationship between the two functions is less clear; "Moreover" more explicitly signals the additive relationship.`,
      success_narrative: `The two review functions are now clearly presented as complementary, additive activities. The Addition Annihilator cannot destroy an addition that "Moreover" so clearly establishes.`,
      failure_narrative: `The Addition Annihilator keeps "However." Now tracking improvement appears to contradict the purpose of assessing errors.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 10,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Conclusion Crusher',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Conclusion Crusher destroys summary transitions, replacing them with transitions that imply the argument is continuing when it is actually concluding. It has attacked a philosophical passage about the Keep's founding purpose.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"The founding scholars believed that grammar was a moral discipline, that logic was its foundation, and that rhetoric was its highest application. ________, Grammar Keep was not merely a place of learning — it was a place of ethical formation."`,
      option_a: `Nevertheless`,
      option_b: `Additionally`,
      option_c: `In sum`,
      option_d: `Specifically`,
      correct_answer: 'C',
      explanation: `The first sentence lists three beliefs of the founding scholars. The second sentence draws a conclusion from those beliefs: Grammar Keep was a place of ethical formation. The second sentence synthesizes the list into a larger claim — it is a summary/conclusion following from the evidence. Option C, "In sum," is a summary transition that correctly signals the second sentence brings the argument to a conclusion. Option A, "Nevertheless," signals contrast — implying the second sentence's claim about ethical formation is surprising or contrary to the listed beliefs, which is the opposite of true. Option B, "Additionally," treats the second sentence as another item in a continuing list, but it is not another belief — it is the synthesizing conclusion drawn from the beliefs. Option D, "Specifically," signals that the second sentence narrows or illustrates the first, but the claim about ethical formation is broader than any of the three listed beliefs — it is a generalization, not a specification.`,
      success_narrative: `The philosophical argument concludes cleanly, the summary transition signaling that the list of beliefs leads to a larger claim. The Conclusion Crusher retreats.`,
      failure_narrative: `The Conclusion Crusher installs "Additionally." The synthesizing conclusion now sounds like a fourth item on a list that was supposed to end.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 11,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Flow Phantom',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Flow Phantom haunts a passage where a transition creates an unnecessary interruption. The ideas already flow naturally — the transition is redundant, even misleading. You must identify whether to keep or remove it.`,
      passage: null,
      question_stem: `Which version of the underlined portion is BEST? "Scholar-Medic Falc was born in the Outer Quarter and trained at the Academy. [Subsequently], she spent twenty years working in the Ink War's most dangerous field posts."`,
      option_a: `Subsequently`,
      option_b: `As a result`,
      option_c: `OMIT the underlined word (begin: "She spent...")`,
      option_d: `However`,
      correct_answer: 'A',
      explanation: `The two sentences describe sequential life events: birth and training, then twenty years in the field. "Subsequently" correctly marks the temporal sequence — the field work came after the training. This transition is appropriate and useful. Option A keeps "Subsequently," which is the correct answer because the sequence marker is genuinely helpful here and captures the chronological relationship. Option B, "As a result," would imply the twenty years of field work was caused by her training and birthplace, which is an overstatement of causation. Option C would omit the transition entirely; while "she spent twenty years" would still be understandable without it, "Subsequently" adds clarity about the chronological order and the transition is not unnecessary. Option D, "However," would imply the field work was surprising given or contrary to her origins and training, which creates a false contrast.`,
      success_narrative: `The biography flows cleanly from training to career, the sequence transition exactly right. The Flow Phantom cannot haunt a transition this purposeful.`,
      failure_narrative: `The Flow Phantom convinces you to remove the transition. The biography now jumps from training to field work with no signal of temporal sequence.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 12,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Logic Looter',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Logic Looter has inserted a completely unnecessary transition into a passage from the Keep's founding chronicle — a transition that implies a logical relationship between two ideas that are simply part of the same observation.`,
      passage: null,
      question_stem: `Which version of the underlined portion is BEST? "The founding charter of Grammar Keep was written in the ancient scholar-script and carved into a slab of white limestone. [Moreover], the slab was displayed in the Keep's entrance hall for all visitors to read."`,
      option_a: `Moreover`,
      option_b: `Therefore`,
      option_c: `However`,
      option_d: `OMIT the underlined word (begin: "The slab...")`,
      correct_answer: 'D',
      explanation: `The first sentence describes the charter: its writing system and material. The second sentence describes where the resulting slab was displayed. These two sentences are part of a continuous description of the same object — the first describes how it was made, the second describes where it was placed. No logical relationship transition is needed because the sentences flow naturally as part of a simple description. "Moreover" implies the second sentence adds a significantly additional, separate point, but the display location is simply the next fact in a continuous description. Option D, omitting the transition, is correct: the prose flows cleanly without it. Option A keeps "Moreover," which artificially elevates the display location as a major additional point. Option B, "Therefore," implies the display was caused by the charter's materials, which is illogical. Option C, "However," implies a contrast — as if displaying the charter was surprising or contrary to making it of white limestone.`,
      success_narrative: `The charter description flows naturally without an unnecessary transition. The Logic Looter cannot loot the logic of prose that flows on its own.`,
      failure_narrative: `The Logic Looter keeps "Moreover" in place. The display location of a slab now appears to be a major additional claim requiring special signaling.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 13,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Connective Crook',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Connective Crook has stolen the connecting logic from a complex paragraph about the philosophical debate between Prescriptivists and Descriptivists. The paragraph has five sentences and a transition word is underlined. You must determine which replacement is best.`,
      passage: `The Prescriptivist scholars argued that grammar rules were objective truths, derived from the logical structure of thought itself. [Therefore], the Descriptivist scholars countered that grammar rules were merely conventions — patterns that had become standard through usage, not through logic. Both factions agreed on one point: the rules mattered. They disagreed only on why they mattered.`,
      question_stem: `The underlined transition word "Therefore" should be replaced with:`,
      option_a: `Consequently`,
      option_b: `In contrast`,
      option_c: `Furthermore`,
      option_d: `LEAVE IT AS IS`,
      correct_answer: 'B',
      explanation: `"Therefore" implies that the Descriptivist position is a logical consequence of the Prescriptivist position — that one follows from the other. But the sentences present opposing views: Prescriptivists say rules come from logic; Descriptivists counter that rules come from convention. The relationship is contrast, not cause and effect. Option B, "In contrast," correctly identifies this as a statement of opposition. Option A, "Consequently," is even more strongly causal than "therefore" and would imply the Descriptivist view is a logical result of the Prescriptivist view, which is backwards. Option C, "Furthermore," would imply the Descriptivists are adding to or agreeing with the Prescriptivists. Option D would leave "Therefore" in place, preserving the logical error.`,
      success_narrative: `The debate passage now presents two genuinely opposing views. The Connective Crook cannot steal the contrast from a paragraph that has been correctly restored.`,
      failure_narrative: `The Connective Crook insists "Therefore" is fine. The Descriptivist response now reads as a logical consequence of the Prescriptivist position — the opposite of a debate.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 14,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Bridge Breaker',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Bridge Breaker has broken the bridge between two ideas in a passage about the Keep's annual report. The transition word is underlined — but it is the wrong one for the relationship being expressed.`,
      passage: `The Punctuation Quarter submitted its best annual report in a decade, citing fifteen-percent improvement in correctly punctuated documents. [In addition], Quarter-Master Desh had faced significant obstacles at the start of the year, including a shortage of trained Wardens and a surge in document volume.`,
      question_stem: `The underlined transition "In addition" should be replaced with:`,
      option_a: `Specifically`,
      option_b: `Consequently`,
      option_c: `Nevertheless`,
      option_d: `LEAVE IT AS IS`,
      correct_answer: 'C',
      explanation: `The first sentence reports a strong positive outcome (best report in a decade, fifteen percent improvement). The second sentence reveals that Desh faced significant obstacles at the start of the year. The logical relationship is contrast/concession: the achievement is impressive specifically because it was achieved despite difficulties. "In addition" would imply the obstacles are another positive detail added to the success, which misrepresents the relationship. Option C, "Nevertheless," is a contrast/concession transition: the obstacles are real, but the success happened anyway — which is the entire point of mentioning both facts together. Option A, "Specifically," would imply the obstacles are a specification or example of the success, which makes no sense. Option B, "Consequently," would imply the success caused the obstacles, which inverts the relationship. Option D keeps "In addition," which treats obstacles as another point in a positive list.`,
      success_narrative: `The annual report passage now reads as a genuine achievement-despite-difficulty story. The Bridge Breaker cannot break a logical bridge this clearly established.`,
      failure_narrative: `The Bridge Breaker keeps "In addition." The obstacles are now presented as just another item in a positive list, as if they were achievements.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 15,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Relationship Rogue',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Relationship Rogue confuses transitions that specify with transitions that contrast, making examples look like opposites. It has infected a passage about the Keep's debate tradition. The underlined transition is wrong.`,
      passage: `The Keep's Fifth Age scholars took debate preparation extremely seriously, spending weeks researching both their own positions and those of their opponents. [However], Senior Scholar Arvan is known to have written fourteen drafts of a single opening argument before a major debate.`,
      question_stem: `The underlined transition "However" should be replaced with:`,
      option_a: `LEAVE IT AS IS`,
      option_b: `For instance`,
      option_c: `As a result`,
      option_d: `Although`,
      correct_answer: 'B',
      explanation: `The first sentence makes a general claim about Fifth Age scholars taking preparation seriously (weeks of research). The second sentence describes a specific example: Scholar Arvan wrote fourteen drafts of an opening argument. The logical relationship is example/illustration: the second sentence gives a concrete instance of the serious preparation described in the first. "However" implies contrast, which would mean Arvan's fourteen drafts were somehow contrary to or unexpected given the general preparation culture — but they perfectly illustrate it. Option B, "For instance," is an example transition that correctly signals the second sentence illustrates the first. Option C, "As a result," would imply Arvan wrote fourteen drafts because of the general preparation culture — which is a causal overstatement. Option D, "Although," would create a concession: despite serious preparation, Arvan wrote fourteen drafts — which implies drafting was contrary to preparation, which makes no sense.`,
      success_narrative: `The debate passage correctly uses example to illustrate its general claim. The Relationship Rogue cannot rogue its way through a transition this precisely chosen.`,
      failure_narrative: `The Relationship Rogue keeps "However." Scholar Arvan's fourteen drafts now appear to contradict the general culture of serious preparation.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 16,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Link Looter',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Link Looter has replaced a transition in a passage about the Prescriptivist-Descriptivist debate. The replaced transition inverts the logical relationship. This is a harder version — you must read the full paragraph carefully.`,
      passage: `Both the Prescriptivists and the Descriptivists agreed that grammar instruction was important. The Prescriptivists taught rules as objective truths; the Descriptivists taught rules as historical conventions. [Therefore], neither side advocated for eliminating grammar instruction altogether — they disagreed only about its philosophical basis.`,
      question_stem: `The underlined transition "Therefore" should be replaced with:`,
      option_a: `Nevertheless`,
      option_b: `Specifically`,
      option_c: `For example`,
      option_d: `LEAVE IT AS IS`,
      correct_answer: 'A',
      explanation: `The paragraph makes a concession argument: despite their significant disagreements about whether grammar rules are truths or conventions, both sides agreed that grammar instruction mattered. The third sentence says "neither side advocated for eliminating grammar instruction" — which is a concessive point: despite the debate, this one thing they agreed on. "Therefore" would imply that neither side wanted to eliminate grammar instruction as a logical consequence of their different approaches — but that is not the argument. The argument is that their disagreement did NOT extend to eliminating grammar instruction, which is a "nevertheless" situation: they disagreed about fundamentals, and yet they agreed on this point. Option A, "Nevertheless," correctly signals this concessive relationship. Option B, "Specifically," would narrow the third sentence as if it were an example of something, which it is not. Option C, "For example," would make the third sentence an illustration of one of the prior sentences, but it is a separate, concessive claim. Option D keeps "Therefore," which is logically incorrect.`,
      success_narrative: `The debate passage reveals its concessive logic: disagreement on philosophy, agreement on purpose. The Link Looter drops its stolen transition and retreats.`,
      failure_narrative: `The Link Looter keeps "Therefore." The agreement on grammar instruction now appears to be a logical consequence of the two sides' different philosophies, which is not the argument at all.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 17,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Pivot Phantom',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Pivot Phantom haunts passages where the argument shifts direction. It replaces contrast transitions with addition transitions, making pivots invisible. It has struck a passage about the Keep's educational history.`,
      passage: null,
      question_stem: `Which transition word or phrase BEST connects these two sentences?\n\n"For its first two centuries, Grammar Keep trained only the children of established Scholar-clan families, maintaining strict hereditary admission policies. ________, by the Third Age, the Keep had opened its doors to any student who could pass a rigorous entrance examination."`,
      option_a: `Similarly`,
      option_b: `Additionally`,
      option_c: `By contrast`,
      option_d: `As a result`,
      correct_answer: 'C',
      explanation: `The sentences describe two different historical policies that are directly opposed: hereditary admission (first two centuries) versus merit-based admission (by the Third Age). The second sentence represents a complete reversal of the first. The logical relationship is contrast. Option C, "By contrast," is a contrast transition that correctly signals the second sentence presents an opposing policy to the first. Option A, "Similarly," would imply the merit-based policy is similar to the hereditary policy — the opposite of what is being said. Option B, "Additionally," treats the second policy as additional information rather than as a contrasting replacement. Option D, "As a result," implies the merit-based policy was caused by the hereditary policy, which is not stated; the causal mechanism (why the change happened) is not described, so we cannot use a causal transition.`,
      success_narrative: `The historical contrast between hereditary and merit-based admission is now clearly signaled. The Pivot Phantom cannot make a reversal invisible.`,
      failure_narrative: `The Pivot Phantom places "Similarly" between the sentences. The merit-based admission policy now appears to resemble the hereditary policy.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 18,
      type: 'standard',
      difficulty: 2,
      enemy_name: 'The Contrast Crook',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Contrast Crook has taken an unnecessary transition from a passage describing the Keep's educational system and demands you recognize that the two sentences flow naturally without any connector. Not every sentence pair needs a transition word.`,
      passage: null,
      question_stem: `Which version of the underlined portion is BEST? "The Keep's morning curriculum covers formal grammar rules, syntax analysis, and sentence-level editing. [In contrast], the afternoon sessions are devoted to rhetoric, logical argumentation, and extended writing practice."`,
      option_a: `In contrast`,
      option_b: `However`,
      option_c: `Meanwhile`,
      option_d: `OMIT the underlined phrase (begin: "The afternoon sessions...")`,
      correct_answer: 'D',
      explanation: `The two sentences describe the morning curriculum and the afternoon curriculum of the Keep's educational system. They are two halves of a complementary description — different content areas that together form the whole curriculum. They are not in contrast to each other; they are sequential parts of the day. "In contrast" incorrectly implies the afternoon curriculum is somehow opposing or surprising given the morning curriculum. "However" similarly implies contrast. "Meanwhile" implies simultaneous action. None of these transitions are accurate. The two sentences flow naturally as a two-part description of the day's curriculum, and no transition is needed. Option D omits the transition, allowing the natural sequential logic to carry the reader from morning to afternoon. This is cleaner and more accurate.`,
      success_narrative: `The curriculum description flows naturally from morning to afternoon without a misleading contrast transition. The Contrast Crook cannot install a contrast where none exists.`,
      failure_narrative: `The Contrast Crook keeps "In contrast." The afternoon curriculum now appears to be in opposition to the morning curriculum, as if they were competing.`,
      xp_reward: 75,
      rune_reward: 1,
      concept_tag: 'transitions',
      difficulty_tag: 'standard',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 19,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Elaboration Eraser',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The deeper ruins test harder transitions — those requiring you to understand the full context of a paragraph, not just a pair of sentences. The Elaboration Eraser has attacked a complex paragraph about the Prescriptivist-Descriptivist debate. The underlined transition must be evaluated against the entire paragraph.`,
      passage: `The Descriptivist movement began, paradoxically, as a defense of the Keep's original mission. The founding scholars, the Descriptivists argued, had studied language as it was actually used — not as they wished it to be. The prescriptive tradition had distorted this by elevating certain usages to the status of universal law. [Indeed], the Descriptivists did not want to tear down grammar instruction; they wanted to return it to its empirical roots.`,
      question_stem: `The underlined transition "Indeed" should be replaced with:`,
      option_a: `LEAVE IT AS IS`,
      option_b: `Therefore`,
      option_c: `However`,
      option_d: `In contrast`,
      correct_answer: 'A',
      explanation: `The paragraph argues that the Descriptivist movement was actually a defense of the original mission (not a radical departure), and that the prescriptive tradition had distorted things. The final sentence makes a crucial clarifying point: the Descriptivists did NOT want to destroy grammar instruction; they wanted to return it to empirical roots. "Indeed" signals emphasis and confirmation: it confirms and intensifies the argument that has been building — in fact, truly, this is the case. This is exactly the right transition: the paragraph has been making the argument that the Descriptivists were actually more faithful to the original mission, and "Indeed" emphatically confirms the final, key point of that argument. Option A, leaving it as is, is correct. Option B, "Therefore," would imply the Descriptivists' goal is a logical consequence of the prescriptive distortion, which is a different logical claim. Option C, "However," would imply the Descriptivists' goal contradicts what was just said — but it confirms and elaborates it. Option D, "In contrast," would signal that the Descriptivists' goals were opposite to the prescriptive tradition's distortions, which is true thematically but not the right transition for this final confirming sentence.`,
      success_narrative: `The paragraph stands as written, "Indeed" perfectly placed to confirm and emphasize its conclusion. The Elaboration Eraser cannot erase a transition that was already correct.`,
      failure_narrative: `The Elaboration Eraser replaces "Indeed" with "However." The paragraph now implies the Descriptivists' goal of restoring empirical roots is surprising or contrary to the prescriptive distortion it just described.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 20,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Summary Sorcerer',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Summary Sorcerer conjures transitions that make arguments appear to conclude when they are still building — and makes building arguments appear to conclude when they need to. It has cast a spell on a complex five-sentence passage.`,
      passage: `Grammar Keep's reputation for intellectual rigor did not develop by accident. The founding scholars designed every aspect of the curriculum to challenge students to the edge of their abilities. Apprentices were given problems that no previous scholar had solved and were expected to make progress. Senior Wardens were required to publish new scholarship every three years or lose their positions. [In short], the culture of constant challenge was built into the Keep's institutional structure from the very beginning.`,
      question_stem: `The underlined transition "In short" should be replaced with:`,
      option_a: `However`,
      option_b: `For example`,
      option_c: `LEAVE IT AS IS`,
      option_d: `Nevertheless`,
      correct_answer: 'C',
      explanation: `The paragraph builds evidence across four sentences: the Keep's rigor was not accidental [1], curriculum challenged students [2], apprentices worked on unsolved problems [3], Wardens had to publish new scholarship [4]. The final sentence draws a conclusion from all this evidence: the culture of challenge was built into the institutional structure from the beginning. "In short" is a summary/conclusion transition that correctly signals this final sentence synthesizes everything that preceded it. This is exactly the right transition — it signals that what follows is a condensed summary of the accumulated evidence. Option A, leaving it as is, is correct. Option A is the answer for "correct" in this case, which is Option C. Option A (the choice labeled A) uses "However," which would imply the conclusion contradicts the evidence — it does not. Option B, "For example," would make the conclusion sound like one example of the general point, which inverts the relationship. Option D, "Nevertheless," implies a concessive relationship — that despite the evidence, the culture was built in — which is illogical.`,
      success_narrative: `The paragraph concludes perfectly with a synthesizing summary. The Summary Sorcerer's spell breaks — it cannot replace a transition that was already doing its job.`,
      failure_narrative: `The Summary Sorcerer replaces "In short" with "However." The paragraph's conclusion now appears to contradict the four sentences of evidence that preceded it.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 21,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Sequence Slayer',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Sequence Slayer is a veteran of the deepest ruins. It does not simply replace transitions — it constructs paragraphs where every transition option is plausible, and only deep understanding of logical relationships distinguishes the right answer from the wrong ones.`,
      passage: `Warden Holt understood that a comma guide alone would not solve the Comma Plague. The rogue Scholar who had started it had used a template — and every document made from that template was contaminated. Holt therefore identified and quarantined the template before distributing his guide. [______], even the best style guide cannot fix errors that have already been embedded in a template used for thousands of documents.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Furthermore`,
      option_b: `After all`,
      option_c: `Therefore`,
      option_d: `On the other hand`,
      correct_answer: 'B',
      explanation: `The paragraph describes Holt's strategic response to the Plague: understanding that a guide alone would not be enough, he quarantined the source template. The final sentence explains WHY quarantining the template was necessary — because no guide can fix errors already embedded in a widely-used template. This final sentence provides the underlying reason/justification for Holt's action. "After all" is a transition that signals the sentence provides an explanatory justification — it is equivalent to "because, when you think about it." This is precisely the logical relationship: the sentence explains why the template had to be quarantined. Option A, "Furthermore," would treat the justification as an additional point rather than an explanation. Option C, "Therefore," would imply the justification is a logical consequence of quarantining the template, which inverts the relationship (the justification explains why he quarantined it, not what resulted from quarantining it). Option D, "On the other hand," signals contrast — implying the final sentence contradicts or opposes the quarantine action, which makes no sense.`,
      success_narrative: `The Comma Plague strategy is explained with perfect logical clarity. The Sequence Slayer cannot slay a sequence that is so clearly reasoned.`,
      failure_narrative: `The Sequence Slayer installs "Therefore." The explanation of why the template had to be quarantined now reads as a consequence of quarantining it — circular logic.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 22,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Pivot Pillager',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Pivot Pillager has stripped the pivoting transition from a complex rhetorical argument about the Keep's founding. Without the pivot, the argument cannot turn from problem to solution. You must identify the best transition for the blank.`,
      passage: `The three founding Scholar-clans disagreed about nearly everything: the primacy of their respective disciplines, the proper structure of the Keep's governance, and the philosophical basis of grammar itself. For years, these disagreements stalled any meaningful progress toward building a shared institution. [______], all three clans shared one overriding fear: that without a permanent institution to preserve their knowledge, the learning of centuries might be lost in a single generation.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `As a result`,
      option_b: `In addition`,
      option_c: `Yet`,
      option_d: `Specifically`,
      correct_answer: 'C',
      explanation: `The paragraph has set up extensive disagreement and stalled progress. The final sentence introduces the shared fear that ultimately united the clans. This is a classic pivot: despite everything that divided them, this one thing united them. The transition must signal contrast/concession: the clans disagreed on everything — yet they shared this one fear. Option C, "Yet," is a contrast/concession transition that perfectly signals this pivot. Option A, "As a result," would imply the shared fear is a consequence of the stalled progress, which misrepresents the relationship. Option B, "In addition," would treat the shared fear as another item in the list of disagreements or as additional information, which obscures the fact that it is the one unifying factor amid all the division. Option D, "Specifically," would imply the shared fear is a specification or example of something just said, but the shared fear is actually the contrary of the disagreements just described.`,
      success_narrative: `The paragraph pivots cleanly from division to unity, the shared fear revealing itself as the only bridge the founding clans had. The Pivot Pillager cannot pillage a pivot this precisely placed.`,
      failure_narrative: `The Pivot Pillager installs "In addition." The shared fear is now just another item in the list of divisions, when it is actually the one thing that ended them.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 23,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Thread Thief',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Thread Thief has woven a complex paragraph from the philosophical treatise and placed a transition that creates a subtle but significant logical error. You must read all five sentences and determine which replacement transition is correct.`,
      passage: `The Keep's best teachers believed that students should struggle with material before receiving explanations. [Consequently], they withheld answers and allowed students to sit with confusion for days before intervening. This approach appeared cruel to outside observers. [Moreover], the students who experienced it reported that their eventual understanding was deeper and more durable than anything they could have achieved by being given the answers immediately. The teachers called this method "the productive friction."`,
      question_stem: `The second underlined transition "Moreover" should be replaced with:`,
      option_a: `However`,
      option_b: `Therefore`,
      option_c: `In addition`,
      option_d: `LEAVE IT AS IS`,
      correct_answer: 'A',
      explanation: `The passage has set up a contrast: the approach "appeared cruel to outside observers." The next sentence reports what the students themselves said — that their understanding was deeper and more durable. This is a classic contrast/concession structure: the approach looked cruel to outsiders, but the students who experienced it reported positive outcomes. "Moreover" would imply the students' positive report adds to or extends the claim about apparent cruelty — but it directly contradicts the outsiders' perception. "However" correctly signals that despite the apparent cruelty, the students found the method valuable. Option A is correct. Option B, "Therefore," would imply the students' positive report was a logical consequence of the apparent cruelty, which is an odd causal claim. Option C, "In addition," shares the same problem as "Moreover" — it treats the contrast as an addition. Option D keeps "Moreover," which is the transition being replaced because it is incorrect.`,
      success_narrative: `The pedagogical passage reveals its true structure: appearance of cruelty versus students' actual experience. The Thread Thief drops the logical thread it was trying to steal.`,
      failure_narrative: `The Thread Thief keeps "Moreover." The students' positive report now appears to add to the perception of cruelty rather than contradict it.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 24,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Connector Crusher',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The Connector Crusher has presented you with a passage in which two transition words are available and you must choose which version creates the most coherent logical structure. Both options are defensible — but only one is correct for this specific context.`,
      passage: `The Grammar Council's emergency response to the Comma Plague was widely praised for its speed. [______], critics later argued that the rushed distribution of Holt's guide created new inconsistencies — districts that received the guide at different times implemented comma rules differently, creating a second wave of confusion that took years to resolve.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Therefore`,
      option_b: `Nonetheless`,
      option_c: `Furthermore`,
      option_d: `Specifically`,
      correct_answer: 'B',
      explanation: `The first sentence praises the Council's response for its speed. The second sentence presents a criticism: the speed created new problems (inconsistent implementation, second wave of confusion). The logical relationship is contrast/concession: the response was praised for speed, but this very speed created new issues. Option B, "Nonetheless," is a contrast/concession transition that correctly signals: despite the praise for speed, critics found fault in its consequences. Option A, "Therefore," would imply the critics' criticism was a logical consequence of the speed being praised — which inverts the relationship. Option C, "Furthermore," would add the criticism as additional positive information rather than as a counter-perspective. Option D, "Specifically," would imply the critics' argument is a specification or example of the Council's praised speed, but it is actually a criticism of it.`,
      success_narrative: `The passage presents a nuanced picture: praised for speed, criticized for the consequences of that speed. The Connector Crusher cannot crush a connection this logically sound.`,
      failure_narrative: `The Connector Crusher installs "Furthermore." The criticism of the rushed distribution now reads as additional praise for the Council's response.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
    {
      encounter_number: 25,
      type: 'standard',
      difficulty: 3,
      enemy_name: 'The Transition Tyrant',
      enemy_type: 'Logic Phantom',
      pre_narrative: `The final guardian of Chapter 17 rises from the ruin floor: the Transition Tyrant, most powerful of the Logic Phantoms. It has constructed a passage of maximum complexity, where the correct transition requires understanding a three-step logical argument. No Scholar has defeated it by guessing.`,
      passage: `The Descriptivist scholars had a problem: their own arguments were being used against them. Every time they cited a real-world example of a so-called "incorrect" usage that was actually widely understood, the Prescriptivists countered that widespread use of an error did not make it acceptable. The Descriptivists needed a better argument than mere frequency of use. [______], they developed what they called the "communicative success" standard: if a usage reliably conveyed the intended meaning to its audience, it was, by definition, functioning correctly — regardless of what the rulebooks said.`,
      question_stem: `Which transition word or phrase best fills the blank in the paragraph above?`,
      option_a: `Nevertheless`,
      option_b: `For instance`,
      option_c: `In response`,
      option_d: `As a result`,
      correct_answer: 'C',
      explanation: `The paragraph traces a strategic problem: the Descriptivists' existing argument was being defeated by Prescriptivists countering with "frequency doesn't make it right." The Descriptivists needed a better argument [sentence 3]. The blank then introduces what they developed. The logical relationship between sentence 3 (they needed a better argument) and sentence 4 (they developed the communicative success standard) is responsive: they developed this new standard in response to the inadequacy of their old argument. Option C, "In response," precisely captures this: the new standard was developed as a direct response to the argumentative failure described in sentence 3. Option A, "Nevertheless," signals contrast/concession — implying the new standard was developed despite something, which is vague and doesn't capture the responsive logic. Option B, "For instance," would make the communicative success standard an example of the need for a better argument, but it is the solution to that need. Option D, "As a result," is close but slightly off: "as a result" implies direct causal consequence, while "in response" captures the intentional, strategic nature of developing a new argument in answer to a challenge.`,
      success_narrative: `The Descriptivist argument is articulated with perfect logical precision. The Transition Tyrant screams and dissolves — defeated by a Scholar who understood not just that a transition was needed, but precisely what kind. You have mastered Chapter 17.`,
      failure_narrative: `The Transition Tyrant claims victory. With "As a result" instead of "In response," the Descriptivists' new argument sounds like an automatic consequence rather than a strategic intellectual choice.`,
      xp_reward: 100,
      rune_reward: 2,
      concept_tag: 'transitions',
      difficulty_tag: 'mastery',
      act_skill_area: 'Rhetoric',
    },
  ]
};

module.exports = chapter17;
